### ISSUE TITLE
The fci_l1c_fdhsi reader should proved the `platform_name` in the attributes

### ISSUE THREAD

**Issue by TAlonglong** [pytroll/satpy#1014]
## Feature Request

The fci_l1c_fdhsi reader should provide the `platform_name` in the attributes.

I guess it is in the netcdf files like `MTG-I1` or something.

Then later when we know the Meteosat number (eg Meteosat-12) we can add a mapping.

**Comment by mraspaud** [comment]
Thanks for reporting this.

**Comment by sjoro** [comment]
the spacecraft IDs in the files are:
MTI1 -> MTG-I 1, same convention shall be used for the follow-up missions (MTI2, MTI2, MTI4)
similarly for sounder missions, the IDs are/will be MTS1, MTS2

**Comment by TAlonglong** [comment]
OK. I suggest we use the spacecraft ID as platform_name until each platform are given a Meteosat name. Then we can add some translation.
platform_name_translate={}
platform_name = platform_name_translate.get(space_craft_id, space_craft_id)

When a spacecraft get a meteosat name:
platform_name_translate={'MTI1': 'Meteosat-12'}
etc

**Comment by sjoro** [comment]
a quick clarification after reading the format specs, the spacecraftID will also be available as a global attribute in the files, no need to rely on the filename only.
