### ISSUE TITLE
Add reader for netcdf datasets written with Satpy

### ISSUE THREAD

**Issue by BENR0** [pytroll/satpy#1016]
## Feature Request

**Is your feature request related to a problem? Please describe.**
It would be nice to be able to read datasets written to netcdf with Satpy into a Satpy Scene again. This would enable users to use the same tools for further processing.

**Describe the solution you'd like**
The reader could utilize the `NetCDF4FileHandler` in netcdf_utils.py and use the `available_datasets()` method to dynamically get datasets in the file and create the appropriate area definition.

**Describe any changes to existing user workflow**
Existing user workflows with Satpy are not affected

**Additional context**
This would alleviate the need to read the data with xarray and manually create the area definition and assign the DataArrays to the Scene.

**Comment by djhoese** [comment]
I approve of this, but would like to make two points (stream of consciousness, sorry):

1. The NetCDF files that Satpy writes out are supposed to be CF compliant. Assuming a NetCDF file being *read* is CF compliant, the only thing that Satpy would like that isn't in the file is the `area` attribute. However, the file *should* provide a `grid_mapping` attribute/variable that can be converted to an AreaDefinition (along with some X/Y variables for the extents). My hope is that the `geoxarray` project or `pyresample` can create an easy to use "xarray accessor" that could make this conversion unnecessary for the user. This would require changing all `.attrs['area']` usage in Satpy with something like `data_arr.pyresample.area` (where `.pyresample` is an accessor created by pyresample).
2. A generic CF NetCDF reader would definitely be nice. Given my above point though it may not be necessary if users can get used to `xr.open_dataset`. Hm, although that limits us for using Satpy in other applications. Not sure.

Either way, maybe we should make a `Scene.from_dataset` or `Scene.from_xarray_dataset` method that could do some of these computations for you.

**Comment by BENR0** [comment]
I like the idea to implement this with a method instead of a reader. One problem I see is that not every dataset is "Satpy" compliant, meaning not all necessary information to create a Scene are contained. With a reader it would be clear that only netcdfs which were created with Satpy can be read.

Is your work on geoxarray or the accessor something that will make it into Satpy in the near future? I am just asking because maybe it would be wiser to invest time there instead of implementing something that will be replaced even though I probably could come up with a draft for a method pretty quickly because I have written some snippets which I already use.

**Comment by djhoese** [comment]
Accessors will start showing up in Satpy and Pyresample in the next year probably. It will allow easier use of Satpy and Pyresample for non-pytroll users.

I think the python code for a generic CF reader could be written to be very generic and get information based on a YAML file for anything missing. This way we can have YAML files specific to certain CF-ish files that supplement anything that the python code can't pull from the file. We could have one `cf` reader that tries its best for users to try as a starting point. If needed we could have a `satpy_cf` one but I would rather that Satpy write out "perfect" CF standard files that have all the necessary information.

**Comment by djhoese** [comment]
There is now a `satpy_cf_nc` reader which I think satisfies the originally proposal in this issue. If you disagree we can reopen this and discuss further. The other semi-off-topic stuff on accessors should be moved to slack or another issue.
