### ISSUE TITLE
Fix meteosat 10 area

### ISSUE THREAD

**Issue by djhoese** [pytroll/satpy#102]
As discussed on the mailing list and slack the Meteosat 10 native satellite area produced by the `hrit_msg` reader is incorrect compared to the mpop reader. @adybbroe was able to come up with the following area from mpop:

```
In [6]: glbd['VIS006'].area
Out[6]: 
Area ID: Meteosat-10seviri[-5567248.07417344 -5570248.47733926  5570248.47733926  5567248.07417344](3712, 3712)
Description: On-the-fly area
Projection ID: geos
Projection: {'a': '6378169.00', 'b': '6356583.80', 'h': '35785831.00', 'lat_0': '0.00', 'lon_0': '0.00', 'proj': 'geos'}
Number of columns: 3712
Number of rows: 3712
Area extent: (-5567248.074173444, -5570248.4773392612, 5570248.4773392612, 5567248.074173444)
```

And from satpy:
```
In [7]: glbd['overview'].info['area']
Out[7]: 
Area ID: some_area_name
Description: On-the-fly area
Projection ID: geosmsg
Projection: {'a': '6378169.0', 'b': '6356583.8', 'h': '35785831.0', 'lon_0': '0.0', 'proj': 'geos', 'units': 'm'}
Number of columns: 3712
Number of rows: 3712
Area extent: (5568748.28340708, 5568748.28340708, -5568748.6866856618, -5568748.6866856618)
```

So even when taking in to consideration that one of the readers keeps the area "upside down" and the other doesn't the extents are still different. The satpy area produces a clipped image on the edges when resampled and shown on a PNG image. The mpop result produces the expected full disk image.

Not sure who is best to assign this to ( @mraspaud, @adybbroe, @pnuu, or maybe me).

**Comment by mraspaud** [comment]
The navigation has been looked over regularly by at least @sfinkens and @ameraner , I'm confident the satpy results are as good as can be. Closing.

**Comment by adybbroe** [comment]
Great, thanks @mraspaud !
