### ISSUE TITLE
Mitiff tests failing on python 3.7 travis environments

### ISSUE THREAD

**Issue by djhoese** [pytroll/satpy#1028]
Seeing this in my #1027 PR. The palette mitiff writer test is failing with:

```
======================================================================

FAIL: test_save_dataset_palette (satpy.tests.writer_tests.test_mitiff.TestMITIFFWriter)

Test writer operation as palette.

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/build/pytroll/satpy/satpy/tests/writer_tests/test_mitiff.py", line 812, in test_save_dataset_palette

    np.testing.assert_allclose(image, expected, atol=1.e-6, rtol=0)

  File "/home/travis/miniconda/envs/test/lib/python3.7/site-packages/numpy/testing/_private/utils.py", line 1533, in assert_allclose

    verbose=verbose, header=header, equal_nan=equal_nan)

  File "/home/travis/miniconda/envs/test/lib/python3.7/site-packages/numpy/testing/_private/utils.py", line 846, in assert_array_compare

    raise AssertionError(msg)

AssertionError: 

Not equal to tolerance rtol=0, atol=1e-06

Mismatched elements: 22 / 20000 (0.11%)

Max absolute difference: 168

Max relative difference: inf

 x: array([[120, 156,   0, ...,   0,   0,   0],

       [  0,   0,   0, ...,   0,   0,   0],

       [  0,   0,   0, ...,   0,   0,   0],...

 y: array([[0, 0, 0, ..., 0, 0, 0],

       [0, 0, 0, ..., 0, 0, 0],

       [0, 0, 0, ..., 0, 0, 0],...
```

I'm not able to reproduce this locally with an existing/updated environment.

CC @TAlonglong Could you look at this?

**Comment by djhoese** [comment]
Well, bad news, I was able to reproduce the failure once locally and then the next execution where all I added was a print statement passed. Now I can't get it to fail again.

**Comment by djhoese** [comment]
This seems like it was caused by a numpy 1.18 on PyPI bug conflicting with the libtiff installed from conda-forge. I'm not sure how to debug this any further and I'm not sure it is even something that *should* be supported by conda-forge or numpy. Closing for now...

**Comment by mraspaud** [comment]
Same problem in appveyor atm...

**Comment by djhoese** [comment]
Link to failing test?

**Comment by mraspaud** [comment]
https://ci.appveyor.com/project/pytroll/satpy/builds/29993473

**Comment by djhoese** [comment]
Ok that's definitely the same issue I was seeing with numpy 1.18 on travis. Or at least the same symptoms...but this is numpy 1.17 on appveyor judging by the logs.

**Comment by djhoese** [comment]
We could try forcing the libtiff build on appveyor to see if that fixes things.

**Comment by mraspaud** [comment]
Tell me what to do :)

**Comment by djhoese** [comment]
Here's how I did it in the travis build while testing: https://github.com/pytroll/satpy/pull/1027/commits/0ecf8ed0b0a5f08273bf7855ae1c0f3abaa2750d

But for Windows it will be a different build...

https://anaconda.org/conda-forge/libtiff/4.1.0/download/win-64/libtiff-4.1.0-h21b02b4_3.tar.bz2

So `libtiff=4.1.0=h21b02b4_3` should work.

**Comment by djhoese** [comment]
We must have fixed this at some point as it is no longer affecting us.
