### ISSUE TITLE
test against xarray master

### ISSUE THREAD

**Issue by dcherian** [pytroll/satpy#1059]
It'd be nice if satpy and other relevant pytroll projects could run CI with xarray's master branch so we can catch bugs like https://github.com/pydata/xarray/issues/3746 and #1058 earlier. 

We test against master branches of dask etc like this: 
https://github.com/pydata/xarray/blob/4c96d53e6caa78d56b785f4edee49bbd4037a82f/ci/azure/install.yml#L13-L34

**Comment by djhoese** [comment]
As an add on to this, we should probably start failing on warnings in at least one environment (specified as an allowed failure).

**Comment by mraspaud** [comment]
@dcherian thanks for bringing this up. I think it's a good idea, we will discuss it and see how we can modify `.travis.yml` to include the master branches of xarray, dask, rasterio...

**Comment by djhoese** [comment]
As pointed out in the various related PRs, this has already helped point out an issue with how our trollimage project is using expand_dims and copying the data. Thanks @dcherian for suggesting it.
