### ISSUE TITLE
Reorder installation instructions to put conda before PyPI

### ISSUE THREAD

**Issue by djhoese** [pytroll/satpy#1060]
We often get users who have difficulty installing Satpy and its dependencies using PyPI. I noticed in our installation instructions that PyPI is listed first. What do we think about putting conda before PyPI and emphasizing that conda is highly recommended due to the number of complex C dependencies we have?

**Comment by pnuu** [comment]
Yes, mentioning installation with `miniconda` first would make life easier for all.
