### ISSUE TITLE
Metop level 2 EUMETCAST BUFR reader

### ISSUE THREAD

**Issue by TalfanBarnie** [pytroll/satpy#1076]
## Feature Request
 Currently there is no reader for IASI Level 2 BUFR data distributed over EUMETCAST

**Describe the solution you'd like**
A IASI level 2 EUMETCAST BUFR reader

**Describe any changes to existing user workflow**
Does not affect other parts
 
**Additional context**
Currently the alternative is to download the data from the archive, but this is not much use for operational purposes.

I'll make a start on this using seviri_l2_bufr as a base (thanks @sjoro for the suggestion)

**Comment by mraspaud** [comment]
IASI is flying on metop, not Sentinel, right ?
