### ISSUE TITLE
Avhrr l1b eps reader changes values of angles after reading

### ISSUE THREAD

**Issue by ninahakansson** [pytroll/satpy#1092]
**Describe the bug**
Avhrr l1b eps reader changes the values of angles after reading. Transforming the array to
numpy using .values does not give the same result each time.

**To Reproduce**

```python
from satpy.scene import Scene
import numpy as np
scn = Scene(
    reader='avhrr_l1b_eps',
    filenames=["AVHR_xxx_1B_M01_20151207044003Z_20151207044303Z_N_O_20151207054914Z"])

scn.load(['satellite_azimuth_angle'])
angle1 = scn['satellite_azimuth_angle'].values
angle2 = scn['satellite_azimuth_angle'].values
assert np.allclose(angle1, angle2)

```

**Expected behavior**
Expected angle1 and angle2 to be identical

**Actual results**
AssertionError

**Environment Info:**
 - OS: [Linux]
 - Satpy Version: [e.g. 0.20.0]
 - PyResample Version: 1.14.0
 - Dask Version: 2.8.1
 - xarray Version 0.15.0

**Additional context**
Problems only for some files.

**Comment by mraspaud** [comment]
What version of python-geotiepoints do you have ?

**Comment by mraspaud** [comment]
and scipy ?

**Comment by ninahakansson** [comment]
Scipy: 1.4.1
Geotiepoints: 1.1.8'

**Comment by mraspaud** [comment]
Ok, even with the same versions as you do and the same file I can't reproduce this on my computer.
I'm on python 3.8.1 but this shouldn't affect the result.

**Comment by mraspaud** [comment]
I found the problem I think, not sure why it doesn't affect me though...
https://github.com/pytroll/satpy/blob/master/satpy/readers/eps_l1b.py#L264-L267

**Comment by mraspaud** [comment]
talked too fast, sorry, this seems to be in order.

**Comment by mraspaud** [comment]
@ninahakansson what version of numpy do you have ?

**Comment by ninahakansson** [comment]
python: 3.6.7
numpy: 1.16.2

**Comment by mraspaud** [comment]
Ok, it looks like updating to numpy 1.18 fixes the problem.

**Comment by mraspaud** [comment]
@ninahakansson is this good enough or do we need a workaround for this problem ?
