### ISSUE TITLE
Print a list of available sensors/readers

### ISSUE THREAD

**Issue by mitkin** [pytroll/satpy#114]
Is there currently a way to print a list of supported sensors/readers? That would make it easier to get started working with the data (e.g. when a user downloads new supported data, it would be more convenient to get the list of readers directly in shell/IDE instead of looking into the ets/readers directory).

Something like 
```python
    from satpy import readers
    readers.list_readers()

    >>> ['sar-c', 'olci', ... ]
````

**Comment by davidh-ssec** [comment]
@mitkin Not yet, but it is definitely needed.

**Comment by djhoese** [comment]
This is now implemented in `master` with:

```
from satpy import available_readers, available_writers
available_readers()
available_writers()
```

Only those YAML configurations that did not result in an import error (when it imported the associated python code) are provided.
