### ISSUE TITLE
Documentation bug: group_files keyword argument reader doc has sentence consisting of only the word "This"

### ISSUE THREAD

**Issue by gerritholl** [pytroll/satpy#1144]
**Describe the bug**

The [documentation for [`satpy.readers.group_files`](https://satpy.readthedocs.io/en/latest/api/satpy.readers.html#satpy.readers.group_files), keyword argument `reader`, is as follows:

> Reader whose file patterns should be used to sort files. This

The second sentence is just "This", and appears broken off.

**To Reproduce**

- Open a browser
- Navigate to https://satpy.readthedocs.io/en/latest/api/satpy.readers.html#satpy.readers.group_files
- Read parameters for function `satpy.readers.group_files`.

**Expected behavior**

I expect complete sentences explaining the use of the keyword argument `reader`.

**Actual results**

I'm getting an incomplete sentence consisting of only the word "This".

**Screenshots**

![grafik](https://user-images.githubusercontent.com/500246/79319247-5b830300-7f08-11ea-90c5-e1c1ea890d8f.png)

**Environment Info:**

Version "latest" on readthedocs as of 2020-04-15.

**Additional context**

I suspect this sentence was intended to say something about this keyword argument being optional or mandatory or how it is being used.

**Comment by djhoese** [comment]
I would say this is incomplete rather than a bug. I started typing something and got distracted and never went back to finish it.
