### ISSUE TITLE
satpy to support reading of satpy generated netcdf cf files

### ISSUE THREAD

**Issue by TAlonglong** [pytroll/satpy#1145]
## Feature Request

satpy now has support for netcdf cf writing.

To be able to reread these data into satpy again I would like a netcdf cf reader for these types of data.

This reader has to support all types of filenames as the image reader( suggested by @mraspaud )

The `available_datasets` mechanism can be used to explore the content of the netcdf cf file ( also suggested by @mraspaud )

**Comment by tsukada-cs** [comment]
I have been asking for this feature as well. Currently, I can't reread NetCDF files as Scene object, so I keep the intermediate files as pickle files, but it is difficult and inconvenient to share them with colleagues.

**Comment by mraspaud** [comment]
I've been starting work on this, check #1205

**Comment by djhoese** [comment]
There is now a `satpy_cf_nc` reader.
