### ISSUE TITLE
GLM data LCFA from Class

### ISSUE THREAD

**Issue by joleenf** [pytroll/satpy#1149]
I retrieved some GLM product data form NOAA class, and the format of that lightning data is slightly different than the glm_l2 reader seems to allow at this time.  The file names are of the form ['{system_environment:2s}_{mission_id:3s}-L2-LCFA-{platform_shortname:3s}_s{start_time:%Y%j%H%M%S%f}_e{end_time:%Y%j%H%M%S%f}_c{creation_time:%Y%j%H%M%S%f}.nc']  which is not currently built into the reader.  I also think that perhaps some of the fields are different in this file.  

Is there an intention to support these files from CLASS 
Am I just searching for the GLM data from the wrong product name in CLASS?  (i.e.  GRGLMPROD):  https://www.bou.class.noaa.gov/saa/products/search?sub_id=0&datatype_family=GRGLMPROD&submit.x=16&submit.y=9 and I should be looking at a different GLM product to use in satpy?

**Comment by djhoese** [comment]
I think we've talked about this on slack in the past.

The `glm_l2` reader in Satpy was initially added by @deeplycloudy to support his gridded GLM product that he creates with his [glmtools](https://github.com/deeplycloudy/glmtools.git). There are placeholders for supporting the LCFA data where the reader would then run glmtools for you.

In my opinion the LCFA data is too complicated (events/groups/flashes) to go directly from the file to something that is usable to Satpy which typically handles 2D geolocated image-ish data, geolocated point data, and in some case geolocated 3D (z-level) data. The only software that I know of to do this conversion from LCFA to some grid-ish format is glmtools.

If you have a use case where you need the events/groups/flashes (or whatever they're called) then let's talk about what our options are and how you plan on using it.

**Comment by joleenf** [comment]
I was asked to convert these LFCA data from netCDF to geoTiff for someone else to use in ArcGIS desktop.  I should look into glmtools for performing that conversion.

**Comment by deeplycloudy** [comment]
@joleenf Yes, glmtools is the thing to use to make imagery. Start with [these docs](https://github.com/deeplycloudy/glmtools/blob/master/docs/index.rst). The imagery is described by [this paper](https://agupubs.onlinelibrary.wiley.com/doi/full/10.1029/2019JD030874).

**Comment by joleenf** [comment]
@deeplycloudy Thanks!  I will work with that.

**Comment by deeplycloudy** [comment]
Regarding the LCFA data, the point data can be useful, especially at the flash and group level. One challenge is the determination of a self-consistent set of flashes, groups, and events, since you have to walk the tree to throw out the right events, and can't just filter each level by lat/lon/time. glmtools can handle this process as well. This, from the README, does the job quite quickly.

```
from glmtools.io.glm import GLMDataset
filename = 'OR_GLM-L2-LCFA_G16_s20180040537000_e20180040537200_c20180040537226.nc'
glm =  GLMDataset(filename)
fl_idx = glm.dataset['flash_area'] > 2000
flash_ids = glm.dataset[{glm.fl_dim: fl_idx}].flash_id.data
smaller_dataset = glm.get_flashes(flash_ids)
print(smaller_dataset)
```

**Comment by joleenf** [comment]
@deeplycloudy Thank-you for the information, caution and hint.  I have forwarded the information to the rest of my work group.

**Comment by joleenf** [comment]
Hi @deeplycloudy and @djhoese I have been using glmtools to convert the LCFA into the grids which the satpy glm_l2 reader easily loads.  Everything seems to be working smoothly.  So should this question be closed?

**Comment by djhoese** [comment]
Thanks @joleenf
