### ISSUE TITLE
amsr2 l1b reader also match amsr2 l2 products

### ISSUE THREAD

**Issue by TAlonglong** [pytroll/satpy#1151]
the amsr2 l1b reader also match amsr2 l2 products

l1b filename: GW1AM2_202004171159_065B_L1SNBTBR_2220220.h5
l2  filename:  GW1AM2_202004161432_090B_L2SNSSWLB3300300.h5

I'm looking into add reading of the L2 SSW product and this needs some small updates to the l1b reader to make it work.

Should I update the l1b reader or should I create a amsr2_l2 reader mostly the same as the l1b reader?

If I create a new reader we need to update the l1b reader to only match L1 data

**Comment by TAlonglong** [comment]
![amsr2-ssw](https://user-images.githubusercontent.com/19924146/79579903-8025d900-80c8-11ea-9517-831a6e29ed31.png)

Just a quick example of the SSW data

**Comment by djhoese** [comment]
I think my preference would be to make a separate reader but just use the same python code (point the YAML to the same python module). If needed, subclass the python class in to a new amsr2_l2.py module.
