### ISSUE TITLE
dealing with 1D array output from data assimilation

### ISSUE THREAD

**Issue by liujake** [pytroll/satpy#1156]
Hi,
Just finished tutorial notebooks. Great package for satellite data processing/plotting! I work on weather satellite data assimilation. Often time DA output file is organized in 1D arrays instead of 2D (y,x) grid satpy dealing with. E.g., tb_obs_chan1(1:n), latitude(1:n), and longitude(1:n). Geolocations in 1D arrays can be irregular. Can satpy resample/plot this type of 1D data?
Zhiquan (Jake) Liu, NCAR/MMM

**Comment by zxdawn** [comment]
@liujake Hi, Zhiquan. You can try the `SwathDefinition` in the pyresample, see here: https://pyresample.readthedocs.io/en/stable/swath.html.
