### ISSUE TITLE
Question about license

### ISSUE THREAD

**Issue by paapu88** [pytroll/satpy#1164]
Dear developers,
I'm working in a small startup and we would like to use and perhaps contribute to satpy. 
satpy seems to use "GNU General Public License".

Question: can I use satpy as a python package in our company programs which we don't give out our source code?

**Comment by mraspaud** [comment]
Dear @paapu88 ,

It would be great to have you help us with satpy :)

I would need to have more details on exactly how you use satpy, but here are some general things to think about:
- The GPL requires the source code of satpy and derivative work to be provided if the satpy software and all derivative work is distributed. So, if you don't ship your software but run in the cloud for example and only expose a webui to the customers, you don't need to release any source code. On the other hand, if you distribute satpy, your software might need to have a GPL-compatible license, read on:
- Is your software considered derivative work in the legal sense according to the GPL ? It is a bit unclear for python, but it is generally considered that if you do `import satpy` in your software, then your software is a derivative work. If you only use files generated by satpy, then your software is not a derivative work, and you don't need to distribute the source code along with it when you distribute it.

But please keep in mind that I'm not a lawyer :)

**Comment by paapu88** [comment]
Thanks a lot for the clarification! 
I'll discuss if we can publish our satpy related work ( the part that would use `import satpy`). The we and others could use the files produced by this published work ( a public git repo)
