### ISSUE TITLE
combine_metadata only supports the average of time attrs

### ISSUE THREAD

**Issue by zxdawn** [pytroll/satpy#1174]
**Describe the bug**
Currently, `combine_metadata` will calculate the mean value of attrs related to time.
But, `start_time` should be the minimum and `end_time` should be the maximum.

**Expected behavior**
MultiScene:
```
start_time 2019-07-25 05:15:10
end_time 2019-07-25 05:34:49
```

**Actual results**
Scene_1:
```
start_time 2019-07-25 05:15:10
end_time 2019-07-25 05:24:49
```

Scene_2:
```
start_time 2019-07-25 05:25:10
end_time 2019-07-25 05:34:49
```

MultiScene:
```
start_time 2019-07-25 05:20:10
end_time 2019-07-25 05:29:49
```

**Comment by djhoese** [comment]
I really thought we were already doing that, but you're right of course. Here's the PR where I added averaging #473. A fix for this could probably remove the python 2 compatibility stuff too.

**Comment by zxdawn** [comment]
@djhoese So, by setting `average_times=False` will lead to the minimum  as `start_time` and maximum as `end_time`? If so, why not supporting `average_times` in `timeseries`?
https://github.com/pytroll/satpy/blob/65cd83f9a6bf301e131a1191a622b52609d42ac8/satpy/multiscene.py#L67

**Comment by djhoese** [comment]
I'm not sure what you are saying. The combine_metadata function needs to be updated to support min/max'ing start/end_time. I'm not sure what the right way is to handle it in the timeseries function.
