### ISSUE TITLE
Areas claiming to view "full globe" should be labelled "full disk" instead

### ISSUE THREAD

**Issue by gerritholl** [pytroll/satpy#1187]
**Describe the bug**

The areas `met09globeFull`, `seviri_0deg`, `seviri_iodc`, `msg_resample_area`, and `met07globe` all claim in their description that they display the "Full globe".  This is wrong, because they view only the full disk, which is less than one hemisphere thus less than 50% of the full globe.  Barring a cleverly placed constellation of giant mirrors, no single instrument can ever view the full globe.  There are some full globe projections in `areas.yaml`, such as `moll` and `robinson`.

**To Reproduce**

Directly visible in the source:

https://github.com/pytroll/satpy/blob/ef24f29c25c08ead1024d608ecf3150c0fcd7051/satpy/etc/areas.yaml#L378-L447

**Expected behavior**

I think descriptions should be correct, and this should be called full disk rather than full globe.

**Actual results**

The actual labelling is wrong.

**Screenshots**

Actual full globe projection:

![grafik](https://user-images.githubusercontent.com/500246/81182136-b8c12000-8fad-11ea-8bc9-ba9429f7912f.png)
*Source: [Wikimedia Commons](https://commons.wikimedia.org/wiki/File:Van_der_Grinten_projection_SW.jpg)*

**Environment Info:**
N/A

**Additional context**

Changing the descriptions may change the output for users who directly use the description of the area definition in their applications.  When fixing the actual names we should keep the old names as aliases for backward compatibility reasons.

**Comment by ameraner** [comment]
Area descriptions mentioning full globe have been corrected, and areas with names containing `full_globe` have been moved to deprecation.
