### ISSUE TITLE
Unknown dataset, solar_zenith_angle

### ISSUE THREAD

**Issue by getrdone93** [pytroll/satpy#1190]
**Describe the bug**
When loading the datasets for natural_color_sun composite, the solar_zenith_angle cannot be found.

**To Reproduce**
- use VIIRS I band data (my data has bands I01 through I05)
- create scene with viirs_l1b reader
- load the scene with natural_color_sun composite

```python
scene = Scene(filenames=[args.input_file], reader='viirs_l1b')
scene.load(['natural_color_sun'])
```

**Expected behavior**
The scene's datasets are loaded without error.

**Actual results**
KeyError: "Unknown datasets: DatasetID(name='solar_zenith_angle', wavelength=None, resolution=371, polarization=None, calibration=None, level=None, modifiers=None)"

**Environment Info:**
 - OS: centos 7
 - Satpy Version: 0.21.0
 - PyResample Version: 0+unknown <--- Is this a problem?

**Additional context**
- I ran ```check_satpy()``` and the viirs_l1b reader is said to be ```ok```. Also, there is no section that says ```Please either conda or pip install as follows```.
- I also know that this composite requires I01, I02, I03 because the ```natural_color_sun``` entry in ```etc/composites/viirs.yaml```. These are found without issue.
- The ```etc/readers/viirs_l1b.yaml``` appears to contain the data for the datasets. It has an ```I_SOLZ``` entry. Should this be getting picked up for ```solar_zenith_angle``` and is not?
- I may be doing something incorrect, I just can't see what that is.

**Comment by TAlonglong** [comment]
I think you need to specify which resolution you want.

Could you try:
`scene.load(['natural_color_sun'], resolution=371)`

**Comment by getrdone93** [comment]
It fails with the same error. I modified the ```I_SOLZ``` entry in ```etc/readers/viirs_l1b.yaml``` to have the name ```solar_zenith_angle```, and it picked it up.
However, I don't know if this is a valid fix because I then get errors about ```Failed to load coordinates for DatasetId...```

**Comment by TAlonglong** [comment]
Sorry, I overlooked your using viirs_l1b.

I have only used viirs_sdr and the config for those two readers are slightly different.

I only have one more idea, and that is to modify the compositor config.
add `i_` in front of https://github.com/pytroll/satpy/blob/master/satpy/etc/composites/viirs.yaml#L111

(and revert your changes in the reader config)

**Comment by getrdone93** [comment]
That gets me to the same place with my modification. It says this:
```
Required file type 'vgeoi' not found or loaded for 'i_lat'
Required file type 'vgeoi' not found or loaded for 'i_lon'
Required file type 'vgeoi' not found or loaded for 'i_solar_zenith_angle'
Failed to load coordinates for 'DatasetID(name='I02', wavelength=(0.845, 0.865, 0.884), resolution=371, polarization=None, calibration='reflectance', level=None, modifiers=())'
Failed to load coordinates for 'DatasetID(name='I01', wavelength=(0.6, 0.64, 0.68), resolution=371, polarization=None, calibration='reflectance', level=None, modifiers=())'
Failed to load coordinates for 'DatasetID(name='I03', wavelength=(1.58, 1.61, 1.64), resolution=371, polarization=None, calibration='reflectance', level=None, modifiers=())'
The following datasets were not created and may require resampling to be generated: DatasetID(name='natural_color_sun', wavelength=None, resolution=371, polarization=None, calibration=None, level=None, modifiers=None)
```
So where is this ```vgeoi`` file type? I am confused. It seems to be related to the subsequent errors.

**Comment by djhoese** [comment]
@getrdone93 You need to provide the geolocation files (that's the `vgeoi` file type it is complaining about). The SZA are in the geolocation files.

**Comment by djhoese** [comment]
The VGEOI files either start with "VGEOI" or "VNP03IMG" where "NP" would be different if this was for JPSS-1.

**Comment by djhoese** [comment]
A full set of VIIRS L1B files for a single pass/granule would look like this:

```
VNP02DNB.A2017345.0000.001.2017345065244.uwssec.nc
VNP02IMG.A2017345.0000.001.2017345065244.uwssec.nc
VNP02MOD.A2017345.0000.001.2017345065244.uwssec.nc
VNP03DNB.A2017345.0000.001.2017345065247.uwssec.nc
VNP03IMG.A2017345.0000.001.2017345065247.uwssec.nc
VNP03MOD.A2017345.0000.001.2017345065247.uwssec.nc
```

**Comment by getrdone93** [comment]
@djhoese @TAlonglong  Okay. Thank you for the quick responses!. It looks like I have to get some more data.

**Comment by djhoese** [comment]
In case someone else finds this, I should have mentioned "03" in the beginning of the name is for geolocation, "02" is the band data, "IMG" is for I-band (a.k.a. IMGagery resolution) data, "MOD" is for M-band (a.k.a. MODerate resolution), and DNB is for Day/Night Band.

**Comment by getrdone93** [comment]
Is there a place to ask questions, rather than submit bug reports? Or should we just submit bug reports? I am very new to satellite data, instruments, and the associated libraries so a question forum would be wonderful.

**Comment by djhoese** [comment]
We have a mailing list and a slack chat that you can join. Check out the getting in touch section on http://pytroll.github.io/
