### ISSUE TITLE
cf_writer should append to Convention global attribute if given header_attr

### ISSUE THREAD

**Issue by TAlonglong** [pytroll/satpy#1191]
Some times user want to add more than the CF convention to the global attribute `Convention`

If the user specify eg. the ACDD (http://wiki.esipfed.org/index.php/Attribute_Convention_for_Data_Discovery) in addition to the CF the Convention is overwritten here:
https://github.com/pytroll/satpy/blob/master/satpy/writers/cf_writer.py#L617

Is it possible to append to the `Convention` global attribute like this
```
if `Conventions` in root.attrs:
  root.attrs['Conventions'] += ', ' + CF_VERSION
else:
  root.attrs['Conventions'] = CF_VERSION
```

**Comment by djhoese** [comment]
Or would it be better to only set the Conventions if not set by the user? Or should we always include the ACDD convention too? What does it take to meet that specification's requirements?

**Comment by TAlonglong** [comment]
Hm not sure what would be the best. After thinking a bit on it, if the user set his/hers own Conventions he/she should be responsible til add all Conventions. I guess as you suggests.

So if the user does specify the Conventions in his/hers global attributes, satpy only add this.

I guess I need to PR this.

You can see here for the recommendations for the ACDD  http://wiki.esipfed.org/index.php/Attribute_Convention_for_Data_Discovery

There is also a nice site which can check you netcdf file: https://compliance.ioos.us/index.html
