### ISSUE TITLE
iber projection lost in the North Pacific

### ISSUE THREAD

**Issue by gerritholl** [pytroll/satpy#1240]
**Describe the bug**

According to its description the satpy built-in `iber` projection should cover "North half of the Iberian Peninsula and the Gulf of Biscay image 0 degrees".  However, as defined it is somewhere in the remote North Pacific.

**To Reproduce**

```python
import pyresample
ar = pyresample.load_area("/home/gholl/checkouts/satpy/satpy/etc/areas.yaml",
        "iber")
(lons, lats) = ar.get_lonlats()
print(lons.min(), lons.mean(), lons.max(), lats.min(), lats.mean(), lats.max())
```

**Expected behavior**

I expect the range of longitudes and latitudes to correspond to the described area, somewhere near the meridian, perhaps a little west of it.

**Actual results**

In reality the area covers longitude 166 to 180 degrees, seemingly shifted by 180 degrees compared to where it should be expected:

```
166.3308164211224 173.2332707794299 179.85396117722175 39.629863255964146 42.60892251305624 45.41767241192362
```

**Environment Info:**

 - Satpy Version: 0.22.1
 - Pyresample Version: 1.16.0

**Comment by djhoese** [comment]
My guess is the description was a copy/paste error from the `sve` area right above `iber`:

https://github.com/pytroll/satpy/blob/9261a1c590dc13b70e24c7b7a765b996663d59a1/satpy/etc/areas.yaml#L55-L77

Actually...nevermind that description seems more accurate for `iber` than `sve`. I'm a little confused by the projection for `iber`. It looks like it should be a UTM zone but is missing the actual UTM zone number. PROJ doesn't even define a default: https://proj.org/operations/projections/utm.html

**Comment by gerritholl** [comment]
This projection was deleted by commit 4126039b2bd6009adb9c427aae70e28b1cd3a334.
