### ISSUE TITLE
Support multiple readers in MultiScene.from_files

### ISSUE THREAD

**Issue by gerritholl** [pytroll/satpy#1268]
## Feature Request

**Is your feature request related to a problem? Please describe.**

`MultiScene.from_files` is a convenient constructor for a `MultiScene`, analogous to the main constructor for the regular `Scene` class.  For a single Scene, I can combine multiple readers by passing filenames either as a dictionary where the keys are reader names, or by passing a collection of readers:

```python
Scene(filenames={"glm_l2": ["/media/nas/x21308/GLM/OR_GLM-L2-GLMC-M3_G16_s20201041802000_e20201041803000_c20202021633520.nc"], "abi_l1b": glob("/data/gholl/cache/fogtools/abi/2020/04/13/18/C*/OR_ABI-L1b-RadC-M6C*_G16_s20201041801134_e*_c*.nc")})
Scene(filenames=["/media/nas/x21308/GLM/OR_GLM-L2-GLMC-M3_G16_s20201041802000_e20201041803000_c20202021633520.nc"] + glob.glob("/data/gholl/cache/fogtools/abi/2020/04/13/18/C*/OR_ABI-L1b-RadC-M6C*_G16_s20201041801134_e*_c*nc"), reader=("abi_l1b", "glm_l2"))
```

for a `MultiScene`, that doesn't seem to work.  Passing a dictionary doesn't work at all due to the required keyword argument `reader` (which must be a string), and passing a tuple of readers seems to ignore all but the first element of the tuple:

```python
In [62]: ms = satpy.MultiScene.from_files(glob.glob("/media/nas/x21308/GLM/GLMC/2020/04/13/18/OR_GLM-L2-GLMC-M3_G16_s202010418*.nc") + glob.glob("/data/gholl/cache/fogtools/abi/2020/04/13/18/C*/OR_ABI-L1b-RadC-M6C*_G16_s20201041801134_e*_c*.nc"), reader=("glm_l2", "abi_l1b"))

In [63]: ms.first_scene.available_dataset_names()
Out[63]:
['average_flash_area',
 'average_group_area',
 'flash_centroid_density',
 'flash_extent_density',
 'group_centroid_density',
 'group_extent_density',
 'minimum_flash_area',
 'total_energy']

In [64]: ms = satpy.MultiScene.from_files(glob.glob("/media/nas/x21308/GLM/GLMC/2020/04/13/18/OR_GLM-L2-GLMC-M3_G16_s202010418*.nc") + glob.glob("/data/gholl/cache/fogtools/abi/2020/04/13/18/C*/OR_ABI-L1b-RadC-M6C*_G16_s20201041801134_e*_c*.nc"), reader=("abi_l1b", "glm_l2"))

In [65]: ms.first_scene.available_dataset_names()
Out[65]:
['C01',
 'C02',
 'C03',
 'C04',
 'C05',
 'C06',
 'C07',
 'C08',
 'C09',
 'C10',
 'C11',
 'C12',
 'C13',
 'C14',
 'C15',
 'C16']
```

**Describe the solution you'd like**

I would like that `MultiScene.from_files` can take multiple readers just like Scene, probably with a similar API.

**Describe any changes to existing user workflow**

There should be no backward compatibility concerns.

**Additional context**

Currently I need to manually construct each of `Scene` objects, essentially doing the work in `from_files` manually for each reader separately, then construct the `MultiScene` from there.

**Comment by gerritholl** [comment]
This would rely on support for multiple readers in `satpy.readers.group_files`.  In the source of the latter, this feature request is already mentioned:

https://github.com/pytroll/satpy/blob/df47897202c91a179fc7cdbb2da8bc58066057cc/satpy/readers/__init__.py#L429

**Comment by gerritholl** [comment]
Open question:

what to do if the starting and ending times do not match between the readers?

For example:

- ABI-L2 CONUS start time: 18:00:00, 18:05:00, 18:10:00 (3 files in 10 minutes)
- GLM-L2 start time: 18:00:00, 18:00:20, 18:00:40, ..., 18:09:40, 18:10:00 (31 files in 10 minutes)

what would be the appropriate grouping here?

**Comment by gerritholl** [comment]
Or should this be not a problem due to the common time threshold?

**Comment by djhoese** [comment]
I *think* the `group_files` function has a time threshold for how it groups the files. So with that keyword argument specified to match ABI (maybe 5 minutes or 5 minutes and 1 second?), you would have to assume that the GLM L2 reader would be able to accept 5 minutes of files at one time. I think.

**Comment by gerritholl** [comment]
Yes, or support multiple ways of aggregation through a keyword argument:

- `mode="multi"`, multiple files for reader B grouped with single file for reader A
- `mode="first"`, ensure one-to-one matching by passing only first file for reader A (closest in start time?)
- `mode="strict"`, raise exception if times don't match (may be suitable when reading L1 and L2 data from same sensor)

In case of GLM, the duration of files output from glmtools are configured by the glmtools user, in practice I'd want to configure them to match the ABI times, so for my use case the `strict` mode would be most appropriate.

**Comment by djhoese** [comment]
> mode="first", ensure one-to-one matching by passing only first file for reader A (closest in start time?)

:thinking: but how do you know that only one file should be given? For ABI you could have 1-16 files passed to each Scene, right? Or am I misunderstanding?

**Comment by gerritholl** [comment]
For `"first"`, I mean one file per channel / start time.  I think the different ABI channels always start at the same time, perhaps a second different at most.  But between the start of one ABI CONUS scan and the next there may be many GLM files.  By `"first"` I mean that it would return only the first GLM file starting after ABI has started.  But I'm not sure this is useful.

As for `strict`, maybe this is not actually common if I have 

```
OR_ABI-L1b-RadC-M6C08_G16_s20201041806134_e20201041808507_c20201041808567.nc
OR_ABI-L1b-RadC-M6C08_G16_s20201041811134_e20201041813507_c20201041814016.nc
```

then I have one file covering 2020-02-13T18:06:13.4/18:08:50.7 and one 2020-02-13T18:11:13.4/18:13:50.7.  I'd probably want to aggregate the GLM flashes for the period 18:06:13.4/18:11:13.4 rather than 18:06:13.4/18:08:50.7.  

Just thinking aloud here.  I know I want to be able to pass files from multiple readers to `MultiScene.from_files` but I don't yet know how I want that it behaves exactly...
