### ISSUE TITLE
High resolution 'true_color' composite issue for Himawari-8 AHI

### ISSUE THREAD

**Issue by andyprata** [pytroll/satpy#127]
#### Code Sample, a minimal, complete, and verifiable piece of code

```python
from satpy.scene import Scene
from datetime import datetime, timedelta


ppp_config_directory = "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/satpy-0.7.5-py2.7.egg/satpy/etc/"
path = "/Users/andyprata/Documents/python/himawari-8/hsd"
path_output = "/Users/andyprata/Documents/python/himawari-8/png/"

time_slot = datetime(2017, 11, 26, 23)
time_slot_str = time_slot.strftime("%Y%m%d%H%M")
fn_out = 'global_hima_'+time_slot_str
print "Processing: "+time_slot_str
global_scene = Scene(platform_name="Himawari-8", sensor="ahi", reader="ahi_hsd",
                     start_time=time_slot,
                     end_time=time_slot + timedelta(minutes=10),
                     base_dir=path,
                     ppp_config_dir=ppp_config_directory)

rgb_composite = 'true_color'
print "Loading composite: "+rgb_composite
global_scene.load([rgb_composite])
print "Saving file..."
global_scene.save_dataset(rgb_composite, path_output+fn_out+'_'+rgb_composite+'.png')
print "Done. File saved here: " + path_output+fn_out+'_'+rgb_composite+'.png'
```
#### Problem description
The issue has been described here: https://groups.google.com/forum/#!topic/pytroll/pN9JLV2j-88
The above code results in the following error: 
KeyError: "No dataset matching 'true_color' found"
The following workaround can be used to avoid the above error, but the output is not the expected result:
```python
local_scene = global_scene.resample(global_scene['B03'].info['area'])
local_scene.save_dataset(rgb_composite, path_output+fn_out+'_'+rgb_composite+'.png')
```
#### Expected Output
![image](https://user-images.githubusercontent.com/8485285/34017626-92be657c-e17a-11e7-94ac-09ae393f8258.png)
Note: this image was generated using the 'true_color_reducedsize' composite.
#### Actual Result, Traceback if applicable
![image](https://user-images.githubusercontent.com/8485285/34017665-be45c3e8-e17a-11e7-982a-384ff9b02c5d.png)

#### Versions of Python, package at hand and relevant dependencies
Python version: 2.7.14
NumPy version: 1.13.1

**Comment by mraspaud** [comment]
This is now fixed in #130 .
