### ISSUE TITLE
Trying to get Earth's semimajor and semiminor axis size from HRIT files

### ISSUE THREAD

**Issue by xcalbet** [pytroll/satpy#1278]
**Describe the bug**
With an older version of satpy (0.16.1) i was getting parameters a and b from the geos projection when reading MSG HRIT files. The ode below was running perfectly. I have now updated to version 0.22.0 and besides getting a nasty warning "UserWarning: You will likely lose important projection information when converting to a PROJ string from another format" the parameter b is gone from the area attribute and I can no longer feed this value into cartopy (or basemap) any more.

**To Reproduce**

```python
from satpy import Scene
from satpy.writers import to_image
from glob import glob
import numpy as np

import matplotlib.pyplot as plt
import cartopy.crs as ccrs
import cartopy.feature as cpf

# Collecting all filenames with this signature
files=glob("./Sat_data/*201907020000*")
# Ingesting them in global_scene
global_scene=Scene(reader="seviri_l1b_hrit",filenames=files)

# Show available dataset names
print("Available datasets")
print(global_scene.available_dataset_names())
# Show available composites (RGB) to generate
print("Available composites")
print(global_scene.available_composite_names())

# Loading 10.8 MSG channel
global_scene.load(['IR_108'])

# Printing contents of variable to have a look
print("start print global_scene -----------------------------------------")
print(global_scene)
print("end   print global_scene -----------------------------------------")

# Loading an airmass RGB (composite)
global_scene.load(['airmass'])

# And saving it in a PNG image file
global_scene.save_dataset('airmass','airmass.png')

# What kind of object is global_scene?
print(type(global_scene['IR_108']))

# We now want to navigate the scene
# We extract the 10.8 scene from global_scene
scn108=global_scene['IR_108']
# Extract resolution information
resolution=scn108.attrs['resolution']

# Extracting area attribute
print("area =",scn108.attrs['area'])
area=scn108.attrs['area']
print("area =",area)
print(type(area))
# Getting projection parameters from area attribute
print(area.proj_dict)
a=area.proj_dict['a']
b=area.proj_dict['b']
h=area.proj_dict['h']
print("a,b,h=",a,b,h)
proj=area.proj_dict['proj']
lon0=area.proj_dict['lon_0']
# And the corners of the image
urx=area.area_extent[0]
ury=area.area_extent[1]
llx=area.area_extent[2]
lly=area.area_extent[3]
print("ur=",urx,ury)
print("ll=",llx,lly)

crs_geo=ccrs.Geostationary(central_longitude=0.0,satellite_height=35785863.0,globe=ccrs.Globe(semimajor_axis=6378137.0,semiminor_axis=6356752.3))

#crs_geo=ccrs.Geostationary(central_longitude=0.0,satellite_height=35785863.0)

# We open basemap with the right projection and corners
ax=plt.axes(projection=crs_geo)
plt.imshow(scn108[-1::-1,-1::-1],origin='upper',extent=(llx,urx,lly,ury),transform=crs_geo,cmap='hot')
ax.coastlines(resolution="10m")
plt.colorbar()
plt.show()

## We have all the info now to plot the image
## with proper navigation
#m=Basemap(projection=proj,llcrnrx=llx,llcrnry=lly,\
#          urcrnrx=urx,urcrnry=ury,resolution='l',\
#          satellite_height=h,lon_0=lon0,\
#          rsphere=(a,b))
#
## Coastlines
#m.drawcoastlines(color='red',linewidth=1)
## Country borders
#m.drawcountries(color='orange')
#
#m.imshow(scn108[-1::-1,-1::-1],origin='upper',cmap='hot')
#plt.colorbar()
#plt.show()


```

**Expected behavior**
Expect to get both semi axis for the Earth (a  and b) to be able to use cartopy properly

**Actual results**
Available datasets
['HRV', 'IR_016', 'IR_039', 'IR_087', 'IR_097', 'IR_108', 'IR_120', 'IR_134', 'VIS006', 'VIS008', 'WV_062', 'WV_073']
Available composites
['airmass', 'ash', 'cloudtop', 'cloudtop_daytime', 'colorized_ir_clouds', 'convection', 'day_microphysics', 'day_microphysics_winter', 'dust', 'fog', 'green_snow', 'hrv_clouds', 'hrv_fog', 'hrv_severe_storms', 'hrv_severe_storms_masked', 'ir108_3d', 'ir_cloud_day', 'ir_overview', 'ir_sandwich', 'natural_color', 'natural_color_nocorr', 'natural_color_raw', 'natural_color_with_night_ir', 'natural_color_with_night_ir_hires', 'natural_enh', 'natural_with_night_fog', 'night_fog', 'night_ir_alpha', 'night_ir_with_background', 'night_ir_with_background_hires', 'night_microphysics', 'overview', 'overview_raw', 'realistic_colors', 'snow', 'vis_sharpened_ir']
/home/xcalbet/.local/lib/python3.6/site-packages/pyproj/crs/crs.py:543: UserWarning: You will likely lose important projection information when converting to a PROJ string from another format. See: https://proj.org/faq.html#what-is-the-best-format-for-describing-coordinate-reference-systems
  proj_string = self.to_proj4()
/home/xcalbet/.local/lib/python3.6/site-packages/pyproj/crs/crs.py:543: UserWarning: You will likely lose important projection information when converting to a PROJ string from another format. See: https://proj.org/faq.html#what-is-the-best-format-for-describing-coordinate-reference-systems
  proj_string = self.to_proj4()
/home/xcalbet/.local/lib/python3.6/site-packages/pyproj/crs/crs.py:543: UserWarning: You will likely lose important projection information when converting to a PROJ string from another format. See: https://proj.org/faq.html#what-is-the-best-format-for-describing-coordinate-reference-systems
  proj_string = self.to_proj4()
/home/xcalbet/.local/lib/python3.6/site-packages/pyproj/crs/crs.py:543: UserWarning: You will likely lose important projection information when converting to a PROJ string from another format. See: https://proj.org/faq.html#what-is-the-best-format-for-describing-coordinate-reference-systems
  proj_string = self.to_proj4()
/home/xcalbet/.local/lib/python3.6/site-packages/pyproj/crs/crs.py:543: UserWarning: You will likely lose important projection information when converting to a PROJ string from another format. See: https://proj.org/faq.html#what-is-the-best-format-for-describing-coordinate-reference-systems
  proj_string = self.to_proj4()
/home/xcalbet/.local/lib/python3.6/site-packages/pyproj/crs/crs.py:543: UserWarning: You will likely lose important projection information when converting to a PROJ string from another format. See: https://proj.org/faq.html#what-is-the-best-format-for-describing-coordinate-reference-systems
  proj_string = self.to_proj4()
/home/xcalbet/.local/lib/python3.6/site-packages/pyproj/crs/crs.py:543: UserWarning: You will likely lose important projection information when converting to a PROJ string from another format. See: https://proj.org/faq.html#what-is-the-best-format-for-describing-coordinate-reference-systems
  proj_string = self.to_proj4()
start print global_scene -----------------------------------------
/home/xcalbet/.local/lib/python3.6/site-packages/pyproj/crs/crs.py:543: UserWarning: You will likely lose important projection information when converting to a PROJ string from another format. See: https://proj.org/faq.html#what-is-the-best-format-for-describing-coordinate-reference-systems
  proj_string = self.to_proj4()
<xarray.DataArray 'reshape-78da6164fbe814142dcc17eeef5a7591' (y: 3712, x: 3712)>
dask.array<concatenate, shape=(3712, 3712), dtype=float32, chunksize=(464, 3712), chunktype=numpy.ndarray>
Coordinates:
    acq_time  (y) datetime64[ns] NaT NaT NaT NaT NaT NaT ... NaT NaT NaT NaT NaT
    crs       object PROJCRS["unknown",BASEGEOGCRS["unknown",DATUM["unknown",...
  * y         (y) float64 -5.566e+06 -5.563e+06 ... 5.566e+06 5.569e+06
  * x         (x) float64 5.566e+06 5.563e+06 5.56e+06 ... -5.566e+06 -5.569e+06
Attributes:
    satellite_longitude:      0.0
    satellite_latitude:       0.0
    satellite_altitude:       35785831.0
    orbital_parameters:       {'projection_longitude': 0.0, 'projection_latit...
    raw_metadata:             {'file_type': 0, 'total_header_length': 6198, '...
    platform_name:            Meteosat-11
    wavelength:               (9.8, 10.8, 11.8)
    standard_name:            toa_brightness_temperature
    georef_offset_corrected:  True
    sensor:                   seviri
    units:                    K
    start_time:               2019-07-02 00:00:09.169000
    end_time:                 2019-07-02 00:12:41.964000
    area:                     Area ID: geosmsg\nDescription: MSG/SEVIRI low r...
    name:                     IR_108
    resolution:               3000.403165817
    calibration:              brightness_temperature
    polarization:             None
    level:                    None
    modifiers:                ()
    ancillary_variables:      []
end   print global_scene -----------------------------------------
/home/xcalbet/.local/lib/python3.6/site-packages/pyproj/crs/crs.py:543: UserWarning: You will likely lose important projection information when converting to a PROJ string from another format. See: https://proj.org/faq.html#what-is-the-best-format-for-describing-coordinate-reference-systems
  proj_string = self.to_proj4()
/home/xcalbet/.local/lib/python3.6/site-packages/pyproj/crs/crs.py:543: UserWarning: You will likely lose important projection information when converting to a PROJ string from another format. See: https://proj.org/faq.html#what-is-the-best-format-for-describing-coordinate-reference-systems
  proj_string = self.to_proj4()
/home/xcalbet/.local/lib/python3.6/site-packages/pyproj/crs/crs.py:543: UserWarning: You will likely lose important projection information when converting to a PROJ string from another format. See: https://proj.org/faq.html#what-is-the-best-format-for-describing-coordinate-reference-systems
  proj_string = self.to_proj4()
/home/xcalbet/.local/lib/python3.6/site-packages/pyproj/crs/crs.py:543: UserWarning: You will likely lose important projection information when converting to a PROJ string from another format. See: https://proj.org/faq.html#what-is-the-best-format-for-describing-coordinate-reference-systems
  proj_string = self.to_proj4()
/home/xcalbet/.local/lib/python3.6/site-packages/pyproj/crs/crs.py:543: UserWarning: You will likely lose important projection information when converting to a PROJ string from another format. See: https://proj.org/faq.html#what-is-the-best-format-for-describing-coordinate-reference-systems
  proj_string = self.to_proj4()
/home/xcalbet/.local/lib/python3.6/site-packages/pyproj/crs/crs.py:543: UserWarning: You will likely lose important projection information when converting to a PROJ string from another format. See: https://proj.org/faq.html#what-is-the-best-format-for-describing-coordinate-reference-systems
  proj_string = self.to_proj4()
/home/xcalbet/.local/lib/python3.6/site-packages/pyproj/crs/crs.py:543: UserWarning: You will likely lose important projection information when converting to a PROJ string from another format. See: https://proj.org/faq.html#what-is-the-best-format-for-describing-coordinate-reference-systems
  proj_string = self.to_proj4()
/home/xcalbet/.local/lib/python3.6/site-packages/pyproj/crs/crs.py:543: UserWarning: You will likely lose important projection information when converting to a PROJ string from another format. See: https://proj.org/faq.html#what-is-the-best-format-for-describing-coordinate-reference-systems
  proj_string = self.to_proj4()
/home/xcalbet/.local/lib/python3.6/site-packages/pyproj/crs/crs.py:543: UserWarning: You will likely lose important projection information when converting to a PROJ string from another format. See: https://proj.org/faq.html#what-is-the-best-format-for-describing-coordinate-reference-systems
  proj_string = self.to_proj4()
/home/xcalbet/.local/lib/python3.6/site-packages/pyproj/crs/crs.py:543: UserWarning: You will likely lose important projection information when converting to a PROJ string from another format. See: https://proj.org/faq.html#what-is-the-best-format-for-describing-coordinate-reference-systems
  proj_string = self.to_proj4()
/home/xcalbet/.local/lib/python3.6/site-packages/pyproj/crs/crs.py:543: UserWarning: You will likely lose important projection information when converting to a PROJ string from another format. See: https://proj.org/faq.html#what-is-the-best-format-for-describing-coordinate-reference-systems
  proj_string = self.to_proj4()
/home/xcalbet/.local/lib/python3.6/site-packages/pyproj/crs/crs.py:543: UserWarning: You will likely lose important projection information when converting to a PROJ string from another format. See: https://proj.org/faq.html#what-is-the-best-format-for-describing-coordinate-reference-systems
  proj_string = self.to_proj4()
/home/xcalbet/.local/lib/python3.6/site-packages/pyproj/crs/crs.py:543: UserWarning: You will likely lose important projection information when converting to a PROJ string from another format. See: https://proj.org/faq.html#what-is-the-best-format-for-describing-coordinate-reference-systems
  proj_string = self.to_proj4()
/home/xcalbet/.local/lib/python3.6/site-packages/pyproj/crs/crs.py:543: UserWarning: You will likely lose important projection information when converting to a PROJ string from another format. See: https://proj.org/faq.html#what-is-the-best-format-for-describing-coordinate-reference-systems
  proj_string = self.to_proj4()
/home/xcalbet/.local/lib/python3.6/site-packages/pyproj/crs/crs.py:543: UserWarning: You will likely lose important projection information when converting to a PROJ string from another format. See: https://proj.org/faq.html#what-is-the-best-format-for-describing-coordinate-reference-systems
  proj_string = self.to_proj4()
/home/xcalbet/.local/lib/python3.6/site-packages/pyproj/crs/crs.py:543: UserWarning: You will likely lose important projection information when converting to a PROJ string from another format. See: https://proj.org/faq.html#what-is-the-best-format-for-describing-coordinate-reference-systems
  proj_string = self.to_proj4()
/home/xcalbet/.local/lib/python3.6/site-packages/pyproj/crs/crs.py:543: UserWarning: You will likely lose important projection information when converting to a PROJ string from another format. See: https://proj.org/faq.html#what-is-the-best-format-for-describing-coordinate-reference-systems
  proj_string = self.to_proj4()
/home/xcalbet/.local/lib/python3.6/site-packages/pyproj/crs/crs.py:543: UserWarning: You will likely lose important projection information when converting to a PROJ string from another format. See: https://proj.org/faq.html#what-is-the-best-format-for-describing-coordinate-reference-systems
  proj_string = self.to_proj4()
/home/xcalbet/.local/lib/python3.6/site-packages/pyproj/crs/crs.py:543: UserWarning: You will likely lose important projection information when converting to a PROJ string from another format. See: https://proj.org/faq.html#what-is-the-best-format-for-describing-coordinate-reference-systems
  proj_string = self.to_proj4()
/home/xcalbet/.local/lib/python3.6/site-packages/pyproj/crs/crs.py:543: UserWarning: You will likely lose important projection information when converting to a PROJ string from another format. See: https://proj.org/faq.html#what-is-the-best-format-for-describing-coordinate-reference-systems
  proj_string = self.to_proj4()
/home/xcalbet/.local/lib/python3.6/site-packages/pyproj/crs/crs.py:543: UserWarning: You will likely lose important projection information when converting to a PROJ string from another format. See: https://proj.org/faq.html#what-is-the-best-format-for-describing-coordinate-reference-systems
  proj_string = self.to_proj4()
/home/xcalbet/.local/lib/python3.6/site-packages/pyproj/crs/crs.py:543: UserWarning: You will likely lose important projection information when converting to a PROJ string from another format. See: https://proj.org/faq.html#what-is-the-best-format-for-describing-coordinate-reference-systems
  proj_string = self.to_proj4()
/home/xcalbet/.local/lib/python3.6/site-packages/pyproj/crs/crs.py:543: UserWarning: You will likely lose important projection information when converting to a PROJ string from another format. See: https://proj.org/faq.html#what-is-the-best-format-for-describing-coordinate-reference-systems
  proj_string = self.to_proj4()
<class 'xarray.core.dataarray.DataArray'>
area = Area ID: geosmsg
Description: MSG/SEVIRI low resolution channel area
Projection ID: msg_lowres
Projection: {'a': '6378169', 'h': '35785831', 'lon_0': '0', 'no_defs': 'None', 'proj': 'geos', 'rf': '295.488065897014', 'type': 'crs', 'units': 'm', 'x_0': '0', 'y_0': '0'}
Number of columns: 3712
Number of rows: 3712
Area extent: (5567248.2834, 5570248.6867, -5570248.6867, -5567248.2834)
area = Area ID: geosmsg
Description: MSG/SEVIRI low resolution channel area
Projection ID: msg_lowres
Projection: {'a': '6378169', 'h': '35785831', 'lon_0': '0', 'no_defs': 'None', 'proj': 'geos', 'rf': '295.488065897014', 'type': 'crs', 'units': 'm', 'x_0': '0', 'y_0': '0'}
Number of columns: 3712
Number of rows: 3712
Area extent: (5567248.2834, 5570248.6867, -5570248.6867, -5567248.2834)
<class 'pyresample.geometry.AreaDefinition'>
{'proj': 'geos', 'lon_0': 0, 'h': 35785831, 'x_0': 0, 'y_0': 0, 'a': 6378169, 'rf': 295.488065897014, 'units': 'm', 'no_defs': None, 'type': 'crs'}
Traceback (most recent call last):
  File "readHRIT.py", line 53, in <module>
    b=area.proj_dict['b']
KeyError: 'b'

**Screenshots**

**Environment Info:**
 - OS: [e.g. OSX, Windows, Linux]
 - Satpy Version: [e.g. 0.9.0]
 - PyResample Version:
 - Readers and writers dependencies (when relevant): [run `from satpy.config import check_satpy; check_satpy()`]

**Additional context**

**Comment by simonrp84** [comment]
Hi @xcalbet. I also encountered this problem, it is because of changes to upstream libraries (proj, I think).
But luckily there is a solution!

If you edit your code to include this then it should work:
```
a = area.proj_dict['a']
rf = proj_dict['rf']
b = a - (a / rf)
```

**Comment by xcalbet** [comment]
Thanks Simon! I was trying to figure out what rf was to no avail. Now I know!!
I have found another solution, which also gets rid of the nasty warnings. Downgrade pyproj to 1.9.6
pip install pyproj==1.9.6

**Comment by simonrp84** [comment]
rf is the flattening radius, i.e: Difference between the polar and equatorial radii. Glad it works! :+1:

**Comment by mraspaud** [comment]
For completeness, another alternative that works with pyproj >= 2.0:
```python
a = area.crs.ellipsoid.semi_major_metre
b = area.crs.ellipsoid.semi_minor_metre
```

Closing this issue, as it seems to be solved.
