### ISSUE TITLE
update _makedirs in satpy.demo

### ISSUE THREAD

**Issue by raybellwaves** [pytroll/satpy#1289]
Given python 2 is dropped
https://satpy.readthedocs.io/en/latest/dev_guide/index.html#coding-guidelines

Could get rid of the comment/code about `exist_ok=True` and update the `_makedirs` function

https://github.com/pytroll/satpy/blob/master/satpy/demo/__init__.py#L59L68

**Comment by djhoese** [comment]
Similar to #1293, this could be a good "foot in the door" contribution. What do you think?

**Comment by djhoese** [comment]
@mraspaud I marked this as a bug since we don't really have a "cleanup" label. Maybe we need a cleanup label and a "component:tests" label?

**Comment by mraspaud** [comment]
Sure!
