### ISSUE TITLE
Feature Request: update to Quickstart to use data from the demo module

### ISSUE THREAD

**Issue by raybellwaves** [pytroll/satpy#1292]
It would be useful to add in an example of using data generated by the demo module e.g. https://satpy.readthedocs.io/en/latest/api/satpy.demo.html#satpy.demo.get_hurricane_florence_abi

**Comment by djhoese** [comment]
I think I'm going to close this as a duplicate of https://github.com/pytroll/pytroll-examples/issues/29. Thanks for all these suggested improvements.
