### ISSUE TITLE
DOC: broken link for geoview

### ISSUE THREAD

**Issue by raybellwaves** [pytroll/satpy#1293]
https://satpy.readthedocs.io/en/latest/quickstart.html#visualizing-data

Points to http://geo.holoviews.org/index.html believe it should be https://geoviews.org/

**Comment by djhoese** [comment]
Thanks for the issue @raybellwaves. These typos/URL issues seem like a good chance for you to get your foot in the door contributing to Satpy. Do you want to take a crack as fixing these and submitting a pull request?
