### ISSUE TITLE
AAPP AVHRR level 1 reader raises a Value error when a channel is missing

### ISSUE THREAD

**Issue by mraspaud** [pytroll/satpy#1330]
**Describe the bug**
Trying to read a missing 3a or 3b channel from the aapp l1b reader raises a ValueError, which is not what satpy usually does for missing channels (KeyError is usually raised).

**To Reproduce**

```python
# Your code here
from satpy.scene import Scene
from satpy.utils import debug_on
debug_on()

scn = Scene(reader='avhrr_l1b_aapp',
            filenames=['/home/a001673/data/satellite/aappl1b/hrpt_noaa18_20190610_1702_72429.l1b'],
            )
channel = '3a'
scn.load([channel])
```

**Expected behavior**
I would expect the reader to handle the missing channels as other reader do. In this case, I believe implementing the channel availability mechanism would help.

**Actual results**
```python-traceback
Traceback (most recent call last):
  File "/home/a001673/usr/src/satpy/satpy/readers/yaml_reader.py", line 785, in _load_dataset_with_area
    ds = self._load_dataset_data(file_handlers, dsid, **kwargs)
  File "/home/a001673/usr/src/satpy/satpy/readers/yaml_reader.py", line 668, in _load_dataset_data
    proj = self._load_dataset(dsid, ds_info, file_handlers, **kwargs)
  File "/home/a001673/usr/src/satpy/satpy/readers/yaml_reader.py", line 644, in _load_dataset
    projectable = fh.get_dataset(dsid, ds_info)
  File "/home/a001673/usr/src/satpy/satpy/readers/aapp_l1b.py", line 112, in get_dataset
    dataset = self.calibrate(key)
  File "/home/a001673/usr/src/satpy/satpy/readers/aapp_l1b.py", line 234, in calibrate
    raise ValueError("Empty dataset for channel 3A")
ValueError: Empty dataset for channel 3A
```

**Environment Info:**
 - OS: Linux
 - Satpy Version: latest master, after 0.22.0

**Comment by mraspaud** [comment]
@djhoese I quickly implemented an `available_datasets` method in that filehandler. It seems to work in that the list of available datasets doesn't include `3a` (using the example above). However, trying to load the dataset still goes all the way to `get_dataset`. Is this a feature or a bug?

**Comment by djhoese** [comment]
@mraspaud What does `scn.available_dataset_ids()` show? I don't remember what time of day I have in my test files but I see 3a and 3b both listed as available.

**Comment by mraspaud** [comment]
At the moment, `available_datasets` isn't implemented so `scn.available_dataset_ids()` shows both. With the function added, I get the expected result (`3a` missing).

**Comment by djhoese** [comment]
Ah ok, it is something you are working on. What should happen is that `available_datasets` from the file handler will end up filling the reader's `available_dataset_ids`. The `get_dataset_key` of the base yaml reader class is meant to check `self.available_ids` first then check `self.all_ids`. The dependency tree is supposed to use this `get_dataset_key` to determine whether or not it *knows* of a dataset and whether or not it is available and should be attempted for loading.

**Comment by mraspaud** [comment]
ah, yes, the `available_only` flag, I remember that.
