### ISSUE TITLE
SEVIRI reader doesn't include Earth-Sun distance in the rad->refl calibration

### ISSUE THREAD

**Issue by simonrp84** [pytroll/satpy#1334]
**Describe the bug**
The [EUMETSAT document](https://www.eumetsat.int/website/wcm/idc/idcplg?IdcService=GET_FILE&dDocName=PDF_MSG_SEVIRI_RAD2REFL&RevisionSelectionMethod=LatestReleased&Rendition=Web) describing solar channel calibration states that, neglecting solar zenith angle, the radiance-to-reflectance calculation should be:
```
reflectance = (pi * radiance * d * d) / solar_irradiance
```
But satpy uses:
```
reflectance = radiance / (solar_irradiance / pi)
```

The `d^2` term, specifying the Earth-Sun distance, is missing and the `pi` is included in the look-up table for solar irradiance rather than being explicitly part of the calculation.

This should be corrected, to ensure that satpy is correctly calculating the reflectance values.

**Additional context**
This issue is primarily to remind me to fix this with a PR.

**Comment by mraspaud** [comment]
This is related to #536 
I think the first step is to see if everyone agrees on having the sun-earth distance include by default.
I we do, we need to make sure all the reader have it applied.
Otherwise, we need to start working on the reader-included modifiers presented in the aforementioned issue.

**Comment by gerritholl** [comment]
It would have to be included in any product calibrated as a "reflectance", by definition of reflectance.  If there is a user need for a product that does not include this, then that could be included with a different name (I don't know what this name would be).
