### ISSUE TITLE
Problem with making MODIS L1 images

### ISSUE THREAD

**Issue by anikfal** [pytroll/satpy#1336]
MODIS L1 file name: MOD021KM.A2020217.1905.061.2020218071403.hdf
Codes are according to: https://github.com/pytroll/pytroll-examples/blob/master/satpy/satpy_rayleigh_modis.ipynb

**Code 1:**
```python
from satpy.scene import Scene
from satpy import find_files_and_readers
from datetime import datetime
files = find_files_and_readers(base_dir='/home/anikfal/datamsg8/modis',
                               sensor="modis",
                               reader='modis_l1b')
scn = Scene(filenames=files)
composite_name = 'true_color'
scn.load([composite_name], resolution=1000)
scn.save_datasets(writer='simple_image')
```
**Error message 1:**
> Traceback (most recent call last):
  File "4.py", line 9, in <module>
    scn.load([composite_name], resolution=1000)
  File "/home/anikfal/miniconda3/envs/mysat/lib/python3.8/site-packages/satpy/scene.py", line 975, in load
    keepables = self.generate_composites()
  File "/home/anikfal/miniconda3/envs/mysat/lib/python3.8/site-packages/satpy/scene.py", line 888, in generate_composites
    return self._read_composites(nodes)
  File "/home/anikfal/miniconda3/envs/mysat/lib/python3.8/site-packages/satpy/scene.py", line 863, in _read_composites
    self._generate_composite(item, keepables)
  File "/home/anikfal/miniconda3/envs/mysat/lib/python3.8/site-packages/satpy/scene.py", line 836, in _generate_composite
    composite = compositor(prereq_datasets,
  File "/home/anikfal/miniconda3/envs/mysat/lib/python3.8/site-packages/satpy/composites/__init__.py", line 565, in __call__
    rayleigh_key = (vis.attrs['platform_name'],
KeyError: 'platform_name'

Code 2 generates an empty png image, without any error/warning:
**Code 2:**
```python
from satpy.scene import Scene
from satpy import find_files_and_readers
from datetime import datetime
files = find_files_and_readers(base_dir='/home/anikfal/datamsg8/modis',
                               sensor="modis",
                               reader='modis_l1b')
scn = Scene(filenames=files)
scn.load(wishlist=['2'], resolution=1000)
scn.save_datasets(writer='simple_image')
```
**Output of scn.available_dataset_ids():**
> [DatasetID(name='1', wavelength=(0.62, 0.645, 0.67), resolution=1000, polarization=None, calibration='counts', level=None, modifiers=()), DatasetID(name='1', wavelength=(0.62, 0.645, 0.67), resolution=1000, polarization=None, calibration='radiance', level=None, modifiers=()), DatasetID(name='1', wavelength=(0.62, 0.645, 0.67), resolution=1000, polarization=None, calibration='reflectance', level=None, modifiers=()), DatasetID(name='10', wavelength=(0.483, 0.488, 0.493), resolution=1000, polarization=None, calibration='counts', level=None, modifiers=()), DatasetID(name='10', wavelength=(0.483, 0.488, 0.493), resolution=1000, polarization=None, calibration='radiance', level=None, modifiers=()), DatasetID(name='10', wavelength=(0.483, 0.488, 0.493), resolution=1000, polarization=None, calibration='reflectance', level=None, modifiers=()), DatasetID(name='11', wavelength=(0.526, 0.531, 0.536), resolution=1000, polarization=None, calibration='counts', level=None, modifiers=()), DatasetID(name='11', wavelength=(0.526, 0.531, 0.536), resolution=1000, polarization=None, calibration='radiance', level=None, modifiers=()), DatasetID(name='11', wavelength=(0.526, 0.531, 0.536), resolution=1000, polarization=None, calibration='reflectance', level=None, modifiers=()), DatasetID(name='12', wavelength=(0.546, 0.551, 0.556), resolution=1000, polarization=None, calibration='counts', level=None, modifiers=()), DatasetID(name='12', wavelength=(0.546, 0.551, 0.556), resolution=1000, polarization=None, calibration='radiance', level=None, modifiers=()), DatasetID(name='12', wavelength=(0.546, 0.551, 0.556), resolution=1000, polarization=None, calibration='reflectance', level=None, modifiers=()), DatasetID(name='13hi', wavelength=(0.662, 0.667, 0.672), resolution=1000, polarization=None, calibration='counts', level=None, modifiers=()), DatasetID(name='13hi', wavelength=(0.662, 0.667, 0.672), resolution=1000, polarization=None, calibration='radiance', level=None, modifiers=()), DatasetID(name='13hi', wavelength=(0.662, 0.667, 0.672), resolution=1000, polarization=None, calibration='reflectance', level=None, modifiers=()), DatasetID(name='13lo', wavelength=(0.662, 0.667, 0.672), resolution=1000, polarization=None, calibration='counts', level=None, modifiers=()), DatasetID(name='13lo', wavelength=(0.662, 0.667, 0.672), resolution=1000, polarization=None, calibration='radiance', level=None, modifiers=()), DatasetID(name='13lo', wavelength=(0.662, 0.667, 0.672), resolution=1000, polarization=None, calibration='reflectance', level=None, modifiers=()), DatasetID(name='14hi', wavelength=(0.673, 0.678, 0.683), resolution=1000, polarization=None, calibration='counts', level=None, modifiers=()), DatasetID(name='14hi', wavelength=(0.673, 0.678, 0.683), resolution=1000, polarization=None, calibration='radiance', level=None, modifiers=()), DatasetID(name='14hi', wavelength=(0.673, 0.678, 0.683), resolution=1000, polarization=None, calibration='reflectance', level=None, modifiers=()), DatasetID(name='14lo', wavelength=(0.673, 0.678, 0.683), resolution=1000, polarization=None, calibration='counts', level=None, modifiers=()), DatasetID(name='14lo', wavelength=(0.673, 0.678, 0.683), resolution=1000, polarization=None, calibration='radiance', level=None, modifiers=()), DatasetID(name='14lo', wavelength=(0.673, 0.678, 0.683), resolution=1000, polarization=None, calibration='reflectance', level=None, modifiers=()), DatasetID(name='15', wavelength=(0.743, 0.748, 0.753), resolution=1000, polarization=None, calibration='counts', level=None, modifiers=()), DatasetID(name='15', wavelength=(0.743, 0.748, 0.753), resolution=1000, polarization=None, calibration='radiance', level=None, modifiers=()), DatasetID(name='15', wavelength=(0.743, 0.748, 0.753), resolution=1000, polarization=None, calibration='reflectance', level=None, modifiers=()), DatasetID(name='16', wavelength=(0.862, 0.8695, 0.877), resolution=1000, polarization=None, calibration='counts', level=None, modifiers=()), DatasetID(name='16', wavelength=(0.862, 0.8695, 0.877), resolution=1000, polarization=None, calibration='radiance', level=None, modifiers=()), DatasetID(name='16', wavelength=(0.862, 0.8695, 0.877), resolution=1000, polarization=None, calibration='reflectance', level=None, modifiers=()), DatasetID(name='17', wavelength=(0.89, 0.905, 0.92), resolution=1000, polarization=None, calibration='counts', level=None, modifiers=()), DatasetID(name='17', wavelength=(0.89, 0.905, 0.92), resolution=1000, polarization=None, calibration='radiance', level=None, modifiers=()), DatasetID(name='17', wavelength=(0.89, 0.905, 0.92), resolution=1000, polarization=None, calibration='reflectance', level=None, modifiers=()), DatasetID(name='18', wavelength=(0.931, 0.936, 0.941), resolution=1000, polarization=None, calibration='counts', level=None, modifiers=()), DatasetID(name='18', wavelength=(0.931, 0.936, 0.941), resolution=1000, polarization=None, calibration='radiance', level=None, modifiers=()), DatasetID(name='18', wavelength=(0.931, 0.936, 0.941), resolution=1000, polarization=None, calibration='reflectance', level=None, modifiers=()), DatasetID(name='19', wavelength=(0.915, 0.94, 0.965), resolution=1000, polarization=None, calibration='counts', level=None, modifiers=()), DatasetID(name='19', wavelength=(0.915, 0.94, 0.965), resolution=1000, polarization=None, calibration='radiance', level=None, modifiers=()), DatasetID(name='19', wavelength=(0.915, 0.94, 0.965), resolution=1000, polarization=None, calibration='reflectance', level=None, modifiers=()), DatasetID(name='2', wavelength=(0.841, 0.8585, 0.876), resolution=1000, polarization=None, calibration='counts', level=None, modifiers=()), DatasetID(name='2', wavelength=(0.841, 0.8585, 0.876), resolution=1000, polarization=None, calibration='radiance', level=None, modifiers=()), DatasetID(name='2', wavelength=(0.841, 0.8585, 0.876), resolution=1000, polarization=None, calibration='reflectance', level=None, modifiers=()), DatasetID(name='20', wavelength=(3.66, 3.75, 3.84), resolution=1000, polarization=None, calibration='brightness_temperature', level=None, modifiers=()), DatasetID(name='20', wavelength=(3.66, 3.75, 3.84), resolution=1000, polarization=None, calibration='radiance', level=None, modifiers=()), DatasetID(name='21', wavelength=(3.929, 3.959, 3.989), resolution=1000, polarization=None, calibration='brightness_temperature', level=None, modifiers=()), DatasetID(name='21', wavelength=(3.929, 3.959, 3.989), resolution=1000, polarization=None, calibration='radiance', level=None, modifiers=()), DatasetID(name='22', wavelength=(3.929, 3.959, 3.989), resolution=1000, polarization=None, calibration='brightness_temperature', level=None, modifiers=()), DatasetID(name='22', wavelength=(3.929, 3.959, 3.989), resolution=1000, polarization=None, calibration='radiance', level=None, modifiers=()), DatasetID(name='23', wavelength=(4.02, 4.05, 4.08), resolution=1000, polarization=None, calibration='brightness_temperature', level=None, modifiers=()), DatasetID(name='23', wavelength=(4.02, 4.05, 4.08), resolution=1000, polarization=None, calibration='radiance', level=None, modifiers=()), DatasetID(name='24', wavelength=(4.433, 4.4655, 4.498), resolution=1000, polarization=None, calibration='brightness_temperature', level=None, modifiers=()), DatasetID(name='24', wavelength=(4.433, 4.4655, 4.498), resolution=1000, polarization=None, calibration='radiance', level=None, modifiers=()), DatasetID(name='25', wavelength=(4.482, 4.5155, 4.549), resolution=1000, polarization=None, calibration='brightness_temperature', level=None, modifiers=()), DatasetID(name='25', wavelength=(4.482, 4.5155, 4.549), resolution=1000, polarization=None, calibration='radiance', level=None, modifiers=()), DatasetID(name='26', wavelength=(1.36, 1.375, 1.39), resolution=1000, polarization=None, calibration='counts', level=None, modifiers=()), DatasetID(name='26', wavelength=(1.36, 1.375, 1.39), resolution=1000, polarization=None, calibration='radiance', level=None, modifiers=()), DatasetID(name='26', wavelength=(1.36, 1.375, 1.39), resolution=1000, polarization=None, calibration='reflectance', level=None, modifiers=()), DatasetID(name='27', wavelength=(6.535, 6.715, 6.895), resolution=1000, polarization=None, calibration='brightness_temperature', level=None, modifiers=()), DatasetID(name='27', wavelength=(6.535, 6.715, 6.895), resolution=1000, polarization=None, calibration='radiance', level=None, modifiers=()), DatasetID(name='28', wavelength=(7.175, 7.325, 7.475), resolution=1000, polarization=None, calibration='brightness_temperature', level=None, modifiers=()), DatasetID(name='28', wavelength=(7.175, 7.325, 7.475), resolution=1000, polarization=None, calibration='radiance', level=None, modifiers=()), DatasetID(name='29', wavelength=(8.4, 8.55, 8.7), resolution=1000, polarization=None, calibration='brightness_temperature', level=None, modifiers=()), DatasetID(name='29', wavelength=(8.4, 8.55, 8.7), resolution=1000, polarization=None, calibration='radiance', level=None, modifiers=()), DatasetID(name='3', wavelength=(0.459, 0.469, 0.479), resolution=1000, polarization=None, calibration='counts', level=None, modifiers=()), DatasetID(name='3', wavelength=(0.459, 0.469, 0.479), resolution=1000, polarization=None, calibration='radiance', level=None, modifiers=()), DatasetID(name='3', wavelength=(0.459, 0.469, 0.479), resolution=1000, polarization=None, calibration='reflectance', level=None, modifiers=()), DatasetID(name='30', wavelength=(9.58, 9.73, 9.88), resolution=1000, polarization=None, calibration='brightness_temperature', level=None, modifiers=()), DatasetID(name='30', wavelength=(9.58, 9.73, 9.88), resolution=1000, polarization=None, calibration='radiance', level=None, modifiers=()), DatasetID(name='31', wavelength=(10.78, 11.03, 11.28), resolution=1000, polarization=None, calibration='brightness_temperature', level=None, modifiers=()), DatasetID(name='31', wavelength=(10.78, 11.03, 11.28), resolution=1000, polarization=None, calibration='radiance', level=None, modifiers=()), DatasetID(name='32', wavelength=(11.77, 12.02, 12.27), resolution=1000, polarization=None, calibration='brightness_temperature', level=None, modifiers=()), DatasetID(name='32', wavelength=(11.77, 12.02, 12.27), resolution=1000, polarization=None, calibration='radiance', level=None, modifiers=()), DatasetID(name='33', wavelength=(13.185, 13.335, 13.485), resolution=1000, polarization=None, calibration='brightness_temperature', level=None, modifiers=()), DatasetID(name='33', wavelength=(13.185, 13.335, 13.485), resolution=1000, polarization=None, calibration='radiance', level=None, modifiers=()), DatasetID(name='34', wavelength=(13.485, 13.635, 13.785), resolution=1000, polarization=None, calibration='brightness_temperature', level=None, modifiers=()), DatasetID(name='34', wavelength=(13.485, 13.635, 13.785), resolution=1000, polarization=None, calibration='radiance', level=None, modifiers=()), DatasetID(name='35', wavelength=(13.785, 13.935, 14.085), resolution=1000, polarization=None, calibration='brightness_temperature', level=None, modifiers=()), DatasetID(name='35', wavelength=(13.785, 13.935, 14.085), resolution=1000, polarization=None, calibration='radiance', level=None, modifiers=()), DatasetID(name='36', wavelength=(14.085, 14.235, 14.385), resolution=1000, polarization=None, calibration='brightness_temperature', level=None, modifiers=()), DatasetID(name='36', wavelength=(14.085, 14.235, 14.385), resolution=1000, polarization=None, calibration='radiance', level=None, modifiers=()), DatasetID(name='4', wavelength=(0.545, 0.555, 0.565), resolution=1000, polarization=None, calibration='counts', level=None, modifiers=()), DatasetID(name='4', wavelength=(0.545, 0.555, 0.565), resolution=1000, polarization=None, calibration='radiance', level=None, modifiers=()), DatasetID(name='4', wavelength=(0.545, 0.555, 0.565), resolution=1000, polarization=None, calibration='reflectance', level=None, modifiers=()), DatasetID(name='5', wavelength=(1.23, 1.24, 1.25), resolution=1000, polarization=None, calibration='counts', level=None, modifiers=()), DatasetID(name='5', wavelength=(1.23, 1.24, 1.25), resolution=1000, polarization=None, calibration='radiance', level=None, modifiers=()), DatasetID(name='5', wavelength=(1.23, 1.24, 1.25), resolution=1000, polarization=None, calibration='reflectance', level=None, modifiers=()), DatasetID(name='6', wavelength=(1.628, 1.64, 1.652), resolution=1000, polarization=None, calibration='counts', level=None, modifiers=()), DatasetID(name='6', wavelength=(1.628, 1.64, 1.652), resolution=1000, polarization=None, calibration='radiance', level=None, modifiers=()), DatasetID(name='6', wavelength=(1.628, 1.64, 1.652), resolution=1000, polarization=None, calibration='reflectance', level=None, modifiers=()), DatasetID(name='7', wavelength=(2.105, 2.13, 2.155), resolution=1000, polarization=None, calibration='counts', level=None, modifiers=()), DatasetID(name='7', wavelength=(2.105, 2.13, 2.155), resolution=1000, polarization=None, calibration='radiance', level=None, modifiers=()), DatasetID(name='7', wavelength=(2.105, 2.13, 2.155), resolution=1000, polarization=None, calibration='reflectance', level=None, modifiers=()), DatasetID(name='8', wavelength=(0.405, 0.4125, 0.42), resolution=1000, polarization=None, calibration='counts', level=None, modifiers=()), DatasetID(name='8', wavelength=(0.405, 0.4125, 0.42), resolution=1000, polarization=None, calibration='radiance', level=None, modifiers=()), DatasetID(name='8', wavelength=(0.405, 0.4125, 0.42), resolution=1000, polarization=None, calibration='reflectance', level=None, modifiers=()), DatasetID(name='9', wavelength=(0.438, 0.443, 0.448), resolution=1000, polarization=None, calibration='counts', level=None, modifiers=()), DatasetID(name='9', wavelength=(0.438, 0.443, 0.448), resolution=1000, polarization=None, calibration='radiance', level=None, modifiers=()), DatasetID(name='9', wavelength=(0.438, 0.443, 0.448), resolution=1000, polarization=None, calibration='reflectance', level=None, modifiers=()), DatasetID(name='latitude', wavelength=None, resolution=1000, polarization=None, calibration=None, level=None, modifiers=()), DatasetID(name='latitude', wavelength=None, resolution=5000, polarization=None, calibration=None, level=None, modifiers=()), DatasetID(name='longitude', wavelength=None, resolution=1000, polarization=None, calibration=None, level=None, modifiers=()), DatasetID(name='longitude', wavelength=None, resolution=5000, polarization=None, calibration=None, level=None, modifiers=()), DatasetID(name='satellite_azimuth_angle', wavelength=None, resolution=250, polarization=None, calibration=None, level=None, modifiers=()), DatasetID(name='satellite_azimuth_angle', wavelength=None, resolution=500, polarization=None, calibration=None, level=None, modifiers=()), DatasetID(name='satellite_azimuth_angle', wavelength=None, resolution=1000, polarization=None, calibration=None, level=None, modifiers=()), DatasetID(name='satellite_zenith_angle', wavelength=None, resolution=250, polarization=None, calibration=None, level=None, modifiers=()), DatasetID(name='satellite_zenith_angle', wavelength=None, resolution=500, polarization=None, calibration=None, level=None, modifiers=()), DatasetID(name='satellite_zenith_angle', wavelength=None, resolution=1000, polarization=None, calibration=None, level=None, modifiers=()), DatasetID(name='solar_azimuth_angle', wavelength=None, resolution=250, polarization=None, calibration=None, level=None, modifiers=()), DatasetID(name='solar_azimuth_angle', wavelength=None, resolution=500, polarization=None, calibration=None, level=None, modifiers=()), DatasetID(name='solar_azimuth_angle', wavelength=None, resolution=1000, polarization=None, calibration=None, level=None, modifiers=()), DatasetID(name='solar_zenith_angle', wavelength=None, resolution=250, polarization=None, calibration=None, level=None, modifiers=()), DatasetID(name='solar_zenith_angle', wavelength=None, resolution=500, polarization=None, calibration=None, level=None, modifiers=()), DatasetID(name='solar_zenith_angle', wavelength=None, resolution=1000, polarization=None, calibration=None, level=None, modifiers=())]

**Environment Info:**
 - OS: Fedora-31
 - Satpy Version: 0.22.0
 - PyResample Version: 1.16.0
 - Trollimage Version: 1.13.0
 - PyKdtree Version: 1.3.1
 - Pyhdf Version: 0.10.2

**Comment by djhoese** [comment]
Thanks for making this separate issue. A couple things, you shouldn't need the `sensor=` in your Scene creation and you shouldn't need the `wishlist=` part in your second code example (ex. `scn.load(['2'], resolution=1000)`). Neither of these are causing the issue though.

The error you are getting suggests some metadata is missing from the reader. What do you get if you do:

```
scn.load(['1', '2', '3', '4'])
print(scn['1'].attrs['platform_name'])
print(scn['2'].attrs['platform_name'])
print(scn['3'].attrs['platform_name'])
print(scn['4'].attrs['platform_name'])
```

**Comment by anikfal** [comment]
**Code 3:**
```python
scn.load(['1', '2', '3', '4'])
print(scn['1'].attrs['platform_name'])
print(scn['2'].attrs['platform_name'])
print(scn['3'].attrs['platform_name'])
print(scn['4'].attrs['platform_name'])
```
**Output of code 3:**
> EOS-Terra
EOS-Terra
EOS-Terra
EOS-Terra

For some MODIS L1 data, the images can be generated. Fore example for the files `MOD021KM.A2020216.0855.061.2020216192432.hdf` and `MOD021KM.A2020216.1955.061.2020217071759.hdf`, although both of them have similar naming patterns, code-4 cannot handle the second file, and shows an empty image:

**Code 4:**
```python
from satpy.scene import Scene
from satpy import find_files_and_readers
from datetime import datetime
files = find_files_and_readers(base_dir='/home/anikfal/datamsg8/modis',
                               reader='modis_l1b')
scn = Scene(filenames=files)
composite_name = 'true_color'
scn.load([composite_name], resolution=1000)
scn.save_datasets(writer='simple_image')
```

**Warning messages of code 4:**
> /home/anikfal/miniconda3/envs/mysat/lib/python3.8/site-packages/dask/core.py:121: RuntimeWarning: invalid value encountered in less
  return func(*(_execute_task(a, cache) for a in args))
/home/anikfal/miniconda3/envs/mysat/lib/python3.8/site-packages/dask/core.py:121: RuntimeWarning: invalid value encountered in log
  return func(*(_execute_task(a, cache) for a in args))

**Output images of code 4:**
The file `MOD021KM.A2020216.0855.061.2020216192432.hdf` seems to be plotted correctly (upper part).
The file `MOD021KM.A2020216.1955.061.2020217071759.hdf` is plotted as an empty image (bottom part).
![true_color_20200803_085500](https://user-images.githubusercontent.com/11738727/92088533-3e30d180-ede2-11ea-9b7f-3a9c4baa6906.png)

**Comment by mraspaud** [comment]
Wasn't it nigthtime at 1955? In which case it's not surprising the true-color image is empty. Try eg the `overview` composite to check if there is data in the file.
