### ISSUE TITLE
hrv composites for global scene

### ISSUE THREAD

**Issue by gkafk** [pytroll/satpy#1339]
global_scene.load(['**hrv_clouds**'])

**The following datasets were not created and may require resampling to be generated**: DatasetID(name='**hrv_cloud**s', wavelength=None, resolution=None, polarization=None, calibration=None, level=None, modifiers=None)

  It works after resampling for local_scenes but not for global, as the most hrv composite products as I can see.
Is there any way to produce the global image for hrv_clouds and hrv_fog or any other composite image containing the resolution of hrv channel?

![MSG_EU_202009030800](https://user-images.githubusercontent.com/64424891/92148144-cb951580-ee24-11ea-9ffe-7ab915d2f4fe.jpg)

**Comment by mraspaud** [comment]
@gkafk indeed this composite is made of HRV and another channel, and they are not at the same resolution.

You can resample to the same resolution (without changing the projection) with the native resampler:
```python
    composite = 'hrv_clouds'
    scn.load([composite])
    lscn = scn.resample(scn.min_area(), resampler='native')
    lscn.show(composite)
```

**Comment by gkafk** [comment]
This is the local scene. Right?
 I need the global image. Full disk image, including HRV channel for better resolution.
![MSG_NAFRGB_FDK_202009030530](https://user-images.githubusercontent.com/64424891/92149881-48c18a00-ee27-11ea-8a52-57e86d2ecfa5.jpg)

**Comment by pnuu** [comment]
With the commands @mraspaud showed, you'll get the full disk data in full HRV resolution. But as you test it, you'll see that the HRV channel won't cover the whole area (imager limitation), and that the image will be rotated 180 degrees (that's how the imager works). But you can flip the resulting scene afterwards. Sorry, don't have the data at hand to give the exact command, but see https://satpy.readthedocs.io/en/stable/quickstart.html#slicing-and-subsetting-scenes for things to try.

**Comment by gkafk** [comment]
Thank you very much.
It works fine!
![MSG_202009031500_result](https://user-images.githubusercontent.com/64424891/92198380-c0150f00-ee63-11ea-992d-95df4c50b53f.jpg)
