### ISSUE TITLE
ir product

### ISSUE THREAD

**Issue by Tsironisa** [pytroll/satpy#1355]
Hi,i use seviri files to build composites.is there anyway to get a memo on load()  about temperature in ir ,or other composites using ir e.g colorized_ir_clouds
if not, where can i get the color table for colorized_ir_clouds combpsite

**Comment by mraspaud** [comment]
Hi, what do you call a memo?

**Comment by Tsironisa** [comment]
i mean a  table relating temperature to image colors like this
![Fig3 3 (1)](https://user-images.githubusercontent.com/70956294/92630987-5f5d5a80-f2d9-11ea-9249-670839291ad9.png)

**Comment by mraspaud** [comment]
@zxdawn maybe can help?

**Comment by zxdawn** [comment]
You can use `decorate` when saving your figure.

```
scn.save_datasets(base_dir='./figures/',
                           filename='enhancement.jpg',
                           compute=True,
                           fill_value=0,
                           datasets=[channel],
                           writer='simple_image',
                           decorate={'decorate': [{'scale': {'colormap': spectral, 'extend': False,
                                                             'cursor': [0, 0], 'bg':'white',
                                                             'title':'Brightness Temperature'}}]
                                    })
```

Note, you need to pass the colormap manually. For more parameters of decorate, you can check the [pydecorate website](https://pydecorate.readthedocs.io/en/latest/).

If you're interested in other methods of plotting colormap, you can check [this notebook](https://github.com/zxdawn/pytroll-examples/blob/combined_colormaps/satpy/Combined_colormaps.ipynb).

**Comment by Tsironisa** [comment]
Thank you very match!!!
