### ISSUE TITLE
Feature request: download tif's if needed in a composite

### ISSUE THREAD

**Issue by raybellwaves** [pytroll/satpy#1362]
Apologies this is not a MCVE but I think it's ok.

When I do `scn.load(['night_ir_with_background_hires'])`. I get `RasterioIOError: BlackMarble_2016_3km_geo.tif: No such file or directory`. I see here https://github.com/pytroll/satpy/blob/280d863d3fd9b183320e344e596b06fed8e52f8f/satpy/etc/composites/visir.yaml#L427

and I see it's looking for a local file `BlackMarble_2016_01deg_geo.tif`.

After some google I see the file can be downloaded from https://neo.sci.gsfc.nasa.gov/archive/blackmarble/2016/global/ (I believe).

It would be good if a user who does `scn.load(['night_ir_with_background_hires'])` need not go and download the file but have the API do it.

An example, this is implemented in cartopy when a user requests coastline of different resolution e.g.
`ax.coastlines(resolution='10m')`. I don't know exactly how they implement but could take inspiration from there.
e.g. https://github.com/SciTools/cartopy/blob/8d11866c06a465764063d9f7fcfa70e8476089e0/tools/feature_download.py

**Comment by djhoese** [comment]
Agreed. This is a known issue that kind of got away from us. This was one of those "oh it would be cool if we could use a static image as a background" and then never actually did it "the right way". Thanks for filing the issue.

**Comment by raybellwaves** [comment]
However, it's a big(ish) file (64.4 Mb) so couldn't prompt for a Y/N for the download

**Comment by djhoese** [comment]
I'd say either we raise an exception saying you need to run a utility function to download the file or automatically download it or both and have a global config option to control what happens.
