### ISSUE TITLE
Can we put pygac on conda-forge?

### ISSUE THREAD

**Issue by yukaribbba** [pytroll/satpy#1403]
## Feature Request

**Is your feature request related to a problem? Please describe.**
-- I want to read avhrr-2 data on noaa-11 to produce images, and satpy.readers.avhrr_l1b_gaclac requires pygac.
-- I set up the whole satpy environment through conda-forge, Anaconda 3, including pyresample, pyspectral, gdal.
-- However, there is no pygac on conda-forge.
-- So I followed the guideline on https://pygac.readthedocs.io/en/develop/ to install pygac and set environment variables.
-- But satpy still can't find it.

**Describe the solution you'd like**
Would someone help me to fix this problem under current environment
OR
Can we put pygac on conda-forge, just like pyresample and pyspectral?

Thank you!

**Comment by djhoese** [comment]
What commands did you run exactly to install pygac and what is the path to your conda environment? Your conda environment will need to be activated before `pip` installing anything. The `--prefix`, `PATH`, and `PYTHONPATH` changes are likely not needed if your environment was already activated.

**Comment by yukaribbba** [comment]
I followed @djhoese and satpy is now able to know my pygac.
But there comes another issue:  Unexpected number of scanlines

/home/ll/anaconda3/lib/python3.8/site-packages/pygac/reader.py:261: RuntimeWarning: Unexpected number of scanlines!
  warnings.warn("Unexpected number of scanlines!",
Traceback (most recent call last):
  File "/home/ll/anaconda3/bin/pygac-run", line 164, in <module>
    pygac.process_file(filename, start_line, end_line)
  File "/home/ll/anaconda3/lib/python3.8/site-packages/pygac/runner.py", line 107, in process_file
    reader.read(filename, fileobj=fileobj)
  File "/home/ll/anaconda3/lib/python3.8/site-packages/pygac/pod_reader.py", line 291, in read
    self.spacecraft_name = self.spacecraft_names[self.spacecraft_id]
KeyError: 108
