### ISSUE TITLE
Encoding of wavelength range

### ISSUE THREAD

**Issue by sfinkens** [pytroll/satpy#1449]
**Describe the bug**
The `µ` character which is used as wavelength unit for the `DataID` can cause problems with certain character encodings of the terminal.

Maybe we should change the units to `'um'` to avoid these kind of problems?

**To Reproduce**

```python
# test.py
from satpy.tests.utils import make_dataid

dataid = make_dataid(name='foo', wavelength=(1, 2, 3))
print(dataid)
```

**Expected behavior**
No exception, and in an ideal case the same output.

**Actual results**
a) UTF-8
```
$ export LC_CTYPE="en_US.UTF-8"
$ python test.py
2â¯ÂµmÂ (1-3â¯Âµm)
```

b) latin-1 aka ISO-8859-1
```
$ export LC_CTYPE="en_US.ISO-8859-1"
Traceback (most recent call last):
  File "test3.py", line 20, in <module>
    print(scene2['foo'].attrs['wavelength'])
UnicodeEncodeError: 'latin-1' codec can't encode character '\u202f' in position 3: ordinal not in range(256)
```

**Environment Info:**
 - OS: Linux
 - Satpy Version: 0.24.0

**Comment by mraspaud** [comment]
I think the character that causes problem is the non-breakable space between the number and the µ. Although it's a valid unicode character...

**Comment by mraspaud** [comment]
It's actually a narrow nbsp, which doesn't have a ISO 8859 counterpart.

the International System of Units on wikipedia says: 
> The value of a quantity is written as a number followed by a space (representing a multiplication sign) and a unit symbol; e.g., 2.21 kg, 7.3×102 m2, 22 K. This rule explicitly includes the percent sign (%)[28]:134 and the symbol for degrees Celsius (°C).[28]:133 Exceptions are the symbols for plane angular degrees, minutes, and seconds (°, ′, and ″, respectively), which are placed immediately after the number with no intervening space.

Hence I think this should be changed to a regular nbsp.
