### ISSUE TITLE
Small error in documentation

### ISSUE THREAD

**Issue by paapu88** [pytroll/satpy#1453]
Dear Developers,

In documentation at 
https://satpy.readthedocs.io/en/stable/api/satpy.readers.html#satpy.readers.ahi_hsd.AHIHSDFileHandler
there are some  '::' in dictionaries instead of ':'

For instance there is now
```
scene = satpy.Scene(filenames,
                    reader='ahi_hsd',
                    reader_kwargs={'mask_space':: False})
```
that is after 'masked_space' there is errorneous '::'
Same thing at couple of other places for the 'ahi_hsd' reader documentation.

Terveisin, Markus

**Comment by djhoese** [comment]
I think this is something @simonrp84 accidentally added in a couple docstrings. I thought he fixed these in other places, but maybe he missed a few. Any memory of this @simonrp84? @paapu88 Would you mind making a pull request to fix this?

**Comment by simonrp84** [comment]
No, this wasn't me @djhoese. The reason I included `::` in some other files was because I copied the example of `ahi_hsd` as I thought this was the right way to do it.
