### ISSUE TITLE
Broken links to new EUMETSAT website

### ISSUE THREAD

**Issue by gerritholl** [pytroll/satpy#1484]
**Describe the bug**

In various places in satpy there are broken links to the new EUMETSAT website.  For example, the documentation for the `seviri_l1b_hrit` contains a broken link to the level 1.5 fileformat description on the EUMETSAT website.

**To Reproduce**

- Navigate to https://satpy.readthedocs.io/en/stable/readers.html#introduction
- Click on the link with the anchor _MSG Level 1.5 Image Format Description_
- Observe Error 404

**Expected behavior**

I expect that the link connects me with the image format description.

**Actual results**

In reality I get 404 - Page not found.

**Additional context**

Arguably this bug in in the EUMETSAT website because [cool URIs dont change](https://www.w3.org/Provider/Style/URI.html), but regrettably it's going to be up to pytroll to update the link.

We should probably search through all the docs and source code of all pytroll packages for links to the EUMETSAT website to check and potentially update them all.

**Comment by helgaweb** [comment]
@gerritholl It also holds for link in the slstr_l1b reader
https://github.com/pytroll/satpy/blob/a3774e151e0b8181f2de89ae84f46902eec3bede/satpy/readers/slstr_l1b.py#L41

**Comment by ameraner** [comment]
The links in `seviri_l1b_hrit`, `seviri_l1b_nc`, `seviri_base` and `_geos_area` will be fixed with https://github.com/pytroll/satpy/pull/1485 as that PR is already touching those files (I started fixing them before seeing this issue). But I'm sure there are more around! So maybe you can change this issue to be general about all EUM links?

**Comment by gerritholl** [comment]
@ameraner  Done.
