### ISSUE TITLE
The reader "viirs_l1b" cannot read the VIIRS L1B data

### ISSUE THREAD

**Issue by anikfal** [pytroll/satpy#1489]
**Code:**
```python
from glob import glob
from satpy.scene import Scene
myfile = glob("VNP02DNB_NRT.A2020326.0912.001.nc")
scn = Scene(reader="viirs_l1b", filenames=myfile)
```

**Error message:**
> /home/anikfal/miniconda3/lib/python3.8/site-packages/satpy/resample.py:150: UserWarning: Gradient search resampler not available, upgrade Pyresample.
  warnings.warn('Gradient search resampler not available, upgrade Pyresample.')
No filenames found for reader: viirs_l1b
Don't know how to open the following files: {'VNP02DNB_NRT.A2020326.0912.001.nc'}
Traceback (most recent call last):
  File "1viirs.py", line 9, in <module>
    scn = Scene(reader="viirs_l1b", filenames=myfile)
  File "/home/anikfal/miniconda3/lib/python3.8/site-packages/satpy/scene.py", line 151, in __init__
    self._readers = self._create_reader_instances(filenames=filenames,
  File "/home/anikfal/miniconda3/lib/python3.8/site-packages/satpy/scene.py", line 200, in _create_reader_instances
    return load_readers(filenames=filenames,
  File "/home/anikfal/miniconda3/lib/python3.8/site-packages/satpy/readers/__init__.py", line 504, in load_readers
    raise ValueError("No supported files found")
ValueError: No supported files found

**Environment Info:**
 - OS: Fedora-33
 - Satpy Version: 0.23.0
```python
from satpy.config import check_satpy
check_satpy()
```
> ...
vii_l1b_nc:  ok
vii_l2_nc:  ok
viirs_compact:  ok
viirs_edr_active_fires:  ok
viirs_edr_flood:  cannot find module 'satpy.readers.viirs_edr_flood' (No module named 'pyhdf')
viirs_l1b:  ok
viirs_sdr:  ok
virr_l1b:  ok
...

**Comment by djhoese** [comment]
This was updated by @simonrp84 in #1420 and was release in Satpy 0.24. Please update your version of Satpy. Closing this since this should be fixed. Feel free to comment here if you still have issues after upgrading and we can reopen it.

**Comment by anikfal** [comment]
The previous problem has been solved by updating to version 0.24. But now the code asks for the coordinates which are missing.
The output of `print(scn.available_dataset_names())` is `['DNB']`

**code:**
```python
from satpy.scene import Scene
from glob import glob
myfile = glob("VNP02DNB_NRT.A2020326.0912.001.nc")
scn = Scene(reader="viirs_l1b", filenames=myfile)
scn.load(['DNB'])
```
**Error message:**
> Required file type 'vgeod' not found or loaded for 'dnb_lon'
> Required file type 'vgeod' not found or loaded for 'dnb_lat'
> Failed to load coordinates for 'DataID(name='DNB', wavelength=WavelengthRange(min=0.5, central=0.7, max=0.9, unit='µm'), resolution=743, calibration=<calibration.radiance>, modifiers=())'

My aim is to convert the VIIRS data to GeoTIFF.

**Comment by djhoese** [comment]
These messages are warnings, not necessarily errors. Satpy will always try to load the geolocation information for the data it is loading and it can't do that without the geolocation files in the case of VIIRS data.

For saving to geotiff: you won't be able to do that without resampling as VIIRS data is not pre-gridded (it is a swath of pixels and non-uniform distances/sizes). Resampling will also require the geolocation files as you can't resample without knowing where the pixels are.

**Comment by anikfal** [comment]
The geolocation file (`file2`) is available, and the coordinates `i_lon` and `i_lat` can be loaded from it. How can we assign them to the main data (`'I05'`) from `file1`? So we can resample the data.
I could not find much information about the coordinate assignment in the documentation and examples.

**Code:**
```python
from satpy.scene import Scene
from glob import glob
file1 = glob("VNP02IMG_NRT.A2020351.0154.001.nc")
file2 = glob("VNP03IMG_NRT.A2020354.0012.001.nc")
scn_main = Scene(reader="viirs_l1b", filenames=file1)
scn_geoloc = Scene(reader="viirs_l1b", filenames=file2)
scn_geoloc.load(['i_lon'])
scn_geoloc.load(['i_lat'])
main_data.load(['I05'])
```

**Comment by djhoese** [comment]
You need to pass all the files to a single Scene object:

```
scn = Scene(reader='viirs_l1b', filenames=[file1, file2])
scn.load(['I05'])
new_scn = scn.resample(some_area)
new_scn.save_datasets(...)
```

If you personally want to access the lon/lat arrays then the easiest way would be to do:

```
lons, lats = scn['I05'].attrs['area'].get_lonlats()
```

But the resampling in Scene.resample already knows how to do this.
