### ISSUE TITLE
Replace pkg_resources usage with version.py file

### ISSUE THREAD

**Issue by djhoese** [pytroll/satpy#1509]
Related: #678 and #856

This was mentioned in #856, but setuptools_scm has an option to write the version information to a python module version.py. It was decided in my PR that we should use the `pkg_resources` method though which dynamically loads the installed package data to get the version. It has come to my attention since this PR that this is actually a terrible idea. What happens is that for large python environments, `pkg_resources` has to search through all package metadata to get the version information. I'm not sure why it is this way, but it has been reported for other projects I work on (vispy) where it ends up taking **seconds** just to import the package because of the time it takes to get the version number.

Thoughts @mraspaud?

**Comment by pdebuyl** [comment]
For info, versioneer has been moved to a dedicated github org and is alive again. If ever this is of interest of course :-)

https://github.com/python-versioneer/python-versioneer
