### ISSUE TITLE
Improve documentation/handling of string input for config_path 

### ISSUE THREAD

**Issue by ameraner** [pytroll/satpy#1530]
## Feature Request

**Is your feature request related to a problem? Please describe.**
When setting up at runtime the configuration parameter `config_path`, this must be defined as a list containing strings:
```python
satpy.config.set(config_path=["/my/new/config/path"])
```
The other parameter `cache_dir` and `data_dir`, in contrary, must be a string. Although this difference is described in https://github.com/pytroll/satpy/blob/master/doc/source/config.rst, it is easy to oversee that specific passage if the page is not read carefully.
Moreover, if the user inputs a string, the code executes without complaints, but the config path will not be handled properly and Satpy will fail to find the configuration files. It will not be very easy for a user to find out why this is happening.

**Describe the solution you'd like**
I propose to highlight the fact that  `config_path` must be a list more clearly in the documentation, possibly adding an explicit code snipped for this specific case. There is now only an example for `cache_dir`, which might induce a reader to assume that the other parameters all work the same.
Additionally, the code could be adapted to handle a string and emit a warning if the user passes a string instead of a list, or throw an exception with a meaningful message.

**Describe any changes to existing user workflow**
None, just clearer configuration setup instructions.

**Comment by djhoese** [comment]
@ameraner Please checkout #1534 and let me know if that looks better.
