### ISSUE TITLE
modifier API documentation not included with sphinx-generated API documentation

### ISSUE THREAD

**Issue by gerritholl** [pytroll/satpy#1538]
**Describe the bug**

There is API documentation in the [`satpy.modifier` package](https://github.com/pytroll/satpy/tree/master/satpy/modifiers), but this documentation is not included in [readthedocs satpy subpackages](https://satpy.readthedocs.io/en/stable/api/satpy.html#subpackages), which only includes composites, dataset, demo, enhancements, readers, and writers.

**To Reproduce**

- Browse to https://satpy.readthedocs.io/en/stable/api/satpy.html#subpackages
- Look for `satpy.modifiers` API documentation

**Expected behavior**

Find `satpy.modifiers` API documentation.

**Actual results**

Not find `satpy.modifiers` API documentation.

**Additional context**

It seems all other packages are present.

**Comment by djhoese** [comment]
This should be closed now with #1543. Waiting on RTD to build the docs.

**Comment by djhoese** [comment]
https://satpy.readthedocs.io/en/latest/api/satpy.modifiers.html
