### ISSUE TITLE
Satpy problems with MODIS

### ISSUE THREAD

**Issue by jee34** [pytroll/satpy#1549]
When i execute satpy, the program complains there is too much datasets to load. It worked fine a few weeks ago.
As an input i use :       xxxx....250m.hdf      xxxxx.500m.hdf         xxxx.1000m.hdf      xxx.geo.hdf

picture_type='true_color'
myfiles=glob("/mnt/d/WSL_FOLDER/HOME/IMAPP/data/level1/*.hdf")
scene=Scene(filenames=myfiles,reader='modis_l1b')
scene.load([picture_type])
natscn=scene.resample(resampler='native')
#natscn.show(picture_type)
natscn.save_dataset(picture_type,filename='./satpy_aqua.png')

----------------------------------------------------------------------------------------------

[WARNING: 2021-02-13 19:39:52 : satpy.node] Too many possible datasets to load for DataQuery(name='satellite_azimuth_angle', calibration='reflectance')
[WARNING: 2021-02-13 19:39:52 : satpy.node] Too many possible datasets to load for DataQuery(name='satellite_zenith_angle', calibration='reflectance')
[WARNING: 2021-02-13 19:39:52 : satpy.node] Too many possible datasets to load for DataQuery(name='solar_azimuth_angle', calibration='reflectance')
[WARNING: 2021-02-13 19:39:52 : satpy.node] Too many possible datasets to load for DataQuery(name='solar_zenith_angle', calibration='reflectance')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  aqua_jlm.py", line 26, in <module>  scene.load([picture_type])
  scene.py", line 1182, in load   self.generate_possible_composites(generate, unload)
  scene.py", line 1239, in generate_possible_composites   keepables = self._generate_composites_from_loaded_datasets()
  scene.py", line 1251, in _generate_composites_from_loaded_datasets  return self._generate_composites_nodes_from_loaded_datasets(nodes)
  scene.py", line 1257, in _generate_composites_nodes_from_loaded_datasets   self._generate_composite(node, keepables)
  scene.py", line 1315, in _generate_composite       composite = compositor(prereq_datasets,
  modifiers/atmosphere.py", line 67, in __call__     sata, satz, suna, sunz = self.get_angles(vis)
  modifiers/atmosphere.py", line 49, in get_angles  sat_lon, sat_lat, sat_alt = get_satpos(vis)
  utils.py", line 325, in get_satpos                 lon = dataset.attrs['satellite_longitude']  KeyError: 'satellite_longitude'

**Comment by djhoese** [comment]
Sorry things stopped working. There were definitely some major changes to the low level parts of Satpy recently. Could you tell us what version of Satpy you are running?

**Comment by jee34** [comment]
I use satpy 0.25.1

Regards.

Télécharger Outlook pour Android<https://aka.ms/ghei36>

________________________________

**Comment by mraspaud** [comment]
Thanks for bringing this problem to our attention, I will try to reproduce it locally.

**Comment by jee34** [comment]
No problem Martin.

Télécharger Outlook pour Android<https://aka.ms/ghei36>

________________________________

**Comment by mraspaud** [comment]
@jee34 I could reproduce the problem and have now PR:d a fix in #1556 . Would you mind checking that the PR fixes the issue for you?

**Comment by jee34** [comment]
Thank you very much, it worked.
Regards.

Télécharger Outlook pour Android<https://aka.ms/ghei36>

________________________________
