### ISSUE TITLE
Add animation example

### ISSUE THREAD

**Issue by djhoese** [pytroll/satpy#157]
#### Problem description

We should have an example in the documentation or https://github.com/pytroll/pytroll-examples of using satpy + ffmpeg to create an animated gif. Maybe on of two or more datasets being swapper for a single time or multiple times for a single channel (requires multiple Scene objects). I know it is fairly simple to generate a GIF using PIL so we could provide a utility method for this. Maybe that is the best way to go? Although ffmpeg could allow someone to make a movie (mp4, mov, etc).

**Comment by davidh-ssec** [comment]
This example and probably whatever functions get added to satpy to assist in this should use the `imageio` library. This isn't necessarily in the realm of a writer since it would have to operate on more than one Scene at a time.

https://github.com/imageio/imageio
