### ISSUE TITLE
Crash when reaching warnings.DeprecationWarning

### ISSUE THREAD

**Issue by ameraner** [pytroll/satpy#1573]
**Describe the bug**
After #1565 , Satpy crashes when reaching e.g.
https://github.com/pytroll/satpy/blob/master/satpy/scene.py#L273-L274

**To Reproduce**

```python
new_scn = scn.resample(scn.min_area())
```

**Expected behavior**
Show the DeprecationWarning and don't crash.
This is solved by removing the `warnings.`
```bash
warnings.warn("'min_area' is deprecated, use 'coarsest_area' instead.",
                      DeprecationWarning)
```

**Actual results**
```bash
  File "/tcenas/home/andream/code/satpy_latest/satpy/satpy/scene.py", line 274, in min_area
    warnings.DeprecationWarning)
AttributeError: module 'warnings' has no attribute 'DeprecationWarning'
```

**Environment Info:**
Python 3.7, latest Satpy master after the mentioned PR

**Comment by ameraner** [comment]
@pnuu @djhoese @mraspaud FYI

**Comment by ameraner** [comment]
Are those warnings being suppressed anyway somewhere? Not sure how, but they don't show up for me.

**Comment by djhoese** [comment]
This is the main discussion about #1554. DeprecationWarning warnings are not shown by Python by default. So a lot of Satpy deprecation warnings (and other scientific libraries) choose to use the default UserWarning. UserWarnings do show up by default. However, as @gerritholl pointed out you can't handle deprecation warnings in a special way if they are indistinguishable from all the other UserWarnings. #1554 is the best compromise we could come up with.

**Comment by djhoese** [comment]
@ameraner If you haven't already can you make a PR for the fix you mentioned above?

**Comment by ameraner** [comment]
Done!
