### ISSUE TITLE
Don't allow auxiliary downloads during tests

### ISSUE THREAD

**Issue by djhoese** [pytroll/satpy#1587]
## Feature Request

**Is your feature request related to a problem? Please describe.**
I was just working with @joleenf on #1511 and I realized that Satpy shouldn't allow aux downloads when tests are running. This should stop tests from accidentally downloading files when they should be mocked.

**Describe the solution you'd like**
Seems like, accordingly to stackoverflow, the easiest solution would be to detect if we're running pytest:

```
import sys

if "pytest" in sys.modules:
    ...
```

Then raise an exception inside the retrieve function.

**Describe any changes to existing user workflow**
This doesn't effect users, only developers. Developers will have to make sure not to download files in their tests which I didn't want anyway.

**Comment by hombyk-nevzi2-dAxzyd** [comment]
![image](https://user-images.githubusercontent.com/80834046/111777080-60ed8800-88e5-11eb-80b8-cc3c0173a838.jpeg)
