### ISSUE TITLE
slstr_l2: Failed to filter out correct files using find_files_and_readers() with start_time and end_time

### ISSUE THREAD

**Issue by JohannesSMHI** [pytroll/satpy#1594]
**Describe the bug**
```satpy.readers.find_files_and_readers``` does not filter out the correct files based on start_time and end_time.

Possibly something fishy with the file_pattern of satpy/etc/readers/slstr_l2.yaml ?

Data source: CODA

**To Reproduce**

```python
from datetime import datetime
from satpy import Scene, find_files_and_readers

sen3_data_l2 = 'C:/Temp/Satellit/sentinel_data/sst'
filenames = find_files_and_readers(
    start_time=datetime(2020, 6, 1, 7, 10),
    end_time=datetime(2020, 6, 1, 12, 50),
    base_dir=sen3_data_l2,
    reader='slstr_l2',
    sensor='slstr_l2',
)
```

**Expected behavior**
```python
>>>pprint(filenames)
{'slstr_l2': 'C:/Temp/Satellit/sentinel_data/sst\\20200601092517-MAR-L2P_GHRSST-SSTskin-SLSTRA-20200601113739-v02.0-fv01.0.nc']}
```

**Actual results**
Text output of actual results or error messages including full tracebacks if applicable.
[DEBUG: 2021-03-12 09:05:42 : satpy.readers.yaml_reader] Reading ('C:\\Continuum\\Miniconda3\\envs\\satpy_env\\Lib\\site-packages\\satpy\\etc\\readers\\slstr_l2.yaml',)

```python
>>>pprint(filenames)
{'slstr_l2': ['C:/Temp/Satellit/sentinel_data/sst\\20210213100240-MAR-L2P_GHRSST-SSTskin-SLSTRA-20210213121415-v02.0-fv01.0.nc',
              'C:/Temp/Satellit/sentinel_data/sst\\20200601092517-MAR-L2P_GHRSST-SSTskin-SLSTRA-20200601113739-v02.0-fv01.0.nc']}
```

**Environment Info:**
 - OS: Windows10
 - Satpy Version: 0.25.1

**Comment by djhoese** [comment]
I think this is a problem in the file pattern in the reader:

```
'{dt1:%Y%m%d%H%M%S}-{generating_centre:3s}-{type_id:3s}_GHRSST-SSTskin-SLSTR{something:1s}-{dt2:%Y%m%d%H%M%S}-{version}.nc'
```

The `find_files_and_readers` function uses parameters `start_time` and `end_time` if they exist. This file pattern uses `dt1` and `dt2`. Any idea what these dates represent in the filename (I'm not familiar with this data)?

**Comment by djhoese** [comment]
@eysteinn May have ideas as the original author of this reader (that's what git tells me at least).

**Comment by JohannesSMHI** [comment]
Ah, right. So dt1 and dt2 should probably be replaced by start_time and end_time.. but that did not solve the issue..

'SLSTRB' as file_type seems to indicate that we´re only working with the SLSTR sensor on Sentinel-3B and not 3A as well (perhaps not relevant for this  particular case though)

**Comment by djhoese** [comment]
Hm if the start/end time change in the file pattern didn't fix it, then I'm not sure where to go from here. I don't have a ton of time to look deeper so hopefully @eysteinn or another expert on this data can investigate more.

**Comment by JohannesSMHI** [comment]
Cool, we wait for @eysteinn, otherwise I´ll might have another look at it next week..

**Comment by JohannesSMHI** [comment]
@djhoese So ```find_files_and_readers``` does in fact work as expected if you replace dt1 and dt2 with start_time and end_time (I must have done some typos last time..)

**Comment by djhoese** [comment]
@JohannesSMHI Great! Do you think you could make a pull request?
