### ISSUE TITLE
wrong gamma for red beam of cira_fire_temperature RGB

### ISSUE THREAD

**Issue by hproe** [pytroll/satpy#1650]
**Describe the bug**
According to documentation, which is referenced in the respective yaml files, the gamma value for the red beam (C07/NIR3.9) of cira_fire_temperature RGB shall be 0.4 and not 1.4.

```python
  cira_fire_temperature:
    standard_name: cira_fire_temperature
    reference: http://rammb.cira.colostate.edu/training/visit/quick_guides/Fire_Temperature_RGB.pdf
    operations:
      - name: stretch
        method: !!python/name:satpy.enhancements.stretch
        kwargs:
          stretch: crude
          min_stretch: [273, 0.0, 0.0]
          max_stretch: [333, 100.0, 75.0]
      - name: gamma
        method: !!python/name:satpy.enhancements.gamma
        kwargs:
          gamma: [**0.4**, 1, 1]
```

**Screenshots**
![compare](https://user-images.githubusercontent.com/36047781/115895039-44032200-a45a-11eb-8fc2-1943c715e857.png)
correct RGB is to the left

**Environment Info:**
 - OS:[Linux
 - Satpy Version: 0.27.0

**Comment by djhoese** [comment]
FYI you missed the last three ticks on your code block. I've fixed it so now the images show up. Thanks for the issue.
