### ISSUE TITLE
Nan values when resample with Kompsat

### ISSUE THREAD

**Issue by ptcongbk** [pytroll/satpy#1664]
Hi everyone,

I am trying to get samples from Kompsat full-disk using ami_l1b. The final results contained a lot of Nan values as the sample images. Do you have any ideas why it happened? 

Much appreciated.

![koreaIR087_202104050300](https://user-images.githubusercontent.com/8589691/117557602-f58b8f80-b0b7-11eb-8980-455d819bf9e5.png)

**Comment by simonrp84** [comment]
Can you please share the code you're using to read and resample the data?

**Comment by ptcongbk** [comment]
Yes, for sure, @simonrp84. Here is my code.

import glob
from satpy import Scene
from pyresample import get_area_def
from pyresample.utils import get_area_def

files =  glob(path + "*.nc")
scn = Scene(files, reader='  ')
area_id = 'korea'
x_size = 230
y_size = 258
area_extent =  (-230081.30238210218, -255028.30785934266, 230081.30238209982, 260877.24912037785)
projection = '+proj=laea +lat_0=36.48944825845746 +lon_0=127.43408442536264 +ellps=WGS84'
description = "korea"
proj_id = 'laea_127.43408442536264_36.48944825845746'

areadef = get_area_def(area_id, description, proj_id, projection,x_size, y_size, area_extent)
lons, lats = areadef.get_lonlats() 
available_datasets = scn.available_dataset_names()

 for dataset in available_datasets:
    scn.load([dataset])
    local_scene = scn.resample(areadef,resampler='nearest', skipna=True)
    #local_scene.save_dataset(name, filename=name+'.png')
    bandData = local_scene[dataset]
    local_scene.save_dataset(dataset, '{channel}_{datetime}.png'.format(channel=dataset, datetime=scn.start_time.strftime('%Y%m%d%H%M')))
    del scn[dataset]

**Comment by djhoese** [comment]
This isn't the issue, but I don't think `skipna` is used by the `nearest` resampler.

Do you get these types of results for all data cases? There are certain patterns that we expect if some resampling parameters are misconfigured/sub-optimal, but not like what you're seeing. These results make me think that something in the reader is wrong...or I'm just wrong about the resampling. What does the image look like if you don't resample and call `save_datasets` on the original `scn`? Do you see any missing/bad pixels there?

**Comment by ptcongbk** [comment]
I tried the different resamplers and I forgot to remove the `skipna `so that is the reason it is there. I tested the resample in many different timeframes but the results are quite the same.

However, if I saved it from the original `scn`, it works perfectly as the attached image.
![image](https://user-images.githubusercontent.com/8589691/117575617-f65b0a80-b125-11eb-9f7b-cd6f930176bc.png)

Do you have any suggestions for me?

**Comment by ptcongbk** [comment]
Thank you so much for your helps @djhoese,

It works 👯. 

![koreaIR087_202104050300](https://user-images.githubusercontent.com/8589691/117591391-99884000-b177-11eb-929a-341fb0c539aa.png)

I will play around more with this parameter.

**Comment by djhoese** [comment]
@simonrp84 you doca lot of AMI stuff, right? Do you do resampling? Have you seen results like this?

@ptcongbk Satpy is supposed to make an educated guess about what this parameter should default to. I'm surprised it is this bad, especially near the middle of the full disk.

**Comment by simonrp84** [comment]
@djhoese I always work in full disk or cropped disk, never resampled. Will have al ook and see what I can find, though.

**Comment by simonrp84** [comment]
Hm, running the same code as @ptcongbk (only replacing `import glob` with `from glob import glob` I get output that looks OK. There's no `NaN` areas at all...

**Comment by djhoese** [comment]
@simonrp84 @ptcongbk What reader(s) are you using? I see somehow that the reader doesn't exist in the code example above.

**Comment by ptcongbk** [comment]
Hi @djhoese and @simonrp84, 

I am using `ami_l1b' too. I got the main branch in your GitHub branch so can it be the problem?

**Comment by ptcongbk** [comment]
@djhoese I got a copy from my professor for research purposes (I am not sure how he got it).

I uploaded it to google drive here https://drive.google.com/drive/folders/1nGq8w4xCH1ZqW6rkU6AYITtBW-N5CN0G?usp=sharing.

**Comment by djhoese** [comment]
@ptcongbk Do you normally provide all of these files to a single Scene? The Scene isn't able to handle more than one time step at a time. Try changing your glob pattern so you are only operating on one time step of data and see if that changes the results.

**Comment by ptcongbk** [comment]
@djhoese how stupid I am. It works. Sorry I missed it from the beginning. Thank you so much for your help.

**Comment by djhoese** [comment]
@mraspaud maybe we create a separate issue specifically for this task and close this? I think @pnuu or someone had a suggested way of handling this and mentioned it on slack.
