### ISSUE TITLE
Cropping a country from an earth image using latitude and longitude coordinate

### ISSUE THREAD

**Issue by willows-1** [pytroll/satpy#1669]
Hi, I would like to know how can I crop a country from an earth image using latitude and longitude coordinate? I pasted a code below and I am getting the error: "TypeError: Plotting requires coordinates to be numeric, boolean, or dates of type numpy.datetime64, datetime.datetime, cftime.datetime or pandas.Interval. Received data of type object instead." Another error I got was "ValueError: the first argument to .sel must be a dictionary". Appreciate all the help I can get ! This is my code so far:

```
import pyproj as proj

input_lon, input_lat = 103.851959,1.290270

# setup projections
crs_wgs = proj.Proj(init='epsg:4326') 
crs_bng = proj.Proj(init='epsg:27700') 

# then cast geographic coordinate pair to the projected system
x, y = proj.transform(crs_wgs, crs_bng, input_lon, input_lat)

#Slicing singapore from earth image using coordinates

crop = scn[my_channel].sel(x, y)

#crop = scn[my_channel].sel(latitude= 1.290270, longitude= 103.851959)

crop
plt.figure()  # create a new figure
crop.plot.imshow() 
plt.title("Map of country ")
```

**Comment by djhoese** [comment]
I've updated your post with three backticks before and after your code block. This helps with the code formatting.

As for your use case, are you trying to crop a "chunk" of the image out and plot it? Your code so far looks like you are trying to select a single point as you only have a single longitude and latitude point in your `.sel` call.

**Comment by willows-1** [comment]
Hi djhoese, thanks for your reply! So in the .sel call, I need to mention 2 longitude and latitude points? So in that case the code will be the one I pasted below?

"""
import pyproj as proj

input_lon, input_lat = 103.851959,1.290270

input_lon2, input_lat2 = 110.437, 5.234 

# setup projections
crs_wgs = proj.Proj(init='epsg:4326') 
crs_bng = proj.Proj(init='epsg:27700') 

# then cast geographic coordinate pair to the projected system
x, y = proj.transform(crs_wgs, crs_bng, input_lon, input_lat)
x2, y2 = proj.transform(crs_wgs, crs_bng, input_lon2, input_lat2)

#Slicing country from earth image using coordinates

crop = scn[my_channel].sel(x, x2, y, y2)

crop
plt.figure()  # create a new figure
crop.plot.imshow() 
plt.title("Map of country ")

"""

**Comment by djhoese** [comment]
When you specify a single coordinate pair in the `.sel` call you are only requesting the data for that single point. If you want a range of data then you need to do something else. That said, I am not very familiar with complex indexing in xarray. Fortunately though Satpy has a crop method already: https://satpy.readthedocs.io/en/stable/api/satpy.scene.html#satpy.scene.Scene.crop

With this method you should be able to pass your lon/lat points directly with `ll_bbox=[lon_min, lat_min, lon_max, lat_max]`.

**Comment by willows-1** [comment]
so if I use the method that you suggested, I dont need to import pyproj?

**Comment by djhoese** [comment]
Correct. Satpy will do the coordinate conversion for you.

**Comment by willows-1** [comment]
alright, so I edited the code as below. But I am getting the error as seen in the screenshot below:

```
cropped_scn = scn.crop(ll_bbox=(-105, 40, -95, 50))
remapped_scn = cropped_scn.resample(resampler='native')

plt.figure()  # create a new figure
remapped_scn.plot.imshow() 
plt.title("Map of singapore - 09/04/21 0200 Time")
```

```
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
<ipython-input-11-7f07ab09f146> in <module>
----> 1 cropped_scn = scn.crop(ll_bbox=(-105, 40, -95, 50))
      2 remapped_scn = cropped_scn.resample(resampler='native')

C:\ProgramData\anaconda3\envs\satpy\lib\site-packages\satpy\scene.py in crop(self, area, ll_bbox, xy_bbox, dataset_ids)
    589             area = get_area_def(area)
    590         new_coarsest_area, min_y_slice, min_x_slice = self._slice_area_from_bbox(
--> 591             coarsest_area, area, ll_bbox, xy_bbox)
    592         new_target_areas = {}
    593         for src_area, dataset_ids in new_scn.iter_by_area():

C:\ProgramData\anaconda3\envs\satpy\lib\site-packages\satpy\scene.py in _slice_area_from_bbox(src_area, dst_area, ll_bbox, xy_bbox)
    471                 src_area.crs, src_area.width, src_area.height,
    472                 xy_bbox)
--> 473         x_slice, y_slice = src_area.get_area_slices(dst_area)
    474         return src_area[y_slice, x_slice], y_slice, x_slice
    475 

C:\ProgramData\anaconda3\envs\satpy\lib\site-packages\pyresample\geometry.py in get_area_slices(self, area_to_cover, shape_divisible_by)
   2252             logger.debug('Cannot determine appropriate slicing. '
   2253                          "Data and projection area do not overlap.")
-> 2254             raise NotImplementedError
   2255         x, y = self.get_xy_from_lonlat(np.rad2deg(intersection.lon),
   2256                                        np.rad2deg(intersection.lat))

NotImplementedError: 

```

**Comment by djhoese** [comment]
What data are you reading? Are you sure that your bounding box lies *completely* within your source data?

**Comment by willows-1** [comment]
I am reading a .dat file, which is a satellite image of the earth

**Comment by willows-1** [comment]
but besides the bounding box, the rest of the code is fine?

**Comment by djhoese** [comment]
What Satpy reader are you using?

The code as you have it looks fine. There may be some other things you need to do depending on what you're trying to visualize (a Satpy composite? a single band? etc).

**Comment by willows-1** [comment]
I am using ahi_shd as the reader and I am visualizing single band. I managed to changed the bounding box and get it to load but now the problem is plotting. Below is the edited code:

[cropped_scn = scn.crop(ll_bbox=(0, 40, 100, 100))
remapped_scn = cropped_scn.resample(resampler='native')

plt.figure()  # create a new figure
remapped_scn.plot.imshow() 
plt.title("Map of country - 09/04/21 0200 Time")](url)

The error I am getting is for the plotting. I am getting this error as seen below:

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-14-5a1edfcb682d> in <module>
      1 plt.figure()  # create a new figure
----> 2 remapped_scn.plot.imshow() 
      3 plt.title("Map of singapore - 09/04/21 0200 Time")

AttributeError: 'Scene' object has no attribute 'plot'
```

**Comment by djhoese** [comment]
Before, in your original code, you were calling `.sel` on `scn[my_channel]` where `scn[my_channel]` is an xarray DataArray. The `.crop` method on the `Scene` has returned a new `Scene` object, not a `DataArray`. You need to do `remapped_scn[my_channel].plot.imshow()`.

**Comment by willows-1** [comment]
Hi djhoese, I used the remapped_scn[my_channel].plot.imshow() but I am still getting the image of the earth and not a zoom in picture of a country. Below is the edited code so far:

```
cropped_scn = scn.crop(ll_bbox=(0, 40, 10, 110))
remapped_scn = cropped_scn.resample(resampler='native')

plt.figure()  # create a new figure
remapped_scn[my_channel].plot.imshow()
plt.title("Map of country")
```

**Comment by djhoese** [comment]
I think you have your bbox coordinates wrong. It should be (lon_min, lat_min, lon_max, lat_max). 110 is above the maximum latitude of 90.

**Comment by willows-1** [comment]
I got the cropped picture now, thanks djhoese for all the help! So just to clarify, the coordinates should always be in this order: (lon_min, lat_min, lon_max, lat_max)? Also to get the crop picture of a region, its better to have a bounding box rather than a single point?

**Comment by djhoese** [comment]
Yes, in that order, as the docstring says.

You need to specify the range of data you want. Your data is 2-dimensional (a `y` dimension and an `x` dimension) so that means you have to have a starting point and ending point for each dimension. Another way to describe this is as a bounding box which is made up of a xmin, ymin, xmax, and ymax. If you give a single point then you are only going to get a single point. I'm not sure if xarray supports this in the way you need so Satpy's `crop` method is needed.

**Comment by djhoese** [comment]
I'm going to close this as it seems your original issue is resolved. If you don't think so feel free to comment here and we'll reopen it. We can also continue this discussion here while this is closed if you'd like.

**Comment by willows-1** [comment]
> I'm going to close this as it seems your original issue is resolved. If you don't think so feel free to comment here and we'll reopen it. We can also continue this discussion here while this is closed if you'd like.

sure djhoese, thank you for helping me out!

**Comment by willows-1** [comment]
Hi djhoese, to follow up with the issue of cropping a region from a satellite image, is it possible to crop a region using cartopy?
Below is the code I followed from a website but I cant crop it. I am getting the error as seen below. Do let me know how I can crop using cartopy function

```
%matplotlib notebook
import matplotlib.pyplot as plt

crs = scn[my_channel].attrs['area'].to_cartopy_crs()

crop= crs.crop(ll_bbox=(100, 0, 110, 5))
ax = plt.axes(projection=crs)

my_data = scn[my_channel]
my_data.plot.imshow(transform=crs)
ax.coastlines()
ax.gridlines()
```
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-23-f707ccfcfbbd> in <module>
----> 1 crop= crs.crop(ll_bbox=(100, 0, 110, 5))
      2 ax = plt.axes(projection=crs)
      3 
      4 my_data = scn[my_channel]
      5 my_data.plot.imshow(transform=crs)

AttributeError: '_PROJ4Projection' object has no attribute 'cr
```op'

**Comment by djhoese** [comment]
I'm not sure what you mean. What isn't working? Can't you change your extents to match the region you want? Note that you probably have to convert your extents to the geostationary projection which is what your `CRS` object is in.

**Comment by willows-1** [comment]
Hi djhoese, the code is working but I am not able to get the desired output which is the image of the country's land. What the output is showing is just an outline of the region and not land (seen in the putline of region zip file).

**Comment by djhoese** [comment]
No need to use zip files. Here are your images (for my own reference):

![SharedScreenshot](https://user-images.githubusercontent.com/1828519/118268911-a3fe4e80-b483-11eb-90f7-93b16581eeb5.jpg)

![outline of region](https://user-images.githubusercontent.com/1828519/118268962-b4162e00-b483-11eb-9f75-c0680e8ff238.jpg)

So is the data not what you expect (the colors of the pixels)? Or is the location you are seeing not what you expect?

**Comment by willows-1** [comment]
I want to obtain the country Singapore (ie. outlined at row 2 from the bottom) but all I see is its outline

I am intending to see something like this:
![image](https://user-images.githubusercontent.com/66007300/118272561-5fab9680-b4f5-11eb-9c3f-ab6844be0222.png)

**Comment by willows-1** [comment]
is there a way to modify the code?

**Comment by djhoese** [comment]
Your extents are `extent = [103, 105, 1, 3]`, what happens if you change them to `extent = [103, 104, 1, 2]`? Maybe I'm not understanding the question, but if you want a smaller region then make your extents smaller.

**Comment by willows-1** [comment]
I got this image:

![image](https://user-images.githubusercontent.com/66007300/118275343-e31ab700-b4f8-11eb-9d34-889f92326c01.png)

Its a closer view but still showing the outline of the country. Usually how to view the land as seen in the picture below?

![image](https://user-images.githubusercontent.com/66007300/118275549-2543f880-b4f9-11eb-85b0-d28ea7e91b2a.png)

**Comment by djhoese** [comment]
The outlines are added because you have this in your code:

```
ax.coastlines(resolution= '10m')
```

The reason you don't see a difference between land and sea is probably because of the instrument band you chose. Some wavelengths/bands show land better than others. If you want something that looks like your last image then you probably want the `true_color` composite. That's what you'll need to ask for in your `scn.load(['true_color'])` call. It all depends on what you want. If you do use `true_color` then you'll also need to add `rgb="bands"` to your `imshow` call. There may be one other step, but I'll wait for your answer on what you want before we get into that.

**Comment by willows-1** [comment]
I want the view the land and be able to see difference between land and sea

**Comment by willows-1** [comment]
but do I have to import composites?

**Comment by djhoese** [comment]
Are you just trying to make a pretty picture? Then you should load `true_color` (set `my_channel = "true_color"`). Below is some code that provides an example of what you need to do to get this to work with cartopy. Note that I set `my_channel` to true_color and I resample the Scene because the bands that make up the true_color RGB are not the same resolution and resampling is needed to make them all the same resolution.

```
%matplotlib notebook
import matplotlib.pyplot as plt
import cartopy
import cartopy.crs as ccrs
from cartopy._crs import (CRS, Geodetic, Globe, PROJ4_VERSION,
                          WGS84_SEMIMAJOR_AXIS, WGS84_SEMIMINOR_AXIS)
from satpy.writers import get_enhanced_image
from satpy import Scene

central_lon, central_lat = 103.82287200000002, 1.3649170000000002

my_channel = 'true_color'
scn = Scene(reader='ahi_hsd', filenames=[...])
scn.load([my_channel])
new_scn = scn.resample(resampler='native')

CRS = new_scn[my_channel].attrs['area'].to_cartopy_crs()
extent = [103, 105, 1, 3]
ax = plt.axes(projection=ccrs.Orthographic(central_lon, central_lat))
ax.set_extent(extent)

my_data = new_scn[my_channel]

# only needed if loading an RGB composite:
my_data = get_enhanced_image(my_data).data

my_data.plot.imshow(transform=CRS, rgb='bands')
ax.coastlines(resolution= '10m')
ax.gridlines()
```

**Comment by willows-1** [comment]
yeap, I am trying to make the picture look neater

**Comment by willows-1** [comment]
but when I tried to run the code as seen below, I am getting error:

```
central_lon, central_lat = 103.82287200000002, 1.3649170000000002

my_channel = 'true_color'
scn = Scene(reader='ahi_hsd', filenames= filenames)
scn.load([my_channel])
new_scn = scn.resample(resampler='native')
```
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-4-b8e13661ba23> in <module>
      4 scn = Scene(reader='ahi_hsd', filenames= filenames)
      5 scn.load([my_channel])
----> 6 new_scn = scn.resample(resampler='native')

C:\ProgramData\anaconda3\envs\satpy\lib\site-packages\satpy\scene.py in resample(self, destination, datasets, generate, unload, resampler, reduce_data, **resample_kwargs)
    815 
    816         if destination is None:
--> 817             destination = self.finest_area(to_resample_ids)
    818         new_scn = self.copy(datasets=to_resample_ids)
    819         # we may have some datasets we asked for but don't exist yet

C:\ProgramData\anaconda3\envs\satpy\lib\site-packages\satpy\scene.py in finest_area(self, datasets)
    233 
    234         """
--> 235         return self._compare_areas(datasets=datasets, compare_func=max)
    236 
    237     def max_area(self, datasets=None):

C:\ProgramData\anaconda3\envs\satpy\lib\site-packages\satpy\scene.py in _compare_areas(self, datasets, compare_func)
    203         areas = [x for x in areas if x is not None]
    204         if not areas:
--> 205             raise ValueError("No dataset areas available")
    206 
    207         if not all(isinstance(x, type(areas[0]))

ValueError: No dataset areas available
```

**Comment by willows-1** [comment]
As of now I only have single band, which is B01. So this means I cant do composite image?

**Comment by djhoese** [comment]
The error means that no data was loaded. This likely means your filenames weren't read properly.

> As of now I only have single band, which is B01. So this means I cant do composite image?

If you only have the files for the B01 band then you can't create an RGB composite. You can only load and view B01 data. B01, as you have seen, does not show a difference between land and water due to the wavelength it is measuring/detecting.

**Comment by willows-1** [comment]
ahh I see, make sense now. So once I have B02, B03, and other such bands, composite image can be created based on the code you created?

**Comment by djhoese** [comment]
Yes...at least that's the idea.

**Comment by willows-1** [comment]
> Yes...at least that's the idea.

yeap alright, understood now. Thank you very much for assisting me. I am still new to satpy and satellite image analysis so I am still learning along the way. Once I get the data for other bands, I will try out the code and let you know if its working. But I believe this time it will work.

Thank you very much :)

**Comment by djhoese** [comment]
If you haven't already, you should maybe look at my tutorial: https://github.com/pytroll/tutorial-satpy-half-day

**Comment by willows-1** [comment]
> If you haven't already, you should maybe look at my tutorial: https://github.com/pytroll/tutorial-satpy-half-day

yeap I have been viewing your tutorials too and have been learning a lot from you! I just need a bit more practice with this :)

**Comment by willows-1** [comment]
Hi djhoese, I obtained the data for other bands and I tried to run the code that you provided but its taking very long time for the jupyter notebook to load, causing my laptop crash a few times. Is there a reason for this?

**Comment by djhoese** [comment]
Well the reason is likely that you are working with a lot more data. How much memory and how many cores do you have on the system that is executing the notebook?

You may find some tips for performance on the Satpy FAQ: https://satpy.readthedocs.io/en/stable/faq.html

Otherwise, I may need more information about how it is crashing. For example, do you get an error? You may need to resample the data to a smaller area as a full disk image may be too much for cartopy to handle quickly and perform well.

**Comment by willows-1** [comment]
Hi djhoese, currently there are 4 cores in my laptop and RAM is 16GB. The laptop crashed before showing any results, so I cant tell if there was any error. What is the code to resample the data to a smaller area?

**Comment by djhoese** [comment]
In that case, I would look at the FAQ linked above and look at reducing the chunk size of your data.

Since I know that you want to crop the data, that would be another option **if** you did it with Satpy (`Scene.crop`). Right now the way you are doing it is passing all the data to matplotlib/cartopy, they are computing the images for these data, and then displaying only the chunk being used. This is very wasteful from a resources point of view.

If you don't want to crop the data, the easiest way to resample to a smaller (lower resolution) version of the image would be to do:

```
new_scn = scn.resample(scn.coarsest_area(), resampler='native')
```

Instead of the resample call you are doing now. Otherwise, you'd have to create your own AreaDefinition and do nearest neighbor resampling (or another resampling algorithm) to that smaller or lower resolution AreaDefinition.

**Comment by willows-1** [comment]
noted, thank you very much
