### ISSUE TITLE
KeyError 'v' using Scene(base_dir=, reader=)

### ISSUE THREAD

**Issue by howff** [pytroll/satpy#167]
#### Code Sample, a minimal, complete, and verifiable piece of code

```python
global_scene = Scene(reader='viirs_sdr', base_dir='/data/viirs1/201801241307')
```
#### Problem description

Gives an error

```
   File "/packages/pytroll/local/lib/python2.7/site-packages/satpy/readers/__init__.py", line 398, in load_readers
   readers_files = set(filenames[reader[idx]])
KeyError: 'v'
```

There are four ways to initialise a Scene
1. base_dir='dir'
2. filenames=glob('dir/*.h5')
3. base_dir='dir, reader='viirs_sdr'
4. filenames=glob('dir/*.h5'), reader='viirs_sdr'

Option 3 is the one which fails with KeyError.

#### Versions of Python, package at hand and relevant dependencies

satpy 0.8.0

**Comment by mraspaud** [comment]
Yes, the `basedir` option is now removed since 0.8.0. I can't find a warning for this in the docs, so we have to fix this, and the error you get it not clear at all, but here is the recommended way of doing it now:
http://satpy.readthedocs.io/en/latest/readers.html#search-for-local-files

**Comment by davidh-ssec** [comment]
The `Scene.__init__` should have used the `find_files_and_readers` function internally along with a deprecation warning (agreed this is not documented well enough). My worry is that the `find_files_and_readers` function may be returning unexpected output (a single string when it should be a list of filenames).
