### ISSUE TITLE
Rename fci_l1c_fdhsi to fci_l1c_nc

### ISSUE THREAD

**Issue by ameraner** [pytroll/satpy#1684]
## Feature Request

**Is your feature request related to a problem? Please describe.**
The current FCI L1c reader is called `fci_l1c_fdhsi`, where `fdhsi` indicates the imaging mode (Full Disc High Spectral resolution Imagery). The counterpart of `fdhsi` is the `hrfi` imaging mode (High spatial Resolution Fast Imagery). HRFI images will be distributed in separate NetCDF4 files, that however have exactly the same filetype and structure as FDHSI files. The channels inside the HRFI, and therefore the Satpy datasets, will have different names (e.g. `vis_06_hr` in HRFI instead of `vis_06` in FDHSI).

Keeping the current `fci_l1c_fdhsi` reader name implies that in future, when the first (test) data for HRFI will be available, we will have to implement an `fci_l1c_hrfi` reader.

Since the filetype and structure is essentially identical, there is however no reason to have two readers defined.

**Describe the solution you'd like**
Rename the `fci_l1c_fdhsi` to `fci_l1c_nc`.
With this
- we have only one reader for all FCI L1c files, making the usage of Satpy simpler
- we comply to the usual convention of having readers called as `instrument_level_format`
- by having two filetypes in the yaml, we can still assign the `_hr` datasets to the HRFI files, and, if necessary, have different handling in the filehandlers.

This PR comes a little late, but fortunately not _too_ late, as released test data has not spread too much yet, and limited users are already using Satpy for it.
However, there are already users/software that have implemented workflows using the old reader name, and some documentation.

I would therefore propose to rename the reader, but find a solution to keep the old name working for a while.

The best solution in my opinion would be to use the `OLD_READERS` mechanism in `configs_for_reader`
https://github.com/pytroll/satpy/blob/88938ab8e0eb2b2f6ae89665733b7e2281720fce/satpy/readers/__init__.py#L260-L268
in the current implementation, however, a hard ValueError is raised. To make the transition smoother, I would propose to go back to a Warning instead, at least for a while. This means basically undoing what @djhoese did in https://github.com/pytroll/satpy/pull/597. Note that `OLD_READERS` is currently empty, so returning to a Warning would not affect any other workflow.

Another, less elegant, solution would be to keep the old yaml file around, pointing to the renamed FileHandler.

Please let me know your thoughts, if you agree with my preferred solution or if I'm missing something.

FYI @gerritholl @mraspaud @sjoro

**Comment by mraspaud** [comment]
I support the renaming!

Regarding the Warning vs Error: We might need this in the future again, so how about having an extra `PENDING_OLD_READER_NAMES` also that would issue the warning? and then when the pending period is over, the reader name is moved to `OLD_READER_NAMES` ?

**Comment by sjoro** [comment]
the first prototype of the reader was created before trying to streamline and/or rationalise the namings. so, i also support the renaming!

**Comment by gerritholl** [comment]
The first prototype of this reader was called`fci_fdhsi` and was added in #13.

I am in doubt about the name change.  The current name is consistent with the naming pattern `<sensor>[_<processing level>[_<level detail>]][_<file format>]`.  I find it somewhat debatable whether NetCDF is a complete format identifier.  The format identifier `fdhsi` is more precies than `nc`.  There can be many file formats using NetCDF.  What if some future project reprocesses the FCI record and publishes the files in a different file format that is _also_ based on NetCDF?  This reader doesn't just read any NetCDF file containing FCI data, it reads the official EUMETSAT format as defined in the PUG EUM/MTG/USR/13/719113.  Should that be captured in the reader name?

**Comment by mraspaud** [comment]
yes, `DeprecationWarning` sounds good!

**Comment by ameraner** [comment]
The `PENDING_OLD_READER_NAMES` is being added in https://github.com/pytroll/satpy/issues/1684
