### ISSUE TITLE
Remove `compression` argument from CF writer `save_datasets`

### ISSUE THREAD

**Issue by BENR0** [pytroll/satpy#1699]
## Feature Request

**Is your feature request related to a problem? Please describe.**
The documentation says the `compression` argument is passed on to xarray's `to_netcdf` method and links to the xarray documentation for more information. This is a little confusing because
the `to_netcdf` method does not have a `compression` argument. Instead the compression can be specified b within the encoding dictionary. While this in itself might confuse users additionally it is unclear what will happen if the user supplies an encoding dictionary to the `save_datasets` method which includes information regarding compression. Which setting takes precedence then?

**Describe the solution you'd like**
In order to keep it close to the `to_netcdf` method the `compression` parameter should be removed and the documentation updated that compression is possible using the `encoding` parameter which will be passed to `to_netcdf` together with the link to the xarray documentation.

**Describe any changes to existing user workflow**
The default behavior should not change but users currently using the `compression` argument would need to change their code.

**Comment by sfinkens** [comment]
I agree, good catch!

**Comment by djhoese** [comment]
Do either of you have the time to make a PR for this?

**Comment by mraspaud** [comment]
@djhoese not really, but still...

**Comment by mraspaud** [comment]
Ok, after some discussion on slack, it seems to be a consensus that the default behaviour of compressing netcdf files should be phased-out to let the user take control through the encoding parameter and attribute, as is done in `xarray.to_netcdf`.
