### ISSUE TITLE
Unable to read HY-2B SCA L2B file

### ISSUE THREAD

**Issue by MengXin001** [pytroll/satpy#1728]
I noticed that there has `hy2_scat_l2b_h5` reader in Satpy so I tried to plot the wind field scan data of hy-2b.
```import os, glob
from satpy.scene import Scene
filenames = ['D:\Desktop\sate\H2B_OPER_SCA_L2B_OR_20210612T094756_20210612T103141_13188_pwp_250_07_owv.h5']
scn = Scene(filenames, reader='hy2_scat_l2b_h5')
```
and then responds to the following

```
No filenames found for reader: hy2_scat_l2b_h5
Don't know how to open the following files: {'D:\\Desktop\\sate\\H2B_OPER_SCA_L2B_OR_20210612T094756_20210612T103141_13188_pwp_250_07_owv.h5'}
Traceback (most recent call last):
  File "C:\Users\Lenovo\Documents\Sate\gf.py", line 6, in <module>
    scn = Scene(filenames, reader='hy2_scat_l2b_h5')
  File "C:\Users\Lenovo\miniconda3\envs\my_satpy_env\lib\site-packages\satpy\scene.py", line 108, in __init__
    self._readers = self._create_reader_instances(filenames=filenames,
  File "C:\Users\Lenovo\miniconda3\envs\my_satpy_env\lib\site-packages\satpy\scene.py", line 157, in _create_reader_instances
    return load_readers(filenames=filenames,
  File "C:\Users\Lenovo\miniconda3\envs\my_satpy_env\lib\site-packages\satpy\readers\__init__.py", line 496, in load_readers
    raise ValueError("No supported files found")
ValueError: No supported files found
```

**Comment by mraspaud** [comment]
@MengXin001 Thanks a lot for reporting this issue!

This reader was written for data distributed by EUMETSAT and as such it has a different filename pattern (see here: https://github.com/pytroll/satpy/blob/main/satpy/etc/readers/hy2_scat_l2b_h5.yaml#L11 ). Maybe it could be as easy as adding another file pattern here, but I don't know if EUM does anything to the format. @TAlonglong do you know?

**Comment by MengXin001** [comment]
Thanks!
I got the data from [NSOAS](https://osdds.nsoas.org.cn/),it is different from the data filename that Eumetsat distributes.

**Comment by mraspaud** [comment]
You could try adding a filepattern that matches your filename to see if it works?

**Comment by TAlonglong** [comment]
I think Eumetsat only rename the files to match the WMO filename structure. See here https://navigator.eumetsat.int/product/EO:EUM:DAT:0381?query=hy&s=simple.

So it should work to add a new filename.

**Comment by MengXin001** [comment]
I successfully plotted the product, thank you!

**Comment by mraspaud** [comment]
@MengXin001 nice that you fixed it! how did the filepattern you added look like? maybe we can add it to satpy so that other user like you can read the product out of the box?

**Comment by MengXin001** [comment]
> @MengXin001 nice that you fixed it! how did the filepattern you added look like? maybe we can add it to satpy so that other user like you can read the product out of the box?
Alright, I converted the filename format of NSOAS to EUM format. Because I don’t know the meaning of some format in the NSOAS documents , some of which are not used in the documents distributed by EUM. 😅
