### ISSUE TITLE
geotiff writer ignores dtype argument, always writes float if enhance=False

### ISSUE THREAD

**Issue by gerritholl** [pytroll/satpy#1730]
**Describe the bug**

When writing a geotiff with `enhance=False`, satpy always writes floating points, even if `dtype="uint8"` is passed.  For single channels, this leads to an unwanted dtype in the image.  For RGBs, this leads to ValueError.

**To Reproduce**

```python
import os
from glob import glob
from satpy import Scene
from satpy.utils import debug_on; debug_on()
seviri_files = glob("/media/nas/x21308/scratch/SEVIRI/202103300900/H-000*")
sc = Scene(filenames=seviri_files, reader=["seviri_l1b_hrit"])
sc.load(["IR_108", "airmass"])
ls = sc.resample("eurol")
ls.save_dataset("IR_108", enhance=False, dtype="uint8")
ls.save_dataset("airmass", enhance=False, dtype="uint8")
```

**Expected behavior**

I expect that two unenhanced images with dtype=uint8 are written.

**Actual results**

For the single channel image, `gdalinfo` reveals:

```
Band 1 Block=2560x1 Type=Float32, ColorInterp=Gray
```

For the RGB, Python throws a ValueError:

```
Traceback (most recent call last):
  File "/home/gholl/checkouts/protocode/mwe/rgb-unenhanced.py", line 10, in <module>
    ls.save_dataset("airmass", enhance=False, dtype="uint8")
  File "/home/gholl/checkouts/satpy/satpy/scene.py", line 986, in save_dataset
    return writer.save_dataset(self[dataset_id],
  File "/home/gholl/checkouts/satpy/satpy/writers/__init__.py", line 811, in save_dataset
    return self.save_image(img, filename=filename, compute=compute, fill_value=fill_value, **kwargs)
  File "/home/gholl/checkouts/satpy/satpy/writers/geotiff.py", line 208, in save_image
    raise ValueError("Image must be in 'L' mode for floating "
ValueError: Image must be in 'L' mode for floating point geotiff saving
```

**Environment Info:**
 - Satpy Version: v0.29.0-51-g7b8eb8d4 (latest main at the time of writing)
 - PyResample Version: v1.12.0
 - trollimage version: v1.15.0-1-g6a663c1

**Additional context**

`git bisect` reveals this bug was introduced in #1499.

**Comment by BENR0** [comment]
Sorry I missed this too. While this definitely is a bug it seems to me that saving an unenhanced image with "unit8" is in most cases not really wanted because there will be clipping of the data. Maybe a warning should be added for the case when clipping possibly might occur? In any case I added the fix suggested by @djhoese in #1733.
