### ISSUE TITLE
Ask For Help: How to operate SunZenithCorrector manually?

### ISSUE THREAD

**Issue by yukaribbba** [pytroll/satpy#1759]
Doing some exercises on PySpectral without satpy. I need get band data soloar-zenith corrected before passing them to rayleigh corrector. So I tried `sunzen_corr_cos` in `utils.py`:

```
from pyorbital.astronomy import get_alt_az, sun_zenith_angle

sunz = sun_zenith_angle('2021-07-08T05:00:00.000000', londata, latdata)
sunz_rad = np.deg2rad(sunz)
cos_zen = cos_zen('2021-07-08T05:00:00.000000', londata, latdata)

limit = 88.
max_sza = 95.

limit_rad = np.deg2rad(limit)
limit_cos = np.cos(limit_rad)
max_sza_rad = np.deg2rad(max_sza)
max_sza_cos = np.cos(max_sza_rad)

corr = 1. / cos_zen

grad_factor = (sunz_rad - limit_rad) / (max_sza_rad - limit_rad)
grad_factor = 1 - np.log(grad_factor + 1) / np.log(2)
grad_factor = grad_factor.clip(0.)

corr = np.where(cos_zen > limit_cos, grad_factor / limit_cos, 1. / cos_zen)
```

But the only visible part in the output is the day/night boundary.
![image](https://user-images.githubusercontent.com/72339781/125195440-3787ac00-e288-11eb-9fc3-7a21665d82cc.png)

I change to 
`corr = np.where(cos_zen < limit_cos, grad_factor / limit_cos, 1. / cos_zen)`

This time I got the whole image, but it looks very strange, especially on the edge area.
![image](https://user-images.githubusercontent.com/72339781/125195548-ab29b900-e288-11eb-9a41-0a559e1f7256.png)

Compared to the satpy version, the gradient is hard and slim. Also, it seems that there is not sufficient sun_z correction so the rayleigh correction becomes too strong.
![image](https://user-images.githubusercontent.com/72339781/125195656-3145ff80-e289-11eb-9d60-e1d63ea44207.png)

So how can I get this done?

**Comment by djhoese** [comment]
In this line:

```python
grad_factor = (sunz_rad - limit_rad) / (max_sza_rad - limit_rad)
```

You should have `np.arccos(cos_zen)` where you have `sunz_rad`. At least that's the first major difference I see.

The `np.where` versus `.where` used in the Satpy method is important. `np.where(cond, x, y)` means "where 'cond' is True return 'x' else 'y'". [In xarray](http://xarray.pydata.org/en/stable/generated/xarray.DataArray.where.html), the `data.where(cond, x)` means "where 'cond' is True give me 'data', else give me 'x'". So it requires the opposite condition in your case. Your last line should probably be:

```python
corr = np.where(cos_zen > limit_cos, corr, grad_factor / limit_cos)
```

**Comment by yukaribbba** [comment]
@djhoese Ok, I got this. Thanks!

**Comment by djhoese** [comment]
Keep us updated on how it goes. If you get it to work please close this issue.
