### ISSUE TITLE
[Question] Geolocation information of FengYun4A (FY-4A) AGRI L1B data

### ISSUE THREAD

**Issue by ektf1147** [pytroll/satpy#1773]
Hello.

I am using Satpy to read FengYun (FY)-4A AGRI L1B data and I would like to ask a question.

I have attached my simple code to read and plot the FY-4A AGRI band 3 (center wavelength: 0.83 um) image.

```python
from satpy import Scene
from glob import glob
import matplotlib.pyplot as plt
from mpl_toolkits.basemap import Basemap
import numpy as np


#### 1. Read FengYun-4A C03 (0.86 um) data
fname = glob('../../Datasets/FY_4A_AGRI/FY4A-_AGRI--_N_DISK_1047E_L1-_FDI-_MULT_NOM_20190317050000_20190317051459_1000M_V0001.HDF')
scn = Scene(reader='agri_l1', filenames=fname)

##### a. Load channel
scn.load(['C03'])

##### b. Crop specific area
lonmin, latmin, lonmax, latmax = 125, 35, 130, 40
crop_scn = scn.crop(ll_bbox=(lonmin, latmin, lonmax, latmax))

##### c. Read 0.86 um reflectance
sat_w_tb_vis = crop_scn['C03'].values

##### d. Read lat/lon
area_def = crop_scn['C03'].attrs['area']
sat_w_lon, sat_w_lat = area_def.get_lonlats()


####  2. Plot FengYun-4A C03 (0.86 um) data
fig, ax = plt.subplots()

m = Basemap(projection='merc', lat_0=37.35, lon_0=126.58, resolution = 'h',
                       urcrnrlat=latmax, llcrnrlat=latmin, llcrnrlon=lonmin, urcrnrlon=lonmax)

m.drawcoastlines(color='yellow', linewidth=0.25)
m.drawparallels(np.arange(latmin, latmax+1, 2), labels = [True, False, False, False], color='yellow')
m.drawmeridians(np.arange(lonmin, lonmax+1, 2), labels = [False, False, False, True], color='yellow')

img = m.pcolormesh(sat_w_lon, sat_w_lat, sat_w_tb_vis, latlon=True, cmap=plt.cm.binary_r)
ax.set_title('FengYun-4A C03 reflectance', loc= 'left')

plt.savefig('./FengYun-4A_C03_reflectance_mercator.png', dpi=300, bbox_inches='tight')
```

I have attached the resulting figure.
From this figure,  I think that it seems to be an error in the geolocation information of FY-4A AGRI data 
(e.g. paying attention to land boundaries or red arrow).

I wonder if this is a problem with the FY-4A data, or a problem with Satpy, or just my code.
Any advice would be appreciated.

The Satpy version I used is 0.25.1.

![FengYun-4A_C03_reflectance_mercator](https://user-images.githubusercontent.com/59725357/126754348-e57657e7-ac86-466e-b00c-36558ad2d0d5.png)

**Comment by mraspaud** [comment]
@ektf1147 Thanks for asking this question!

@zxdawn is then one who worked most on this reader, so maybe he can answer also, but some pointers:
- pcolormesh is know for shifting the plot in both x and y directions I think, try imshow to see if it makes a difference.
- Check multiple scene to see if the shift is consistent. On some geostationary satellites, the data wobbles (Meteosat is notably affected by this)
- the creation of the area for basemap could differ from the one satpy read from the file. You should be able to get the cartopy (and even maybe basemap) definition from the `scn["C03"].attrs["area"]` object with the `to_cartopy_crs` method, see for example here: https://pyresample.readthedocs.io/en/latest/plot.html#getting-a-cartopy-crs

**Comment by zxdawn** [comment]
@ektf1147 Could you check these global attributes in the downloaded file?
https://github.com/pytroll/satpy/blob/07a87af496fafca1bcb061824f532a01ab927f48/satpy/readers/agri_l1.py#L36-L41

If these are correct, then it may be the plotting issue mentioned by @mraspaud

**Comment by ektf1147** [comment]
@mraspaud Thanks for your quick response!

I tried to check your comments using the cartopy (+imshow) instead of Basemap. I attached my code as follows.

-----------------------------------------------------------------------------------------------------------------------------
from satpy import Scene
from glob import glob
import matplotlib.pyplot as plt
from mpl_toolkits.basemap import Basemap
import numpy as np
import cartopy

########################################
# 1. Read FengYun-4A C03 (0.86 um) data
########################################
fname = glob('../../Datasets/FY_4A_AGRI/FY4A-_AGRI--_N_DISK_1047E_L1-_FDI-_MULT_NOM_20190317050000_20190317051459_1000M_V0001.HDF')
scn = Scene(reader='agri_l1', filenames=fname)

# a. Load channel
scn.load(['C03'])

# b. Crop specific area 
lonmin, latmin, lonmax, latmax = 125, 35, 130, 40
crop_scn = scn.crop(ll_bbox=(lonmin, latmin, lonmax, latmax))

# c. Read 0.86 um reflectance
sat_w_tb_vis = crop_scn['C03'].values

# d. Read lat/lon
area_def = crop_scn['C03'].attrs['area']
crs = area_def.to_cartopy_crs()


########################################
# 2. Plot FengYun-4A C03 (0.86 um) data
########################################

fig, ax = plt.subplots(subplot_kw=dict(projection=crs))
coastlines = ax.coastlines(color='yellow', resolution='10m', linewidth=.1)  
ax.set_global()
img = plt.imshow(sat_w_tb_vis, origin='upper', cmap=plt.cm.binary_r, extent=crs.bounds, transform=crs)
ax.set_title('FengYun-4A C03 reflectance', loc= 'left')

plt.savefig('./FengYun-4A_C03_reflectance_imshow_201903170500_cartopy.png', dpi=300, bbox_inches='tight')

-----------------------------------------------------------------------------------------------------------------------------

I have attached the resulting figure (2019.03.17, 05:00 UTC).
![FengYun-4A_C03_reflectance_imshow_20190317050000_cartopy](https://user-images.githubusercontent.com/59725357/126948134-ced9cd43-9c96-4cef-8c09-717775f5c296.png)


I also checked the another scene (2020.01.14, 03:00 UTC)
![FengYun-4A_C03_reflectance_imshow_20200114030000_cartopy](https://user-images.githubusercontent.com/59725357/126948986-747bf9a1-6bdd-4859-a9ec-e9e9a05fe499.png)


From above figures, I think that similar patterns were found..


I also checked the scene  (2019.03.17, 05:00 UTC) for Himawari-8 HSD data and attached the resulting figure.
![Himawari-8_B04_reflectance_imshow_201903170500_cartopy](https://user-images.githubusercontent.com/59725357/126950350-a19cd7ec-913e-4152-ade7-22d171c48d9f.png)



@zxdawn Thanks for your quick response!
I am sorry, but could you tell me how to check what you mentioned..?

**Comment by zxdawn** [comment]
@ektf1147 The easiest way is to open the file in software called Panoply. Then, just click to see the attributes.

**Comment by ektf1147** [comment]
@zxdawn Thanks! I used the Panoply software to check the global attributes of FY-4A AGRI data.
The global attributes of FY-4A AGRI 1 km data which I used are as follows:

  // global attributes:
  :Responser = "NSMC";
  :Version_Of_Software = "V0001";
  :Software_Revision_Date = "2016-08-16";
  :Observing_Beginning_Date = "2019-03-17";
  :Observing_Beginning_Time = "05:00:04.551";
  :Observing_Ending_Date = "2019-03-17";
  :Observing_Ending_Time = "05:12:38.927";
  :Data_Creating_Date = "2019-03-17";
  :Data_Creating_Time = "05:15:38.624";
  :AdditionalAnnotation = "shinetek";
  :OBIType = "DISK";
  :ProductID = "FY4A-_AGRI--_N_DISK_1047E_L1-_FDI-_MULT_NOM_20190317050000_20190317051459_1000M_V0001.HDF";
  :ProducetName = "FY4A-_AGRI--_N_DISK_1047E_L1-_FDI-_MULT_NOM_20190317050000_20190317051459_1000M_V0001.HDF";
  :Satellite_Name = "FY4A";
  :Sensor_Name = "AGRI";
  :Sensor_Identification_Code = "AGRI";
  :Dataset_Name = "MULT";
  :File_Name = "FY4A-_AGRI--_N_DISK_1047E_L1-_FDI-_MULT_NOM_20190317050000_20190317051459_1000M_V0001.HDF";
  :File_Alias_Name = "FY4A-_AGRI--_N_DISK_1047E_L1-_FDI-_MULT_NOM_20190317050000_20190317051459_1000M_V0001.HDF";
  :VisCorrectionCoefficientVer = "V2";
  :Data_Quality = 1UB; // ubyte
  :Number_Of_Scans = 65535; // int
  :Incomplete_Scans = 65535; // int
  :QA_Scan_Flag = 0UB; // ubyte
  :QA_Pixel_Flag = 0US; // ushort
  :Begin_Line_Number = 0US; // ushort
  :End_Line_Number = 10991US; // ushort
  :Begin_Pixel_Number = 0US; // ushort
  :End_Pixel_Number = 10991US; // ushort
  :NOMCenterLat = 0.0f; // float
  :NOMCenterLon = 104.7f; // float
  :NOMSatHeight = 3.5786E7f; // float
  :RegCenterLon = 65535.0f; // float
  :RegCenterLat = 65535.0f; // float
  :RegLength = 10992.0f; // float
  :RegWidth = 10992.0f; // float
  :dEA = 6378.14; // double
  :dSamplingAngle = 28.0; // double
  :dSteppingAngle = 28.0; // double
  :dObRecFlat = 298.257223563; // double

**Comment by zxdawn** [comment]
Oh, I see. The  `_COFF_list,  _CFAC_list ,  _LOFF_list, and _LFAC_list` aren't available in the attributes. They store these parameters in [separate PDF](https://github.com/pytroll/satpy/files/6876948/lonlat.pdf). The satpy version is as same as it ... No idea what causes the problem.

**Comment by mraspaud** [comment]
@zxdawn can you see the same problem with your data?

**Comment by ektf1147** [comment]
@mraspaud @zxdawn I'm not sure if this is the right solution, but I tried to comment out the line 163 in satpy/readers/agri_l1.py as follows:
           area_extent = (area_extent[0] + 2000, area_extent[1], area_extent[2] + 2000, area_extent[3])
     -> #area_extent = (area_extent[0] + 2000, area_extent[1], area_extent[2] + 2000, area_extent[3])

I attached the resulting figure (2019.03.17, 05:00 UTC)
![FengYun-4A_C03_reflectance_imshow_201903170500_cartopy-new](https://user-images.githubusercontent.com/59725357/127093372-8d27e809-3de1-43ca-a4ce-a4510ce06e44.png)

This is the another scene (2020.01.14, 03:00 UTC)
![FengYun-4A_C03_reflectance_imshow_202001140300_cartopy-new](https://user-images.githubusercontent.com/59725357/127093577-7ffa11ec-6196-4608-9401-d61feb64c79f.png)

**Comment by zxdawn** [comment]
@ektf1147 That could be the cause. I checked the commits and found that edited by @simonrp84: https://github.com/pytroll/satpy/commit/6254d82850f07ffa34cfd9de7708a9e0de73c7c1#diff-977b6587f01c689edd0c9c465c9bf9a2dcec4300b976428278e2ced1d20b0f55. Could you explain why did you add `+2000`, @simonrp84 ?

**Comment by simonrp84** [comment]
I think we discussed this on slack a long time ago: The geolocation was off by half a pixel, and the `+2000` fixed this.
However, I know that @sfinkens did some work refactoring the geostationary area code and am pretty sure he fixed the issue while doing so - meaning this `+2000` may not be needed any more.

I will test if the results improve with that removed.

**Comment by simonrp84** [comment]
Please see my pull request, #1782. This should fix the geolocation offset that you are seeing. In the PR I have included graphics similar to your own to illustrate the change.

@ektf1147 It'd be great if you could test this and check that it fixes your issue!

**Comment by ektf1147** [comment]
@simonrp84 Thanks for your hard work! I have tested your code and included the results. I think that it fixed the geolocation information of FY-4A AGRI. More accurate tests should be done by Satpy experts..

- Used file name: 'FY4A-_AGRI--_N_DISK_1047E_L1-_FDI-_MULT_NOM_20190317050000_20190317051459_1000M_V0001.HDF'
- Before correction
![FengYun-4A_C03_reflectance_imshow_201903170500_cartopy_old](https://user-images.githubusercontent.com/59725357/127868441-f6ad2a0b-0f48-4bc7-ad36-940d4bf3177a.png)

- After correction
![FengYun-4A_C03_reflectance_imshow_201903170500_cartopy-corrected](https://user-images.githubusercontent.com/59725357/127868457-45cb2fa2-deba-4896-86ad-94607d349084.png)

**Comment by sfinkens** [comment]
@simonrp84 I didn't have time to finish my work on the geostationary area extents. But I'll make sure to check FY-4A as well!
