### ISSUE TITLE
Remaining work items before 0.9 beta release

### ISSUE THREAD

**Issue by djhoese** [pytroll/satpy#178]
#### Problem description

The `feature-xarray` branch was merged to the `develop` branch recently. This was to reduce the amount of work needed to keep the xarray branch up to date with on-going fixes and features being added to SatPy. **However**, not everything in the xarray branch works or has been converted to work with xarray. This issue is a list of all of the things that still need to be converted or things that do not work in the xarray branch. If something does not work in both the `maint/0.8` branch **and** it does not work in the `develop` branch then it should get its own issue. If you are a maintainer of SatPy just add your items to the lists below, otherwise please comment on this issue and we will add them to the list.

- [x] Readers
  - [ ] IASI L2
  - [ ] LI L2
  - [x] GAC & LAC avhrr
  - [x] AMSR2
  - [ ] FCI
  - [ ] Callipso Caliop
  - [x] GEOCAT
  - [x] CLAVR-x
  - [x] Sentinel 3 SLSTR
  - [x] ABI L1B
  - [x] AAPP avhrr
  - [x] EPS avhrr
  - [x] NWCSAF products
  - [x] MAIA products
  - [x] Sentinel 1 SAR-C
  - [x] Sentinel 2 MSI
  - [x] VIIRS SDR
  - [x] VIIRS L1B
  - [x] VIIRS Compact
  - [x] MODIS HDF4 (level1)
  - [x] GOES 16
  - [x] GOES 15 HRIT
  - [x] Himawari HSD
  - [x] MSG HRIT
  - [x] MSG Native
  - [x] GOMS HRIT
  - [x] JMA HRIT
  - [x] NC OLCI L1B
  - [x] NC OLCI L2
  - [ ] generic_image (@loreclem)
  - [ ] ghrsst_osisaf
  - [ ] nc_nwcsaf_msg
  - [ ] scatsat_l2b
  - [x] nc_slstr
- [x] Composites
  - [x] VIIRS adaptive_dnb
  - [x] VIIRS histogram_dnb
  - [x] VIIRS dynamic_dnb
  - [x] VIIRS hncc_dnb
  - [x] VIIRS ratio sharpened composites (true color and false color)
  - [x] VIIRS Dust composites (fog and dust)
  - [x] VIIRS RGB composites (overview, etc)
  - [x] VIIRS Sun Normalized composites (natural_sun, etc)
  - [x] VIIRS snow_age
  - [x] ABI True Color
  - [x] ABI Natural Color
  - [x] ABI Airmass
- [x] Documentation
  - [x] Make sure any mention of `.info` is changed to `.attrs`
  - [x] Mention that xarray and dask are being used
  - [x] Update setup.py minimum dependency versions (xarray >=0.10.1, trollimage >=1.3.0, etc)
- [x] Misc.
  - [x] Filter reader data by area (might work already?)
  - [x] EWA Resampling algorithm
  - [x] Reduce redundant data load between composites when the they are resampled
  - [x] Adding coastlines via `.show` or `save_datasets`
  - [x] Remove 'Dataset' class from `satpy/dataset.py`
  - [ ] `convert_to_ninjotiff.py` script (@loreclem) 

Untested:
 - [x] SCMI writer
 - [ ] NinJoTIFF writer
 - [x] Custom datasets `scn['x'] = xarray.DataArray(my_data, attrs={...})`

**Comment by adybbroe** [comment]
I can load the overview composite, but remapping it give a seg fault!
This is with 
Python 2.7.5
Numpy 1.13.1
Xarray 0.10.0
Pyproj 1.9.5.1
