### ISSUE TITLE
Deprecate Scene.attrs property

### ISSUE THREAD

**Issue by djhoese** [pytroll/satpy#1799]
## Feature Request

**Is your feature request related to a problem? Please describe.**
I'm working on #1797 and I'm running into this annoyance where I'd like to get all the sensor names for the loaded datasets. Since there is already a `Scene.attrs["sensors"]` then I should just get it from that. However, this value is only set when the Scene is created. I propose deprecating `Scene.attrs` as it is used right now (see below for details). It is not kept up to date and does not reflect the actual loaded data if there is any difference between the reader's metadata and the actual DataArray metadata.

Currently the `.attrs` dictionary holds:

* sensors: A set of sensor names gathered from the reader's `sensor_names` property. 
* start_time: Minimum start_time among all loaded readers
* end_time: Maximum end_time among all loaded readers

**Describe the solution you'd like**

1. Remove the sensors/start_time/end_time default contents of `.attrs`.
2. Keep `.attrs` as an empty dictionary that users can add to (similar to xarray.Dataset), but does not change Satpy behavior at all and will only ever be used as extra metadata if it makes sense (ex. CF writer global attributes maybe?).
3. Optionally provide `.sensors`, `.start_time`, and `.end_time` properties on the Scene to get the equivalent metadata on-the-fly when it is requested. The values would be gathered by the loaded datasets and would not contact the reader's metadata at all.

**Describe any changes to existing user workflow**
Are there any backwards compatibility concerns? Changes to the build process? Additional dependencies?

**Additional context**

Other options:

1. For point 3 of my above proposed solution: we could fallback to the reader's metadata if no DataArrays are loaded.
2. Provide a wrapper (`Scene.__getattr__`) that automatically generates the `.attrs` metadata when `Scene.attrs` is requested. Or make `.attrs` a property (see mention of xarray below).
3. Provide a helper method that the internals of Satpy (the stuff my PR needs to use) that updates the metadata on ever `__setitem__`, `.load`, `__delitem__` call.

We have talked in other issues and meetings of making the `Scene` more like xarray's Dataset object. I think if this deprecation proposal is accepted that we avoid "magic" properties related to existing xarray interfaces like `.attrs` (my point 2 above).

**Comment by sfinkens** [comment]
I totally agree, if the information isn't static, it should become a property. An empty dict for the user's metadata is a nice idea, too.

**Comment by mraspaud** [comment]
Good idea with the seeing over this. I would try to mimic as much as possible the behaviour of `xr.Dataset` objects, as this is where we want to go, right?

**Comment by djhoese** [comment]
> as this is where we want to go, right?

Yes. I mention that in my last paragraph (I know, it is long). I'll try my best.

**Comment by djhoese** [comment]
This was technically closed back in https://github.com/pytroll/satpy/pull/1797. `.attrs` no longer holds anything that satpy depends on.
