### ISSUE TITLE
how to xRITDecompress files for using satpy

### ISSUE THREAD

**Issue by miladmz** [pytroll/satpy#1803]
Hi I want to read seviri hrit file with this format (H-000-MSG1__-MSG1_IODC___-HRV______-000001___-202009260430-C_) and get this error (WARNING:hrit_base:Unpacking failed: XRIT_DECOMPRESS_PATH is not defined (complete path to xRITDecompress) 
I found that my file is compressed but don't know what to do !!!!
thank you

**Comment by pnuu** [comment]
You need to build [this](https://gitlab.eumetsat.int/open-source/PublicDecompWT) software and use that decopress each segment which have the ending `C_`, or set a environment variable `XRIT_DECOMPRESS_PATH` pointing to the executable file so that Satpy will handle the decompression.

**Comment by miladmz** [comment]
thank you for your help 
may help me how to set this environment for all segments 


> You need to build [this](https://gitlab.eumetsat.int/open-source/PublicDecompWT) software and use it to decompress each segment which has the ending `C_`, or set an environment variable `XRIT_DECOMPRESS_PATH` pointing to the executable file so that Satpy will handle the decompression.

**Comment by miladmz** [comment]
> You need to build [this](https://gitlab.eumetsat.int/open-source/PublicDecompWT) software and use it to decompress each segment which has the ending `C_`, or set an environment variable `XRIT_DECOMPRESS_PATH` pointing to the executable file so that Satpy will handle the decompression.

**Comment by mraspaud** [comment]
note that the public-decomp-wt software can now be installed directly with conda:
`conda install -c eumetsat public-decomp-wt`

**Comment by miladmz** [comment]
thank you 
I found this package is on Linux and can't install it on win64

**Comment by miladmz** [comment]
> You need to build [this](https://gitlab.eumetsat.int/open-source/PublicDecompWT) software and use it to decompress each segment which has the ending `C_`, or set an environment variable `XRIT_DECOMPRESS_PATH` pointing to the executable file so that Satpy will handle the decompression.

may explain how can I set the environment for all segments

**Comment by miladmz** [comment]
I build  xRITDecompress.cpp but not any .exe file created !!! 
 just .obj file

**Comment by miladmz** [comment]
@pdebuyl Hi
I install conda install -c eumetsat public-decomp-wt on wsl Linux
now would you help me how to use it? 
i cant import  it

**Comment by pnuu** [comment]
> @pdebuyl Hi
> I install conda install -c eumetsat public-decomp-wt on wsl Linux
> now would you help me how to use it?

This is answered two times above.

https://github.com/pytroll/satpy/issues/1803#issuecomment-905467629
https://github.com/pytroll/satpy/issues/1803#issuecomment-906244425

**Comment by simonrp84** [comment]
FWIW, the decompression tool is now installable and useable from Windows.
