### ISSUE TITLE
error in reading HRIT file

### ISSUE THREAD

**Issue by miladmz** [pytroll/satpy#1811]
Hi 
I use "scn = Scene(reader="seviri_l1b_hrit", filenames=filenames,reader_kwargs={'fill_hrv': False}) " witout any error or warning but when i want to load HRV data " data = scn.load(['HRV'])"
i got this error "python3.7/site-packages/pyresample/geometry.py:1113: RuntimeWarning: invalid value encountered in double_scalars  self.pixel_size_y = (area_extent[3] - area_extent[1]) / float(height)" and
"python3.7/site-packages/pyproj/crs/crs.py:543: UserWarning: You will likely lose important projection information when converting to a PROJ string from another format. See: https://proj.org/faq.html#what-is-the-best-format-for-describing-coordinate-reference-systems proj_string = self.to_proj4()" 
 and  data will ne None

**Comment by pnuu** [comment]
The `scn.load()` method does not return anything. After `scn.load(["HRV"])` you can access the data by accessing the `scn["HRV"]` `DataArray`. As for the warning, you can just ignore it.

You can browse training materials and usage examples from https://github.com/pytroll/pytroll-examples

**Comment by miladmz** [comment]
@pnuu  thank you so much  but I got all values, nan :
I check my code and its correct :
scn = Scene(reader="seviri_l1b_hrit", filenames=filenames,reader_kwargs={'fill_hrv': False})
scn.load(["HRV"])
HRV_v = scn["HRV"].values 
and HRV_v is just nan

**Comment by pdebuyl** [comment]
Can you post a sufficient example program? One that I could run at the command-line to make sure that I exercise the same code as you, or run with ipython's `%run` magic to examine the variables afterwards. Also, for diagnosing errors it is important to share the version number of satpy.

    print(satpy.__version__)

should show it.

**Comment by pdebuyl** [comment]
@mraspaud @djhoese This is an abandoned support request, it could be closed.

**Comment by djhoese** [comment]
If you say so. @miladmz let us know if still have questions about this.
