### ISSUE TITLE
How to use 'lookup' enhancement?

### ISSUE THREAD

**Issue by yukaribbba** [pytroll/satpy#1826]
The documentation there is quite simple...

**Comment by djhoese** [comment]
There is one example here:

https://github.com/pytroll/satpy/blob/a6f26f3abeb92a91fa98326cd158d75c1ce765c9/satpy/etc/enhancements/generic.yaml#L619-L625

By the looks of that example and the lookup source code, it looks like it expects a "table" to lookup color values. In other words a list of lists of RGB/RGBA values. So the input data is expected to be an 8-bit unsigned integer between 0 and 255, or at least a float between those values that will be cast to uint8, and the list of colors is then indexed by those values. Looking at this code makes me think that there may be a bug in it though as the lookup function never adds the additional bands dimension based on the lookup table. I'm not entirely sure why a colormap using the colorize or palettize methods wouldn't be better.

@pnuu @mraspaud Any memory of who added this and why it is used for `snow_age`? Maybe the colormap YAML support didn't exist back then so this was added instead.
