### ISSUE TITLE
pytest satpy/tests does not work

### ISSUE THREAD

**Issue by sahar-github** [pytroll/satpy#1829]
**Describe the bug/error**
Import error while loading conftest 
could you please guide me how should i resolve this issue?
Thanks 

**Actual results**
Import error while loading conftest 
satpy/--init--.py:21: in module 
from satpy.version import version as --version-- 
module not found: no module named satpy.version

**Comment by mraspaud** [comment]
Hi, could you tell us how you installed satpy?

**Comment by sahar-github** [comment]
Hi
thanks for your prompt response
I just followed the steps from the developer's guide:
Developer’s Guide — Satpy 0.30.1.dev0+ga6f26f3a.d20210917 documentation
<https://satpy.readthedocs.io/en/stable/dev_guide/index.html>

**Comment by djhoese** [comment]
Can you try the `pip install -e .` part again and make sure it succeeds? The `version.py` module is created when Satpy is first installed. If it isn't properly installed that module won't be created and you get this error.

**Comment by sahar-github** [comment]
Sure, thanks for the suggestion. I tried it. the installation of satpy was successful (I had two satpy folders it seems instead of one,  i.e. I had to run the script from satpy/satpy/pytest instead of satpy/pytest). 
However now I have a new error after running the test! please see the attached screenshot
![error_testSATPY](https://user-images.githubusercontent.com/77753619/134172410-0226cfeb-4cd3-49fe-850c-ec11c4374326.PNG)

**Comment by djhoese** [comment]
Some of these are optional dependencies. Unless you plan on doing development on the things being tested in these failing tests I personally wouldn't worry about it. You can find the full list of dependencies needed to run all tests here:

https://github.com/pytroll/satpy/blob/a6f26f3abeb92a91fa98326cd158d75c1ce765c9/setup.py#L38-L40

I'm realizing though that there isn't an easy way to install these dependencies except to do it manually. I'll make a pull request for that. Regardless, what are you hoping to work on? I wouldn't worry about running all the Satpy tests unless you plan on doing large changes to the library. Each reader and writer has their own dependencies so installing all of them can get annoying (especially the C-based compile ones).

Hope this clears some stuff up. I'll work on making this easier in a new PR this morning and documenting it better.

**Comment by sahar-github** [comment]
Thanks for the declaration. I would like to add a new reader to satpy, and for that I do not require dependencies of MODIS. Then I can just ignore the errors right?

**Comment by djhoese** [comment]
Yes, I think they can be ignored. Or you could install the extra dependencies yourself and then the tests would pass. It is up to you.

I'm going to consider this issue closed as I think we've addressed the primary issue (missing dependencies).

**Comment by sahar-github** [comment]
Thank you
