### ISSUE TITLE
Add parallax correction

### ISSUE THREAD

**Issue by gerritholl** [pytroll/satpy#1845]
## Feature Request

**Is your feature request related to a problem? Please describe.**

Geostationary satellites view high-latitude satellites at a large angle.  This leads to a shift in the geolocation of cloud tops, in particular when the cloud top is high.  This shift is particularly apparent when a cloud top product is combined with other data sources, such as radar, ground-based lightning networks, or model data.  The problem appears both in automated processing or in standard visualisation.  The higher the spatial resolution of the satellite instrument, the more apparent this problem becomes.

**Describe the solution you'd like**

We need a parallax correction for automated processing of satellite data in combination with radar data at DWD, in particular for MTG.

**Describe any changes to existing user workflow**

This would be a new feature, so it would not be detrimental to any existing user workflow.

**Additional context**

There was a parallax correction in mpop, implemented by @uhamann / @meteoswiss-mdr in https://github.com/pytroll/mpop/commit/8cc2131c5449198f30743eff00799a720080914b with contributions from @m4sth0 and others.  This parallax correction was never ported to satpy.  It's implemented in mpop at https://github.com/pytroll/mpop/blob/5df80ff71a71d8ded567aa7021d9f77084273dd1/mpop/channel.py#L619-L756.

There is a PR in progress by @zxdawn in #1282.

**Comment by pnuu** [comment]
Wouldn't this be more `component:composite` (like in #1282) or even `component:resampling` rather than `component:enhancement`?

**Comment by simonrp84** [comment]
I guess the biggest question is: What data will be used for the CTH? How do we ensure it's generic?

**Comment by gerritholl** [comment]
> Wouldn't this be more `component:composite` (like in #1282) or even `component:resampling` rather than `component:enhancement`?

I don't know.  I remain confused by enhancements and modifiers.  Feel free to retag however you feel appropriate :)

> I guess the biggest question is: What data will be used for the CTH? How do we ensure it's generic?

Yes, there are some design questions to consider.  It should work for CTH from any source.  I intend to make time for this at the next PCW; hopefully we can get enough interested people together for a brainstorm on how to fit this into Satpy.

**Comment by pnuu** [comment]
> I don't know. I remain confused by enhancements and modifiers.
Modifiers do something to the input data before compositing, enhancements apply stretching and such to the composites.

> Feel free to retag however you feel appropriate :)
:heavy_check_mark:

**Comment by gerritholl** [comment]
@meteoswiss-mdr (Ulrich Hamann and Jussi Leinonen) have developed
https://github.com/meteoswiss-mdr/monti-pytroll/blob/parallax/scripts/parallax.py based on work by @zxdawn and @simonrp84.
