### ISSUE TITLE
Data Type of AHI NetCDF Output

### ISSUE THREAD

**Issue by Steve-Albers** [pytroll/satpy#1866]
**Describe the bug**
The output data type seems to be hard to predict when converting AHI-HSD data to NetCDF

**To Reproduce**

```python
encoding = {
    "B13": {
        "dtype": "double",
        "_FillValue": 65535,
        "scale_factor": 0.06145332, # some scale factor float,
        "add_offset": 89.62 # some add offset float,
    }
}

global_scene.save_datasets(writer='cf',engine='netcdf4',exclude_attrs=['raw_metadata'],include_lonlats=False,encoding=encoding)

```

**Expected behavior**
In this experiment though a double B03 variable was requested to appear in the NetCDF, though I ended up with short instead.

**Actual results**

        short B03(y, x) ;
                B03:_FillValue = -1s ;
                B03:calibration = "reflectance" ;
                B03:end_time = "2021-10-25 20:09:40.451869" ;
                B03:grid_mapping = "FLDK" ;
                B03:id = "{\"name\": \"B03\", \"wavelength\": [0.62, 0.64, 0.66, \"\\u00b5m\"], \"resolution\": 500, \"calibration\": 1, \"modifiers\": []}" ;
                B03:modifiers = "" ;
                B03:orbital_parameters = "{\"projection_longitude\": 140.7, \"projection_latitude\": 0.0, \"projection_altitude\": 35785863.0, \"satellite_actual_longitude\": 140.65801379456522, \"satellite_actual_latitude\": -0.008779484230671103, \"satellite_actual_altitude\": 35788284.01247587, \"nadir_longitude\": 140.2571231622773, \"nadir_latitude\": 0.03739495156361317}" ;
                B03:platform_name = "Himawari-8" ;
                B03:resolution = 500L ;
                B03:satellite_altitude = 35788347.6892822 ;
                B03:satellite_latitude = -0.0087794842306711 ;
                B03:satellite_longitude = 140.658093509269 ;
                B03:scheduled_time = "2021-10-25 20:00:00" ;
                B03:sensor = "ahi" ;
                B03:standard_name = "toa_bidirectional_reflectance" ;
                B03:start_time = "2021-10-25 20:00:21.053440" ;
                B03:units = "%" ;
                string B03:wavelength = "0.62", "0.64", "0.66", "µm" ;
                B03:add_offset = 0. ;
                B03:scale_factor = 0.01 ;

**Screenshots**

**Environment Info:**
 - OS: Linux
 - Satpy Version: [e.g. 0.9.0]
 - PyResample Version:
 - Readers and writers dependencies (when relevant): [run `from satpy.utils import check_satpy; check_satpy()`]

**Additional context**

**Comment by Steve-Albers** [comment]
The versions where the encoding isn't having an effect are as follows if this helps with tracking things:

satpy                     0.30.1  
xarray                    0.19.0 

The versions I tested where the encoding is working are older as. noted below:

satpy                     0.23.0              
xarray                    0.16.1

**Comment by djhoese** [comment]
Could you put together a small minimal example that demonstrates the issue so I can try debugging this further (while the CF authors are on leave)?

**Comment by Steve-Albers** [comment]
Here is one example if this helps to home in on things:

# This script should yield a "short" variable type in the output NetCDF file

from satpy import Scene
from glob import glob


# Band 03

filenames = glob("him8files/*_B03_*.bz2")
global_scene = Scene(reader="ahi_hsd", filenames=filenames)
print(global_scene.available_dataset_names())
global_scene.load(['B03'])
band_vis = global_scene["B03"]
print(band_vis)

# https://satpy.readthedocs.io/en/stable/api/satpy.writers.html#module-satpy.writers.cf_writer
# global_scene.save_datasets(writer='simple_image')

# global_scene.save_datasets(writer='cf',engine='netcdf4',exclude_attrs=['raw_metadata'],include_lonlats=False)

encoding = {
    "B03": {
        "dtype": "int16",
        "_FillValue": -1,
        "scale_factor": 0.01,       # some scale factor float,
        "add_offset": 0.            # some add offset float,
    }
}


global_scene.save_datasets(writer='cf',engine='netcdf4',exclude_attrs=['raw_metadata'],include_lonlats=False,encoding=encoding)

**Comment by Steve-Albers** [comment]
Attached is an example that may help to home in on things:

```# This script should yield a "short" variable type in the output NetCDF file

from satpy import Scene
from glob import glob


# Band 03

filenames = glob("him8files/*_B03_*.bz2")
global_scene = Scene(reader="ahi_hsd", filenames=filenames)
print(global_scene.available_dataset_names())
global_scene.load(['B03'])
band_vis = global_scene["B03"]
print(band_vis)

# https://satpy.readthedocs.io/en/stable/api/satpy.writers.html#module-satpy.writers.cf_writer
# global_scene.save_datasets(writer='simple_image')

# global_scene.save_datasets(writer='cf',engine='netcdf4',exclude_attrs=['raw_metadata'],include_lonlats=False)

encoding = {
    "B03": {
        "dtype": "int16",
        "_FillValue": -1,
        "scale_factor": 0.01,       # some scale factor float,
        "add_offset": 0.            # some add offset float,
    }
}


global_scene.save_datasets(writer='cf',engine='netcdf4',exclude_attrs=['raw_metadata'],include_lonlats=False,encoding=encoding)

**Comment by Steve-Albers** [comment]
As it turns out we now have the desired 'short' variable showing up in both of our test environments. These two tests are now using more similar syntax when doing the encoding and thus we think both the newer and older versions of `satpy/xarray` are now working for us.

**Comment by djhoese** [comment]
Oh wow! That's great. I'm glad I was lazy and waited until tonight to look into this. So this issue can be closed?

**Comment by Steve-Albers** [comment]
Indeed - I'm also glad you had waited until I had more complete information about the various tests we're running. Feel free to close this ticket and thanks for your help!
