### ISSUE TITLE
Download and install Satpy for raspberry pi

### ISSUE THREAD

**Issue by gersmit** [pytroll/satpy#1893]
I have stil problems with installing Satpy on the Raspberry Pi 3 and 4 Debian Buster.
Can someone explane to me where and how i can download Satpy zipfile and install.
Not pip or pip3 because this is not possible.

Thanks in advance
Greetigs Ger

**Comment by djhoese** [comment]
Pip/pip3 are downloading the files from PyPI. You can get the tar.gz file from there: https://pypi.org/project/satpy/#files. You'd still need to install setuptools to install satpy which comes with pip. So if pip is a problem in some way I'm not sure downloading the source tarball and installing it is going to help much.

Otherwise, you could download a zip archive of the github repository but that shouldn't be necessary and will come with a lot of extra files that you don't need. The above PyPI tarball is the preferred method.

**Comment by gersmit** [comment]
It worked, I installed all programs manually and..... it works. A small problem has arisen. When I test with the basic processing of the Scene to images it works. The moment I want to switch to matplotlib, the script stops without an error.
This happens with the line:
**image = np.asarray(new_scn[comp]).transpose(1,2,0)**
 a message will appear:
**=============================== RESTART: Shell ===============================**.
Can you tell me why this is and what software is still missing from me?

Thanks for an answer and greetings
Ger

**Comment by gersmit** [comment]
Ps The above was created after full update and upgrade RPI OS.

**Comment by djhoese** [comment]
Well that isn't much of an error message, but my guess is you're running out of memory. You could try using xarray's matplotlib helpers and do `new_scn[comp].plot.imshow()` then follow that with `plt.show()`. But that will also probably fail in a similar way. You could also try transposing the dask array and then converting it to a numpy array. Right now you might be making to copies of the data and wasting memory.

**Comment by gersmit** [comment]
@djhoese, You are great, thank you. I have an RPI3, new sdcard 32gb, the very latest utilities and I'm stuck. I don't think about memory, a temp. plot worked well.
I have now put the new sdcard in the RPI4 4gb and voila ...... perfect.
So now only an RPI 8GB next to it, then it can no longer break and I may also make / use HRV images?

Sorry for asking and thanks again and greetings
Ger

**Comment by djhoese** [comment]
> So now only an RPI 8GB next to it, then it can no longer break and I may also make / use HRV images?

I don't know. I don't use SEVIRI data usually so you'll have to try things out and see how it goes. It seems like your original issue has been fixed so I'm going to close this.

**Comment by simonrp84** [comment]
The RPI4 has much more memory (up to 4GB vs 1GB for the RPI3) and that's probably what has helped here. On an RPI4 you may be able to process HRV, but it's probably still going to be quite tight for memory.
