### ISSUE TITLE
MPEF Product Header record definition , in seviri_base.py, needs to be updated 

### ISSUE THREAD

**Issue by ColinDuff** [pytroll/satpy#1903]
The MPEF product header has been updated , with additional fields being added using the existing 20 Character Padding field 

When trying to read in our latest MSG BUFR products we are getting a decode error in the recarray2dict method when it tries to read in and decode this Padding field

File "/tcenas/home/cduff/PycharmProjects/satpy/satpy/readers/eum_base.py", line 91, in recarray2dict
    data = data.split(':')[0].strip()
TypeError: a bytes-like object is required, not 'str'

We should also improve the error handling in eum_base.py as currently it will just pass when a type error occurs
 
Linux
satpy version 0.25.2

**Comment by ColinDuff** [comment]
you can assign this issue to me , will fix during PCW

**Comment by sfinkens** [comment]
Fixed by https://github.com/pytroll/satpy/pull/1905
