### ISSUE TITLE
Wrong dtype of `uint32` array saved by the cf_writer

### ISSUE THREAD

**Issue by zxdawn** [pytroll/satpy#1945]
**Describe the bug**

When the type of DataArray is `uint32`, it will be float64 in the netcdf file generated by cf_writer.

**To Reproduce**

```python
from satpy import Scene
scn = Scene(['./201908/S5P_PAL__L2__NO2____20190811T022605_20190811T040734_09459_01_020301_20211110T023157.nc'], reader='tropomi_l2')
scn.load(['processing_quality_flags'])

print(scn['processing_quality_flags'].dtype)

scn.save_datasets(filename='test',
                    datasets=['processing_quality_flags'],
                    compute=True,
                    writer='cf',
                    engine='netcdf4',
                    )

print(xr.open_dataset('test')['processing_quality_flags'].dtype)
```

**Expected behavior**
The dtype should still be `uint32`.

**Actual results**
```
uint32

float64
```

**Environment Info:**
 - OS: Linux
 - Satpy Version: 0.31.0

**Comment by zxdawn** [comment]
I tested the pure xarray method:

```
import numpy as np
import xarray as xr

da = xr.DataArray(np.array([1,2,3], dtype='uint32')).rename('test_array')
da.to_netcdf("test_1", engine='netcdf4')
with xr.open_dataset('test_1') as ds:
    print(ds['test_array'].dtype)
```

Output: `uint32`. So, it should be something wrong in the CF writer.

**Comment by mraspaud** [comment]
@zxdawn thanks for reporting this! Any help with solving this is very welcome :)

**Comment by zxdawn** [comment]
@mraspaud It seems `unit32` isn't CF compatible: https://github.com/pytroll/satpy/blob/2067358c212d3f71c1317c589753a1778f8c6768/satpy/writers/cf_writer.py#L183-L191

Here's the data types supported by CF 1.9 from the [website](http://cfconventions.org/Data/cf-conventions/cf-conventions-1.9/cf-conventions.html#_data_types):
`string, char, byte, unsigned byte, short, unsigned short, int, unsigned int, int64, unsigned int64, float or real, and double`.

**Comment by zxdawn** [comment]
Anyway, I check the last step of exporting to netcdf:https://github.com/pytroll/satpy/blob/2067358c212d3f71c1317c589753a1778f8c6768/satpy/writers/cf_writer.py#L855-L856

`dataset`:
```
<xarray.Dataset>
Dimensions:                   (y: 4173, x: 450)
Coordinates:
    longitude                 (y, x) float32 dask.array<chunksize=(4096, 450), meta=np.ndarray>
    latitude                  (y, x) float32 dask.array<chunksize=(4096, 450), meta=np.ndarray>
Dimensions without coordinates: y, x
Data variables:
    processing_quality_flags  (y, x) uint32 dask.array<chunksize=(4096, 450), meta=np.ndarray>
```

`encoding`:
```
{'longitude': {'chunksizes': (4096, 450)}, 'latitude': {'chunksizes': (4096, 450)}, 'processing_quality_flags': {'chunksizes': (4096, 450)}}
```

`other_to_netcdf_kwargs`:
```
{'compute': True}
```

The dtype is still `uint32`, don't understand why it becomes float64 at the end ...

**Comment by zxdawn** [comment]
Ha, If I open the exported data in Panoply or ncdump, it's `uint`:

```
  	uint processing_quality_flags(y, x) ;
  		processing_quality_flags:_FillValue = 4294967295U ;
  		processing_quality_flags:comment = "Flags indicating conditions that affect quality of the retrieval." ;
  		processing_quality_flags:end_time = "2019-06-09 22:27:23" ;
  		processing_quality_flags:file_key = "PRODUCT/SUPPORT_DATA/DETAILED_RESULTS/processing_quality_flags" ;
  		processing_quality_flags:file_type = "tropomi_l2" ;
```

But, xarray open the exported variable as float64 ...

Note that it's `uint` for the simple manual case below.
```
import numpy as np
import xarray as xr

da = xr.DataArray(np.array([1,2,3], dtype='uint')).rename('test_array')
da.to_netcdf("test_1", engine='netcdf4')
with xr.open_dataset('test_1') as ds:
    print(ds['test_array'].dtype)
```

**Comment by zxdawn** [comment]
It seems it's some bug of xarray. Submitted to the [xarray issue page](https://github.com/pydata/xarray/issues/6091).

**Comment by zxdawn** [comment]
OK. This is caused by the `nan` value which is a float type during the xarray reading process. You can check the link above to see the example.
