### ISSUE TITLE
Contribute to Satpy

### ISSUE THREAD

**Issue by anikfal** [pytroll/satpy#1948]
Hi,

After cloning Satpy into my local system, what are the next steps? I mean how can I explicitly import it? Should I create a new Conda environment? etc.

**Comment by mraspaud** [comment]
Hi,

if you already have an active conda environment, you can then install the contents of satpy in edit mode with `pip install -e .`. After that, when you make changes, they should be reflected in your enviromnent.

See also: https://satpy.readthedocs.io/en/stable/dev_guide/CONTRIBUTING.html

Thanks for wanting to give us a hand! Good luck!

**Comment by djhoese** [comment]
Feel free to keep commenting on this issue, but since the original question was answered I'm going to close it.

**Comment by anikfal** [comment]
Thank you for your considerations.

`pip install -e .` could install Satpy's dependencies, however, it finally failed with some errors. I prefer not to copy the errors here.
Instead, `python setup.py develop` could make it successfully, and now I can import it explicitly.

Before that, I created a new Conda environment.

**Comment by djhoese** [comment]
@anikfal Any idea what package `pip` was trying to install when it failed? What is your operating system? What version of python? Another option for installation is to do `conda install -c conda-forge --only-deps satpy` then do `pip install -e .`. This makes it so all of satpy's dependencies are installed through conda-forge but satpy is still an editable installation.

**Comment by anikfal** [comment]
- OS: Fedora-33
 - Python Version: 3.9.7
 - Satpy Version: 0.33.2

@djhoese  I tried to regenerate the errors by `pip install -e .` in a newly created conda environment. Though I am not sure if they are the same ones, because despite of the errors, I can import Satpy.
It seems to be a permission issue:

> Requirement already satisfied: zipp>=0.5 in /home/anikfal/.local/lib/python3.9/site-packages (from importlib-metadata->pyresample>=1.11.0->satpy==0.33.2.dev5+gbd784cac) (3.6.0)
> Requirement already satisfied: locket in /home/anikfal/.local/lib/python3.9/site-packages (from partd>=0.3.10->dask[array]>=0.17.1->satpy==0.33.2.dev5+gbd784cac) (0.2.1)
> Requirement already satisfied: python-dateutil>=2.7.3 in /usr/lib/python3.9/site-packages (from pandas>=1.1->xarray!=0.13.0,>=0.10.1->satpy==0.33.2.dev5+gbd784cac) (2.8.1)
> Requirement already satisfied: pytz>=2017.3 in /usr/lib/python3.9/site-packages (from pandas>=1.1->xarray!=0.13.0,>=0.10.1->satpy==0.33.2.dev5+gbd784cac) (2020.5)
> Installing collected packages: satpy
>   Running setup.py develop for satpy
>     ERROR: Command errored out with exit status 1:
>      command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/anikfal/11/satpy2/satpy/setup.py'"'"'; __file__='"'"'/home/anikfal/11/satpy2/satpy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps --user --prefix=
>          cwd: /home/anikfal/11/satpy2/satpy/
>     Complete output (32 lines):
>     running develop
>     /tmp/pip-build-env-h5ywywr5/overlay/lib/python3.9/site-packages/setuptools/command/easy_install.py:156: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
>       warnings.warn(
>     WARNING: The user site-packages directory is disabled.
>     /tmp/pip-build-env-h5ywywr5/overlay/lib/python3.9/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
>       warnings.warn(
>     error: can't create or remove files in install directory
>     
>     The following error occurred while trying to add or remove files in the
>     installation directory:
>     
>         [Errno 13] Permission denied: '/usr/lib/python3.9/site-packages/test-easy-install-3661.write-test'
>     
>     The installation directory you specified (via --install-dir, --prefix, or
>     the distutils default setting) was:
>     
>         /usr/lib/python3.9/site-packages/
>     
>     Perhaps your account does not have write access to this directory?  If the
>     installation directory is a system-owned directory, you may need to sign in
>     as the administrator or "root" account.  If you do not have administrative
>     access to this machine, you may wish to choose a different installation
>     directory, preferably one that is listed in your PYTHONPATH environment
>     variable.
>     
>     For information on other options, you may wish to consult the
>     documentation at:
>     
>       https://setuptools.pypa.io/en/latest/deprecated/easy_install.html
>     
>     Please make the appropriate changes for your system and try again.
>     
>     ----------------------------------------
> ERROR: Command errored out with exit status 1: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/anikfal/11/satpy2/satpy/setup.py'"'"'; __file__='"'"'/home/anikfal/11/satpy2/satpy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps --user --prefix= Check the logs for full command output.

**Comment by djhoese** [comment]
It looks like you may be using a `pip` or `python` (or `pip3` or `python3`) that are coming from your system python and **NOT** from your conda environment (which I think you said is what you are using). The thing that tips me off to this is paths like `/usr/lib/python3.9/site-packages` showing up in your error message. Conda environments are meant to be completely self contained and not access system resources/packages. Did you maybe forget to activate your conda environment?

**Comment by anikfal** [comment]
I am pretty sure that the conda environment was activated. However, I repeated the whole process in another conda environment named `satpy_temp3`.
Despite of the errors, it seems to be editable and I can import it.

> **(satpy_temp3) [anikfal@dhcppc4 satpy]$ pip install -e .**
> Defaulting to user installation because normal site-packages is not writeable
> Obtaining file:///home/anikfal/11/satpy3/satpy
>   Installing build dependencies ... done
>   Getting requirements to build wheel ... done
>     Preparing wheel metadata ... done
> Requirement already satisfied: numpy>=1.13 in /usr/lib64/python3.9/site-packages (from satpy==0.33.2.dev5+gbd784cac) (1.19.4)
> Requirement already satisfied: pillow in /home/anikfal/.local/lib/python3.9/site-packages (from satpy==0.33.2.dev5+gbd784cac) (8.4.0)
> Requirement already satisfied: pooch in /home/anikfal/.local/lib/python3.9/site-packages (from satpy==0.33.2.dev5+gbd784cac) (1.5.2)
> Requirement already satisfied: trollsift in /home/anikfal/.local/lib/python3.9/site-packages (from satpy==0.33.2.dev5+gbd784cac) (0.3.5)
> Requirement already satisfied: pykdtree in /home/anikfal/.local/lib/python3.9/site-packages (from satpy==0.33.2.dev5+gbd784cac) (1.3.4)
> Requirement already satisfied: xarray!=0.13.0,>=0.10.1 in /home/anikfal/.local/lib/python3.9/site-packages (from satpy==0.33.2.dev5+gbd784cac) (0.20.2)
> Requirement already satisfied: donfig in /home/anikfal/.local/lib/python3.9/site-packages (from satpy==0.33.2.dev5+gbd784cac) (0.6.0)
> Requirement already satisfied: pyyaml in /usr/lib64/python3.9/site-packages (from satpy==0.33.2.dev5+gbd784cac) (5.4.1)
> Requirement already satisfied: zarr in /home/anikfal/.local/lib/python3.9/site-packages (from satpy==0.33.2.dev5+gbd784cac) (2.10.3)
> Requirement already satisfied: pyresample>=1.11.0 in /home/anikfal/.local/lib/python3.9/site-packages (from satpy==0.33.2.dev5+gbd784cac) (1.22.3)
> Requirement already satisfied: appdirs in /home/anikfal/.local/lib/python3.9/site-packages (from satpy==0.33.2.dev5+gbd784cac) (1.4.4)
> Requirement already satisfied: pyproj>=2.2 in /usr/lib64/python3.9/site-packages (from satpy==0.33.2.dev5+gbd784cac) (2.6.1.post1)
> Requirement already satisfied: trollimage>1.10.1 in /home/anikfal/.local/lib/python3.9/site-packages (from satpy==0.33.2.dev5+gbd784cac) (1.17.0)
> Requirement already satisfied: dask[array]>=0.17.1 in /home/anikfal/.local/lib/python3.9/site-packages (from satpy==0.33.2.dev5+gbd784cac) (2021.12.0)
> Requirement already satisfied: requests in /usr/lib/python3.9/site-packages (from pooch->satpy==0.33.2.dev5+gbd784cac) (2.24.0)
> Requirement already satisfied: packaging in /usr/lib/python3.9/site-packages (from pooch->satpy==0.33.2.dev5+gbd784cac) (20.4)
> Requirement already satisfied: pandas>=1.1 in /home/anikfal/.local/lib/python3.9/site-packages (from xarray!=0.13.0,>=0.10.1->satpy==0.33.2.dev5+gbd784cac) (1.3.5)
> Requirement already satisfied: numcodecs>=0.6.4 in /home/anikfal/.local/lib/python3.9/site-packages (from zarr->satpy==0.33.2.dev5+gbd784cac) (0.9.1)
> Requirement already satisfied: asciitree in /home/anikfal/.local/lib/python3.9/site-packages (from zarr->satpy==0.33.2.dev5+gbd784cac) (0.3.3)
> Requirement already satisfied: fasteners in /home/anikfal/.local/lib/python3.9/site-packages (from zarr->satpy==0.33.2.dev5+gbd784cac) (0.16.3)
> Requirement already satisfied: importlib-metadata in /home/anikfal/.local/lib/python3.9/site-packages (from pyresample>=1.11.0->satpy==0.33.2.dev5+gbd784cac) (4.10.0)
> Requirement already satisfied: setuptools>=3.2 in /usr/lib/python3.9/site-packages (from pyresample>=1.11.0->satpy==0.33.2.dev5+gbd784cac) (49.1.3)
> Requirement already satisfied: configobj in /home/anikfal/.local/lib/python3.9/site-packages (from pyresample>=1.11.0->satpy==0.33.2.dev5+gbd784cac) (5.0.6)
> Requirement already satisfied: fsspec>=0.6.0 in /home/anikfal/.local/lib/python3.9/site-packages (from dask[array]>=0.17.1->satpy==0.33.2.dev5+gbd784cac) (2021.11.1)
> Requirement already satisfied: partd>=0.3.10 in /home/anikfal/.local/lib/python3.9/site-packages (from dask[array]>=0.17.1->satpy==0.33.2.dev5+gbd784cac) (1.2.0)
> Requirement already satisfied: cloudpickle>=1.1.1 in /home/anikfal/.local/lib/python3.9/site-packages (from dask[array]>=0.17.1->satpy==0.33.2.dev5+gbd784cac) (2.0.0)
> Requirement already satisfied: toolz>=0.8.2 in /home/anikfal/.local/lib/python3.9/site-packages (from dask[array]>=0.17.1->satpy==0.33.2.dev5+gbd784cac) (0.11.2)
> Requirement already satisfied: chardet<4,>=3.0.2 in /usr/lib/python3.9/site-packages (from requests->pooch->satpy==0.33.2.dev5+gbd784cac) (3.0.4)
> Requirement already satisfied: idna<3,>=2.5 in /usr/lib/python3.9/site-packages (from requests->pooch->satpy==0.33.2.dev5+gbd784cac) (2.10)
> Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/lib/python3.9/site-packages (from requests->pooch->satpy==0.33.2.dev5+gbd784cac) (1.25.8)
> Requirement already satisfied: six in /usr/lib/python3.9/site-packages (from packaging->pooch->satpy==0.33.2.dev5+gbd784cac) (1.15.0)
> Requirement already satisfied: pyparsing>=2.0.2 in /usr/lib/python3.9/site-packages (from packaging->pooch->satpy==0.33.2.dev5+gbd784cac) (2.4.7)
> Requirement already satisfied: python-dateutil>=2.7.3 in /usr/lib/python3.9/site-packages (from pandas>=1.1->xarray!=0.13.0,>=0.10.1->satpy==0.33.2.dev5+gbd784cac) (2.8.1)
> Requirement already satisfied: pytz>=2017.3 in /usr/lib/python3.9/site-packages (from pandas>=1.1->xarray!=0.13.0,>=0.10.1->satpy==0.33.2.dev5+gbd784cac) (2020.5)
> Requirement already satisfied: zipp>=0.5 in /home/anikfal/.local/lib/python3.9/site-packages (from importlib-metadata->pyresample>=1.11.0->satpy==0.33.2.dev5+gbd784cac) (3.6.0)
> Requirement already satisfied: locket in /home/anikfal/.local/lib/python3.9/site-packages (from partd>=0.3.10->dask[array]>=0.17.1->satpy==0.33.2.dev5+gbd784cac) (0.2.1)
> Installing collected packages: satpy
>   Running setup.py develop for satpy
>     ERROR: Command errored out with exit status 1:
>      command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/anikfal/11/satpy3/satpy/setup.py'"'"'; __file__='"'"'/home/anikfal/11/satpy3/satpy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps --user --prefix=
>          cwd: /home/anikfal/11/satpy3/satpy/
>     Complete output (32 lines):
>     running develop
>     /tmp/pip-build-env-wkn2dyd_/overlay/lib/python3.9/site-packages/setuptools/command/easy_install.py:156: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
>       warnings.warn(
>     WARNING: The user site-packages directory is disabled.
>     /tmp/pip-build-env-wkn2dyd_/overlay/lib/python3.9/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
>       warnings.warn(
>     error: can't create or remove files in install directory
>     
>     The following error occurred while trying to add or remove files in the
>     installation directory:
>     
>         [Errno 13] Permission denied: '/usr/lib/python3.9/site-packages/test-easy-install-11199.write-test'
>     
>     The installation directory you specified (via --install-dir, --prefix, or
>     the distutils default setting) was:
>     
>         /usr/lib/python3.9/site-packages/
>     
>     Perhaps your account does not have write access to this directory?  If the
>     installation directory is a system-owned directory, you may need to sign in
>     as the administrator or "root" account.  If you do not have administrative
>     access to this machine, you may wish to choose a different installation
>     directory, preferably one that is listed in your PYTHONPATH environment
>     variable.
>     
>     For information on other options, you may wish to consult the
>     documentation at:
>     
>       https://setuptools.pypa.io/en/latest/deprecated/easy_install.html
>     
>     Please make the appropriate changes for your system and try again.
>     
>     ----------------------------------------
> ERROR: Command errored out with exit status 1: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/anikfal/11/satpy3/satpy/setup.py'"'"'; __file__='"'"'/home/anikfal/11/satpy3/satpy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps --user --prefix= Check the logs for full command output.



Another time, I repeated it with `sudo` in the same conda environment. It was successful, but with different messages:

> **(satpy_temp3) [anikfal@dhcppc4 satpy]$ sudo pip install -e .**
> [sudo] password for anikfal: 
> WARNING: Running pip install with root privileges is generally not a good idea. Try `pip install --user` instead.
> Obtaining file:///home/anikfal/11/satpy3/satpy
>   Installing build dependencies ... done
>   Getting requirements to build wheel ... done
>     Preparing wheel metadata ... done
> Collecting dask[array]>=0.17.1
>   Downloading dask-2021.12.0-py3-none-any.whl (1.0 MB)
>      |████████████████████████████████| 1.0 MB 43 kB/s 
> Collecting donfig
>   Downloading donfig-0.6.0.tar.gz (27 kB)
> Collecting appdirs
>   Downloading appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)
> Collecting xarray!=0.13.0,>=0.10.1
>   Downloading xarray-0.20.2-py3-none-any.whl (845 kB)
>      |████████████████████████████████| 845 kB 61 kB/s 
> Requirement already satisfied: pyproj>=2.2 in /usr/lib64/python3.9/site-packages (from satpy==0.33.2.dev5+gbd784cac) (2.6.1.post1)
> Collecting pooch
>   Downloading pooch-1.5.2-py3-none-any.whl (57 kB)
>      |████████████████████████████████| 57 kB 72 kB/s 
> Requirement already satisfied: numpy>=1.13 in /usr/lib64/python3.9/site-packages (from satpy==0.33.2.dev5+gbd784cac) (1.19.4)
> Collecting zarr
>   Downloading zarr-2.10.3-py3-none-any.whl (146 kB)
>      |████████████████████████████████| 146 kB 60 kB/s 
> Collecting pyresample>=1.11.0
>   Downloading pyresample-1.22.3-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.whl (3.4 MB)
>      |████████████████████████████████| 3.4 MB 130 kB/s 
> Collecting trollimage>1.10.1
>   Downloading trollimage-1.17.0.tar.gz (65 kB)
>      |████████████████████████████████| 65 kB 154 kB/s 
> Requirement already satisfied: pillow in /usr/lib64/python3.9/site-packages (from satpy==0.33.2.dev5+gbd784cac) (7.2.0)
> Collecting pykdtree
>   Downloading pykdtree-1.3.4-cp39-cp39-manylinux1_x86_64.whl (210 kB)
>      |████████████████████████████████| 210 kB 183 kB/s 
> Requirement already satisfied: pyyaml in /usr/lib64/python3.9/site-packages (from satpy==0.33.2.dev5+gbd784cac) (5.4.1)
> Collecting trollsift
>   Downloading trollsift-0.3.5.tar.gz (42 kB)
>      |████████████████████████████████| 42 kB 94 kB/s 
> Collecting partd>=0.3.10
>   Downloading partd-1.2.0-py3-none-any.whl (19 kB)
> Collecting fsspec>=0.6.0
>   Downloading fsspec-2021.11.1-py3-none-any.whl (132 kB)
>      |████████████████████████████████| 132 kB 255 kB/s 
> Requirement already satisfied: packaging>=20.0 in /usr/lib/python3.9/site-packages (from dask[array]>=0.17.1->satpy==0.33.2.dev5+gbd784cac) (20.4)
> Collecting cloudpickle>=1.1.1
>   Downloading cloudpickle-2.0.0-py3-none-any.whl (25 kB)
> Collecting toolz>=0.8.2
>   Downloading toolz-0.11.2-py3-none-any.whl (55 kB)
>      |████████████████████████████████| 55 kB 180 kB/s 
> Collecting pandas>=1.1
>   Downloading pandas-1.3.5-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (11.5 MB)
>      |████████████████████████████████| 11.5 MB 52 kB/s 
> Requirement already satisfied: requests in /usr/lib/python3.9/site-packages (from pooch->satpy==0.33.2.dev5+gbd784cac) (2.24.0)
> Collecting asciitree
>   Downloading asciitree-0.3.3.tar.gz (4.0 kB)
> Collecting fasteners
>   Downloading fasteners-0.16.3-py2.py3-none-any.whl (28 kB)
> Collecting numcodecs>=0.6.4
>   Downloading numcodecs-0.9.1-cp39-cp39-manylinux2010_x86_64.whl (6.4 MB)
>      |████████████████████████████████| 6.4 MB 98 kB/s 
> Requirement already satisfied: setuptools>=3.2 in /usr/lib/python3.9/site-packages (from pyresample>=1.11.0->satpy==0.33.2.dev5+gbd784cac) (49.1.3)
> Collecting importlib-metadata
>   Downloading importlib_metadata-4.10.0-py3-none-any.whl (17 kB)
> Collecting configobj
>   Downloading configobj-5.0.6.tar.gz (33 kB)
> Collecting locket
>   Downloading locket-0.2.1-py2.py3-none-any.whl (4.1 kB)
> Requirement already satisfied: six in /usr/lib/python3.9/site-packages (from packaging>=20.0->dask[array]>=0.17.1->satpy==0.33.2.dev5+gbd784cac) (1.15.0)
> Requirement already satisfied: pyparsing>=2.0.2 in /usr/lib/python3.9/site-packages (from packaging>=20.0->dask[array]>=0.17.1->satpy==0.33.2.dev5+gbd784cac) (2.4.7)
> Requirement already satisfied: pytz>=2017.3 in /usr/lib/python3.9/site-packages (from pandas>=1.1->xarray!=0.13.0,>=0.10.1->satpy==0.33.2.dev5+gbd784cac) (2020.5)
> Requirement already satisfied: python-dateutil>=2.7.3 in /usr/lib/python3.9/site-packages (from pandas>=1.1->xarray!=0.13.0,>=0.10.1->satpy==0.33.2.dev5+gbd784cac) (2.8.1)
> Requirement already satisfied: chardet<4,>=3.0.2 in /usr/lib/python3.9/site-packages (from requests->pooch->satpy==0.33.2.dev5+gbd784cac) (3.0.4)
> Requirement already satisfied: idna<3,>=2.5 in /usr/lib/python3.9/site-packages (from requests->pooch->satpy==0.33.2.dev5+gbd784cac) (2.10)
> Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/lib/python3.9/site-packages (from requests->pooch->satpy==0.33.2.dev5+gbd784cac) (1.25.8)
> Collecting zipp>=0.5
>   Downloading zipp-3.6.0-py3-none-any.whl (5.3 kB)
> Using legacy 'setup.py install' for donfig, since package 'wheel' is not installed.
> Using legacy 'setup.py install' for trollimage, since package 'wheel' is not installed.
> Using legacy 'setup.py install' for trollsift, since package 'wheel' is not installed.
> Using legacy 'setup.py install' for asciitree, since package 'wheel' is not installed.
> Using legacy 'setup.py install' for configobj, since package 'wheel' is not installed.
> Installing collected packages: locket, toolz, partd, fsspec, cloudpickle, dask, donfig, appdirs, pandas, xarray, pooch, asciitree, fasteners, numcodecs, zarr, zipp, importlib-metadata, configobj, pykdtree, pyresample, trollimage, trollsift, satpy
>     Running setup.py install for donfig ... done
>     Running setup.py install for asciitree ... done
>     Running setup.py install for configobj ... done
>     Running setup.py install for trollimage ... done
>     Running setup.py install for trollsift ... done
>   Running setup.py develop for satpy
> Successfully installed appdirs-1.4.4 asciitree-0.3.3 cloudpickle-2.0.0 configobj-5.0.6 dask-2021.12.0 donfig-0.6.0 fasteners-0.16.3 fsspec-2021.11.1 importlib-metadata-4.10.0 locket-0.2.1 numcodecs-0.9.1 pandas-1.3.5 partd-1.2.0 pooch-1.5.2 pykdtree-1.3.4 pyresample-1.22.3 satpy toolz-0.11.2 trollimage-1.17.0 trollsift-0.3.5 xarray-0.20.2 zarr-2.10.3 zipp-3.6.0

**Comment by djhoese** [comment]
What's weird is paths like ` /home/anikfal/.local/lib/python3.9/site-packages` showing up. I would think that `pip`/`conda` would look there when working with a conda environment. If you do `which pip` and `which python` (from a bash terminal) when you have that environment active, what do you get?

**Comment by anikfal** [comment]
```
(satpy_temp3) [anikfal@dhcppc4 satpy]$ which pip
/usr/bin/pip
(satpy_temp3) [anikfal@dhcppc4 satpy]$ which python
/usr/bin/python
```

It is interesting that when the new conda environment `satpy_temp3` is not activated, their paths are from miniconda3.
```
(base) [anikfal@dhcppc4 bin]$ which pip
~/miniconda3/bin/pip
(base) [anikfal@dhcppc4 bin]$ which python
~/miniconda3/bin/python
```

**Comment by djhoese** [comment]
How are you activating your environment? This is very very strange.

**Comment by anikfal** [comment]
For this test case:
`conda activate satpy_temp3`

**Comment by djhoese** [comment]
What if you do (from a new terminal tab/window):

```bash
conda activate satpy_temp3
hash -r
which pip
which pip3
which python
which python3
conda list setuptools
conda list pip
conda env list
```

**Comment by anikfal** [comment]
```
(base) [anikfal@dhcppc4 satpy]$ conda activate satpy_temp3
(satpy_temp3) [anikfal@dhcppc4 satpy]$ hash -r
(satpy_temp3) [anikfal@dhcppc4 satpy]$ which pip
/usr/bin/pip
(satpy_temp3) [anikfal@dhcppc4 satpy]$ which pip3
/usr/bin/pip3
(satpy_temp3) [anikfal@dhcppc4 satpy]$ which python
/usr/bin/python
(satpy_temp3) [anikfal@dhcppc4 satpy]$ which python3
/usr/bin/python3
(satpy_temp3) [anikfal@dhcppc4 satpy]$ conda list setuptools
# packages in environment at /home/anikfal/miniconda3/envs/satpy_temp3:
#
# Name                    Version                   Build  Channel
(satpy_temp3) [anikfal@dhcppc4 satpy]$ conda list pip
# packages in environment at /home/anikfal/miniconda3/envs/satpy_temp3:
#
# Name                    Version                   Build  Channel
(satpy_temp3) [anikfal@dhcppc4 satpy]$ conda env list
# conda environments:
#
base                     /home/anikfal/miniconda3
movie                    /home/anikfal/miniconda3/envs/movie
mykeras                  /home/anikfal/miniconda3/envs/mykeras
mysat                    /home/anikfal/miniconda3/envs/mysat
satpy_dev                /home/anikfal/miniconda3/envs/satpy_dev
satpy_temp               /home/anikfal/miniconda3/envs/satpy_temp
satpy_temp2              /home/anikfal/miniconda3/envs/satpy_temp2
satpy_temp3           *  /home/anikfal/miniconda3/envs/satpy_temp3
xesmf_env                /home/anikfal/miniconda3/envs/xesmf_env
```

**Comment by djhoese** [comment]
What about, with that environment active:

```bash
echo $PATH
ls -l /home/anikfal/miniconda3/envs/satpy_temp3/bin/python
```

**Comment by anikfal** [comment]
```
echo $PATH
/home/anikfal/miniconda3/envs/satpy_temp3/bin:/home/anikfal/miniconda3/condabin:/home/anikfal/.local/bin:/home/anikfal/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin
```

The next one for this environment has problems. There is not any `bin` directory.
```
ls /home/anikfal/miniconda3/envs/satpy_temp3/
conda-meta
ls /home/anikfal/miniconda3/envs/satpy_temp2
conda-meta
```

But for other environments it seems okay:
```
(satpy_temp3) [anikfal@dhcppc4 satpy]$ ls /home/anikfal/miniconda3/envs/satpy_temp
bin  compiler_compat  condabin  conda-meta  etc  include  lib  man  share  shell  ssl  x86_64-conda_cos6-linux-gnu  x86_64-conda-linux-gnu
(satpy_temp3) [anikfal@dhcppc4 satpy]$ ls /home/anikfal/miniconda3/envs/satpy_dev/
bin  compiler_compat  condabin  conda-meta  etc  include  lib  man  share  shell  ssl  x86_64-conda_cos6-linux-gnu  x86_64-conda-linux-gnu
```

**Comment by djhoese** [comment]
Ok so it seems something is wrong with this environment (or these two satpy_temp3 and satpy_temp2). Do you remember how you created them? It seems `conda activate` knows that they should exist and knows how to change the PATH, but it seems the environment was never fully/properly created.

**Comment by anikfal** [comment]
Yes, they are not properly created. I create all of the environments by `conda create -n name_of_environment`. It seems there are some problems with conda.
