### ISSUE TITLE
AttributeError when cropping data for VIIRS

### ISSUE THREAD

**Issue by MengXin001** [pytroll/satpy#1995]
**Describe the bug**
AttributeError when cropping data for VIIRS. 

**To Reproduce**

```python
scn = Scene(names, reader='viirs_l1b')
scn.load(["I04", "I05", "M15", 'M16'])
georange = (130.58723, 110.26702, 26.378437, 10.7119)[::-1]
latmin, latmax, lonmin, lonmax = georange
crop_scn = scn.crop(ll_bbox=(lonmin, latmin, lonmax, latmax))
```

**Actual results**
```python 
Traceback (most recent call last):
  File "modis_viirs.py", line 216, in <module>
    Satpy()
  File "modis_viirs.py", line 51, in __init__
    self.ask_root()
  File "modis_viirs.py", line 69, in ask_root
    datas = self.extract(roots, args.channel, names)
  File "modis_viirs.py", line 115, in extract
    crop_scn = scn.crop(ll_bbox=(lonmin, latmin, lonmax, latmax))
  File "/root/miniconda3/lib/python3.8/site-packages/satpy/scene.py", line 625, in crop
    if not new_scn.all_same_proj and xy_bbox is not None:
  File "/root/miniconda3/lib/python3.8/site-packages/satpy/scene.py", line 502, in all_same_proj
    return all(all_areas[0].crs == x.crs for x in all_areas[1:])
  File "/root/miniconda3/lib/python3.8/site-packages/satpy/scene.py", line 502, in <genexpr>
    return all(all_areas[0].crs == x.crs for x in all_areas[1:])
AttributeError: 'SwathDefinition' object has no attribute 'crs'
```

**Environment Info:**
 - OS: [Linux]
 - Satpy Version: 0.33.0

**Comment by djhoese** [comment]
That is overall just a bad error message that we should improve. Cropping for SwathDefinitions is not currently supported as it requires loading most/all of the data from the input files in order to determine where to slice the arrays. Additionally, it isn't guaranteed to be accurate/correct as SwathDefinitions don't have any requirements (technically) about where pixels are located inside the swath.

**Comment by MengXin001** [comment]
Thanks for your explanation!  
If I need to crop the data, how can I do it? Or it doesn't support doing this right now?

**Comment by djhoese** [comment]
You can slice the DataArrays or I think the entire Scene using indexes into the array like `sliced_scn = scn[1000:2000, 1500:2500]` (I think this should work). But as far as "crop around the data at these coordinates, you'd have to do that "manually" by looking at the array yourself or you could resample to an AreaDefinition that represents the region you are interested in.

**Comment by MengXin001** [comment]
I will try this method later and thank you again for your answer!
