### ISSUE TITLE
Add reader for Arctica M N-1 hdf5 data

### ISSUE THREAD

**Issue by TAlonglong** [pytroll/satpy#1998]
Add reader for Arctica M N-1 hdf5 data as provided from Eumetsat.

Please see Eumetsat pub ftp site for testdata 

So far no documentation of the format is provided.

**Comment by djhoese** [comment]
This is the same as @gerritholl's new issue #1999, right? His has more information. Should we close this one?

**Comment by TAlonglong** [comment]
Yes. Just saw it.

**Comment by gerritholl** [comment]
Oops, I didn't notice this one was already there, you were faster, sorry :)
