### ISSUE TITLE
abi_l1b reader leaks memory in Python-3.7

### ISSUE THREAD

**Issue by sfinkens** [pytroll/satpy#2008]
**Describe the bug**
The `abi_l1b` reader leaks memory in Python-3.7, see the screenshot below. I suspect this is due to the custom `cached_property` decorator that is used to cache the file object: https://github.com/pytroll/satpy/blob/34bd429235293a87de99062e6b99a98eb17df8ce/satpy/readers/abi_base.py#L57

At least if I replace that with a normal `@property` the memory footprint is constant. But I don't know why.

**To Reproduce**

```python
import satpy
import glob

filenames = glob.glob('*C13*')  # one day of data
for filename in filenames:
    scn = satpy.Scene([filename], reader='abi_l1b')
    scn.load(['C13'])
    scn['C13'].compute()
```

**Screenshots**
![memory_leak_abi_l1b](https://user-images.githubusercontent.com/1991007/152537518-984382b5-0092-4143-a0da-c92eb89a7ea2.png)
Blue: Python-3.7
Black: Python-3.8

**Environment Info:**
 - OS: Linux
 - Satpy Version: 0.33.1

**Comment by djhoese** [comment]
So the `cached_property` is not available in Python 3.7 so we made one up in `satpy/_compat.py`. However, it seems that using `lru_cache` on a class method causes memory leaks: https://stackoverflow.com/questions/33672412/python-functools-lru-cache-with-instance-methods-release-object

So our choices are:

1. Drop Python 3.7 support and ignore the problem.
2. Fix the problem (possibly with the SO answer above), release a bug fix release, then drop Python 3.7 support.
