### ISSUE TITLE
Can make Trollimage colorbar in scene

### ISSUE THREAD

**Issue by gersmit** [pytroll/satpy#2062]
Dear David Hoese,
Here Ger from the Neterlands for a small question.
I am now working with Trollimage and works fine.
My question is, can i make a colorbar in the scene image like as in Matplotlib?
I found 'trollimage.colormap.colorbar(height, length, colormap)', but how can i use this to show the colorbar in the image.

I hope you wil help to explain.

Thanks and greetigs
Ger

**Comment by djhoese** [comment]
That method is a helper method for another package called pydecorate:

https://pydecorate.readthedocs.io/en/latest/usage.html#scales-and-legends-draft

This functionality can be used when saving an image in Satpy with the `Scene.save_dataset` (or `save_datasets`) method using the `decorate` keyword argument. This argument is described here:

https://satpy.readthedocs.io/en/stable/api/satpy.writers.html#satpy.writers.get_enhanced_image

And it is finally used in the `add_decorate` function:

https://satpy.readthedocs.io/en/stable/api/satpy.writers.html#satpy.writers.add_decorate

This function should accept a `scale` keyword that is a dictionary of everything you want to pass to `add_scale` in pydecorate. I realize this is a little awkward to use and there are definitely some improvements that could be made given some recent features that have been added to trollimage, but they aren't implemented yet. I've never personally used this functionality in Satpy but based on the documentation I think it would look like this:

```python
scn.save_datasets(..., decorate={"decorate": [{"scale": {"colormap": some_colormap_object}}]})
```

**Comment by gersmit** [comment]
@djhoese ,
Thanks but one question.
I read about Pydecorate and looks a solution.
I installed aggdraw for python 3 etc
When i use : font = aggdraw.Font('blue', '/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf')
I get error : font=aggdraw.Font('red','/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf')
OSError: cannot load font (no text renderer)

I search the hole Internet but i get answher i have to rewrite some setup.py scripts?

Is there a way to solve the problem?

I hope you no an easy one.

Thanks, greetings
Ger

**Comment by djhoese** [comment]
This suggests that the freetype library was not installed/included in your aggdraw installation. Based on your paths I'm guessing you are on linux, right? How did you install aggdraw (pip, conda)?

**Comment by gersmit** [comment]
I installed Aggdraw on Raspberry pi with pip install aggdraw and pip3 but also sudo apt-get install python3-aggdraw.
Is there a possibility to install the library to let it work good?

**Comment by djhoese** [comment]
Start by installing it from one place. This will help us know which version you are using and other specifics about how it is installed. Let's use the `pip3` version you installed. Could you try installing `sudo apt-get install freetype` and then try reinstalling aggdraw by running `pip3 install --force-reinstall aggdraw`. If you could please post the output of that `pip3` install command that would help.

**Comment by gersmit** [comment]
strange, i get this

pi@raspberrypi:~ $ sudo apt-get install freetype
Pakketlijsten worden ingelezen... Klaar
Boom van vereisten wordt opgebouwd       
De statusinformatie wordt gelezen... Klaar
E: Kan pakket freetype niet vinden  = Can't find package freetype
pi@raspberrypi:~ $

**Comment by djhoese** [comment]
Try `sudo apt-get install libfreetype6 libfreetype6-dev`. At least that's what the packages are called on my PopOS/Ubuntu system.

**Comment by gersmit** [comment]
Hi David, thanks but it will not work.
I do it now with Pillow, text works with that.

One other question:
A question over Satpy readers and Metop nat files satellite can i ask you that here or do i have to made a new issue?

**Comment by mraspaud** [comment]
Hi,
You can look in this table to see if that format is supported:
https://satpy.readthedocs.io/en/stable/#id1

**Comment by gersmit** [comment]
@mraspaud, thanks for the info, i have seen the list.
I get data from Eumetsat and For the seviri data i use reader = "seviri_l1b_native"
This is working fine.

This is the Metop  : MHSx_xxx_1B_M01_20220322032749Z_20220322050949Z_N_O_20220322050457Z.nat
This is the reader i wil use :  avhrr_l1b_eps

With the same python csript, i use for the seviri nat file, with Metop reader i get error:
MHSx_xxx_1B_M01_20220322032749Z_20220322050949Z_N_O_20220322050457Z.nat
files : {'avhrr_l1b_eps': ['MHSx_xxx_1B_M01_20220322032749Z_20220322050949Z_N_O_20220322050457Z.nat']}
No filenames found for reader: avhrr_l1b_eps
Don't know how to open the following files: {'MHSx_xxx_1B_M01_20220322032749Z_20220322050949Z_N_O_20220322050457Z.nat'}
Traceback (most recent call last):
  File "/home/pi/a-sat_werkend_software/test_fast_sat_pic.py", line 108, in <module>
    scn = Scene(filenames=files)
  File "/home/pi/.local/lib/python3.7/site-packages/satpy/scene.py", line 110, in __init__
    reader_kwargs=reader_kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/satpy/scene.py", line 159, in _create_reader_instances
    reader_kwargs=reader_kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/satpy/readers/__init__.py", line 595, in load_readers
    raise ValueError("No supported files found")
ValueError: No supported files found
>>> 

Do you no if i have to use the reader on an other way?

**Comment by pnuu** [comment]
Please create another issue for the Metop native reader, which we don't currently have. The reader you tried is for the EPS format available from Eumetcast. For more interactive discussion you might want to join our Slack: https://pytrollslackin.herokuapp.com/

**Comment by gersmit** [comment]
@pnuu that was also my question.
Thanks for the link, i go to use it.
