### ISSUE TITLE
Method not fully documented in terms of possible key word arguments

### ISSUE THREAD

**Issue by adybbroe** [pytroll/satpy#207]
#### Code Sample, a minimal, complete, and verifiable piece of code

```
In [2]: scn.resample?
Signature: scn.resample(destination=None, datasets=None, compute=True, unload=True, **resample_kwargs)
Docstring: Resample the datasets and return a new scene.
File:      ~/usr/src/satpy/satpy/scene.py
Type:      instancemethod

```
#### Problem description

I had forgot for the name of the key word argument when you want to control how far to search for nearest neighbour when doing resampling. So, thought I should get some help from the online doc pages. But not, see above. The RTD pages doesn't give an answer either.

Then I tried to follow the code. But that seemed to be quite a complex procedure:
`resample`--> `_resampled_scene`-->`resample_dataset`(from `satpy.resample`)--> `resample`--> ?

I ended up finding a previous code example I had lying around, and found the keyword name:
`radius_of_influence` (probably that is from PyResample!?

#### Versions of Python, package at hand and relevant dependencies

Python 2.7.5
Satpy: Recent develop branch (March 5, 2018)

**Comment by djhoese** [comment]
@adybbroe @mraspaud Would it be better to have this docstring reference a specific class/function for the right keyword arguments? Or have one ever-growing docstring with all possible keyword arguments (new resampler -> new keyword arguments)?

On the sphinx docs through autodoc/apidoc this should automatically link to the proper docstring in the API docs. In an interactive interpreter or IDE this would probably cause a user to have to manually track down the related function.
