### ISSUE TITLE
MultiScene.group doesn't work for differing identifier properties

### ISSUE THREAD

**Issue by djhoese** [pytroll/satpy#2089]
**Describe the bug**
This issue was described on the mailing list. A user created a MultiScene with GOES-16, GOES-17, H8, and Meteosat data in each of the Scenes. They then did `mscn.group(...)`, resampled, blended, and did save_datasets on the resulting blended Scene. This blending didn't actually do anything because the DataIDs of the individual Scenes had different `resolution` parameters so the DataIDs were something like `DataID(name="ir_group", resolution=3000.123)`. Blending can only work on DataArrays where the DataIDs are equal.

I think the proper fix might be to take the DataID of the DataArray being put in the group and remove every property from `.attrs` that appears in the DataArray (ex. `resolution`, `calibration`, and even `_satpy_id`). I don't think it is supported and may be mentioned in another issue, but allowing DataQuery objects for selecting DataArrays for a group might be nice.

**To Reproduce**

```python
from satpy import Scene
from glob import glob
from satpy import MultiScene, DataQuery
from satpy.utils import debug_on

debug_on()
h8_scene = Scene(filenames=glob('./*.DAT'), reader='ahi_hsd')
h8_scene.load(['b13_inv'])

g16_scene = Scene(filenames=glob('./*G16*'), reader='abi_l1b')
g16_scene.load(['c13_inv'])

g17_scene = Scene(filenames=glob('./*G17*'), reader='abi_l1b')
g17_scene.load(['c13_inv'])

m08_scene = Scene(filenames=glob('./MSG1*'), reader='seviri_l1b_native')
m08_scene.load(['i18_inv'], upper_right_corner='NE')

m11_scene = Scene(filenames=glob('./MSG4*'), reader='seviri_l1b_native')
m11_scene.load(['i18_inv'], upper_right_corner='NE')

mscn = MultiScene([g17_scene, h8_scene, g16_scene, m08_scene, m11_scene])
groups = {DataQuery(name='ir_group', wavelength=(10, 11, 12)): ['c13_inv', 'b13_inv', 'i18_inv']}
mscn.group(groups)

resampled = mscn.resample('worldeqc3km70', reduce_data=False, radius_of_influence=10000)
blended = resampled.blend()
blended.save_dataset('ir_group')


```

**Expected behavior**
Able to blend a grouped MultiScene.

**Actual results**
No results (empty blended Scene).

**Screenshots**

**Environment Info:**
 - OS: [e.g. OSX, Windows, Linux]
 - Satpy Version: [e.g. 0.9.0]
 - PyResample Version:
 - Readers and writers dependencies (when relevant): [run `from satpy.utils import check_satpy; check_satpy()`]

**Additional context**

I think @zxdawn originally adding the grouping functionality?

**Comment by zxdawn** [comment]
@djhoese Unfortunately, that's not mine ;) It should be assigned to @sfinkens, see https://github.com/pytroll/satpy/pull/983

**Comment by djhoese** [comment]
Oops, sorry.

**Comment by sfinkens** [comment]
Good catch, I'll have a look during the PCW
