### ISSUE TITLE
Problem with merged composites for VIIRS SDR and NWCSAF

### ISSUE THREAD

**Issue by ninahakansson** [pytroll/satpy#2095]
**Describe the bug**
Combining VIIRS SDR data and NWCSAF products in composites is not working if using more than one granule. This is because the y-dimension from the NWCSAF has coordinates scan line number and they are counted relative to the actual granule from 0 to 767. When these are concatenated the coordinates will be repeated and this causes the BackgroundCompositor to crash. The VIIRS SDR data has no y coordinates just the dimension. If I drop x and y coordinates from the data in the nwcsaf reader it works. Also if I use bg_band.data instead of bg_band in _get_merged_image_data it works.

The exception is raised in BackgroundCompositor._get_merged_image_data at this line: 
```python
chan = (fg_band * alpha + bg_band * (1 - alpha))
```

**To Reproduce**

```python
import xarray as xr
arr_with_coords = xr.DataArray([[1, 2, 3, 4, 5 ,6], [4, 5, 6, 7, 8, 9]], coords={"x": [1, 2], "y": [1, 2, 3, 1, 2, 3]})
arr_without_coords = xr.DataArray(arr_with_coords.values, dims=["x", "y"])
arr_with_coords * arr_without_coords.data  # OK
arr_with_coords * arr_without_coords  # Failes
```

**Expected behavior**
I expect to be able to create a composite that merges VIIRS and NWCSAF data also for several granules.

**Actual results**
Text output of actual results or error messages including full tracebacks if applicable.

  File "/home/a001865/git/satpy/satpy/composites/__init__.py", line 1343, in _get_merged_image_data
    chan = (fg_band * alpha + bg_band * (1 - alpha))
  File "/home/a001865/opt/CONDA/envs/ppsepssg/lib/python3.8/site-packages/xarray/core/_typed_ops.py", line 212, in __mul__
    return self._binary_op(other, operator.mul)
  File "/home/a001865/opt/CONDA/envs/ppsepssg/lib/python3.8/site-packages/xarray/core/dataarray.py", line 3093, in _binary_op
    self, other = align(self, other, join=align_type, copy=False)
  File "/home/a001865/opt/CONDA/envs/ppsepssg/lib/python3.8/site-packages/xarray/core/alignment.py", line 368, in align
    new_obj = obj.reindex(
  File "/home/a001865/opt/CONDA/envs/ppsepssg/lib/python3.8/site-packages/xarray/core/dataarray.py", line 1617, in reindex
    ds = self._to_temp_dataset().reindex(
  File "/home/a001865/opt/CONDA/envs/ppsepssg/lib/python3.8/site-packages/xarray/core/dataset.py", line 2948, in reindex
    return self._reindex(
  File "/home/a001865/opt/CONDA/envs/ppsepssg/lib/python3.8/site-packages/xarray/core/dataset.py", line 2977, in _reindex
    variables, indexes = alignment.reindex_variables(
  File "/home/a001865/opt/CONDA/envs/ppsepssg/lib/python3.8/site-packages/xarray/core/alignment.py", line 589, in reindex_variables
    raise ValueError(
ValueError: cannot reindex or align along dimension 'y' because the index has duplicate values

**Screenshots**

**Environment Info:**
 - OS: [e.g. OSX, Windows, Linux]
 - Satpy Version: [e.g. 0.9.0]
 - PyResample Version:
 - Readers and writers dependencies (when relevant): [run `from satpy.utils import check_satpy; check_satpy()`]

**Additional context**

**Comment by djhoese** [comment]
This is a difficult problem to solve...if someone actually needs those scan line numbers. The simplest solution would be to remove them in the reader, but I assume someone wanted them? Do you know if you or @adybbroe or someone else is using these scan line numbers?

The other option is a bit more complicated. We'd have to define a way in the base reader to say "this coordinate variable is a count and should be incremented as it is appended". That's a little weird and I'm not sure the best way to implement that.

**Comment by mraspaud** [comment]
I talked with @ninahakansson over the last couple days about this issue, and as you say @djhoese , the "easy" solution is to remove the `y` coordinate in the reader.

An alternative that we thought about was to use `combine_by_coords` instead of `concat` when putting segments together in the yaml reader, and when it crashes, we know that the `y` coord is fishy, and remove it there instead.

What you mention is also interesting though. If we had a `standard_name` for the coordinates, we could check against those and see that `scan_line_numbers` (if such a standard name is used) can be safely discarded in composite generation for example.

**Comment by ninahakansson** [comment]
My first try with combine_by_coords was not successful. It gave a NotImplementedError and a Type error but not in the _load_dataset function where I used combine_by_coords.
