### ISSUE TITLE
module 'ntpath' has no attribute 'sep'"

### ISSUE THREAD

**Issue by mukul-B** [pytroll/satpy#2154]
(<class 'AttributeError'>, AttributeError("module 'ntpath' has no attribute 'sep'"), <traceback object at 0x0000012A5190FD40>)

when i debug the code on scene constructor

g_reader = 'abi_l1b'
        goes_scene = Scene(reader=g_reader,
                           filenames=[path, ])

**Comment by djhoese** [comment]
Could you please provide the entire traceback and information about what operating system you are on and what version of satpy you have? Is there a reason you deleted the template for the issue? Please provide the information that the issue originally requested:

```
**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**

```python
# Your code here

```

**Expected behavior**
A clear and concise description of what you expected to happen.

**Actual results**
Text output of actual results or error messages including full tracebacks if applicable.


**Screenshots**
If applicable, add screenshots to help explain your problem.

**Environment Info:**
 - OS: [e.g. OSX, Windows, Linux]
 - Satpy Version: [e.g. 0.9.0]
 - PyResample Version:
 - Readers and writers dependencies (when relevant): [run `from satpy.utils import check_satpy; check_satpy()`]

**Additional context**
Add any other context about the problem here.
```

**Comment by djhoese** [comment]
It's been about a month and you haven't provided any additional information. I'm going to close this until more information is given.
