### ISSUE TITLE
ValueError: time data '2022-07-11T00:30:01Z' does not match format '%Y-%m-%dT%H:%M:%S.%fZ'

### ISSUE THREAD

**Issue by huanglii** [pytroll/satpy#2163]
**Describe the bug**
When I try to read the data of FY4A, the code threw `ValueError: time data '2022-07-11T00:30:01Z' does not match format '%Y-%m-%dT%H:%M:%S.%fZ'`.

**To Reproduce**

```python
from satpy import Scene
from glob import glob

filenames = glob('./data/FY4A-_AGRI--_N_REGC_1047E_L1-_FDI-_MULT_NOM_20220711003000_20220711003417_0500M_V0001.HDF')
global_scene = Scene(reader="agri_l1", filenames=filenames)
```

**Expected behavior**

**Actual results**

```
[DEBUG: 2022-08-03 09:50:15 : satpy.readers.yaml_reader] Assigning to agri_l1: ['./data/FY4A-_AGRI--_N_REGC_1047E_L1-_FDI-_MULT_NOM_20220711003000_20220711003417_0500M_V0001.HDF']
Traceback (most recent call last):
  File "E:/Code/python/satpy/main.py", line 20, in <module>
    global_scene = Scene(reader="agri_l1", filenames=filenames)
  File "C:\Users\huangli\miniconda3\envs\satpy\lib\site-packages\satpy\scene.py", line 123, in __init__
    reader_kwargs=reader_kwargs)
  File "C:\Users\huangli\miniconda3\envs\satpy\lib\site-packages\satpy\scene.py", line 144, in _create_reader_instances
    reader_kwargs=reader_kwargs)
  File "C:\Users\huangli\miniconda3\envs\satpy\lib\site-packages\satpy\readers\__init__.py", line 571, in load_readers
    fh_kwargs=reader_kwargs_without_filter[None if reader is None else reader[idx]])
  File "C:\Users\huangli\miniconda3\envs\satpy\lib\site-packages\satpy\readers\yaml_reader.py", line 618, in create_filehandlers
    fh_kwargs=fh_kwargs)
  File "C:\Users\huangli\miniconda3\envs\satpy\lib\site-packages\satpy\readers\yaml_reader.py", line 604, in _new_filehandlers_for_filetype
    return list(filtered_iter)
  File "C:\Users\huangli\miniconda3\envs\satpy\lib\site-packages\satpy\readers\yaml_reader.py", line 573, in filter_fh_by_metadata
    filehandler.metadata['start_time'] = filehandler.start_time
  File "C:\Users\huangli\miniconda3\envs\satpy\lib\site-packages\satpy\readers\agri_l1.py", line 236, in start_time
    return datetime.strptime(start_time, '%Y-%m-%dT%H:%M:%S.%fZ')
  File "C:\Users\huangli\miniconda3\envs\satpy\lib\_strptime.py", line 577, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "C:\Users\huangli\miniconda3\envs\satpy\lib\_strptime.py", line 359, in _strptime
    (data_string, format))
ValueError: time data '2022-07-11T00:30:01Z' does not match format '%Y-%m-%dT%H:%M:%S.%fZ'
```

**Screenshots**

**Environment Info:**
 - OS: Windows
 - Satpy Version: 0.36.0
 - PyResample Version: 1.23.0
 - Readers and writers dependencies (when relevant): agri_l1

**Additional context**

**Comment by djhoese** [comment]
Thanks for filing this issue. I think you may have run into a very rare case/bug. Let's see if we can figure out how to fix it.

Would it be possible for you to run `ncdump -h your_file.HDF` and show me what it says for the following global attributes:

```
                :Observing\ Beginning\ Date = "2022-01-17" ;
                :Observing\ Beginning\ Time = "00:00:04.554" ;
                :Observing\ Ending\ Date = "2022-01-17" ;
                :Observing\ Ending\ Time = "00:12:39.044" ;
```

@simonrp84 have you ever run into this?

**Comment by simonrp84** [comment]
Nope, but I can test with that file.

**Comment by simonrp84** [comment]
Ok, I have just tried to reproduce this error with the same file that @huanglii used (`FY4A-_AGRI--_N_REGC_1047E_L1-_FDI-_MULT_NOM_20220711003000_20220711003417_0500M_V0001.HDF`). But the file works OK for me, and I see a time of `2022-07-11T00:30:01.805Z`.

@huanglii perhaps the file is corrupted? Can you open it in other programs and, as @djhoese suggests above, find the observation beginning date and time?

**Comment by huanglii** [comment]
@djhoese The global properties are as follows:
```
// global attributes:
                :Observing\ Beginning\ Date = "2022-07-11" ;
                :Observing\ Beginning\ Time = "00:30:01" ;
                :Observing\ Ending\ Date = "2022-07-11" ;
                :Observing\ Ending\ Time = "00:34:08" ;
```

**Comment by mraspaud** [comment]
Interesting, so it looks like the times you have in your files lack the microseconds, while @simon_p's have them. Can I ask where you get your data from?
In any case, I'd be OK with fixing the reader to accept your time format too, if you want to have a look at it?

**Comment by huanglii** [comment]
> Interesting, so it looks like the times you have in your files lack the microseconds, while @simonrp84 's have them. Can I ask where you get your data from? In any case, I'd be OK with fixing the reader to accept your time format too, if you want to have a look at it?

I can't find the source of the data. 😕

**Comment by zxdawn** [comment]
Em ... Where did you download the data? @huanglii It's better to download if from the [NSMC website](http://satellite.nsmc.org.cn/portalsite/).

**Comment by huanglii** [comment]
The data comes from other department. I can't comfirm whether it has been corrupted.
Thanks. @zxdawn
