### ISSUE TITLE
Available Readers Problem

### ISSUE THREAD

**Issue by emirhanaigoritma** [pytroll/satpy#2192]
**Available Readers doesn't contain any grb readers**
When I try to read my grb file, with the following code, it can not read it. Because the grb reader is not included in available readers.

**To Reproduce**

```python
from satpy import available_readers
available_readers()
scn = Scene(reader = 'seviri_l2_grib', filenames = filenames)

```

**Expected behavior**
I tried to investigate my readers via: anaconda3->envs->myenv->lib->python 3.9->site-packages->satpy->readers 
In this "readers" folder, seviri_l2_grib reader is included. But in the code above, it's not shown. So it can not read my grb file.

**Actual results**

INFO:satpy.readers:Cannot use ['/home/arda/anaconda3/envs/sonenv/lib/python3.9/site-packages/satpy/etc/readers/seviri_l2_grib.yaml']
WARNING:satpy.readers:Don't know how to open the following files: {'turkey/MSG2-SEVI-MSGCLMK-0100-0100-20220801150000.000000000Z-20220801151339-4812894.grb'}
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Input In [4], in <cell line: 1>()
----> 1 scn = Scene(reader = 'seviri_l2_grib',filenames = filenames)

File ~/anaconda3/envs/sonenv/lib/python3.9/site-packages/satpy/scene.py:133, in Scene.__init__(self, filenames, reader, filter_parameters, reader_kwargs)
    130 if filenames:
    131     filenames = convert_remote_files_to_fsspec(filenames, storage_options)
--> 133 self._readers = self._create_reader_instances(filenames=filenames,
    134                                               reader=reader,
    135                                               reader_kwargs=cleaned_reader_kwargs)
    136 self._datasets = DatasetDict()
    137 self._wishlist = set()

File ~/anaconda3/envs/sonenv/lib/python3.9/site-packages/satpy/scene.py:154, in Scene._create_reader_instances(self, filenames, reader, reader_kwargs)
    149 def _create_reader_instances(self,
    150                              filenames=None,
    151                              reader=None,
    152                              reader_kwargs=None):
    153     """Find readers and return their instances."""
--> 154     return load_readers(filenames=filenames,
    155                         reader=reader,
    156                         reader_kwargs=reader_kwargs)

File ~/anaconda3/envs/sonenv/lib/python3.9/site-packages/satpy/readers/__init__.py:581, in load_readers(filenames, reader, reader_kwargs)
    578         break
    580 _check_remaining_files(remaining_filenames)
--> 581 _check_reader_instances(reader_instances)
    582 return reader_instances

File ~/anaconda3/envs/sonenv/lib/python3.9/site-packages/satpy/readers/__init__.py:620, in _check_reader_instances(reader_instances)
    618 def _check_reader_instances(reader_instances):
    619     if not reader_instances:
--> 620         raise ValueError("No supported files found")
    621     if not any(list(r.available_dataset_ids) for r in reader_instances.values()):
    622         raise ValueError("No dataset could be loaded. Either missing "
    623                          "requirements (such as Epilog, Prolog) or none of the "
    624                          "provided files match the filter parameters.")

ValueError: No supported files found

**Screenshots**
![Screenshot from 2022-08-24 16-54-38](https://user-images.githubusercontent.com/111423852/186439406-2b40e6e7-6e2a-4c78-99a0-80936238cf81.png)

**Environment Info:**
 - OS: Linux
 - Satpy Version: 0.37.1

**Comment by djhoese** [comment]
Hi, thanks for filing this issue. Could you try running the `check_satpy` function as described here:

https://satpy.readthedocs.io/en/stable/quickstart.html#troubleshooting

This will likely reveal that you are missing a dependency like `pygrib` which I think is a dependency for this reader you are trying to use. Sorry about the confusion.

**Comment by emirhanaigoritma** [comment]
thank you!!
