### ISSUE TITLE
If you do `python -c "import scipy.sparse"` do you get a similar error?

### ISSUE THREAD

**Issue by biechifanle** [pytroll/satpy#2206]
can run pip install -i https://pypi.tuna.tsinghua.edu.cn/simple scipy==1.7.3

**Comment by mraspaud** [comment]
I think you have the wrong repository here, this is satpy, not scipy.

**Comment by biechifanle** [comment]
Oh yes, in fact I am running the mrcnn model, but I am using the tf 2.x version, which caused a lot of errors.
