### ISSUE TITLE
Question: Why the ellipsoid of a geostationary satellite image is not typical WGS84?

### ISSUE THREAD

**Issue by yukaribbba** [pytroll/satpy#2228]
Part of gdalinfo result from a GK-2A image, which is generated by a normal satpy script.
```
Size is 11000, 11000
Coordinate System is:
PROJCRS["unknown",
    BASEGEOGCRS["GCS_unknown",
        DATUM["D_unknown",
            ELLIPSOID["unknown",6378137,298.257024882273,
                LENGTHUNIT["metre",1,
                    ID["EPSG",9001]]]],
```
The reverse flattening is a little bit different from WGS84's 298.257223563

**Comment by djhoese** [comment]
This isn't up to us. We just read it from the file metadata. You'd have to ask NOAA, JMA, and KMA who made the ABI/AHI/AMI instruments on the GRS80 datum/ellipsoid. I'm not sure why that information/label "GRS80" doesn't always make it into the WKT in the geotiff.

**Comment by yukaribbba** [comment]
OK got it.
