### ISSUE TITLE
'cached_property' from 'functools' - seems incompatible with python3.7

### ISSUE THREAD

**Issue by RobWatersMet** [pytroll/satpy#2233]
**Describe the bug**
Installed via conda-forge with python 3.7 

ImportError: cannot import name 'cached_property' from 'functools' (/home/rob/miniconda3/envs/sat_rgb/lib/python3.7/functools.py) 

**To Reproduce**
conda create -n  test python=3.7
conda install -c conda-forge satpy 

```python
from satpy.readers import load_readers
```

**Expected behavior**
enforce python >=3.8 in setup.py rather than 3.7

**Actual results**

(sat_rgb) rob@MS009899:~/code/enhanced_rgb/ensat$ python
Python 3.7.13 (default, Mar 29 2022, 02:18:16)
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from satpy.readers import load_readers
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/rob/miniconda3/envs/sat_rgb/lib/python3.7/site-packages/satpy/__init__.py", line 35, in <module>
    from satpy.multiscene import MultiScene  # noqa
  File "/home/rob/miniconda3/envs/sat_rgb/lib/python3.7/site-packages/satpy/multiscene.py", line 32, in <module>
    from satpy.scene import Scene
  File "/home/rob/miniconda3/envs/sat_rgb/lib/python3.7/site-packages/satpy/scene.py", line 36, in <module>
    from satpy.readers import load_readers
  File "/home/rob/miniconda3/envs/sat_rgb/lib/python3.7/site-packages/satpy/readers/__init__.py", line 37, in <module>
    from .yaml_reader import AbstractYAMLReader
  File "/home/rob/miniconda3/envs/sat_rgb/lib/python3.7/site-packages/satpy/readers/yaml_reader.py", line 40, in <module>
    from functools import cached_property
ImportError: cannot import name 'cached_property' from 'functools' (/home/rob/miniconda3/envs/sat_rgb/lib/python3.7/functools.py)

**Environment Info:**
 - OS: Linux
 - Satpy Version:  0.37.1             pyhd8ed1ab_0    conda-forge
 - PyResample Version:  1.23.0           py37hfb7772e_1    conda-forge

**Comment by pnuu** [comment]
Python 3.7 support was dropped in May 27, 2022 with https://github.com/pytroll/satpy/commit/90ceb7354bb98196dd54c53fe68e1ce5e938281c

It seems that the conda-forge recipe still has `>=3.7` in it: https://github.com/conda-forge/satpy-feedstock/blob/main/recipe/meta.yaml#L25 

Ping @djhoese

**Comment by djhoese** [comment]
Yeah looks like there are two releases on conda-forge that need to be removed then...darn. I'm not sure conda-forge's preferences for removing builds just for version limits. I'll read up on it today hopefully.

**Comment by djhoese** [comment]
I also don't know if conda-forge technically supports Python 3.7 anymore.

**Comment by djhoese** [comment]
Ah they dropped it 10 days ago:

https://conda-forge.org/docs/user/announcements.html#dropping-python-3-7

I'm guessing that means that the packages will just stop being generated for Python 3.7.

**Comment by djhoese** [comment]
FYI there is a new build on conda-forge with the correct version limits. I'm still looking into patching the old releases with the bad version limit.

https://github.com/conda-forge/satpy-feedstock/pull/54

**Comment by djhoese** [comment]
This PR will patch the necessary metadata if/when it is merged by conda-forge admins: https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/334

**Comment by pnuu** [comment]
Closing, https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/334 has been merged.
