### ISSUE TITLE
Add support for HRFI imagery in the FCI L1c reader

### ISSUE THREAD

**Issue by ameraner** [pytroll/satpy#2273]
## Feature Request

The current reader is able to read only FDHSI (normal resolution) data. It would be great to expand it to read also high-resolution HRFI data, which will be disseminated via EUMETCast Terrestrial and the Data Store. 

**Describe the solution you'd like**
Expand the `fci_l1c_nc` reader to accept HRFI data.

**Describe any changes to existing user workflow**
No changes, just expanded capabilities.

**Comment by gerritholl** [comment]
Is there any test data for this?

**Comment by ameraner** [comment]
We have test data coming from the EUM-internal ground processor tests. Unfortunately it's not public, but I will try to ask if it's possible to share a sample for this Pytroll development...
