### ISSUE TITLE
Resampling from MSG Satellite projection to Dutch weather radar projection, area_extent missing

### ISSUE THREAD

**Issue by nickdndndn** [pytroll/satpy#2289]
**Short Description**
I want to reproject my MSG satellite data to the Dutch weather radar projection so I end up with an array of (765,700) that matches the weather radar data grid, but area_extent is missing.

**Projections**
My MSG satellite data has this projection:

```
Projection: {'a': '6378169', 'h': '35785831', 'lon_0': '9.5', 'no_defs': 'None', 'proj': 'geos', 'rf': '295.488065897014', 'type': 'crs', 'units': 'm', 'x_0': '0', 'y_0': '0'}
Number of columns: 3712
Number of rows: 3712
Area extent: (5567248.2834, 5570248.6867, -5570248.6867, -5567248.2834)
```

And my target Dutch weather radar has that projection: ! area extent is not known
```
'proj': 'stere', 'lat_0': 90, 'lon_0': 0, 'lat_ts': 60,'a':6378.14, 'b': 6356.75, 'x_0': 0, 'y_0':0'x_0': '0', 'y_0': '0'}, 
units=km
Number of columns: 700
Number of rows: 765
Area extent: (?, ?, ?, ?)
```

**area_extent**
I have tried every possible area_extend combination, but nothing seems to match my expected results.

- area_extent(0.0, 48.9, 9.01, 55.97) : Actual lat lon as described in radar info
- area_extent(-398051.271528, 398051.271528, -378762.237125, 406654.714735) converted with "satpy/utils/coord2area_def.py"

**Actual line of code causing the issue**
```
my_area= create_area_def('my_area', {'proj': 'stere', 'lat_0': 90, 'lon_0': 0, 'lat_ts': 60, 'a':6378.14, 'b': 6356.75, 'x_0': 0, 'y_0':0}, 
                         width=700, height=765, area_extent=(-330412.541484, -383295.151926, 330412.541484, 402604.245735), units='km'
                         ) 
new_scn = scn.resample(my_area, resampler='nearest')
```

**Actual Results**
The actual result is an empty plot
![50e68db3-32f7-4d79-a5ba-c6302f81e9bb](https://user-images.githubusercontent.com/24464873/202807133-7730d6c3-0149-4245-8e47-4d93c9cf63d6.png)

**Comment by mraspaud** [comment]
I'm not in front of computer right now, but here are a couple of things you could try
- set a and b to mètres in the stere projection
- plot the created area with cartopy and show coastline to see how fat off you are
- lat0 set to something else than 90, although I suppose you got that from the radar projection, so it should work....
