### ISSUE TITLE
satpy installation failed with pip

### ISSUE THREAD

**Issue by s110419025** [pytroll/satpy#2326]
**Describe the bug**
I followed the instructions in [satpy.readthedocs.io](https://satpy.readthedocs.io/en/latest/install.html) trying to install satpy on my windows 10 PC with pip but failed.

**To Reproduce**
`pip install satpy`

**Expected behavior**
satpy installed successfully

**Actual results**
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> numcodecs

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

**Screenshots**
![Screenshot (6)](https://user-images.githubusercontent.com/22673872/207546907-0eed175a-d74d-4f1a-9b31-e6a39543c9f1.png)

**Environment Info:**
 - OS: Windows 10
 - Satpy Version: not installed
 - PyResample Version: not installed

**Additional context**
Seems there's something wrong with the numcodecs package. 
Is there anyway to fix it?

**Comment by djhoese** [comment]
The important part of that error message is likely further up in the console. If you could provide more of the message as text that would be appreciated.

Otherwise, you could try pip installing just numcodecs. Note if this is a Python 3.11 environment that num_codecs hasn't had a release that supports 3.11 yet (they said hopefully this week).

**Comment by s110419025** [comment]
Yeah it's probably because I'm using Python 3.11, guess I'll try using conda with python 3.9 virtual env instead, thank you so much!

**Comment by djhoese** [comment]
I mean Python 3.10 is fine. Or maybe try in a week with Python 3.11. I think numcodec is the main one holding up zarr and other parts of dask which are the main ones missing for satpy.
