### ISSUE TITLE
`numpy.bool` type deprecated, new release needed

### ISSUE THREAD

**Issue by sbrodehl** [pytroll/satpy#2339]
**Describe the bug**
`np.bool` support was dropped with numpy 1.24, see https://github.com/numpy/numpy/pull/22607
This is already fixed in `main` with https://github.com/pytroll/satpy/commit/e97803fb255474412286afb0498275ce5f2be090, but no release was made since then.

Therefore, running satpy with the latest numpy version fails.

**To Reproduce**

```python
import satpy.readers.seviri_l1b_hrit
```

**Expected behavior**
No error.

**Actual results**
```python
  File "__init__.py", line 36, in <module>
    import satpy.readers.seviri_l1b_hrit
  File ".../lib/python3.8/site-packages/satpy/readers/seviri_l1b_hrit.py", line 202, in <module>
    from satpy.readers.hrit_base import (
  File ".../lib/python3.8/site-packages/satpy/readers/hrit_base.py", line 49, in <module>
    from satpy.readers.seviri_base import dec10216
  File ".../lib/python3.8/site-packages/satpy/readers/seviri_base.py", line 480, in <module>
    mpef_product_header = MpefProductHeader().get()
  File "../lib/python3.8/site-packages/satpy/readers/seviri_base.py", line 452, in get
    ('GsicsCalMode', np.bool),
    AttributeError: module 'numpy' has no attribute 'bool'
```

**Environment Info:**
 - OS: [e.g. OSX, Windows, Linux]
 - Satpy Version: Version 0.38.0 (latest pip install)
 - Numpy Version: 1.24.1 (latest pip install)
 - PyResample Version:
 - Readers and writers dependencies (when relevant): [run `from satpy.utils import check_satpy; check_satpy()`]

**Additional context**
-

**Comment by djhoese** [comment]
Satpy 0.39.0 was just released which should include these fixes. The conda-forge release will come later today.
