### ISSUE TITLE
HTTPSConnectionPool（host='zenodo.org'， port=443）

### ISSUE THREAD

**Issue by luochunxi** [pytroll/satpy#2343]
**Describe the bug**

**To Reproduce**

```python
# Your code here
in this code:
composite = 'true_color'
scn.load([composite])
have same error:

HTTPSConnectionPool(host='zenodo.org', port=443): Max retries exceeded with url: /record/1288441/files/pyspectral_atm_correction_luts_marine_clean_aerosol.tgz (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available."))
```

**Expected behavior**

**Actual results**
Text output of actual results or error messages including full tracebacks if applicable.

**Screenshots**

**Environment Info:**
 - OS: [e.g. OSX, Windows, Linux]   ==Windows
 - Satpy Version: [e.g. 0.9.0]             ==0.36.0
 - PyResample Version:                    ==1.22.0
 - Readers and writers dependencies (when relevant): [run `from satpy.utils import check_satpy; check_satpy()`]

**Additional context**

**Comment by luochunxi** [comment]
Readers
=======
C:\Users\admin\AppData\Local\Programs\Python\Python39\lib\site-packages\h5py\__init__.py:36: UserWarning: h5py is running against HDF5 1.12.1 when it wa
s built against 1.12.2, this may cause problems
  _warn(("h5py is running against HDF5 {0} when it was built against {1}, "
Warning! ***HDF5 library version mismatched error***
The HDF5 header files used to compile this application do not match
the version used by the HDF5 library to which this application is linked.
Data corruption or segmentation faults may occur if the application continues.
This can happen when an application was compiled by one version of HDF5 but
linked with a different version of static or shared HDF5 library.
You should recompile the application or check your shared library related
settings such as 'LD_LIBRARY_PATH'.
You can, at your own risk, disable this warning by setting the environment
variable 'HDF5_DISABLE_VERSION_CHECK' to a value of '1'.
Setting it to 2 or higher will suppress the warning messages totally.
Headers are 1.12.2, library is 1.12.1
        SUMMARY OF THE HDF5 CONFIGURATION
        =================================

General Information:
-------------------
                   HDF5 Version: 1.12.1
                  Configured on: 2022-03-04
                  Configured by: Ninja
                    Host system: Windows-10.0.17763
              Uname information: Windows
                       Byte sex: little-endian
             Installation point: D:/bld/hdf5_split_1646412547396/_h_env/Library

Compiling Options:
------------------
                     Build Mode: RELEASE
              Debugging Symbols: OFF
                        Asserts: OFF
                      Profiling: OFF
             Optimization Level: OFF

Linking Options:
----------------
                      Libraries:
  Statically Linked Executables: OFF
                        LDFLAGS: /machine:x64
                     H5_LDFLAGS:
                     AM_LDFLAGS:
                Extra libraries: D:/bld/hdf5_split_1646412547396/_h_env/Library/lib/libcurl.lib;D:/bld/hdf5_split_1646412547396/_h_env/Library/lib/libss
l.lib;D:/bld/hdf5_split_1646412547396/_h_env/Library/lib/libcrypto.lib
                       Archiver: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.16.27023/bin/HostX64/x64/lib.exe
                         Ranlib: :

Languages:
----------
                              C: YES
                     C Compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.16.27023/bin/HostX64/x64/cl.exe 19.16.2
7045.0
                       CPPFLAGS:
                    H5_CPPFLAGS:
                    AM_CPPFLAGS:
                         CFLAGS:   /DWIN32 /D_WINDOWS
                      H5_CFLAGS: /W3;/wd4100;/wd4706;/wd4127
                      AM_CFLAGS:
               Shared C Library: YES
               Static C Library: YES

                        Fortran: OFF
               Fortran Compiler:
                  Fortran Flags:
               H5 Fortran Flags:
               AM Fortran Flags:
         Shared Fortran Library: YES
         Static Fortran Library: YES

                            C++: ON
                   C++ Compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.16.27023/bin/HostX64/x64/cl.exe 19.16.2
7045.0
                      C++ Flags:
                   H5 C++ Flags: /W3;/wd4100;/wd4706;/wd4127
                   AM C++ Flags:
             Shared C++ Library: YES
             Static C++ Library: YES

                            JAVA: OFF
                 JAVA Compiler:

Features:
---------
                   Parallel HDF5: OFF
Parallel Filtered Dataset Writes:
              Large Parallel I/O:
              High-level library: ON
                Build HDF5 Tests: ON
                Build HDF5 Tools: ON
                    Threadsafety: ON (recursive RW locks: )
             Default API mapping: v112
  With deprecated public symbols: ON
          I/O filters (external):  DEFLATE
                             MPE:
                      Direct VFD:
                      Mirror VFD:
              (Read-Only) S3 VFD: 1
            (Read-Only) HDFS VFD:
                         dmalloc:
  Packages w/ extra debug output:
                     API Tracing: OFF
            Using memory checker: OFF
 Memory allocation sanity checks: OFF
          Function Stack Tracing: OFF
                Use file locking: best-effort
       Strict File Format Checks: OFF
    Optimization Instrumentation:
Bye...

**Comment by djhoese** [comment]
It would be nice if you filled out the issue template, but maybe I've extracted your problem without the requested information.

> "Can't connect to HTTPS URL because the SSL module is not available."

How did you create your python environment? You seem to not have SSL available and/or can't connect to HTTPS (SSL) websites from your machine. This is not a Satpy or pyspectral (the library actually making the request to zenodo) problem, but your environment or system seems to be invalid.

**Comment by djhoese** [comment]
Same answer for the HDF5 information: your environment seems incredibly damaged. You'll need to provide more information about how you created it for us to provide any help. Again though, this isn't a Satpy issue, but we'll help where we can.

**Comment by luochunxi** [comment]
> HDF5 信息的答案相同：您的环境似乎遭到了难以置信的破坏。您需要提供有关您如何创建它的更多信息，以便我们提供任何帮助。同样，这不是一个Satpy问题，但我们会尽我们所能提供帮助。

谢谢您，问题已经解决，是因为下载不到这俩文件  pyspectral_rsr_data.tgz pyspectral_atm_correction_luts_no_aerosol.tgz
，通过浏览器手动下载后添加到对应目录后可以运行了
![image](https://user-images.githubusercontent.com/49057556/211247791-d73f0199-e814-429c-8c1d-25c4697df398.png)

**Comment by zxdawn** [comment]
@mraspaud Ofc. It's fixed as @luochunxi said that's the problem of the Chinese Internet. Downloading these files and putting them into pyspectral directories work well!

**Comment by mraspaud** [comment]
Thanks a lot!
