### ISSUE TITLE
Alpha band improvement for DayNightCompositor

### ISSUE THREAD

**Issue by yukaribbba** [pytroll/satpy#2357]
## Feature Request

**Is your feature request related to a problem? Please describe.**
Under "day/night only" mode, an alpha band will be added to the output image for transparency, even if I set `fill_value=0` in geotiff. However, sometimes I just want a single-band image with masked-out area, like the right one below.
![image](https://user-images.githubusercontent.com/72339781/213435266-84fb4946-9647-411d-bc80-67150c55217d.png)

**Describe the solution you'd like**
Add an argument to the compositor to switch alpha band on/off. 

I'll start a PR for this.

**Comment by mraspaud** [comment]
Thanks for reporting this issue. Do I understand correctly that you are not interested in space as a background, you just want black instead?

**Comment by yukaribbba** [comment]
> Thanks for reporting this issue. Do I understand correctly that you are not interested in space as a background, you just want black instead?

Yep.
