### ISSUE TITLE
Problem caching angles derivation: `TypeError: Object of type float32 is not JSON serializable`

### ISSUE THREAD

**Issue by adybbroe** [pytroll/satpy#2366]
**Describe the bug**

I am using this function to get satellite zenith angles on a NWCSAF/PPS cloud scene:
`satpy.modifiers.angles.get_satellite_zenith_angle`

With the newly improved `nwcsaf_nc.py` reader (see #2355), that now also provides the necessary orbital parameters so angles can be derived without having to also load the HRIT channel data for instance, then I get this error:

`TypeError: Object of type float32 is not JSON serializable`

If I change the `get_orbital_parameters` function in the reader to explicitly also return the `float` of the `sub-satellite_longitude` read from file then I get rid of the error. Like this:

```
                satellite_nominal_longitude=self.nc.attrs["sub-satellite_longitude"],
```

So I suppose something in the angles-caching is making some assumptions on the format that is now always true?

**To Reproduce**

```python
# Your code here

```

**Expected behavior**

No exception error when using cached satellite zenith angles.

**Actual results**

```
File ~/usr/src/forks/satpy/satpy/modifiers/angles.py:376, in get_satellite_zenith_angle(data_arr)
    367 def get_satellite_zenith_angle(data_arr: xr.DataArray) -> xr.DataArray:
    368     """Generate satellite zenith angle for the provided data.
    369 
    370     Note that this function can benefit from the ``satpy.config`` parameters
   (...)
    374 
    375     """
--> 376     satz = _get_sensor_angles(data_arr)[1]
    377     return satz

File ~/usr/src/forks/satpy/satpy/modifiers/angles.py:449, in _get_sensor_angles(data_arr)
    446 area_def = data_arr.attrs["area"]
    447 chunks = _geo_chunks_from_data_arr(data_arr)
--> 449 sata, satz = _get_sensor_angles_from_sat_pos(sat_lon, sat_lat, sat_alt,
    450                                              data_arr.attrs["start_time"],
    451                                              area_def, chunks)
    452 sata = _geo_dask_to_data_array(sata)
    453 satz = _geo_dask_to_data_array(satz)

File ~/usr/src/forks/satpy/satpy/modifiers/angles.py:142, in ZarrCacheHelper.__call__(self, cache_dir, *args)
    140 """Call the decorated function."""
    141 new_args = self._sanitize_args_func(*args) if self._sanitize_args_func is not None else args
--> 142 arg_hash = _hash_args(*new_args, unhashable_types=self._uncacheable_arg_types)
    143 should_cache, cache_dir = self._get_should_cache_and_cache_dir(new_args, cache_dir)
    144 zarr_fn = self._zarr_pattern(arg_hash)

File ~/usr/src/forks/satpy/satpy/modifiers/angles.py:258, in _hash_args(unhashable_types, *args)
    256     hashable_args.append(arg)
    257 arg_hash = hashlib.sha1()  # nosec
--> 258 arg_hash.update(json.dumps(tuple(hashable_args)).encode('utf8'))
    259 return arg_hash.hexdigest()

File ~/mambaforge/envs/python3.10/lib/python3.10/json/__init__.py:231, in dumps(obj, skipkeys, ensure_ascii, check_circular, allow_nan, cls, indent, separators, default, sort_keys, **kw)
    226 # cached encoder
    227 if (not skipkeys and ensure_ascii and
    228     check_circular and allow_nan and
    229     cls is None and indent is None and separators is None and
    230     default is None and not sort_keys and not kw):
--> 231     return _default_encoder.encode(obj)
    232 if cls is None:
    233     cls = JSONEncoder

File ~/mambaforge/envs/python3.10/lib/python3.10/json/encoder.py:199, in JSONEncoder.encode(self, o)
    195         return encode_basestring(o)
    196 # This doesn't pass the iterator directly to ''.join() because the
    197 # exceptions aren't as detailed.  The list call should be roughly
    198 # equivalent to the PySequence_Fast that ''.join() would do.
--> 199 chunks = self.iterencode(o, _one_shot=True)
    200 if not isinstance(chunks, (list, tuple)):
    201     chunks = list(chunks)

File ~/mambaforge/envs/python3.10/lib/python3.10/json/encoder.py:257, in JSONEncoder.iterencode(self, o, _one_shot)
    252 else:
    253     _iterencode = _make_iterencode(
    254         markers, self.default, _encoder, self.indent, floatstr,
    255         self.key_separator, self.item_separator, self.sort_keys,
    256         self.skipkeys, _one_shot)
--> 257 return _iterencode(o, 0)

File ~/mambaforge/envs/python3.10/lib/python3.10/json/encoder.py:179, in JSONEncoder.default(self, o)
    160 def default(self, o):
    161     """Implement this method in a subclass such that it returns
    162     a serializable object for ``o``, or calls the base implementation
    163     (to raise a ``TypeError``).
   (...)
    177 
    178     """
--> 179     raise TypeError(f'Object of type {o.__class__.__name__} '
    180                     f'is not JSON serializable')

TypeError: Object of type float32 is not JSON serializable
```
**Screenshots**

**Environment Info:**
 - OS: Linux
 - Satpy Version: `0.39.1.dev121+g3854afd8e`
 - PyResample Version:
 - Readers and writers dependencies (when relevant): [run `from satpy.utils import check_satpy; check_satpy()`]

**Additional context**

**Comment by adybbroe** [comment]
Seems like it happens in the below function. 
When `arg` is directly as it comes from the netCDF file it is of type `<class 'numpy.float32'>`. But this is also the case after the rounding below, so don't understand why that does't work. When the `arg` is of type `float` everything is fine. The rounding again returns a `float` (the same type). So, I would have expected it to work in both cases!?

```
def _sanitize_observer_look_args(*args):
    new_args = []
    for arg in args:
        if isinstance(arg, datetime):
            new_args.append(STATIC_EARTH_INERTIAL_DATETIME)
        elif isinstance(arg, (float, np.float64, np.float32)):
            # round floating point numbers to nearest tenth
            new_args.append(round(arg, 1))
        elif _is_chunk_tuple(arg) and _chunks_are_irregular(arg):
            new_chunks = _regular_chunks_from_irregular_chunks(arg)
            new_args.append(new_chunks)
        else:
            new_args.append(arg)
    return new_args
```

**Comment by djhoese** [comment]
The simplest solution is to fix the reader to not include numpy types in the `.attrs` of the DataArray created by the reader. Bottom line is I use JSON to serialize the function arguments so I can hash them and then use that hash as the filename for the cached results. Numpy types don't serialize into JSON so it fails. I suppose I could use something other than JSON, but this seems like a special case.

I think we can close this?

**Comment by mraspaud** [comment]
why not convert to float in the sanitization function?

**Comment by djhoese** [comment]
> why not convert to float in the sanitization function?

@mraspaud because JSON is used in other places in Satpy or there are other libraries doing serialization of this data (NetCDF in the CF writer) so I'm not sure the conversion should be done here. I guess it could be easier to just do it here, but I'm also not sure we should support numpy scalar types in `.attrs`.

**Comment by adybbroe** [comment]
I am doing both at the moment and have a PR that is supposed to close this. Ok @djhoese ?

**Comment by adybbroe** [comment]
Ok, so I have implemented the casting in the reader now. I have the casting still in the `angles.py` but I am happy removing that!
I have also added a note in the developers guide on this. Happy with any suggested improvements!

**Comment by mraspaud** [comment]
I'm not sure about this. It feels wrong to have to change the type provided by the reader for the serialization to work... Will think more about this.

**Comment by mraspaud** [comment]
So, indeed JSON does only support one type of float, which is logical as it cannot distinguish between different alternatives. But for the serializing in this case, it should not matter if the float is 32 or 64, especially since it is rounded to the nearest integer.
For the other places this uses in, my opinion is that the serialization should take care of the conversion, since it might be of importance to the user to know what original type the metadata is in (for example scale and offset might be in float32 for a reason).

**Comment by djhoese** [comment]
That's fine. I think I think of this as the readers returning a "standard" object (a DataArray with specific possible types and structures) and the error being encountered here is revealing an issue in the data being returned by the reader, not necessarily the caching. The fix/casting in the caching is an improvement in the flexibility of the caching and I can be fine with that.

**Comment by adybbroe** [comment]
> So, indeed JSON does only support one type of float, which is logical as it cannot distinguish between different alternatives. But for the serializing in this case, it should not matter if the float is 32 or 64, especially since it is rounded to the nearest integer. For the other places this uses in, my opinion is that the serialization should take care of the conversion, since it might be of importance to the user to know what original type the metadata is in (for example scale and offset might be in float32 for a reason).

Just a correction/comment: It is not rounding to an integer, but to the nearest float with one decimal: e.g. `12.34` to `12.3` 

I take it that you bot support (are okay with) the fix in the sanitaztion function.
