### ISSUE TITLE
Bug remapping SEVIRI data - bounding box too small

### ISSUE THREAD

**Issue by adybbroe** [pytroll/satpy#2377]
**Describe the bug**

I am reading cloud products derived from SEVIRI data using the NWCSAF/Geo v2021 package. But when remapping it seems data are cut wrongly so I don't get all the data mapped on the output area, see picture below.

**To Reproduce**

I have the netCDF file that I read for this case here:
https://www.dropbox.com/s/9x7q6ex1h4puiks/S_NWC_CT_MSG4_MSG-N-VISIR_20230201T170000Z_PLAX.nc?dl=0

It does cover the full MTG-N area.

```python
# Your code here
areaid = 'eurol'
geo_files = glob(os.path.join(DATADIR, "S_NWC_*_MSG4_MSG-N-VISIR_20230201T1700*_PLAX.nc"))
scn = Scene(filenames=geo_files, reader='nwcsaf-geo')
scn.load(['ct', 'cloudtype'])
local = scn.resample(areaid, radius_of_influence=20000)
stime = datetime.strftime(local.start_time, '%Y%m%d_%H%M')
local.save_dataset('cloudtype',
                  filename='./cloudtype_geo_{time}_{area}.png'.format(time=stime, area=areaid))
```

**Expected behavior**
I would have expected much more data to the west and east in the output image (see below). I think the southern boundary is correct.

**Actual results**
See the below image!

**Screenshots**

Here the resulting image after remapping:

![cloudtype_geo_20230201_1709_eurol](https://user-images.githubusercontent.com/169069/216377212-3d06fa7e-aadf-4776-a971-aa7b7e216bd3.png)

**Environment Info:**
 - OS: [e.g. OSX, Windows, Linux]
 - Satpy Version: 0.39.0
 - PyResample Version: 1.26
 - Readers and writers dependencies (when relevant): [run `from satpy.utils import check_satpy; check_satpy()`]

I have tested with Pyresample 1.25 on Python 3.11 as well. 1.24 doesn't install under Py3.11.
And the same behaviour with the latest Satpy main as well, though the image is B/W then, see #2376 

**Additional context**

**Comment by adybbroe** [comment]
I realize it may well be an issue with Pyresample, but now it is posted here, as this is where I encountered it!

**Comment by pnuu** [comment]
As a first guess I'd try passing `reduce_data=False` to the resampling call to prevent cropping.

**Comment by mraspaud** [comment]
@pnuu that doesn't seem to help...

**Comment by mraspaud** [comment]
So here is the source image without resampling, and I don't think the resampling it doing anything wrong here! Can we close this?
![image](https://user-images.githubusercontent.com/167802/217198219-ab102f96-dd68-49ed-b72e-fc7e10a41a97.png)
