### ISSUE TITLE
The cloud_top_height composite broken for PPS

### ISSUE THREAD

**Issue by ninahakansson** [pytroll/satpy#2392]
**Describe the bug**
The CloudTopHeightCompositor is not working. It is used in the composit cloud_top_height in visir.yaml. The problem happend with PR #2301. Replacing  CloudTopHeightCompositor with SingleBandCompositor gives an image that no longer handles the fill_value_color attribute in the ctth_alti_pal. It could be fixed if the 
colormap in trollimage  (in function from_array_with_metadata) reads and apply the attribute. Like this:

```python

       color_array = np.concatenate((values[:, np.newaxis], squeezed_palette), axis=1)
       fill_color =palette.attrs.get('fill_value_color', None)
        if fill_color is not None:
            fill_color = np.array(fill_color)
            if valid_range is not None:
                lower = np.append( np.array(valid_range[0]) * scale_factor + add_offset - 1, fill_color)
                upper = np.append( np.array(valid_range[1]) * scale_factor + add_offset + 1, fill_color)
                color_array = np.concatenate((lower[np.newaxis,:], color_array, upper[np.newaxis,:]), axis=0)
```

Not sure how that would affect palettes without palette_meanings but with  fill_value_color attribute though. Might be better ways to fix it.

**To Reproduce**

```python
# Your code here
filename2 = "S_NWC_CTTH_alti_noaa18_00000_20230213T1034434Z_20230213T1050239Z..nc"
scn1.load(['cloud_top_height'])
scn1.show( 'cloud_top_height')
```

**Expected behavior**
Expected the cloud_top_height composite to load without errors.

**Actual results**
Text output of actual results or error messages including full tracebacks if applicable.

[DEBUG: 2023-02-14 13:28:58 : satpy.writers] Data for DataID(name='cloud_top_height') will be enhanced with options:
	[{'name': 'palettize', 'method': <function palettize at 0x7f06c8ff9670>, 'kwargs': {'palettes': [{'dataset': 'ctth_alti_pal', 'color_scale': 255}]}}]
Traceback (most recent call last):
  File "/home/a001865/git/foua_python_scripts/nina/test_satpy_nwcsaf.py", line 22, in <module>
    scn1.show( 'cloud_top_height')
  File "/home/a001865/miniconda3/envs/ppsepssg/lib/python3.9/site-packages/satpy/scene.py", line 987, in show
    img = get_enhanced_image(self[dataset_id].squeeze(), overlay=overlay)
  File "/home/a001865/miniconda3/envs/ppsepssg/lib/python3.9/site-packages/satpy/writers/__init__.py", line 441, in get_enhanced_image
    enhancer.apply(img, **dataset.attrs)
  File "/home/a001865/miniconda3/envs/ppsepssg/lib/python3.9/site-packages/satpy/writers/__init__.py", line 1216, in apply
    fun(img, *args, **kwargs)
  File "/home/a001865/miniconda3/envs/ppsepssg/lib/python3.9/site-packages/satpy/enhancements/__init__.py", line 349, in palettize
    img.palettize(full_cmap)
  File "/home/a001865/git/trollimage/trollimage/xrimage.py", line 1377, in palettize
    raise ValueError("Image should be grayscale to colorize")
ValueError: Image should be grayscale to colorize

**Screenshots**

**Environment Info:**
 - OS: [e.g. OSX, Windows, Linux]
 - Satpy Version: [0.40.0]
 - PyResample Version:
 - Readers and writers dependencies (when relevant): [run `from satpy.utils import check_satpy; check_satpy()`]

**Additional context**

**Comment by ninahakansson** [comment]
I think the CloudTopHeightCompositor also made sure that clouds was not smeared out when remapped. As it used the status flag to separate actual nodata from cloud free.

**Comment by gerritholl** [comment]
Can you share some sample input data?  We don't use PPS so I was not able to test this.

**Comment by gerritholl** [comment]
I have some sample data now.  I actually get a _different_ failure when I try to load all datasets and composites:

```python
from satpy import Scene
from glob import glob
from pathlib import Path
from os import fspath
from satpy.utils import debug_on; debug_on()
bd = Path("/media/nas/x21308/scratch/NWCSAF-PPS/pps_products")
sc = Scene(filenames=[fspath(p) for p in bd.glob("*.nc")],
           reader="nwcsaf-pps_nc")
sc.load(sc.available_dataset_names())
sc.load(sc.available_composite_names())
ls = sc.resample("nqeuro3km")
ls.save_datasets(
        filename="/tmp/{platform_name}-{sensor}-{name}-{start_time:%Y%m%d%H%M}-{area.area_id}-test.tif",
        writer="geotiff")
```

fails with

```python-traceback
Traceback (most recent call last):
  File "/data/gholl/checkouts/protocode/read-pps.py", line 11, in <module>
    ls.save_datasets(
  File "/data/gholl/checkouts/satpy/satpy/scene.py", line 1198, in save_datasets
    return writer.save_datasets(dataarrays, compute=compute, **save_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/gholl/checkouts/satpy/satpy/writers/__init__.py", line 752, in save_datasets
    results.append(self.save_dataset(ds, compute=False, **kwargs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/gholl/checkouts/satpy/satpy/writers/__init__.py", line 876, in save_dataset
    img = get_enhanced_image(dataset.squeeze(), enhance=self.enhancer, overlay=overlay,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/gholl/checkouts/satpy/satpy/writers/__init__.py", line 445, in get_enhanced_image
    enhancer.apply(img, **dataset.attrs)
  File "/data/gholl/checkouts/satpy/satpy/writers/__init__.py", line 1227, in apply
    fun(img, *args, **kwargs)
  File "/data/gholl/checkouts/satpy/satpy/enhancements/__init__.py", line 352, in palettize
    full_cmap = _merge_colormaps(kwargs, img)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/gholl/checkouts/satpy/satpy/enhancements/__init__.py", line 366, in _merge_colormaps
    cmap = create_colormap(itm, img)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/gholl/checkouts/satpy/satpy/enhancements/__init__.py", line 480, in create_colormap
    cmap = _create_colormap_from_dataset(img, dataset, color_scale)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/gholl/checkouts/satpy/satpy/enhancements/__init__.py", line 496, in _create_colormap_from_dataset
    match = find_in_ancillary(img.data, dataset)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/gholl/checkouts/satpy/satpy/utils.py", line 705, in find_in_ancillary
    raise ValueError(
ValueError: Could not find dataset named cma_pal in ancillary variables for dataset 'cloudmask_extended'
```

although when I run it in a different terminal I do get the `ValueError` reported by Nina, so there might be two or more problems with semi-random circumstances determining which one is triggered first.

**Comment by gerritholl** [comment]
Failing composites: cloud_drop_effective_radius, cloud_optical_thickness, cloud_top_height, cloudmask_extended

Successful composites: cloud_top_phase, cloud_top_pressure, cloud_top_temperature, cloud_water_mask, cloudmask, cloudmask_probability, cloudtype, ice_water_path, liquid_water_path
