### ISSUE TITLE
Scene complains if it receives a dataset without geographic information

### ISSUE THREAD

**Issue by mitkin** [pytroll/satpy#24]
```
scene = satpy.scene.Scene()
ds = projectable.Dataset(np.arange(8), foo="bar")                             
 scene['ds'] = ds 
``` 
Returns
```
ValueError: Only 'Projectable' objects can be assigned
```

@mraspaud says dataset should also be accepted

**Comment by davidh-ssec** [comment]
I'm a little confused by the title versus the example you showed. Your title makes it sound like `Projectable(data, area=None)` (or equivalent) should work. Your example makes it look like you want `scn['ds'] = Dataset(...)` to work. Which issue are we addressing? Both?

Technically the Scene object should allow generic Dataset objects to be assigned to it and this is typically done for metadata that can't be resampled. I think for the `Projectable` with no area @mraspaud and I had talked about just getting rid of `Projectable` all together and only having `Dataset` with special handling if it doesn't have an `area`.

**Comment by mitkin** [comment]
@davidh-ssec , you are totally right, the title is/was misleading. I filed it in the middle of the hacking session, and haven't updated after the confusion has been sorted out.

Having a `Dataset` object only sounds like a good idea, it will be also in line with the `get_dataset` method name used in the readers.

**Comment by davidh-ssec** [comment]
This has been fixed on the develop branch as Projectables have now been merged in to Datasets. This exception is still raised if a non-Dataset is assigned.
