### ISSUE TITLE
Inconsistent behavior of time attributes in EUM L1 GEO readers

### ISSUE THREAD

**Issue by strandgren** [pytroll/satpy#2409]
As described here https://satpy.readthedocs.io/en/latest/readers.html#time-metadata, readers for geostationary data shall have two sets of `start_time` and `end_time` if available:

1. `observation_start_time` and `observation_end_time`: the start and end times of the actual instrument acquisition/scanning.
2. `nominal_start_time` and `nominal_end_time`: The “human friendly” time describing the start and end of the data observation interval or repeat cycle. For data with 15 minute resolution (e.g. SEVIRI), `nominal_start_time` and `nominal_end_time` should be 15 minutes apart with `nominal_start_time` at e.g. `13:15:00` (see documentation linked above for more details).

These four attributes shall be stored in a dataset attribute called `time_parameters`.

Furthermore, to have consistent times for e.g the calculation and caching of solar zenith angles, the dataset attributes `start_time` and `end_time` shall point to `nominal_start_time` and `nominal_end_time`, respectively.

Work towards this was started, but not finalized for the `seviri_l1b_native` and `seviri_l1b_hrit` readers in https://github.com/pytroll/satpy/pull/1877. However, there are still inconsistencies between the readers and with respect to the reader guidelines on time attributes, see "To Reproduce" below. Furthermore, such an implementation is currently missing in the `fci_l1c_nc` reader.

**To Reproduce**

**Example with `seviri_l1b_native`:**
```bash
In [1]: from satpy import Scene
In [2]: filename_native = '</path/to/file>'
In [3]: scn = Scene(filenames=[filename_native], reader='seviri_l1b_native')
In [4]: scn.load(['IR_108'])

In [5]: scn['IR_108'].attrs['start_time']
Out[5]: datetime.datetime(2023, 3, 12, 12, 0, 10, 804807)

In [6]: scn['IR_108'].attrs['end_time']
Out[6]: datetime.datetime(2023, 3, 12, 12, 15, 10, 479229)

In [8]: scn['IR_108'].attrs['time_parameters']
Out[8]:
{'nominal_start_time': datetime.datetime(2023, 3, 12, 12, 0, 10, 804807),   # Not `nominal_start_time` as defined in documentation, should be datetime.datetime(2023, 3, 12, 12, 0)
 'nominal_end_time': datetime.datetime(2023, 3, 12, 12, 15, 10, 479229),   # Not `nominal_end_time` as defined in documentation, should be datetime.datetime(2023, 3, 12, 12, 15)
 'observation_start_time': datetime.datetime(2023, 3, 12, 12, 0, 10, 804000),  # Correct
 'observation_end_time': datetime.datetime(2023, 3, 12, 12, 12, 44, 1000)}   # Correct
```

**Example with `seviri_l1b_hrit`:**
```bash
In [1]: from satpy import Scene
In [2]: import glob
In [3]: filenames_hrit = glob.glob('</path/to/files/*202303121200*>')
In [5]: scn = Scene(filenames=filenames_hrit, reader='seviri_l1b_hrit')
In [6]: scn.load(['IR_108'])

In [7]: scn['IR_108'].attrs['start_time']
Out[7]: datetime.datetime(2023, 3, 12, 12, 0, 10, 804000)  # Currently not pointing to `nominal_start_time`

In [8]: scn['IR_108'].attrs['end_time']
Out[8]: datetime.datetime(2023, 3, 12, 12, 12, 44, 1000)    # Currently not pointing to `nominal_start_time`

In [9]: scn['IR_108'].attrs['time_parameters']  # `time_parameters` attribute is missing
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
Cell In[9], line 1
----> 1 scn['IR_108'].attrs['time_parameters']
KeyError: 'time_parameters'

In [11]: scn['IR_108'].attrs['nominal_start_time']
Out[11]: datetime.datetime(2023, 3, 12, 12, 0, 10, 804807)  # Not `nominal_start_time` as defined in documentation, should be datetime.datetime(2023, 3, 12, 12, 0)

In [12]: scn['IR_108'].attrs['nominal_end_time'] 
Out[12]: datetime.datetime(2023, 3, 12, 12, 15, 10, 479229)   # Not `nominal_end_time` as defined in documentation, should be datetime.datetime(2023, 3, 12, 12, 15)

In [13]: scn['IR_108'].attrs['observation_start_time']   # No `observation_start_time` defined in reader (currently simply start_time)
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
Cell In[13], line 1
----> 1 scn['IR_108'].attrs['observation_start_time']
KeyError: 'observation_start_time'

In [14]: scn['IR_108'].attrs['observation_end_time']   # No `observation_end_time` defined in reader (currently simply end_time)
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
Cell In[14], line 1
----> 1 scn['IR_108'].attrs['observation_end_time']
KeyError: 'observation_end_time'
```

**Expected behavior**
Datasets attributes `start_time`, `end_time` and `time_parameters` are available as defined here: https://satpy.readthedocs.io/en/latest/readers.html#time-metadata

**Actual results**
Inconsistent behavior with e.g. incorrect definition/use of `nominal_start_time` and `nominal_end_time`.

**Proposed Solution**
Based on the observed behavior and looking into the readers as well as the Satpy documentation I propose the following:

*seviri_l1b_native:*
- Apply rounding to current `nominal_start_time` and `nominal_end_time` since the information read from the header (`TrueRepeatCycleStart` and `PlannedRepeatCycleEnd`) does not represent the expected meaning of the `nominal` times, i.e. rounded to the start and end of the 15min observation window (12:00:00 - 12:15:00) in the example above.
- When applying the rounding, we should account for the different scan/service modes (temporal resolutions) in order to apply the rounding correctly.

*seviri_l1b_hrit:*
- Move `nominal_start_time` and `nominal_end_time` to the `time_parameters` attribute (currently missing) and add deprecation warnings for the "direct access" to `nominal_start_time` and `nominal_end_time`.
- Apply same type of rounding to the `nominal_start_time` and `nominal_end_time` as for the native reader.
- Add properties `observation_start_time` and `observation_end_time` and add to the `time_parameters` attribute (use the times currently used for `start_time` and `end_time`).
- Make `start_time` and `end_time` point to `nominal_start_time` and `nominal_end_time`, respectively.
- use `self.start_time` to compute `satpos` (https://github.com/pytroll/satpy/blob/main/satpy/readers/seviri_l1b_hrit.py#L341)

*fci_l1c_nc:*
- Add properties `observation_start_time` and `observation_end_time` (same as current `start_time` and `end_time`) and add to the `time_parameters` attribute (currently missing).
- Add properties `nominal_start_time` and `nominal_end_time` and add to the `time_parameters` attribute. Here we can get the times in the "human friendly" format by using the repeat cycle number together with information about the different scan/service modes. We should also make sure that the `nominal_start_time` and `nominal_end_time` stay the same independent of the number of chunks read(?).
- Make `start_time` and `end_time` point to `nominal_start_time` and `nominal_end_time`, respectively.

**Environment Info:**
 - OS: Linux
 - Satpy Version: main

**Way Forward**
We (EUM) will start working on a PR for this soon, but are of course open to any input on the proposed solution above.

**Comment by ameraner** [comment]
For the human-readable FCI start and end time, one could use something like:
```python
RC_date = start_time.replace(hour=0, minute=0, second=0, microsecond=0)

if coverage=='FD':
    RC_period_min = 10
else:
    RC_period_min = 2.5

RC_start_time = RC_date + datetime.timedelta(minutes=(RC_n-1)*RC_period_min)
RC_end_time = RC_start_time + datetime.timedelta(minutes=RC_period_min)
```
where `start_time`, `RC_n` and `coverage` are available from the filename pattern matching.

**Comment by gerritholl** [comment]
> Move nominal_start_time and nominal_end_time to the time_parameters attribute (currently missing) and add deprecation warnings for the "direct access" to nominal_start_time and nominal_end_time.

Times are commonly used in the `filename` parameter in `save_datasets`, so this may require quite many users to replace `{start_time}` by `{time_parameters[start_time]}` in their `filename` str; not all users may be aware the latter is even possible (the syntax looks suspiciously similar to dictionary lookup, but is not really).

**Comment by djhoese** [comment]
If they're using `nominal` then there should still be `.attrs['start_time']` which should be equivalent to the nominal time and the default for most filenaming.

**Comment by gerritholl** [comment]
Oh, I thought all time attributes were moving to `time_parameters`, but if `start_time` remains as a direct attribute, then that's not an issue for most users.

**Comment by djhoese** [comment]
The `start_time`/`end_time` should always exist and be equal to nominal time whenever possible. Nominal and observation times will be in `time_parameters`. `start_time`/`end_time` will be used for filename (default something like `{name}_{start_time:%Y%m%d_%H%M%S}.tif`) and for caching keys like the satellite angle generation.

**Comment by YouvaEUMex** [comment]
Hey I juste realise that there is and independant start/end time handling for prologue/epilogue in HRIT files: 
https://github.com/pytroll/satpy/blob/main/satpy/readers/hrit_base.py#L226 
https://github.com/pytroll/satpy/blob/main/satpy/readers/hrit_base.py#L231 
that actually screw up the unit testing of the HRIT reader. How should we handle this?

**Comment by ameraner** [comment]
Let's not forget about the `seviri_l1b_nc` reader please, as I see that it's missing in the discussion here and the draft PR.

**Comment by YouvaEUMex** [comment]
> Let's not forget about the `seviri_l1b_nc` reader please, as I see that it's missing in the discussion here and the draft PR.

done in https://github.com/pytroll/satpy/pull/2420/commits/00f6c91a4d2ef52d68260a6655931bd32fa87d14
