### ISSUE TITLE
Wrong start_time, end_time attributes after MultiScene.blend(blend_function=timeseries)

### ISSUE THREAD

**Issue by gerritholl** [pytroll/satpy#2427]
**Describe the bug**

After producing a scene with `MultiScene.blend(blend_function=timeseries)`, the attributes `start_time` and/or `end_time` on the resulting Scene are wrong.

**To Reproduce**

```python
import hdf5plugin
from glob import glob
from satpy.multiscene import MultiScene, timeseries
from satpy.utils import debug_on; debug_on()

ms = MultiScene.from_files(
        glob("/media/nas/x21308/MTG_test_data/2022_05_MTG_Testdata/RC010[012]/*BODY*.nc"),
        reader="fci_l1c_nc",
        group_keys=["repeat_cycle_in_day"])
channels = ["ir_105", "ir_133", "wv_63", "wv_73"]
ms.load(channels)
sc = ms.blend(blend_function=timeseries)
print(sc.start_time, sc.end_time)
print(ms.scenes[0].start_time, ms.scenes[-1].end_time)
```

**Expected behavior**

I expect as the final output from the print functions:

```
2017-09-20 16:30:08 2017-09-20 16:59:22
2017-09-20 16:30:08 2017-09-20 16:59:22
```

**Actual results**

The result of the print functions is:

```
2017-09-20 16:40:08 2017-09-20 16:49:22
2017-09-20 16:30:08 2017-09-20 16:59:22
```

**Environment Info:**
 - OS: openSUSE 15.3
 - Satpy Version: v0.41.1-18-gb92fe9ebb (current GitHub main)

**Additional context**

The attributes are also wrong on the individual datasets that have been blended.

**Comment by djhoese** [comment]
@adybbroe and I had a conversation similar to this when he added his recent weighted blending. Right now the timeseries functionality uses `combine_metadata` which for some reason that I don't recall does not handle start/end time in any special way and only averages them.

Usage:

https://github.com/pytroll/satpy/blob/9c960e5b14917bd856b68e3d772505871329700c/satpy/multiscene.py#L124

Definition docstring:

https://github.com/pytroll/satpy/blob/9c960e5b14917bd856b68e3d772505871329700c/satpy/dataset/metadata.py#L35-L38

I think we need to update `combine_metadata` to min/max start/end times. @mraspaud @pnuu?
