### ISSUE TITLE
Missing dependencies in setup.py for running all the tests

### ISSUE THREAD

**Issue by sjoro** [pytroll/satpy#2471]
**Describe the bug**
I installed a new fresh Satpy-development environment following the instructions:
https://satpy.readthedocs.io/en/stable/dev_guide/index.html#developer-s-guide

a handfull of tests fail due to missing packages/modules. these seem to be:
`python-eccodes`
`h5netcdf`
`xarray-datatree`
`skyfield`
`ephem`
`pint-xarray`
`astropy `

**To Reproduce**

Create new dev-environment as instructed and run

```python
pytest satpy/tests
```

**Expected behavior**
All tests should run once the dev-environment has been setup as per instructions
Missing dependencies should probably be added to:
https://github.com/pytroll/satpy/blob/main/setup.py#L38

**Actual results**
Example output from one of the test runs...
```
=============================================== short test summary info ================================================
FAILED satpy/tests/test_utils.py::TestGetSatPos::test_get_satpos_from_satname - ModuleNotFoundError: No module named 'skyfield'
FAILED satpy/tests/compositor_tests/test_viirs.py::TestVIIRSComposites::test_hncc_dnb_nomoonpha - ImportError: The 'ephem' library is required to calculate moon illumination fraction
FAILED satpy/tests/modifier_tests/test_parallax.py::TestParallaxCorrectionClass::test_correct_area_no_orbital_parameters - ModuleNotFoundError: No module named 'skyfield'
FAILED satpy/tests/modifier_tests/test_parallax.py::TestParallaxCorrectionSceneLoad::test_double_load - ModuleNotFoundError: No module named 'skyfield'
FAILED satpy/tests/modifier_tests/test_parallax.py::TestParallaxCorrectionSceneLoad::test_enhanced_image - ModuleNotFoundError: No module named 'skyfield'
FAILED satpy/tests/writer_tests/test_geotiff.py::TestGeoTIFFWriter::test_float_write_with_unit_conversion - ModuleNotFoundError: No module named 'pint_xarray'
```

**Environment Info:**
 - OS: macOS Ventura 13.3.1
 - Satpy Version: 0.42.2.dev12+g2aac9e4b6

**Comment by djhoese** [comment]
Which pip install command did you follow? The section after the one you linked to shows how to install test dependencies, but you are right there seem to be some missing dependencies.

Another option for us as satpy developers would be to skip tests that we know require these extra dependencies if they aren't available.

**Comment by sjoro** [comment]
i was following the instructions as they are:
```
conda create -n satpy-dev python=3.8
conda activate satpy-dev
conda install --only-deps satpy
pip install -e .
pip install -e ".[tests]"
```

**Comment by djhoese** [comment]
Yeah I just wanted to make sure you saw the `".[tests]"` version of the pip install command but that became clear after I sent the comment.

**Comment by sjoro** [comment]
is python 3.8 still the recommended python version? or something newer... like 3.10? or even 3.11? should the instructions be updated at the same time?

**Comment by djhoese** [comment]
Oh, I didn't even realize a number was specified there. We could probably change that (maybe remove the `=3.8`). If it needs to be specified or helps users to have it specified then `3.11` is the preferred.
