### ISSUE TITLE
Does python3.8 and below seem to fail to install via the command line "conda install -c conda-forge satpy"?

### ISSUE THREAD

**Issue by yhyxzx** [pytroll/satpy#2580]
**Describe the bug**
My python virtual environment is 3.8. I can't install satpy using the command line conda install -c conda-forge satpy(= X.XX.X). Since it needs to be paired with other packages such as scikit-image,opencv-python,pyhdf, etc., it seems that it is not advisable to use python version 3.9 or above, so I am in great confusion and want to ask for advice!

**To Reproduce**

```python
# Your code here
conda install -c conda-forge satpy(= X.XX.X)
conda install -c conda-forge opencv
conda install -c anaconda scikit-image
conda install -c conda-forge pyhdf
```

**Expected behavior**
Find a collocation that enables these packages to coexist.

**Environment Info:**
 - OS: Windows
 - Satpy Version:  0.39.0

**Comment by djhoese** [comment]
Python 3.8 and below are no longer supported or maintained by the conda-forge project. You'll need to update your version of Python to get the latest updates.

Your main issue may be mixing conda channels. Is there a reason you are installing scikit-image from the anaconda channel? It is available from conda-forge as far as I can tell.

Also note that running a single install (or environment creation) with all dependencies listed will perform much better (it will be faster to install the packages) as the dependency solver will know all of the information for the packages you want at once rather than trying to make new packages work with an existing environment.

**Comment by yhyxzx** [comment]
Thank you. According to your suggestion, I ran the following command and successfully installed the package I needed.
conda install -c conda-forge satpy scikit-image pyhdf
conda install -c conda-forge opencv
conda install -c conda-forge matplotlib

**Comment by djhoese** [comment]
Glad you got it working. Regarding my comment on install performance, don't do these package installs as 3 separate commands. Do `conda install -c conda-forge satpy scikit-image pyhdf opencv matplotlib` all at once. Even better, create your environment with all of the packages listed:

```
conda create -n my_env python=3.11 satpy scikit-image pyhdf opencv matplotlib
```

**Comment by yhyxzx** [comment]
The order does not seem to work @djhoese 

(base) PS C:\Users\Administrator> conda create -n my_env python=3.11 satpy scikit-image pyhdf opencv matplotlib
Retrieving notices: ...working... done
Collecting package metadata (current_repodata.json): done
Solving environment: unsuccessful attempt using repodata from current_repodata.json, retrying with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - satpy
  - pyhdf

Current channels:

  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/win-64
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

In fact, it seemed like a long wait to run the following command, so I aborted the wait in time and chose to install them group by group.
'''
conda install -c conda-forge satpy scikit-image pyhdf opencv matplotlib
'''

**Comment by yhyxzx** [comment]
The order does not seem to work @djhoese 

(base) PS C:\Users\Administrator> conda create -n my_env python=3.11 satpy scikit-image pyhdf opencv matplotlib
Retrieving notices: ...working... done
Collecting package metadata (current_repodata.json): done
Solving environment: unsuccessful attempt using repodata from current_repodata.json, retrying with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - satpy
  - pyhdf

Current channels:

  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/win-64
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

In fact, it seemed like a long wait to run the following command, so I aborted the wait in time and chose to install them group by group.
'''
conda install -c conda-forge satpy scikit-image pyhdf opencv matplotlib
'''

**Comment by djhoese** [comment]
Ah sorry, I forgot the `-c conda-forge` in the environment creation command. I have my own conda configuration to always use conda-forge so I forget that flag sometimes.

I don't use opencv or scikit-image so there is a chance they don't have Python 3.11 packages yet.

If you make a lot of conda environments you could also look at using mamba and the mambaforge project. These use a faster dependency solver (something being added to the main `conda` package manager in the future) and can really speed up environment creation and package installations.

**Comment by yhyxzx** [comment]
I learned. Thank you for your patience.
