### ISSUE TITLE
 Is there a corresponding reader for S3A_SL_2_WST?

### ISSUE THREAD

**Issue by yhyxzx** [pytroll/satpy#2591]
For the L2 product WST of the Sentinel 3 SLSTR sensor,
For example, _S3A_SL_2_WST____20231006T185134_20231006T203233_20231008T045502_6059_104_141______MAR_O_NT_003.SEN3_.
Is there a corresponding reader for S3A_SL_2_WST?

**Comment by yhyxzx** [comment]
This is my current list
from satpy import available_readers
available_readers()
['abi_l1b', 'abi_l1b_scmi', 'abi_l2_nc', 'acspo', 'agri_fy4a_l1', 'agri_fy4b_l1', 'ahi_hrit', 'ahi_hsd', 'ahi_l1b_gridded_bin', 'ami_l1b', 'amsr2_l1b', 'amsr2_l2', 'amsr2_l2_gaasp', 'amsub_l1c_aapp', 'atms_l1b_nc', 'atms_sdr_hdf5', 'avhrr_l1b_aapp', 'avhrr_l1b_eps', 'avhrr_l1b_hrpt', 'avhrr_l1c_eum_gac_fdr_nc', 'clavrx', 'cmsaf-claas2_l2_nc', 'electrol_hrit', 'epic_l1b_h5', 'fci_l1c_nc', 'fci_l2_nc', 'generic_image', 'geocat', 'ghi_l1', 'ghrsst_l2', 'glm_l2', 'goes-imager_hrit', 'goes-imager_nc', 'gpm_imerg', 'hsaf_h5', 'hy2_scat_l2b_h5', 'iasi_l2', 'iasi_l2_cdr_nc', 'ici_l1b_nc', 'jami_hrit', 'li_l2_nc', 'maia', 'meris_nc_sen3', 'mersi2_l1b', 'mersi_ll_l1b', 'mhs_l1c_aapp', 'mimicTPW2_comp', 'mirs', 'modis_l1b', 'modis_l2', 'msu_gsa_l1b', 'mtsat2-imager_hrit', 'mviri_l1b_fiduceo_nc', 'mwi_l1b_nc', 'mws_l1b_nc', 'nucaps', 'nwcsaf-geo', 'nwcsaf-msg2013-hdf5', 'nwcsaf-pps_nc', 'oceancolorcci_l3_nc', 'olci_l1b', 'olci_l2', 'omps_edr', 'safe_sar_l2_ocn', 'satpy_cf_nc', 'seadas_l2', 'seviri_l1b_hrit', 'seviri_l1b_icare', 'seviri_l1b_native', 'seviri_l1b_nc', 'slstr_l1b', 'smos_l2_wind', 'tropomi_l2', 'vaisala_gld360', 'vii_l1b_nc', 'vii_l2_nc', 'viirs_compact', 'viirs_edr_active_fires', 'viirs_edr_flood', 'viirs_l1b', 'viirs_l2_cloud_mask_nc', 'viirs_sdr', 'viirs_vgac_l1c_nc', 'virr_l1b']

**Comment by mraspaud** [comment]
I don't think we have a reader for slstr level 2 data atm, but contributions are welcome!

**Comment by yhyxzx** [comment]
Ok, thank you.
