### ISSUE TITLE
GCOM-C Support (Continued)

### ISSUE THREAD

**Issue by CocoasColas** [pytroll/satpy#2618]
I noticed that in the past you guys have started the development to add support for the GCOM-C Satellite, in 2022 it seems like the development suddenly stopped. I was wondering if you guys are planning to continue and finish adding support for the GCOM-C Satellite as me and I'm sure a few others are wondering this as well. #1094 is the hyperlink to the pull request. I've tried adding my own support with Satpy for the SGLI instrument and I will say it was without any success which was a bit unfortunate.

**Comment by mraspaud** [comment]
@CocoasColas Thanks for reminding use of this! It was me who started this reader, but I never got the incentive to finish it as it's nothing we need or plan to use in my job. But I can have a look and see how much needs to be done here.

**Comment by mraspaud** [comment]
@CocoasColas I've been working on #1094 a bit, and the VN files should be fully supported now, would you like to check if it works for you?

**Comment by CocoasColas** [comment]
So far I am very pleased with the results, it seems to be working exactly as intended without any issues.

**Comment by mraspaud** [comment]
I think I'm ready for review with #1094 . Both VN, IR and POL files should now be supported.  @CocoasColas Feel free to check it out and report on #1094 directly.
