### ISSUE TITLE
How to get the available dataset names from the reader

### ISSUE THREAD

**Issue by adybbroe** [pytroll/satpy#263]
#### Problem description
We have a MSG SEVIRI native format data file with a subset of SEVIRI bands in the file.
However, when we request the available dataset names we get all. This is because the scene object does not use the information already retrieved in the reader. Reading the file header we have the information of which datasets are in the file. But this is not passed further. We tried adding a `available_dataset_ids` method to the reader, but this is not called/used when doing the below. We also tried passing the read-name to the call but that didn't make a difference.

How should one do?

```
In [2]: nat.available_dataset_names()
Out[2]: 
['HRV',
 'IR_016',
 'IR_039',
 'IR_087',
 'IR_097',
 'IR_108',
 'IR_120',
 'IR_134',
 'VIS006',
 'VIS008',
 'WV_062',
 'WV_073']
```

#### Versions of Python, package at hand and relevant dependencies

This was using the SatPy from the latest msg-hrit-native-merge branch, which we are working on for a PR.
 The above is seen both in python 3.4.6 and 2.7.5

Thank you for reporting an issue !

**Comment by xuesongle** [comment]
Each dataset name represents a band of channel in your local drive. Which band to be loaded into the Scene object depends on those parameters. The long list there tells you that you have all files in different bands in your base directory but not loaded 
For example
nat.load(["IR_016"])
nat.save_datasets(writer='simple_image')

will save the data in "IR_016" band into a PNG image file.

**Comment by djhoese** [comment]
As mentioned in the other issue, this is covered by #434. I'll close this in favor of that discussion.
