### ISSUE TITLE
SunZenithReducer defaults make True Color FCI imagery too dark at high solar zenith angles

### ISSUE THREAD

**Issue by ameraner** [pytroll/satpy#2643]
The [SunZenithReducer modifier](https://github.com/pytroll/satpy/blob/c09c1475b50d36d13807e3ac69d234eae5c1d609/satpy/modifiers/geometry.py#L164) has been implemented in https://github.com/pytroll/satpy/pull/2556 to have a nice, smooth and artefact-free transition into nighttime when Rayleigh correction is applied to VIS-based composites (see PR for details).

As reported by Cris (MetOffice) [in the mailing list](https://groups.google.com/g/pytroll/c/KBo5lrB1o4c/m/fswWJMlfCQAJ), the current defaults for the reducer are making imagery at high solar angles **too dark**.
How come? The defaults were defined for the FCI First Image publications, which was taken close to the equinox (rather uniform illumination), and with the goal to produce imagery with very smooth day/night transitions. Now that we're entering the first winter season on the North hemisphere, with permanently high solar zenith angles, the issue is emerging.

I've done some experiments, trying to optimise the tradeoffs between (in descending order of importance):
- keeping as much data as possible close to the terminator, with usable brightness
- avoiding the reddish artefacts 
- avoiding the limb-glow caused by the sunzen correction, particularly the "peak" line at the terminator
- keeping a natural transition appearance

What I came up with was increasing the limit angle (where the reduction starts to kick-in) from 55° to 80°, and decrease the strength (defining the shape of the reduction function, [see plot here](https://github.com/pytroll/satpy/pull/2554#issue-1864570418) ) from 1.5 to 1.3.

A few examples from a few days ago (20231117)
**Northern Europe**
| Settings           | 8UTC | 12UTC |
|--------------------|------|-------|
| No reduction ( reddish artefacts + glow)     | ![8noreduce](https://github.com/pytroll/satpy/assets/49722768/36dfd23f-2e53-4bb5-a85e-d3d8ade92adf) |    ![noreduce](https://github.com/pytroll/satpy/assets/49722768/4c9dc387-d3ed-4ce2-a3d9-6fc5995073d3)|
| 55° limit, 1.5 strength (current main - no artefacts, no glow, but too dark too early)|   ![855](https://github.com/pytroll/satpy/assets/49722768/51b1a832-8d98-400c-a639-a2574a57ffd8) |   ![55](https://github.com/pytroll/satpy/assets/49722768/b8d724f5-7710-4fbc-9719-a07204d87d3c) |
| 80° limit, 1.3 strength (proposal)  | ![8n80-1p3](https://github.com/pytroll/satpy/assets/49722768/2bd9b1a7-d5a9-4f52-bfcc-bca42a051cff) |   ![n80-1p3](https://github.com/pytroll/satpy/assets/49722768/92c3976d-abf6-455e-811d-609ea331abb7) |

**Full-disc**
| Settings           | 8UTC | 12UTC |
|--------------------|------|-------|
| No reduction ( reddish artefacts + glow)  | ![8fnoreduce](https://github.com/pytroll/satpy/assets/49722768/1da132c2-c88b-4676-9034-7232001fd02f) |  ![fnoreduce](https://github.com/pytroll/satpy/assets/49722768/9c75680a-6bb0-4455-9eaf-20dc2fba5c84) |
|  55° limit, 1.5 strength (current main - no artefacts, no glow, but too dark too early) | ![8f551p5](https://github.com/pytroll/satpy/assets/49722768/50a3e4f1-dbbf-49d9-b570-8d53410b232d) | ![f551p5](https://github.com/pytroll/satpy/assets/49722768/4f2749ff-6f06-454e-a923-d812eade8b94) |
| 80° limit, 1.3 strength (proposal)  | ![8f80-1p3](https://github.com/pytroll/satpy/assets/49722768/37ea4774-83d2-487d-8fd4-1bf83c88a7f7) | ![f80-1p3](https://github.com/pytroll/satpy/assets/49722768/c017b645-28da-4e39-8a99-80bbf50a4732)  |

**First Image** (for comparison for an equinox scene)
| Settings           |  | 
|--------------------|------|
| No reduction | ![firstimagenocorr](https://github.com/pytroll/satpy/assets/49722768/ea69a33d-143e-4ffc-bb02-e0dad6e2ba78) |
| 55° limit, 1.5 strength - Current main, very similar to published version | ![firstimageoriginal](https://github.com/pytroll/satpy/assets/49722768/ca04bb2a-07ba-468f-aeed-621b44e20de5) |
| 80° limit, 1.3 strength (proposal) | ![firstimagef80-1p3](https://github.com/pytroll/satpy/assets/49722768/5a2032a5-bdf8-4e80-bd06-53b90f2d0542) |

We (with @strandgren ) think the new setting satisfies well the tradeoff points above, let me know what you think!

In any case, I would propose to add in the FCI composites the version without reduction, so that it's easily accessible for users that need to keep as much data as possible, at the cost of introducing some artefacts. What should the name be? `true_color_nosunzreduction`?

----
PS: if someone wants to experiment with the parameters, the full definition of the modifier looks like this:
```  
sunz_reduced:
    modifier: !!python/name:modifiers.geometry.SunZenithReducer
    correction_limit: 80
    strength: 1.3
    max_sza: 90
    optional_prerequisites:
      - solar_zenith_angle
```
(to be modified either in local custom composite configuration, or [here](https://github.com/pytroll/satpy/blob/ace39993e9a6df57541a1b8cc43aa63b2fb82eec/satpy/etc/composites/visir.yaml#L19-L22))

**Comment by mraspaud** [comment]
Very nice work summing this up with examples!
I agree the proposal looks like a very good compromise of the different requirements. I also agree a version with no reduction is good to have. How about `true_color_fully_normalized`for the name?

**Comment by adybbroe** [comment]
Yes, agree with Martin, good work and very nicely compiled and explained. And yes always good to also have the option to go back to "no reduction".

**Comment by ameraner** [comment]
Thanks, glad you like it :)
mmm tbh I'm not convinced by the `fully_normalized`, since it sounds a bit "absolute" and there are probably more normalizations one could apply that are not included here. Along that line, maybe `fully_sunzencorrected` could work?

**Comment by ameraner** [comment]
A preview how the new setup will look like on EUMETView (today 09:40 UTC):

![image](https://github.com/pytroll/satpy/assets/49722768/f2998148-5408-4f93-adf1-5faef345e67e)
