### ISSUE TITLE
How to intepret the parameter values in  AreaDefinition

### ISSUE THREAD

**Issue by xuesongle** [pytroll/satpy#269]
#### Code Sample, a minimal, complete, and verifiable piece of code

```python
# Your code here
area_id = 'japan'
x_size = 2407
y_size = 1655
area_extent = (-1203877.326193321, -754860.2505908236, 1203877.3261933187, 900373.6358697552)
projection = '+proj=laea +lat_0=37.5 +lon_0=137.5 +ellps=WGS84'
description = "Japan"
proj_id = 'laea_137.5_37.5'
areadef = get_area_def(area_id, description, proj_id, projection,x_size, y_size, area_extent)
local_scene = scn.resample(areadef)
```
#### Problem description

I used the code example from https://github.com/pytroll/pytroll-examples/blob/master/satpy/ahi_true_color_pyspectral.ipynb
It did show the local Scene in Japan but I do not understand how to convert from latitude, longitude into projected coordinates as specified in area_extent. Would someone kindly shed a light on this issue or tell me which resource I can look at? Many Thanks here.

#### Versions of Python, package at hand and relevant dependencies

Thank you for reporting an issue !

**Comment by mraspaud** [comment]
@xuesongle you can maybe have a look at this script: https://github.com/pytroll/satpy/blob/master/utils/coord2area_def.py 

This should help you transform longitude and latitude requirements to an area definition

**Comment by davidh-ssec** [comment]
I should note that it is on my todo list to make AreaDefinitions easier to create.
