### ISSUE TITLE
msg_native reader fails when order number has a hyphen in it

### ISSUE THREAD

**Issue by simonrp84** [pytroll/satpy#277]
#### Code Sample, a minimal, complete, and verifiable piece of code

# Your code here
from satpy import Scene
infile	=	['/indir/MSG2-SEVI-MSG15-0100-NA-20101101135742.336000000Z-20101101135754-1260206-1.nat']
global_scene = Scene(filenames=infile,sensor="seviri", reader="native_msg")

#### Problem description

The above code will fail with an error. If I edit the order number (1260206-1) to something that doesn't contain the hyphen (1260206) then satpy works OK. It appears that the code isn't set up to deal with orders that span multiple parts (-1, -2, etc).

#### Expected Output

Satpy loads MSG native data

#### Actual Result, Traceback if applicable
Traceback (most recent call last):
  File "Make_MSG_new.py", line 3, in <module>
    global_scene = Scene(filenames=infile,sensor="seviri", reader="native_msg")
  File "/local/home/proud/VEnv/lib/python2.7/site-packages/satpy/scene.py", line 144, in __init__
    self.info.update(self._compute_metadata_from_readers())
  File "/local/home/proud/VEnv/lib/python2.7/site-packages/satpy/scene.py", line 162, in _compute_metadata_from_readers
    for x in self.readers.values())
  File "/local/home/proud/VEnv/lib/python2.7/site-packages/satpy/scene.py", line 162, in <genexpr>
    for x in self.readers.values())
  File "/local/home/proud/VEnv/lib/python2.7/site-packages/satpy/readers/yaml_reader.py", line 406, in start_time
    raise RuntimeError("Start time unknown until files are selected")
RuntimeError: Start time unknown until files are selected

#### Versions of Python, package at hand and relevant dependencies
2.7

Thank you for reporting an issue !

**Comment by davidh-ssec** [comment]
In addition to make the reader accept multi-part files I think we'll need to work on a better error message when no files are matched to the reader.

**Comment by davidh-ssec** [comment]
We currently have the following file patterns:

```
    file_patterns: ['{satid:4s}-{instr:4s}-MSG{product_level:2d}-0100-NA-{processing_time1:%Y%m%d%H%M%S.%f}000Z-{processing_time2:%Y%m%d%H%M%S}-{order_id:d}.nat',
                    '{satid:4s}-{instr:4s}-MSG{product_level:2d}-0100-NA-{processing_time1:%Y%m%d%H%M%S.%f}000Z-NA.nat',
                    '{satid:4s}-{instr:4s}-MSG{product_level:2d}-0100-NA-{processing_time1:%Y%m%d%H%M%S.%f}000Z-{order_id:d}.nat']
```

I don't see why we can't make it two patterns where the order_id accepts any remaining string at the end of the pattern. Unless we are actually using the order id integer for some reason. @cduff65 @mraspaud  Thoughts?

**Comment by adybbroe** [comment]
I agree @djhoese As far as I know the order-id is not used anywhere. Any views @sjoro ?

Another small thing @simonrp84 : 
I have learned that it is preferable to let the `find_files_and_readers` find the files for you first and then pass the resulting dictionary to the Scene object, like this:

```
from satpy import Scene
from satpy import find_files_and_readers
hrit_files = find_files_and_readers(base_dir="/home/a000680/data/hrit/20180102/", reader='hrit_msg')
hrit = Scene(filenames=hrit_files)
```

You can also pass start and end time and sensor (if needed) to the function.

**Comment by sjoro** [comment]
@djhoese @adybbroe Order ID is not used anywhere in satpy, hence it could be changed to a string for the parser. Order ID is for the user to identify and keep track of the files for the ordered set. anyone working on fixing this?

**Comment by sjoro** [comment]
Fixed and merged to `develop`
