### ISSUE TITLE
Documentation points to missing setup.py

### ISSUE THREAD

**Issue by ameraner** [pytroll/satpy#2782]
**Describe the bug**
After https://github.com/pytroll/satpy/pull/2763, the Satpy docs now point to the non-existing `setup.py` file in a couple of spots (see this search: https://github.com/search?q=repo%3Apytroll%2Fsatpy+setup.py&type=code ).

**To Reproduce**

Clicking on the hyperlink e.g. here: https://satpy.readthedocs.io/en/stable/install.html#pip-based-installation causes a 404 error.

**Expected behavior**
The mentions of `setup.py` in the docs should be removed and the according docs instructions updated.

**Comment by mraspaud** [comment]
I'm on it
