### ISSUE TITLE
Help about Netcdf Data

### ISSUE THREAD

**Issue by markjinz** [pytroll/satpy#2839]
Thank you for your help

**Comment by mraspaud** [comment]
Hi @markjinz 

Something like this can work to generate a netcdf file:
```python
    scn = Scene(filenames=filenames,
                reader='seviri_l1b_hrit',
                )


    composites = ["VIS006", "VIS008", ...]
    scn.load(composites)
    rscn = scn.resample("eurol")
    rscn.save_datasets(writer="cf")
```
Or have you tried that already?

**Comment by markjinz** [comment]
> Hi @markjinz
> 
> Something like this can work to generate a netcdf file:
> 
> ```python
>     scn = Scene(filenames=filenames,
>                 reader='seviri_l1b_hrit',
>                 )
> 
> 
>     composites = ["VIS006", "VIS008", ...]
>     scn.load(composites)
>     rscn = scn.resample("eurol")
>     rscn.save_datasets(writer="cf")
> ```
> 
> Or have you tried that already?

hello @mraspaud 
this is my code : 
from satpy import Scene
import glob
filenames = glob.glob('./raw02/H*202405281015*')
scn = Scene(filenames=filenames, reader='seviri_l1b_hrit')
scn.load(['IR_120', 'IR_108'])
scn.save_datasets(writer='cf', datasets=['IR_120', 'IR_108'], filename='seviri_test.nc',
                      exclude_attrs=['raw_metadata'],groups={'ir': ['IR_120', 'IR_108']})
but i have this problem :
/home/mark/anaconda3/envs/finland/lib/python3.10/site-packages/satpy/writers/cf_writer.py:571: FutureWarning: The default behaviour of the CF writer will soon change to not compress data by default.
  warnings.warn("The default behaviour of the CF writer will soon change to not compress data by default.",
No time dimension in datasets of group ir, skipping time bounds creation.
[None, None]
And i have a heavy file as output

**Comment by markjinz** [comment]
this is what i get when i print the scene :
<xarray.DataArray 'reshape-834a5d14e33e86483a99116485dad0ba' (y: 3712, x: 3712)>
dask.array<concatenate, shape=(3712, 3712), dtype=float32, chunksize=(464, 3712), chunktype=numpy.ndarray>
Coordinates:
    acq_time  (y) datetime64[ns] NaT NaT NaT NaT NaT NaT ... NaT NaT NaT NaT NaT
    crs       object PROJCRS["unknown",BASEGEOGCRS["unknown",DATUM["unknown",...
  * y         (y) float64 -5.566e+06 -5.563e+06 ... 5.566e+06 5.569e+06
  * x         (x) float64 5.566e+06 5.563e+06 5.56e+06 ... -5.566e+06 -5.569e+06
Attributes: (12/19)
    orbital_parameters:       {'projection_longitude': 0.0, 'projection_latit...
    platform_name:            Meteosat-10
    units:                    K
    wavelength:               10.8 µm (9.8-11.8 µm)
    sensor:                   seviri
    nominal_end_time:         2024-05-28 10:30:09.735653
    ...                       ...
    name:                     IR_108
    resolution:               3000.403165817
    calibration:              brightness_temperature
    modifiers:                ()
    _satpy_id:                DataID(name='IR_108', wavelength=WavelengthRang...
    ancillary_variables:      []

**Comment by djhoese** [comment]
Sorry @markjinz, Martin is on holiday and I have very little experience with SEVIRI data and with outputting to NetCDF files in Satpy but maybe I can help or find someone who can help more.

1. What exactly is the problem with the file being produced?
2. You mentioned you have times in seconds, why is that bad?
3. Could you provide the `ncdump -h` of the file being produced?
4. Asking the above in another way, what do you have now and what do you want it to look like?
5. I wouldn't worry about the warning you were getting for now about the compression deprecation (unless you really need deprecation).
6. I'm not sure where the `[None, None]` output is coming from. Is that a print in your code or a print left over in the CF writer code somewhere?

Otherwise, @pytroll/seviri_power_users might be able to help.

**Comment by gerritholl** [comment]
To avoid huge files with the NetCDF writer, you need to pass `encoding=` for each of your variables:

```python
    ls.save_datasets(
            writer="cf",
            format="NETCDF4",
            filename=os.path.join(
                out_dir,
                "{platform_name}-{sensor}-{area.area_id}-{name}-{start_time:%Y%m%d%H%M%S}-{end_time:%Y%m%d%H%M%S}.nc"),
            encoding={
                "IR_108":
                {"zlib": True,
                 "complevel": 9,
                 "scale_factor": 0.1,
                 "dtype": "int16",
                 "_FillValue": 0}},
            include_lonlats=False)
```

Example for FCI:

**Comment by markjinz** [comment]
> To avoid huge files with the NetCDF writer, you need to pass `encoding=` for each of your variables:
> 
> ```python
>     ls.save_datasets(
>             writer="cf",
>             format="NETCDF4",
>             filename=os.path.join(
>                 out_dir,
>                 "{platform_name}-{sensor}-{area.area_id}-{name}-{start_time:%Y%m%d%H%M%S}-{end_time:%Y%m%d%H%M%S}.nc"),
>             encoding={
>                 "IR_108":
>                 {"zlib": True,
>                  "complevel": 9,
>                  "scale_factor": 0.1,
>                  "dtype": "int16",
>                  "_FillValue": 0}},
>             include_lonlats=False)
> ```
> 
> Example for FCI, producing a simple NetCDF file with a single uncalibrated channel:
> 
> ```python
> import hdf5plugin
> from satpy import Scene
> from glob import glob
> filenames = glob(".../W_XX-EUMETSAT-Darmstadt,IMG+SAT,MTI1+FCI-1C-RRAD-*-FD--CHK-BODY--DIS-NC4E_C_EUMT_20231115*_IDPFI_OPE_20231115*_20231115*_N_JLS_C_0054_*.nc")
> sc = Scene(filenames=filenames, reader="fci_l1c_nc")
> sc.load(["vis_06"], calibration="counts")
> sc.save_dataset(
>         "vis_06",
>         "/media/nas/x21308/scratch/FCI/{platform_name}-{sensor}-{area.area_id}-{name}-{start_time:%Y%m%d%H%M%S}-{end_time:%Y%m%d%H%M%S}.nc",
>         encoding={"vis_06": {"dtype": "int16", "zlib": True}},
>         include_lonlats=False)
> ```

hi @gerritholl 
The problem is that the output gives me multiple numbers such as 3712 ( number of x/y) , whereas I only want one specific timestamp. It seems as though there are no dimensions of time in the file test2.nc

netcdf tes2 {
dimensions:
	y = 3712 ;
	x = 3712 ;
variables:
	int64 msg_seviri_fes_3km ;
		msg_seviri_fes_3km:crs_wkt = "PROJCRS[\"unknown\",BASEGEOGCRS[\"unknown\",DATUM[\"unknown\",ELLIPSOID[\"unknown\",6378169,295.488065897014,LENGTHUNIT[\"metre\",1,ID[\"EPSG\",9001]]]],PRIMEM[\"Greenwich\",0,ANGLEUNIT[\"degree\",0.0174532925199433],ID[\"EPSG\",8901]]],CONVERSION[\"unknown\",METHOD[\"Geostationary Satellite (Sweep Y)\"],PARAMETER[\"Longitude of natural origin\",0,ANGLEUNIT[\"degree\",0.0174532925199433],ID[\"EPSG\",8802]],PARAMETER[\"Satellite Height\",35785831,LENGTHUNIT[\"metre\",1,ID[\"EPSG\",9001]]],PARAMETER[\"False easting\",0,LENGTHUNIT[\"metre\",1],ID[\"EPSG\",8806]],PARAMETER[\"False northing\",0,LENGTHUNIT[\"metre\",1],ID[\"EPSG\",8807]]],CS[Cartesian,2],AXIS[\"(E)\",east,ORDER[1],LENGTHUNIT[\"metre\",1,ID[\"EPSG\",9001]]],AXIS[\"(N)\",north,ORDER[2],LENGTHUNIT[\"metre\",1,ID[\"EPSG\",9001]]]]" ;
		msg_seviri_fes_3km:false_easting = 0. ;
		msg_seviri_fes_3km:false_northing = 0. ;
		msg_seviri_fes_3km:geographic_crs_name = "unknown" ;
		msg_seviri_fes_3km:grid_mapping_name = "geostationary" ;
		msg_seviri_fes_3km:horizontal_datum_name = "unknown" ;
		msg_seviri_fes_3km:inverse_flattening = 295.488065897014 ;
		msg_seviri_fes_3km:latitude_of_projection_origin = 0. ;
		msg_seviri_fes_3km:long_name = "msg_seviri_fes_3km" ;
		msg_seviri_fes_3km:longitude_of_prime_meridian = 0. ;
		msg_seviri_fes_3km:longitude_of_projection_origin = 0. ;
		msg_seviri_fes_3km:perspective_point_height = 35785831. ;
		msg_seviri_fes_3km:prime_meridian_name = "Greenwich" ;
		msg_seviri_fes_3km:projected_crs_name = "unknown" ;
		msg_seviri_fes_3km:reference_ellipsoid_name = "unknown" ;
		msg_seviri_fes_3km:semi_major_axis = 6378169. ;
		msg_seviri_fes_3km:semi_minor_axis = 6356583.8 ;
		msg_seviri_fes_3km:sweep_angle_axis = "y" ;
	double IR_108_acq_time(y) ;
		IR_108_acq_time:_FillValue = NaN ;
		IR_108_acq_time:long_name = "Mean scanline acquisition time" ;
		IR_108_acq_time:units = "milliseconds since 2024-05-28 10:15:25.199000" ;
		IR_108_acq_time:calendar = "proleptic_gregorian" ;
	double y(y) ;
		y:units = "m" ;
		y:standard_name = "projection_y_coordinate" ;
	double x(x) ;
		x:units = "m" ;
		x:standard_name = "projection_x_coordinate" ;
	short IR_108(y, x) ;
		IR_108:_FillValue = 0s ;
		IR_108:calibration = "brightness_temperature" ;
		IR_108:end_time = "2024-05-28 10:30:00" ;
		IR_108:georef_offset_corrected = "true" ;
		IR_108:grid_mapping = "msg_seviri_fes_3km" ;
		IR_108:modifiers = "" ;
		IR_108:nominal_end_time = "2024-05-28 10:30:00" ;
		IR_108:nominal_start_time = "2024-05-28 10:15:00" ;
		IR_108:orbital_parameters = "{\"projection_longitude\": 0.0, \"projection_latitude\": 0.0, \"projection_altitude\": 35785831.0, \"satellite_nominal_longitude\": 0.0, \"satellite_nominal_latitude\": 0.0, \"satellite_actual_longitude\": 0.14213524549124887, \"satellite_actual_latitude\": -1.0056943964497782, \"satellite_actual_altitude\": 35779889.24494431}" ;
		IR_108:platform_name = "Meteosat-10" ;
		IR_108:reader = "seviri_l1b_hrit" ;
		IR_108:resolution = 3000.403165817 ;
		IR_108:sensor = "seviri" ;
		IR_108:standard_name = "toa_brightness_temperature" ;
		IR_108:start_time = "2024-05-28 10:15:00" ;
		IR_108:time_parameters = "{\"nominal_start_time\": \"2024-05-28 10:15:00\", \"nominal_end_time\": \"2024-05-28 10:30:00\", \"observation_start_time\": \"2024-05-28 10:15:09.839000\", \"observation_end_time\": \"2024-05-28 10:27:42.214000\"}" ;
		IR_108:units = "K" ;
		string IR_108:wavelength = "10.8 µm (9.8-11.8 µm)" ;
		IR_108:coordinates = "IR_108_acq_time" ;
		IR_108:scale_factor = 0.1 ;

// global attributes:
		:history = "Created by pytroll/satpy on 2024-07-03 08:42:41.625364" ;
		:Conventions = "CF-1.7" ;
}

**Comment by gerritholl** [comment]
> The problem is that the output gives me multiple numbers such as 3712 ( number of x/y) , whereas I only want one specific timestamp. It seems as though there are no dimensions of time in the file test2.nc

I don't really understand what you mean by multiple numbers.  It is accurate that x=3712 and y=3712 as two separate dimensions.

It is a known issue that there is no direct way to include a time dimension.  At https://github.com/pytroll/satpy/issues/2428 someone has proposed a (possibly noncompliant) way to include one.

**Comment by markjinz** [comment]
> > The problem is that the output gives me multiple numbers such as 3712 ( number of x/y) , whereas I only want one specific timestamp. It seems as though there are no dimensions of time in the file test2.nc
> 
> I don't really understand what you mean by multiple numbers. It is accurate that x=3712 and y=3712 as two separate dimensions.
> 
> It is a known issue that there is no direct way to include a time dimension. At #2428 someone has proposed a (possibly noncompliant) way to include one.
The issue is that when I try to read the output in programs like MCAIDAS, for example, I find many dates, the count is 3712, instead of just one specific date supposed to be like 2024-05-28 10:15:00 .

**Comment by markjinz** [comment]
As you can see on the right side of the image, there are many dates, whereas there should be only one date, which is supposed to be 2024-05-28 10:15:00.

![mcd](https://github.com/pytroll/satpy/assets/173770504/3f2f1189-5448-4d21-b8ab-9f5919cf7d82)

**Comment by ameraner** [comment]
Looks like some comments have been removed from the issue by the OP and the description has been edited, so it's impossible to follow the discussion anymore. I'll close the issue.
