### ISSUE TITLE
  MTG LI data

### ISSUE THREAD

**Issue by markjinz** [pytroll/satpy#2855]
Hello, I have a problem reading the new data of MTG LI . When I try to combine it with HRV and create a dataset that merges the two , Code : 
**fnames={'li_l2_nc' : light_f,
        'seviri_l1b_native': seviri_f    
}
scn= Scene(filenames=fnames)
LiDc={'1': 'accumulated_flash_area' }
RgbDC={'1':  'HRV' } 
ch="%s_%s" %(LiDc['1'],RgbDC['1'])
scn.load([ch],upper_right_corner="NE")**  

I get this error :
**KeyError: "Unknown datasets: {DataQuery(name='accumulated_flash_area_HRV')}"**

**Comment by ameraner** [comment]
Hi @markjinz , 
the composite you are trying to load does not exist in satpy. It is a custom composite created inside the Eumetlab jupyter notebook environment that you're using (https://gitlab.eumetsat.int/eumetlab/weather/weather-labs/weather-labs-1/-/blob/master/Lab11_LI_data_display/LI_Data_explore.ipynb). To be able to generate the composite, you need to configure the local composites as it is done in the Eumetlab notebook, e.g. by setting the env variable (they use `os.environ['SATPY_CONFIG_PATH']="../"`) and having the according folders `composites` and `enhancements` from the Eumetlab repo in the indicated path. See also the documentation for more general info on local config setup: https://satpy.readthedocs.io/en/stable/config.html .

Note that I have a satpy PR open to include some (other) FCI/SEVIRI + LI composites, feel free to try it out and let us know the results: https://github.com/pytroll/satpy/pull/2853

**Comment by markjinz** [comment]
> Hi @markjinz , the composite you are trying to load does not exist in satpy. It is a custom composite created inside the Eumetlab jupyter notebook environment that you're using (https://gitlab.eumetsat.int/eumetlab/weather/weather-labs/weather-labs-1/-/blob/master/Lab11_LI_data_display/LI_Data_explore.ipynb)*. To be able to generate the composite, you need to configure the local composites as it is done in the Eumetlab notebook, e.g. by setting the env variable (they use `os.environ['SATPY_CONFIG_PATH']="../"`) and having the according folders `composites` and `enhancements` from the Eumetlab repo in the indicated path. See also the documentation for more general info on local config setup: https://satpy.readthedocs.io/en/stable/config.html .
> 
> Note that I have a satpy PR open to include some (other) FCI/SEVIRI + LI composites, feel free to try it out and let us know the results: #2853
> 
> *Note that these notebooks have been created and are maintained by the Eumetsat trainers, not by satpy developers. For specific issues related to those notebooks, that are not related to satpy itself, please open an issue on the Eumetsat Gitlab, or send an email to [ops@eumetsat.int](mailto:ops@eumetsat.int)

Hi @ameraner ,
Thank you for the guidance. I will certainly try out your script and provide you with feedback

**Comment by markjinz** [comment]
> > Hi @markjinz , the composite you are trying to load does not exist in satpy. It is a custom composite created inside the Eumetlab jupyter notebook environment that you're using (https://gitlab.eumetsat.int/eumetlab/weather/weather-labs/weather-labs-1/-/blob/master/Lab11_LI_data_display/LI_Data_explore.ipynb)*. To be able to generate the composite, you need to configure the local composites as it is done in the Eumetlab notebook, e.g. by setting the env variable (they use `os.environ['SATPY_CONFIG_PATH']="../"`) and having the according folders `composites` and `enhancements` from the Eumetlab repo in the indicated path. See also the documentation for more general info on local config setup: https://satpy.readthedocs.io/en/stable/config.html .
> > Note that I have a satpy PR open to include some (other) FCI/SEVIRI + LI composites, feel free to try it out and let us know the results: #2853
> > *Note that these notebooks have been created and are maintained by the Eumetsat trainers, not by satpy developers. For specific issues related to those notebooks, that are not related to satpy itself, please open an issue on the Eumetsat Gitlab, or send an email to [ops@eumetsat.int](mailto:ops@eumetsat.int)
> 
> Hi @ameraner , Thank you for the guidance. I will certainly try out your script on MSG data first and provide you with feedback .
Hello again @ameraner , I think I need some help with your script because I am now working with real-time data, and for that, I need to know how you can combine 20 chunks into one file if possible ?

**Comment by ameraner** [comment]
20 chunks of 30 seconds would correspond to 10 minutes, so you can simply change the `accumulation_window` value in my script from `minutes=5` to `minutes=10`, and it should do.

**Comment by mraspaud** [comment]
Closing this, as it looks the question has been answered.
