### ISSUE TITLE
Eliminate dependency on external binaries of PublicDecompWT (xRITDecompress) by using pyPublicDecompWT

### ISSUE THREAD

**Issue by Graenni** [pytroll/satpy#2900]
## Feature Request

**Is your feature request related to a problem? Please describe.**
Reading compressed HRIT files depends on the external binary xRITDecompress which needs to be referenced via environmental variable XRIT_DECOMPRESS_PATH. The dependency on external binaries is not preferred.

**Describe the solution you'd like**
Use Python bindings for EUMETSAT's PublicDecompWT instead:
https://pypi.org/project/pyPublicDecompWT/

By using pyPublicDecompWT the dependency on the external binary can be eliminated and reading HRIT compressed files would be easier.

The implementation seems to be straightforward.

**Comment by mraspaud** [comment]
@Graenni thanks for bringing this to our attention! I think it's a nice idea, would you be willing to give a shot at setting up a pull request for this?

**Comment by Graenni** [comment]
@mraspaud yes, I already have a solution in mind I would like to share.
