### ISSUE TITLE
save.dataset - problem with MTG

### ISSUE THREAD

**Issue by pstruzik** [pytroll/satpy#2914]
**Describe the bug**
When I process MTG FCI data,, I cannot save composite to file. I,m getting message "Memory protection violation (memory dump)".

**To Reproduce**

```python
# Your code here
from satpy.scene import Scene
from satpy.resample import get_area_def
from satpy import find_files_and_readers

dirscr = "/home/piotr/EMCinput/MTG/"
fnames=[dirstr + '/*.nc']
files = find_files_and_readers(base_dir=dirstr, reader='fci_l1c_nc')
scn = Scene(filenames=files)
composite = 'natural_color'
area = 'PS_PL'
scn.load([composite])
scn_resampled = scn.resample(area, resampler='nearest', radius_of_influence=5000)
scn_resampled.save_dataset(composite,'./MTG.png')
```

**Expected behavior**
File MTG.png saved to actual folder

**Actual results**
 message "Memory protection violation (memory dump)"

**Screenshots**

**Environment Info:**
 - OS: Ubuntu Linux
 - Satpy Version: 0.51, 0.44 (both produce the same message)
 - PyResample Version:
 - Readers and writers dependencies (when relevant): [run `from satpy.utils import check_satpy; check_satpy()`]

**Additional context**
The same code, work perfect on Windows 10 environment.

**Comment by mraspaud** [comment]
Thanks for the feedback! I never saw such an error unfortunately...
Do the two environments you mentioned have the same amount of memory?

Other reason I could think of is a broken environment...

**Comment by pstruzik** [comment]
On Windows is 16 GB RAM. On Linux is 32 GB RAM. On Linux, I process operationally MSG data without any problems  (presented on https://sat365.pl).
I have created two virtual environments with satpy 0.44 (used operationally) and newest satpy 0.51. The result is the same.
Without the line: 
scn_resampled.save_dataset(composite,'./MTG.png')
no errors are reported.

Best regards,
Piotr

**Comment by pnuu** [comment]
Even if this doesn't seem to be the case of memory running out, I suggest to try these two things to test are
* `resampler="gradient_search` (requires `shapely`)
* save to geotiff

This way both the resampler and writer are switched, so might help narrow down the source of the error. Both are more efficient than the ones now used.

**Comment by pstruzik** [comment]
I have added:
import shapely

and changed code:

composite = 'natural_color'
area = 'PS_PL'
scn.load([composite])
resampler="gradient_search"
scn_resampled = scn.resample(area, resampler='nearest', radius_of_influence=5000)
scn_resampled.save_dataset(composite,'./MTG.tif')

Result is the same:
(Pytrol10) piotr@piotr-HCAR5000-MI:~$ python3.10 Test_pytroll_MTG.py
dirstr=
/home/piotr/EMCinput/MTG/W_XX-EUMETSAT-Darmstadt,IMG+SAT,MTI1+FCI-1C-RRAD-FDHSI-FD--x-x---x_C_EUMT_20240928172415_IDPFI_OPE_20240928172007_20240928172924_N__C_0105_0000
20240928 1724 MTI1
NatCol_20240928_1724_Eu.jpg
Naruszenie ochrony pamięci (zrzut pamięci)
(Pytrol10) piotr@piotr-HCAR5000-MI:~$ python3 Test_pytroll_MTG.py
dirstr=
/home/piotr/EMCinput/MTG/W_XX-EUMETSAT-Darmstadt,IMG+SAT,MTI1+FCI-1C-RRAD-FDHSI-FD--x-x---x_C_EUMT_20240928172415_IDPFI_OPE_20240928172007_20240928172924_N__C_0105_0000
20240928 1724 MTI1
NatCol_20240928_1724_Eu.jpg
Naruszenie ochrony pamięci (zrzut pamięci)
(Pytrol10) piotr@piotr-HCAR5000-MI:~$ ^C

**Comment by pstruzik** [comment]
The whole code is:

from satpy.scene import Scene
from satpy.resample import get_area_def
from satpy import find_files_and_readers
from datetime import datetime
from PIL import Image
import glob
import warnings
import os
import shutil, sys
import aggdraw
from pydecorate import DecoratorAGG
import hdf5plugin
import pathlib, os
from pathlib import Path
import shapely

#with dask.config.set("array.chunk-size": "32MiB")
  
warnings.filterwarnings('ignore')
srcdir = "/home/piotr/EMCinput/MTG/"
imgdir = "/home/piotr/EMCdata/images/MTG/"

dir = max(pathlib.Path(srcdir).glob('*/'), key=os.path.getmtime)
#print ("sciezka:")
#print (dir)

dirstr = os.path.abspath (dir)
print ("dirstr=")
print (dirstr)

nazwa = os.path.basename (dir)
#print (nazwa)

Dataa = nazwa [74:82]
Rok= nazwa [74:78]
Mies= nazwa [78:80]
Dzien= nazwa [80:82]
Czas = nazwa [82:86]
Godz= nazwa [82:84]
Min= nazwa [84:86]
msg = nazwa [32:36]
print (Dataa, Czas, msg)

fnames=[dirstr + '/*.nc']
files = find_files_and_readers(base_dir=dirstr, reader='fci_l1c_nc')
scn = Scene(filenames=files)
#print(scn.available_dataset_names())


#Natural Color
    
plikout = 'NatCol_' + Dataa + '_' + Czas + '_Eu.jpg'
print (plikout)

composite = 'natural_color'
area = 'PS_PL'
scn.load([composite])
resampler="gradient_search"
scn_resampled = scn.resample(area, resampler='nearest', radius_of_influence=5000)
scn_resampled.save_dataset(composite,'./MTG.tif')

**Comment by pstruzik** [comment]
Sorry, two lines corrected:
#resampler="gradient_search"
scn_resampled = scn.resample(area, resampler='gradient_search', radius_of_influence=5000)

**Comment by strandgren** [comment]
Just as a sanity check, what's inside `dirstr`?

**Comment by pstruzik** [comment]
In dirstr are files dowloaded from EUMETSAT datastore by command:
./eumdac download -c EO:EUM:DAT:0662 --download-coverage Q4 --limit 1 -o /home/piotr/EMCinput/MTG

ls -l:
-rw-rw-r-- 1 piotr piotr 24951868 wrz 29 14:17 W_XX-EUMETSAT-Darmstadt,IMG+SAT,MTI1+FCI-1C-RRAD-FDHSI-FD--CHK-BODY---NC4E_C_EUMT_20240928173016_IDPFI_OPE_20240928172643_20240928172729_N__C_0105_0029.nc
-rw-rw-r-- 1 piotr piotr 22551508 wrz 29 14:19 W_XX-EUMETSAT-Darmstadt,IMG+SAT,MTI1+FCI-1C-RRAD-FDHSI-FD--CHK-BODY---NC4E_C_EUMT_20240928173020_IDPFI_OPE_20240928172701_20240928172746_N__C_0105_0030.nc
-rw-rw-r-- 1 piotr piotr 21806372 wrz 29 14:22 W_XX-EUMETSAT-Darmstadt,IMG+SAT,MTI1+FCI-1C-RRAD-FDHSI-FD--CHK-BODY---NC4E_C_EUMT_20240928173054_IDPFI_OPE_20240928172711_20240928172755_N__C_0105_0031.nc
-rw-rw-r-- 1 piotr piotr 21288420 wrz 29 14:22 W_XX-EUMETSAT-Darmstadt,IMG+SAT,MTI1+FCI-1C-RRAD-FDHSI-FD--CHK-BODY---NC4E_C_EUMT_20240928173056_IDPFI_OPE_20240928172729_20240928172803_N__C_0105_0032.nc
-rw-rw-r-- 1 piotr piotr 21646881 wrz 29 14:23 W_XX-EUMETSAT-Darmstadt,IMG+SAT,MTI1+FCI-1C-RRAD-FDHSI-FD--CHK-BODY---NC4E_C_EUMT_20240928173112_IDPFI_OPE_20240928172737_20240928172819_N__C_0105_0033.nc
-rw-rw-r-- 1 piotr piotr 20478130 wrz 29 14:23 W_XX-EUMETSAT-Darmstadt,IMG+SAT,MTI1+FCI-1C-RRAD-FDHSI-FD--CHK-BODY---NC4E_C_EUMT_20240928173112_IDPFI_OPE_20240928172811_20240928172849_N__C_0105_0035.nc
-rw-rw-r-- 1 piotr piotr 21265837 wrz 29 14:23 W_XX-EUMETSAT-Darmstadt,IMG+SAT,MTI1+FCI-1C-RRAD-FDHSI-FD--CHK-BODY---NC4E_C_EUMT_20240928173113_IDPFI_OPE_20240928172755_20240928172835_N__C_0105_0034.nc
-rw-rw-r-- 1 piotr piotr 18701634 wrz 29 14:24 W_XX-EUMETSAT-Darmstadt,IMG+SAT,MTI1+FCI-1C-RRAD-FDHSI-FD--CHK-BODY---NC4E_C_EUMT_20240928173113_IDPFI_OPE_20240928172819_20240928172856_N__C_0105_0036.nc
-rw-rw-r-- 1 piotr piotr 16716521 wrz 29 14:24 W_XX-EUMETSAT-Darmstadt,IMG+SAT,MTI1+FCI-1C-RRAD-FDHSI-FD--CHK-BODY---NC4E_C_EUMT_20240928173113_IDPFI_OPE_20240928172835_20240928172908_N__C_0105_0037.nc
-rw-rw-r-- 1 piotr piotr 14045073 wrz 29 14:24 W_XX-EUMETSAT-Darmstadt,IMG+SAT,MTI1+FCI-1C-RRAD-FDHSI-FD--CHK-BODY---NC4E_C_EUMT_20240928173120_IDPFI_OPE_20240928172849_20240928172914_N__C_0105_0038.nc
-rw-rw-r-- 1 piotr piotr 10728092 wrz 29 14:26 W_XX-EUMETSAT-Darmstadt,IMG+SAT,MTI1+FCI-1C-RRAD-FDHSI-FD--CHK-BODY---NC4E_C_EUMT_20240928173125_IDPFI_OPE_20240928172856_20240928172919_N__C_0105_0039.nc
-rw-rw-r-- 1 piotr piotr  4486674 wrz 29 14:26 W_XX-EUMETSAT-Darmstadt,IMG+SAT,MTI1+FCI-1C-RRAD-FDHSI-FD--CHK-BODY---NC4E_C_EUMT_20240928173231_IDPFI_OPE_20240928172908_20240928172924_N__C_0105_0040.nc
-rw-rw-r-- 1 piotr piotr  1401598 wrz 29 14:26 W_XX-EUMETSAT-Darmstadt,IMG+SAT,MTI1+FCI-1C-RRAD-FDHSI-FD--CHK-TRAIL---NC4E_C_EUMT_20240928172415_IDPFI_OPE_20240928172007_20240928172924_N__C_0105_0041.nc

**Comment by pstruzik** [comment]
In fact, this is to late time to produce 'Natural_color". The 'airmass' composition gives the same message. From those files, with the same script (added deco and coasts), I produced:
![Airmass_20240928_1724_Eu](https://github.com/user-attachments/assets/fe9a63d6-7b60-4b26-91ca-805c6fe6167a)
![Airmass_20240928_1724_PL](https://github.com/user-attachments/assets/cb658a69-0c36-468f-8957-28d7c67d8b37)

**Comment by pstruzik** [comment]
Presented images were produced on Windows-10 by the same script !

**Comment by pstruzik** [comment]
Regarding dirstr, I was to fast with answer. Application eumdac produce the subfolder:
W_XX-EUMETSAT-Darmstadt,IMG+SAT,MTI1+FCI-1C-RRAD-FDHSI-FD--x-x---x_C_EUMT_20240928172415_IDPFI_OPE_20240928172007_20240928172924_N__C_0105_0000

Inside this subfolder are FCI chunks 29-41 listed in my earlier message. My script finds the latest subfolder in /home/piotr/EMCinput/MTG and this  path is in dirstr.

**Comment by mraspaud** [comment]
So I don't understand the error message copied a bit higher up, but at that point it sounds really strange. I think it's worth the try recreating the environment from scratch.

**Comment by pstruzik** [comment]
When, I have unblocked warnings, I have got such warning:
<frozen importlib._bootstrap>:488: RuntimeWarning: numpy.ndarray size changed, may indicate binary incompatibility. Expected 16 from C header, got 96 from PyObject

**Comment by mraspaud** [comment]
Ok, make sure you have the latest numpy, and that the right numpy is user if you have multiple installations of it (eg conda environment vs linux installation)

**Comment by pstruzik** [comment]
I was playing with script and data and found interesting result. I have deleted all chunks without one - chunk number 38:
W_XX-EUMETSAT-Darmstadt,IMG+SAT,MTI1+FCI-1C-RRAD-FDHSI-FD--CHK-BODY---NC4E_C_EUMT_20240930120044_IDPFI_OPE_20240930115849_20240930115919_N__C_0072_0038.nc

The result was correct (originally Tif, converted to jpg):

![MTG](https://github.com/user-attachments/assets/a9c2d048-4fb6-4ae3-b6fc-52410e32c3c8)

**Comment by pstruzik** [comment]
Execution with all warnings:

(Pytroll) piotr@piotr-HCAR5000-MI:~$ python3 Test_pytroll_MTG.py
dirstr=
/home/piotr/EMCinput/MTG/W_XX-EUMETSAT-Darmstadt,IMG+SAT,MTI1+FCI-1C-RRAD-FDHSI-FD--x-x---x_C_EUMT_20240930115223_IDPFI_OPE_20240930115007_20240930115924_N__C_0072_0000
20240930 1152 MTI1
<frozen importlib._bootstrap>:488: RuntimeWarning: numpy.ndarray size changed, may indicate binary incompatibility. Expected 16 from C header, got 96 from PyObject
NatCol_20240930_1152_Eu.jpg
/home/piotr/Pytroll/lib/python3.12/site-packages/pyresample/future/geometry/_subset.py:103: PendingDeprecationWarning: The `frequency` argument is pending deprecation, use `vertices_per_side` instead
  return area_to_cover.boundary(frequency=boundary_shape, force_clockwise=True)
/home/piotr/Pytroll/lib/python3.12/site-packages/satpy/resample.py:1397: DeprecationWarning: `GradientSearchResampler` is deprecated, please use `create_gradient_search_resampler` instead.
  resampler_instance = resampler_class(source_area, destination_area)
/home/piotr/Pytroll/lib/python3.12/site-packages/pyresample/slicer.py:155: PendingDeprecationWarning: The `frequency` argument is pending deprecation, use `vertices_per_side` instead
  x, y = self.area_to_contain.get_edge_bbox_in_projection_coordinates(frequency=10)
/home/piotr/Pytroll/lib/python3.12/site-packages/pyresample/slicer.py:183: PendingDeprecationWarning: The `frequency` argument is pending deprecation, use `vertices_per_side` instead
  poly_to_crop = Polygon(zip(*self.area_to_crop.get_edge_bbox_in_projection_coordinates(frequency=10)))
(Pytroll) piotr@piotr-HCAR5000-MI:~$

**Comment by pstruzik** [comment]
I don't know, why text is crossout.

**Comment by pstruzik** [comment]
Latest contetn of the script:

from satpy.scene import Scene
from satpy.resample import get_area_def
from satpy import find_files_and_readers
from datetime import datetime
from PIL import Image
import glob
import warnings
import os
import shutil, sys
import aggdraw
from pydecorate import DecoratorAGG
import hdf5plugin
import pathlib, os
from pathlib import Path
import shapely
from pyresample import geometry

#with dask.config.set("array.chunk-size": "32MiB")
  
warnings.filterwarnings('default')
srcdir = "/home/piotr/EMCinput/MTG/"
imgdir = "/home/piotr/EMCdata/images/MTG/"

dir = max(pathlib.Path(srcdir).glob('*/'), key=os.path.getmtime)
#print ("sciezka:")
#print (dir)

dirstr = os.path.abspath (dir)
print ("dirstr=")
print (dirstr)

nazwa = os.path.basename (dir)
#print (nazwa)

Dataa = nazwa [74:82]
Rok= nazwa [74:78]
Mies= nazwa [78:80]
Dzien= nazwa [80:82]
Czas = nazwa [82:86]
Godz= nazwa [82:84]
Min= nazwa [84:86]
msg = nazwa [32:36]
print (Dataa, Czas, msg)

fnames=[dirstr + '/*.nc']
files = find_files_and_readers(base_dir=dirstr, reader='fci_l1c_nc')
scn = Scene(filenames=files)
#print(scn.available_dataset_names())


#Natural Color
     
plikout = 'NatCol_' + Dataa + '_' + Czas + '_Eu.jpg'
print (plikout)

composite = 'natural_color'
#area = 'PS_PL'
area = 'euro1'
scn.load([composite])
#scn_resampled = scn.resample(area, resampler='nearest', radius_of_influence=5000)
scn_resampled = scn.resample(area, resampler='gradient_search', radius_of_influence=5000)
scn_resampled.save_dataset(composite,'./MTG.tif')

**Comment by pstruzik** [comment]
And execution:
```
(Pytroll) piotr@piotr-HCAR5000-MI:~$ python3 Test_pytroll_MTG.py
dirstr=
/home/piotr/EMCinput/MTG/W_XX-EUMETSAT-Darmstadt,IMG+SAT,MTI1+FCI-1C-RRAD-FDHSI-FD--x-x---x_C_EUMT_20240930115223_IDPFI_OPE_20240930115007_20240930115924_N__C_0072_0000
20240930 1152 MTI1
<frozen importlib._bootstrap>:488: RuntimeWarning: numpy.ndarray size changed, may indicate binary incompatibility. Expected 16 from C header, got 96 from PyObject
NatCol_20240930_1152_Eu.jpg
/home/piotr/Pytroll/lib/python3.12/site-packages/pyresample/future/geometry/_subset.py:103: PendingDeprecationWarning: The `frequency` argument is pending deprecation, use `vertices_per_side` instead
  return area_to_cover.boundary(frequency=boundary_shape, force_clockwise=True)
/home/piotr/Pytroll/lib/python3.12/site-packages/satpy/resample.py:1397: DeprecationWarning: `GradientSearchResampler` is deprecated, please use `create_gradient_search_resampler` instead.
  resampler_instance = resampler_class(source_area, destination_area)
/home/piotr/Pytroll/lib/python3.12/site-packages/pyresample/slicer.py:155: PendingDeprecationWarning: The `frequency` argument is pending deprecation, use `vertices_per_side` instead
  x, y = self.area_to_contain.get_edge_bbox_in_projection_coordinates(frequency=10)
/home/piotr/Pytroll/lib/python3.12/site-packages/pyresample/slicer.py:183: PendingDeprecationWarning: The `frequency` argument is pending deprecation, use `vertices_per_side` instead
  poly_to_crop = Polygon(zip(*self.area_to_crop.get_edge_bbox_in_projection_coordinates(frequency=10)))
(Pytroll) piotr@piotr-HCAR5000-MI:~$
```

**Comment by pstruzik** [comment]
```
Pytrol10) piotr@piotr-HCAR5000-MI:~$ pip install numpy
Requirement already satisfied: numpy in ./Pytrol10/lib/python3.10/site-packages (2.1.1)
```

**Comment by pstruzik** [comment]
Sorry, last message was from the second environment where I tried Python 10.
In first environment, I have Python 12.3
```
(Pytroll) piotr@piotr-HCAR5000-MI:~$ pip install numpy
Requirement already satisfied: numpy in ./Pytroll/lib/python3.12/site-packages (2.0.0)
```
and different version ov numpy. The processing results are the same.

**Comment by mraspaud** [comment]
Can you try changing the numpy version to 1.x to see if it helps?

**Comment by mraspaud** [comment]
ok, so I'm still worried about the numpy binary compatibility. Would it be possible for you to install pyresample from source and rebuild the cython extension to see if it helps?

**Comment by djhoese** [comment]
Not that the numpy warning shouldn't be dealt with in the long run, but we used to get that all the time. I'm less concerned about that. I'm wondering if this memory protection violation is actually just coming from running out of memory on your machine. I haven't read this entire thread so sorry if this has already been discussed.

**Comment by mraspaud** [comment]
@djhoese to summarize, the linux with 32GB memory doesn't work, while the windows with 16GB works.

**Comment by pstruzik** [comment]
Problem was solved (;-).
I have installed the same versions od numpy and netCDF4 as on Windows:
numpy 1.26.4
netCDF4 1.6.3

Result:
![MTG_Eu](https://github.com/user-attachments/assets/45763f9d-4b53-4647-b4f2-419e1dc590e2)

**Comment by mraspaud** [comment]
Great that you got it to work!
So you think it's the numpy version which is the problem, or the netcdf4?

**Comment by pstruzik** [comment]
First, I installed netCDF4 1.6.3 but was conflict with numpy. After installation of numpy 1.26.4 everything was OK. I am testing now different composition and areas. No problems until now !

**Comment by mraspaud** [comment]
Do you know what versions of numpy and netcdf4 you had when it crashed?

**Comment by pstruzik** [comment]
netCDF4 1.7.1
numpy 2.1.1

**Comment by mraspaud** [comment]
Thanks, we will try this locally.

**Comment by pstruzik** [comment]
Thanks for constructive discussion.

**Comment by mraspaud** [comment]
Someone in the community tried with the netcdf 1.7.1 and numpy 2.1.1 and didn't have any problems... So maybe it's something else. Anyway, as it seems to work for you now, I'm closing this issue for now.

**Comment by Darxeal** [comment]
I also had a problem with `fci_l1c_nc` crashing.
Downgrading netCDF4 to 1.6.3 also solved the issue for me.
