### ISSUE TITLE
fci_l1c_nc reader ignoring MTG FDHSI segment 41

### ISSUE THREAD

**Issue by valpamp** [pytroll/satpy#2922]
**Describe the bug**
I am using satpy to process EUMETCast Satellite MTG FDHSI data. Everything seems to work like it should, but I noticed that find_files_and_readers only returns segments up to number 40 for each cycle. I noticed this after I enabled my cleanup routine, which relies on the filenames returned by the reader to tell which files it should delete after the processing is complete. This basically resulted in an accumulation of segment 41 files in my "received" directory, and after that I noticed that the reader never included them in the file list in the first place.

Product resampling and saving works normally, since segment 41 is the northernmost segment and probably contains a small amount of usable data at the North Pole.

My question is: is this expected behaviour? I tried looking into the fci_l1c_nc.yaml, and given the file_patterns it looks like segment 41 should indeed be found by the reader function. I also noticed that the expected_segments field is set to 40 rather than 41, but even changing this had no effect.

**To Reproduce**

- Download a complete cycle of MTG FDHSI files from EUMETCast Satellite or from the EUMETCast Data Store
- Load the files using the find_files_and_readers function and the fci_l1c_nc reader
- Check the file count

**Expected behavior**
I would expect the reader to find all 41 segments.

**Actual results**
All segments except the 41st are found.

**Screenshots**
Folder content (41 files, full cycle)
![image](https://github.com/user-attachments/assets/9afd913c-8640-4ab4-ba88-d0f04a8bd5e1)

find_files_and_readers output (40 files, all except segment 41)
![image](https://github.com/user-attachments/assets/b3d73a98-42f5-40bc-99c1-a6e02221cb77)

**Environment Info:**
 - OS: Windows 10 21H2 (OS Build 19044.4651)
 - Satpy Version: 0.51.0 (conda-forge)
 - PyResample Version:
 - Readers and writers dependencies (when relevant):
```
fci_l1c_nc:  ok
fci_l2_bufr:  cannot find module 'satpy.readers.eum_l2_bufr' (Missing eccodes-python and/or eccodes C-library installation. Use conda to install eccodes)
fci_l2_nc:  ok
```

**Additional context**
Maybe I missed the memo and there is a specific reason as to why the final segment is ignored.

**Comment by gerritholl** [comment]
The final segment is the TRAIL segment.  It contains no radiances and indeed no information that Satpy needs and indeed Satpy cannot read it.  The northernmost segment is BODY segment 40.  You will have to find a different way to remove the TRAIL segments.

**Comment by valpamp** [comment]
> The final segment is the TRAIL segment. It contains no radiances and indeed no information that Satpy needs and indeed Satpy cannot read it. The northernmost segment is BODY segment 40. You will have to find a different way to remove the TRAIL segments.

Thanks a lot, I wanted to make sure that there was nothing else going on. Closing the issue.
