### ISSUE TITLE
Load metadata without loading data

### ISSUE THREAD

**Issue by djhoese** [pytroll/satpy#33]
It would be beneficial to users of satpy and for code clarity if satpy reader's could load the metadata for a dataset without having to load the data.

1. If a user loads just the metadata first, how do they then ask for the data?
2. How does satpy use previously loaded metadata when data is loaded? Does it waste the time to recompute it? Cache? Where is it cached? Caching in the main level reader probably makes the most sense since it would have the fully combined/merged metadata and could then take the concatenated data arrays and create a new Dataset object.
3. What happens to areas? Are they loaded with the rest of the metadata? Is there another keyword to load only metadata but not with areas? What's the default?

Any other issues with trying to make this work?

**Comment by davidh-ssec** [comment]
@mindysu and @jsolbrig may be able to help with "gotchas" for doing this. Their GeoIPS software (similar to Polar2Grid and SatPy) already has a two step loading process for metadata and image data. Hopefully in the next couple weeks I can find time to work on this and propose some interfaces.

**Comment by djhoese** [comment]
This is technically resolved with our use of dask in SatPy 0.9 (currently in alpha). Now that a user can do everything up to the point of actually writing output to disk without actually loading/computing data there is no reason to load metadata separately.
