### ISSUE TITLE
`available_readers` to detail unavailable items

### ISSUE THREAD

**Issue by mraspaud** [pytroll/satpy#333]
**Is your feature request related to a problem? Please describe.**
As a debugging feature, it would be really helpful to have `available_readers` detail the reason why the unavailable reader aren't available.

**Describe the solution you'd like**
A possible solution would be to print out the error happening upon attempting to load the unavailable readers.

**Describe any changes to existing user workflow**
As this is a purely for debugging purposes, no changes in the workflow will happen.

**Additional python or other dependencies**
No additional dependencies

**Describe any changes required to the build process**
No changes to the build process

**Describe alternatives you've considered**
No alternatives.

**Additional context**
No context.

**Comment by djhoese** [comment]
Would this be a keyword argument? Would the errors be put in to debug/error log messages or in the returned value somehow? If log messages then I suppose it could always log the reasons?

**Comment by djhoese** [comment]
This has been fixed by @mraspaud by adding the `check_satpy` utility function.
