### ISSUE TITLE
No image is shown in Jupyter notebook via scene.show()

### ISSUE THREAD

**Issue by adybbroe** [pytroll/satpy#347]
**Describe the bug**
In Jupyter notebook the code `scene.show()` does nothing. It is quickly terminated, and no image (neither inline) is shown. 

**To Reproduce**

```python
scene.show()

```

...in a notebook

**Expected behavior**
Image should be shown somewhere!

**Actual results**
No image is shown - code does nothing

**Environment Info:**
Jupyter notebook under Python 2.7

**Comment by djhoese** [comment]
What do you get with:
```
from satpy.utils import in_ipynb
in_ipynb()
```

What happens with python 3.6?

**Comment by djhoese** [comment]
This should now be fixed now that I've released the most recent version of trollimage (currently building).
