### ISSUE TITLE
Warning without problem for NWC SAF products

### ISSUE THREAD

**Issue by khunger** [pytroll/satpy#36]
The product ct and ct_pal are read corectly and the logging ends with the warning "The following datasets were not created:" but no product is listed.

[DEBUG: 2017-03-29 08:08:16 : satpy.readers.nc_nwcsaf_msg] Reading ct.
[DEBUG: 2017-03-29 08:08:16 : satpy.readers.yaml_reader] No coordinates found for DatasetID(name='ct_pal', wavelength=None, resolution=3000, polarization=None, calibration=None, modifiers=())
[DEBUG: 2017-03-29 08:08:16 : satpy.readers.nc_nwcsaf_msg] Reading ct_pal.
[WARNING: 2017-03-29 08:08:16 : satpy.scene] The following datasets were not created:

**Comment by davidh-ssec** [comment]
Thanks @khunger. I've fixed this in the `develop` branch now. It is a little annoying to get a WARNING when everything goes to plan.
