### ISSUE TITLE
Unable to load individual channels from VIIRS_SDR data.

### ISSUE THREAD

**Issue by Krangaas** [pytroll/satpy#364]
#### Code Sample, a minimal, complete, and verifiable piece of code

import numpy as np
from glob import glob
from satpy import Scene
from satpy.utils import debug_on
debug_on()

FILES = glob("C:\scrypts\K11\*.h5")
global_scene = Scene(reader = "viirs_sdr", filenames=FILES)
print(global_scene.available_dataset_names())
global_scene.load(["M01"])
print(global_scene)

#### Problem description

After updating from satpy version 0.8.4 to version 0.9.0 I'm unable to load channels like "M01" and "I01", loading up "DNB" channel works fine though. There seems to be an issue with dimension sizes? 

I downloaded my data from [NOAA](https://www.bou.class.noaa.gov/saa/products/search?sub_id=0&datatype_family=VIIRS_SDR&submit.x=20&submit.y=6). 
#### Expected Output

A printout of the channel attributes like for example wavelength.

#### Actual Result, Traceback if applicable

[DEBUG: 2018-07-11 12:36:22 : satpy.scene] Setting 'PPP_CONFIG_DIR' to 'C:\Users\magnus\Anaconda2\lib\site-packages\satpy\etc'
[DEBUG: 2018-07-11 12:36:22 : satpy.readers] Reading 
['C:\\Users\\magnus\\Anaconda2\\lib\\site-packages\\satpy\\etc\\readers\\viirs_sdr.yaml',
 'C:\\Users\\magnus\\Anaconda2\\lib\\site-packages\\satpy\\etc\\readers\\viirs_sdr.yaml', 
 'C:\\Users\\magnus\\Anaconda2\\lib\\site-packages\\satpy\\etc\\readers\\viirs_sdr.yaml']
[DEBUG: 2018-07-11 12:36:23 : satpy.readers.yaml_reader] Assigning to viirs_sdr: 
['C:\\scrypts\\K11\\SVM05_npp_d20180624_t0049137_e0054541_b34485_c20180624065455405793_nobc_ops.h5',
 'C:\\scrypts\\K11\\SVM04_npp_d20180624_t0049137_e0054541_b34485_c20180624065455390778_nobc_ops.h5',
 'C:\\scrypts\\K11\\SVM07_npp_d20180624_t0049137_e0054541_b34485_c20180624065455422310_nobc_ops.h5',
 'C:\\scrypts\\K11\\SVM06_npp_d20180624_t0049137_e0054541_b34485_c20180624065455415178_nobc_ops.h5',
 'C:\\scrypts\\K11\\SVM01_npp_d20180624_t0049137_e0054541_b34485_c20180624065455287714_nobc_ops.h5',
 'C:\\scrypts\\K11\\SVM03_npp_d20180624_t0049137_e0054541_b34485_c20180624065455381293_nobc_ops.h5',
 'C:\\scrypts\\K11\\SVM02_npp_d20180624_t0049137_e0054541_b34485_c20180624065455371151_nobc_ops.h5',
 'C:\\scrypts\\K11\\SVM09_npp_d20180624_t0049137_e0054541_b34485_c20180624065455443353_nobc_ops.h5',
 'C:\\scrypts\\K11\\SVM08_npp_d20180624_t0049137_e0054541_b34485_c20180624065455432721_nobc_ops.h5',
 'C:\\scrypts\\K11\\GITCO_npp_d20180624_t0049137_e0054541_b34485_c20180624065455552882_nobc_ops.h5',
 'C:\\scrypts\\K11\\SVDNB_npp_d20180624_t0049137_e0054541_b34485_c20180624065455154596_nobc_ops.h5',
 'C:\\scrypts\\K11\\GMTCO_npp_d20180624_t0049137_e0054541_b34485_c20180624065455424255_nobc_ops.h5',
 'C:\\scrypts\\K11\\SVM16_npp_d20180624_t0049137_e0054541_b34485_c20180624065455361229_nobc_ops.h5',
 'C:\\scrypts\\K11\\SVM14_npp_d20180624_t0049137_e0054541_b34485_c20180624065455344773_nobc_ops.h5',
 'C:\\scrypts\\K11\\SVM15_npp_d20180624_t0049137_e0054541_b34485_c20180624065455353654_nobc_ops.h5',
 'C:\\scrypts\\K11\\SVM12_npp_d20180624_t0049137_e0054541_b34485_c20180624065455315513_nobc_ops.h5',
 'C:\\scrypts\\K11\\SVM13_npp_d20180624_t0049137_e0054541_b34485_c20180624065455331094_nobc_ops.h5',
 'C:\\scrypts\\K11\\SVM10_npp_d20180624_t0049137_e0054541_b34485_c20180624065455296521_nobc_ops.h5',
 'C:\\scrypts\\K11\\SVM11_npp_d20180624_t0049137_e0054541_b34485_c20180624065455303681_nobc_ops.h5',
 'C:\\scrypts\\K11\\GIMGO_npp_d20180624_t0049137_e0054541_b34485_c20180624065455577953_nobc_ops.h5',
 'C:\\scrypts\\K11\\GMODO_npp_d20180624_t0049137_e0054541_b34485_c20180624065455458524_nobc_ops.h5',
 'C:\\scrypts\\K11\\SVI01_npp_d20180624_t0049137_e0054541_b34485_c20180624065455465174_nobc_ops.h5',
 'C:\\scrypts\\K11\\SVI03_npp_d20180624_t0049137_e0054541_b34485_c20180624065455499403_nobc_ops.h5',
 'C:\\scrypts\\K11\\SVI02_npp_d20180624_t0049137_e0054541_b34485_c20180624065455486675_nobc_ops.h5',
 'C:\\scrypts\\K11\\SVI05_npp_d20180624_t0049137_e0054541_b34485_c20180624065455555451_nobc_ops.h5',
 'C:\\scrypts\\K11\\SVI04_npp_d20180624_t0049137_e0054541_b34485_c20180624065455527492_nobc_ops.h5',
 'C:\\scrypts\\K11\\GDNBO_npp_d20180624_t0049137_e0054541_b34485_c20180624065455133496_nobc_ops.h5']
[DEBUG: 2018-07-11 12:36:23 : satpy.composites] Looking for composites config file viirs.yaml
[DEBUG: 2018-07-11 12:36:23 : satpy.composites] Looking for composites config file visir.yaml
['DNB', 'I01', 'I02', 'I03', 'I04', 'I05', 'M01', 'M02', 'M03', 'M04', 'M05', 'M06', 'M07', 'M08','M09',
 'M10', 'M11', 'M12', 'M13', 'M14', 'M15', 'M16', 'dnb_latitude', 'dnb_longitude','dnb_lunar_zenith_angle',
 'dnb_moon_illumination_fraction', 'dnb_solar_zenith_angle', 'i_latitude','i_longitude','m_latitude',
 'm_longitude', 'satellite_azimuth_angle', 'satellite_zenith_angle', 'solar_azimuth_angle', 'solar_zenith_angle']
[DEBUG: 2018-07-11 12:36:24 : satpy.readers.yaml_reader] No coordinates found for DatasetID(name='m_latitude', wavelength=None, resolution=742, polarization=None, calibration=None, level=None, modifiers=())
[DEBUG: 2018-07-11 12:36:24 : satpy.readers.viirs_sdr] No scaling factors found for DatasetID(name='m_latitude',
 wavelength=None, resolution=742, polarization=None, calibration=None, level=None, modifiers=())
[DEBUG: 2018-07-11 12:36:24 : satpy.readers.viirs_sdr] Unknown units for file key 'DatasetID(name='m_latitude', wavelength=None, resolution=742, polarization=None, calibration=None, level=None, modifiers=())'
[DEBUG: 2018-07-11 12:36:24 : satpy.readers.yaml_reader] No coordinates found for DatasetID(name='m_longitude', wavelength=None, resolution=742, polarization=None, calibration=None, level=None, modifiers=())
[DEBUG: 2018-07-11 12:36:24 : satpy.readers.viirs_sdr] No scaling factors found for DatasetID(name='m_longitude', wavelength=None, resolution=742, polarization=None, calibration=None, level=None, modifiers=())
[DEBUG: 2018-07-11 12:36:24 : satpy.readers.viirs_sdr] Unknown units for file key 'DatasetID(name='m_longitude', wavelength=None, resolution=742, polarization=None, calibration=None, level=None, modifiers=())'
[DEBUG: 2018-07-11 12:36:24 : satpy.readers.viirs_sdr] Adjusting scaling factors to convert '1' to '%'
[ERROR: 2018-07-11 12:36:24 : satpy.readers.yaml_reader] Could not load dataset 'DatasetID(name='M01', wavelength=(0.402, 0.412, 0.422), resolution=742, polarization=None, calibration='reflectance', level=None, modifiers=('sunz_corrected',))':
 arguments without labels along dimension 'y' cannot be aligned because they have different dimension sizes: set([3072, 768L])
Traceback (most recent call last):
  File "C:\Users\magnus\Anaconda2\lib\site-packages\satpy\readers\yaml_reader.py", line 721, in _load_dataset_with_area
    ds = self._load_dataset_data(file_handlers, dsid, **slice_kwargs)
  File "C:\Users\magnus\Anaconda2\lib\site-packages\satpy\readers\yaml_reader.py", line 575, in _load_dataset_data
    proj = self._load_dataset(dsid, ds_info, file_handlers)
  File "C:\Users\magnus\Anaconda2\lib\site-packages\satpy\readers\yaml_reader.py", line 547, in _load_dataset
    projectable = fh.get_dataset(dsid, ds_info)
  File "C:\Users\magnus\Anaconda2\lib\site-packages\satpy\readers\viirs_sdr.py", line 263, in get_dataset
    data = self.scale_swath_data(data, factors)
  File "C:\Users\magnus\Anaconda2\lib\site-packages\satpy\readers\viirs_sdr.py", line 203, in scale_swath_data
    data = data * factors[:, 0] + factors[:, 1]
  File "C:\Users\magnus\Anaconda2\lib\site-packages\xarray\core\dataarray.py", line 1805, in func
    self, other = align(self, other, join=align_type, copy=False)
  File "C:\Users\magnus\Anaconda2\lib\site-packages\xarray\core\alignment.py", line 154, in align
    % (dim, sizes))
ValueError: arguments without labels along dimension 'y' cannot be aligned because they have different dimension sizes: set([3072, 768L])
[WARNING: 2018-07-11 12:36:24 : satpy.scene] The following datasets were not created: DatasetID(name='M01', wavelength=(0.402, 0.412, 0.422), resolution=742, polarization=None, calibration='reflectance', level=None, modifiers=('sunz_corrected',))

#### Versions of Python, package at hand and relevant dependencies

OS: Windows 7
SatPy Version: 0.9.0
PyResample Version: 1.10.1
Python version: 2.7

**Comment by Krangaas** [comment]
Sorry my bad, I'm on version 0.9.0.

**Comment by djhoese** [comment]
@Krangaas I just tested this on my own data and it works for me. My data is a single granule for a single band in each file. Is there a chance that your data is aggregated (multiple granules per file)? It's possible the functionality to read that data has not been migrated to work with xarray/dask.

**Comment by Krangaas** [comment]
How would I go about finding out if my data is aggregated? Is the data downloaded from NOAA aggregated?

**Comment by djhoese** [comment]
Usually there is a check box when you order data to say whether or not you want it aggregated. Judging by the filename I think yours are aggregated. My files have times like `t1801245_e1802487`, much shorter than yours. From what I can tell this looks like it is supposed to be working so I would consider this a bug. I'll have to find some aggregated files in my own set of files to test this and find time to actually fix it. If you have time to look in to it I can point you in the right direction. I'm hoping it is just a typo.

**Comment by Krangaas** [comment]
I had a look around the NOAA product ordering page and couldn't find a checkbox to toggle aggregating, I have some time to look into it right now if you have any ideas.

**Comment by djhoese** [comment]
This method of the VIIRS SDR reader should be the starting point: https://github.com/pytroll/satpy/blob/master/satpy/readers/viirs_sdr.py#L193

This is supposed to already handle repeating the factors to cover the entire data array, but obviously something isn't working. Either your data files are corrupt or in a way that was not expected or this code is wrong. I guess it depends what the shape of the factors variable is going in to the function.

**Comment by Krangaas** [comment]
I think I previously toggled off de-aggregation when ordering the data from NOAA, I'll redownload the data with de-aggregation on now.

**Comment by Krangaas** [comment]
I redownloaded the data, made sure it was de-aggregated and it worked. thanks for the help!
