### ISSUE TITLE
Sentinel 3 SLSTR reading the solar/viewing angles fails

### ISSUE THREAD

**Issue by RutgerK** [pytroll/satpy#366]
When using the `nc_slstr` reader the solar and viewing angles aren't loaded properly. 

Given a loaded SLSTR scene, the available datasets are:
```python
scn.available_dataset_names()

['S1', 'S2', 'S3', 'S4', 'S5', 'S6', 'S7', 'S8', 'S9', 'latitude', 'longitude', 
'satellite_azimuth_angle', 'satellite_zenith_angle', 'solar_azimuth_angle', 
'solar_zenith_angle']
```` 
But indexing the scene with `scn['solar_azimuth_angle']` results in a `KeyError`.

After digging around a bit I noticed three issues. 

First, there is a "mapper dictionary" for the datatset names  in the `NCSLSTRAngles` class which looks like:

```python
    datasets = {'satellite_azimuth_angle': 'satellite_azimuth_t' + view,
                'satellite_zenith_angle': 'satellite_zenith_t' + view,
                'solar_azimuth_angle': 'solar_azimuth_t' + view,
                'solar_zenith_angle': 'solar_zenith_t' + view}
```

Based on the SLSTR products I have this should be `sat_`, instead of `satellite_`:

```python
    datasets = {'satellite_azimuth_angle': 'sat_azimuth_t' + view,
                'satellite_zenith_angle': 'sat_zenith_t' + view,
                'solar_azimuth_angle': 'solar_azimuth_t' + view,
                'solar_zenith_angle': 'solar_zenith_t' + view}
```

Secondly, the `_FillValue` attribute doesn't exist for the `geometry_tn.nc`, and also not for the `cartesian_*.nc` products. The missing values have are filled with `NaN`, so this could be fixed with:

`variable.attrs.get('_FillValue', np.nan)`

That would still use the `_FillValue` attribute if it's present in the attributes of the dataset, and otherwise assume `np.nan`.

Lastly, the `NCSLSTRAngles` class returns what looks like a deprecated `Dataset` class, but SatPy seems to expect an `xarray` dataset. By peaking at the OLCI reader, I changed the old code:

```python
        proj = Dataset(values,
                       copy=False,
                       units=units,
                       platform_name=self.platform_name,
                       standard_name=variable.attrs['standard_name'],
                       sensor=self.sensor)
        return proj
```
to:
```python
        proj = xr.DataArray(da.from_array(values, chunks=(CHUNK_SIZE, CHUNK_SIZE)),
                            dims=['y', 'x'])

        proj.attrs['platform_name'] = self.platform_name
        proj.attrs['sensor'] = self.sensor

        proj.attrs.update(key.to_dict())

        return proj
```

I made a branch on my fork which has these changes implemented, but i'm not sure if i fixed everything conform the SatPy standards:
https://github.com/RutgerK/satpy/tree/fix_slstr

Additionally that branch also uses `os.path.sep` in the `yaml reader` which is necessary on Windows,  otherwise SatPy won't find any files:

These are some of the files I tried this on:
```
S3A_SL_1_RBT____20180628T102931_20180628T103231_20180629T155259_0179_033_008_2700_LN2_O_NT_003.SEN3
S3A_SL_1_RBT____20180629T100320_20180629T100620_20180630T152011_0179_033_022_2700_LN2_O_NT_003.SEN3
S3A_SL_1_RBT____20180630T093709_20180630T094009_20180701T151640_0179_033_036_2700_LN2_O_NT_003.SEN3
S3A_SL_1_RBT____20180702T102546_20180702T102846_20180703T150049_0179_033_065_2700_LN2_O_NT_003.SEN3
```

**Environment Info:**
 - OS: Window 10 64bit
 - SatPy Version: 0.9.0 (py35)
 - PyResample Version: 1.10.0  (py35)

**Comment by djhoese** [comment]
I think this is one of the readers that has not been converted to using xarray/dask. It is *supposed* to raise an ImportError and not be available instead of trying to let you use it. I might have screwed that up with some of my last minute commits before the 0.9.0 release. Does your use case now work with your branch? I would suggest making a pull request.

However, your changes for `os.path.sep` shouldn't be needed. I think we try to assume that `/` is the separator in the file patterns provided in the reader's YAML files so `/` should always be used and we don't want to use `sep` because this would make some readers work on some platforms and not work on others.

**Comment by RutgerK** [comment]
Without the `os.path.sep` it doesn't find any files for me, with it it does. I'll try some different ways of specifying my `base_dir` to see if there might be away around it without the change. In any case its a separate issue of that of the SLSTR reader and since it impacts all readers something that should be tested thoroughly for different use cases, not just my Sentinel tries.

I think the SLSTR readers was almost entirely converted for use with xarray. The radiance and brightness bands work out of the box with 0.9, just not the angle bands, which are handled in a different class. And even that class reads them with xarray, it only returns a `Dataset` object instead of an xarray dataset.

I don't mind doing a pull request, just for the reader. But what holds me back is the fact that at some point someone probably was able to use the reader successfully. So I would want to know why I had slightly different named attributes and the missing "fillvalue"attribute. If for example ESA updated the format, changing it would be a good thing. But if someone is using a different product type, changing it will break it for someone else.

For as far a I know I picked the most standard level 1 product there is (S3A_SL_1_RBT). But I can download some other formats tomorrow and check their attributes.

**Comment by djhoese** [comment]
@RutgerK Good points. @mraspaud looks like the last person to have worked on the reader but he is on holiday for a couple more weeks. Maybe if he checks his email he can give us some more information.

For the `sep` thing: your specific change is using the `pattern` that comes from the YAML files. So those specified here: https://github.com/pytroll/satpy/blob/master/satpy/etc/readers/nc_slstr.yaml#L14
Would you mind printing out what the pattern is when you run it and see if that is not the case?

**Comment by RutgerK** [comment]
I checked a few different products, there are actually not that many at this time. All are consistent in their naming and available attributes.

These are some products with a very old and new processing date (collection 002, and 003). Different receiving station and different "timeliness".

```

S3A_SL_1_RBT____20170824T100224_20170824T100524_20170825T141008_0179_021_236_1980_LN2_O_NT_002.SEN3
Variable          Attributes
sat_azimuth_tn    ['long_name', 'standard_name', 'units']
sat_path_tn       ['long_name', 'units']
sat_zenith_tn     ['long_name', 'standard_name', 'units']
solar_azimuth_tn  ['long_name', 'standard_name', 'units']
solar_path_tn     ['long_name', 'units']
solar_zenith_tn   ['long_name', 'standard_name', 'units']


S3A_SL_1_RBT____20180711T094006_20180711T094306_20180711T115509_0179_033_193_1980_SVL_O_NR_003.SEN3
Variable          Attributes
sat_azimuth_tn    ['long_name', 'standard_name', 'units']
sat_path_tn       ['long_name', 'units']
sat_zenith_tn     ['long_name', 'standard_name', 'units']
solar_azimuth_tn  ['long_name', 'standard_name', 'units']
solar_path_tn     ['long_name', 'units']
solar_zenith_tn   ['long_name', 'standard_name', 'units']


S3A_SL_1_RBT____20180711T094006_20180711T094306_20180712T134930_0179_033_193_1980_LN2_O_NT_003.SEN3
Variable          Attributes
sat_azimuth_tn    ['long_name', 'standard_name', 'units']
sat_path_tn       ['long_name', 'units']
sat_zenith_tn     ['long_name', 'standard_name', 'units']
solar_azimuth_tn  ['long_name', 'standard_name', 'units']
solar_path_tn     ['long_name', 'units']
solar_zenith_tn   ['long_name', 'standard_name', 'units']
```
Made with:
https://gist.github.com/RutgerK/e779ff44ea39bfe3866b545090bff339

I also quickly scanned the news items, the only product format change I could find was:
https://scihub.copernicus.eu/news/News00321

In the detailed PDF they don't mention anything about variable names or attributes. 

Lets wait and see if @mraspaud comes up with something.

**Comment by mraspaud** [comment]
@RutgerK Thanks for reporting this issue. I was probably in a rush when implementing the angles, so I only tested solar angles, not satellite angles.

From what I can see, the satellite angles should indeed be `sat_`*.

Also, as you say, the `Dataset` object should be replaced by an `xarray.DataArray` instance.

A PR would be really great, thanks !

Don't hesitate to ping me here or on slack. I may be on holidays, but check the messages at least every other day.

**Comment by RutgerK** [comment]
Thanks for confirming, I'll make a PR tomorrow. The branch is basically done already but I have to remove my separator hack for the yaml reader. Enjoy your holiday.
