### ISSUE TITLE
Add 'to_xarray_dataset' method to Scene

### ISSUE THREAD

**Issue by djhoese** [pytroll/satpy#367]
**Is your feature request related to a problem? Please describe.**
The Scene object was built and designed to replacing existing interfaces coming from satpy's predecessor mpop. However, now that we have switched to using xarray.DataArray objects as our main data containers we could and probably should switch to using xarray.Dataset objects (http://xarray.pydata.org/en/stable/generated/xarray.Dataset.html).

**Describe the solution you'd like**
Add a `Scene.to_xarray_dataset` or maybe `Scene.to_dataset` method that returns an xarray Dataset object from the loaded datasets.

**Describe any changes to existing user workflow**
Additional optional method right now that doesn't need to be used for anything. We *could* use this in the future to separate out the Scene -> writer interface so that writers are more xarray-specific (read: generic) and not Scene specific.

**Additional python or other dependencies**
None

**Describe any changes required to the build process**
None

**Describe alternatives you've considered**
It has been on my radar for a while that we could/should replace the Scene object with a Dataset object, but right now there is too much functionality inside the Scene object to do this smoothly.

**Comment by gerritholl** [comment]
This already exists...?  Wis there some PR that should have closed this but didn't?

**Comment by djhoese** [comment]
The referenced one above did it, #541.
