### ISSUE TITLE
Add ability to set output image size for `Scene.show`

### ISSUE THREAD

**Issue by djhoese** [pytroll/satpy#368]
**Is your feature request related to a problem? Please describe.**
Using the show method in a jupyter notebook creates a PNG image that is the same size as the original dataset. Sometimes people want a small quicklook, not a complete full resolution representation of the data.

**Describe the solution you'd like**
Add a `size=None` keyword parameter that takes `(width, height)` tuple to specify the size of the output image. Not sure how exactly the resizing should be done (striding/slicing, Pillow method?, etc).

**Describe any changes to existing user workflow**
None. Optional new keyword argument.

**Additional python or other dependencies**
None.

**Describe any changes required to the build process**
No.

**Describe alternatives you've considered**
We could also add a `persist=False` keyword which would automatically call `persist()` on the dask array underneath a dataset before running it through the enhancement step so that any computations aren't wasted.

**Comment by roshgor** [comment]
Hi. If this is open, can I take it up?

**Comment by djhoese** [comment]
@roshgor I don't think anyone has tried to tackle this so feel free. Do you have any idea how you plan to implement it? Would you generate the full image and then ask Pillow to resize it? Or would you try to use something like `Scene.aggregate` to average the pixels to a smaller size? Or something else?
