### ISSUE TITLE
Slicing failed for 'Europe Canary' area

### ISSUE THREAD

**Issue by meteoswiss-mdr** [pytroll/satpy#37]
Providing the area argument for a scene object (tested for the MTG-LI reader) results in a wrong result array slice when using the area *Europe Canary*. In contrast the *eurol* area works correctly. It seems, that the slice is cutting at the middle of the image and return only the lower part (Look at the attached image). The sliced part is in white.
![satpy_slicing_europecanary_mtgli](https://cloud.githubusercontent.com/assets/16132533/24497011/b177850c-1542-11e7-84af-831b48b27614.png)

**Comment by m4sth0** [comment]
Closed with commit 371291928ce
