### ISSUE TITLE
Extend Sentinel 3 SLSTR reader to read oblique angle and cloud mask flags

### ISSUE THREAD

**Issue by egede** [pytroll/satpy#393]
Is there a reason that the nc_slstr` reader is not able to read the oblique view from SLSTR? Also the ability to read the cloud mask flags is not there? To enhance the reader with this seems to be fairly easy to implement.

**Comment by egede** [comment]
Thanks for the quick reply. I only just became aware of `satpy` and will most likely convert to use that instead. I will create a pull request when there is something to look at. I am also aware of #371.

**Comment by mraspaud** [comment]
@RutgerK your analysis is correct. One more option which I tend to like it to add the view to the DatasetID named tuple somehow, like we have for the polarisation. Now, either we just add it to the tuple statically, or rather we switch the DatasetID to something dynamic which is created on demand from the attributes of the DataArray object. @djhoese and I talked about this a while ago, I would need to go quite deep in the satpy code, but I don't think it is necessarily complicated. Care to to chime on this @djhoese ?

**Comment by djhoese** [comment]
I'm not super familiar with this instrument/data, but I'll assume that each view provides a whole swath of data. So each view is technically a separate product.

Of the options discussed I think the three "best" are:

1. Add a suffix to datasets for the other/new views (ex. `S1o` or `S1_oblique`)
2. Add a 'view' or equivalent parameter to the DatasetID
3. Rewrite/finalize the query-based DatasetID replacement

I vote for 1 as the short term solution. It is the easiest thing that doesn't affect anyone else. Number 2 seems like a good solution for the overall issue, but the wrong way of implementing it. I feel like there may be a bigger problem involved here that isn't completely clear yet. Like polarization and views and maybe even pressure levels are very similar problems that should have the same solution. I'm not sure yet if that means a different parameter in the DatasetID for each or if they can be combined. Of course if they get combined then suddenly you have combinations of them like a nadir view with two polarizations.

@mraspaud if you have time to try 3 and some examples of how you think it would be used by the user...good luck 😉 I'm not against it, I just don't want to dedicate the brain time to think about it with all the other things I want to add/change in satpy.

**Comment by djhoese** [comment]
I should also note that I have tried both 1 and 2 for different readers. The "grib" reader currently uses a "level" parameter which I added to DatasetID. It is flawed because it currently forces hPa as the units of the levels, but that doesn't work for all readers and doesn't even work for all common grib datasets.

The "nucaps" reader uses suffixes like `_100mb` but also provides 3D datasets so `Temperature` is 3D, but `Temperature_100mb` is just that one pressure level. You can also filter what levels are returned by providing the reader additional keyword arguments like `pressure_levels=[100, 500]` for levels between 100mb and 500mb.

**Comment by egede** [comment]
Implementing the oblique view with a suffix is as said fairly straight forward and I will have a go at that. For the cloud mask a similar thing can be done. It will turn the `yaml` file somewhat long but it should be clear enough.
