### ISSUE TITLE
Add AUTHORS file to replace individual copyright authors

### ISSUE THREAD

**Issue by djhoese** [pytroll/satpy#398]
Following something like that described here: https://opensource.google.com/docs/releasing/authors/

It would be nice to have an AUTHORS file to clean up the copyright statements in satpy to have some consistency. The basic idea is that all authors (names, usernames, and maybe email?) get added to the AUTHORS file and the copyright statement in each source code file would use "Pytroll Developers" on the copyright line.

Additionally, it would be nice to make the license/copyright statement more consistent. I would prefer that blank lines start with a `#` for consistency and to treat the whole block as one single block. I'll even go as far as saying I would like to remove the years from the copyright. My understanding is that the year in every source file is not needed and only needs to be updated in the main LICENSE file in the repository.

@mraspaud @pnuu @adybbroe Please give me your opinion on all of these matters.

**Comment by pnuu** [comment]
Sounds sensible. I've also noticed that the years tend to lag behind for a year or four depending on activity in a given file. Often even if the file was edited recently.

**Comment by djhoese** [comment]
We could follow what the verde project does (https://github.com/fatiando/verde/blob/master/AUTHORS.md) which includes having a bot on pull requests that automatically asks contributors to add their name to the authors list if they aren't already.

**Comment by djhoese** [comment]
@leouieda Could you point us to the service that does this?

**Comment by leouieda** [comment]
I'm using the [Welcome bot](https://probot.github.io/apps/welcome/) to post those messages. It will post when a new user submits an issue, creates a PR, or get's the first PR merged. You can configure the messages in a `.github/config.yml` file: https://github.com/fatiando/verde/blob/master/.github/config.yml

**Comment by djhoese** [comment]
The AUTHORS.md file has been added now (a while ago) and contributor's are asked to add their name as part of the PR template. Closing this.
