### ISSUE TITLE
Can not set customized tags for geotiff writer with rasterio method

### ISSUE THREAD

**Issue by yufeizhu600** [pytroll/satpy#403]
**Describe the bug**
Can not set customize geotiff tags while using satpy geotiff writer with rasterio method.

It was working with satpy v0.7.4.

**To Reproduce**

```python

#!/usr/bin/env python
# -*- coding: utf-8 -*-

from satpy import Scene
from satpy.utils import debug_on
from satpy.writers import get_enhanced_image, to_image

from satpy.writers.geotiff import GeoTIFFWriter

import glob

debug_on()

dt_start = "s20180791545447"
    
filenames = glob.glob('./ABI-L1b-RadF/OR_ABI-L1b-RadF-M3C??_G16_' + dt_start + '*.nc')

glb_scn = Scene(reader='abi_l1b', filenames=filenames)

glb_scn.load(['C07'])

img = get_enhanced_image(glb_scn['C07'])

mytags = {'TIFFTAG_IMAGEDESCRIPTION' : 'NDATA_TYPE=mydtype'}
outfile = './test.tif'

gtiff_writer = GeoTIFFWriter(tags=mytags)

img.save(outfile, writer=gtiff_writer)
```

**Expected behavior**
When check the info of the output geotiff file by using gdalinfo, the TIFFTAG_IMAGEDESCRIPTION should appear in the Metadata section as below

%gdalinfo test.tif
... ...
Metadata:
  AREA_OR_POINT=Area
  **TIFFTAG_IMAGEDESCRIPTION=NDATA_TYPE=mydtype**
  TIFFTAG_DATETIME=2018:08:23 19:00:52

**Actual results**
%gdalinfo test.tif

... ...
Metadata:
  AREA_OR_POINT=Area
  TIFFTAG_DATETIME=2018:08:23 19:00:52

**Environment Info:**
 - OS: Unbutu 14.04
 - satpy==0.9.1
 - rasterio==1.0.2

**Comment by djhoese** [comment]
Can you verify that the way you are providing kwargs/metadata is the same way that rasterio expects it? All kwargs passed to the sapty writer *should* be passed directly to the rasterio save methods.

**Comment by djhoese** [comment]
This may require updates in trollimage to use the methods described here: https://github.com/mapbox/rasterio/blob/master/docs/topics/tags.rst#writing-tags

**Comment by yufeizhu600** [comment]
Thanks Dave, I have upgraded trollimage from v1.5.1 to v1.5.4; but still have same problem.
