### ISSUE TITLE
Installation through Conda

### ISSUE THREAD

**Issue by WxmanJ** [pytroll/satpy#404]
I am trying to install SatPy through Anaconda 3. 

Upon installing Anaconda 3, I ran the following command 
```
conda install satpy
```
The following error came as a result:
```
Solving environment: failed

UnsatisfiableError: The following specifications were found to be in conflict:
  - satpy
Use "conda info <package>" to see the dependencies for each package.
```
Any suggestions?

**Comment by djhoese** [comment]
You shouldn't have to do anything special if you installed Anaconda 3 to use python 3, but regardless satpy is supported on python 2.7 too. Did you add the conda-forge channel to your conda config?

**Comment by WxmanJ** [comment]
I did.

**Comment by djhoese** [comment]
It's possible one of the dependencies for satpy is having issues being installed, but the error message (unhelpfully) is just reporting the top package that is the issue. Let me see if I can debug this on a local virtual machine. You could also try installing pyresample, gdal, and rasterio as a test.

**Comment by WxmanJ** [comment]
Sure. I will let you know if I receive any error messages.

**Comment by djhoese** [comment]
Good news is I got the same situation on a fresh CentOS 7 VM. If we both debug this we should be able to figure out what is going on.

**Comment by WxmanJ** [comment]
No issues installing each package. There were a bunch of upgrades/downgrades. When I installed satpy after these other packages, it appears to install.

**Comment by djhoese** [comment]
Also if I add "satpy" to the end of that long install command I get a resolvable environment. Must be a specific version of rasterio that is a problem.

**Comment by djhoese** [comment]
As far as I can tell this is an issue with `rasterio` and the dependencies included in the `anaconda` meta-package. Given the many issues with dependency resolutions in conda right now I'm not eager to spend a lot of time figuring out exactly what dependencies are the issue. This could very well be fixed in the next version of anaconda, conda, rasterio, or gdal. Hard to tell unless @ocefpaf is up to date on all the gdal/rasterio environment issues.

So technically this is not satpy's fault...and to avoid doing any more work on this I'm going to stick with that excuse.

**Comment by ocefpaf** [comment]
> Hard to tell unless @ocefpaf is up to date on all the gdal/rasterio environment issues.

Did you tried a solution with only `defaults` or `conda-forge`? Mixing channels at this moment is a no-go :-(

> So technically this is not satpy's fault...and to avoid doing any more work on this I'm going to stick with that excuse.

Nope, it is not. I'll play with this later today to see if there is anything we need to add/remove/fix.

**Comment by ocefpaf** [comment]
Without `defaults` an env with those packages is solvable:

```
conda config --remove channels defaults

conda create --name TEST python=3.6 satpy xarray dask h5py netcdf4 pillow pyyaml six trollimage trollsift pyspectral pykdtree

conda activate TEST

python -c "import satpy; print(satpy.__version__)"
0.9.2
```
