### ISSUE TITLE
SEVIRI HRIT day-microphysics rgb not possible - missing wavelength in dataset id 

### ISSUE THREAD

**Issue by adybbroe** [pytroll/satpy#44]
The day microphysics RGB requires pyspectral, and the interface requires a wavelength. At the moment this is None in the dataset id from the HRIT MSG reader.

Add the following to the FileHandler init:
out.info['wavelength'] = info['wavelength']

**Comment by davidh-ssec** [comment]
This is fixed with ef60fb89a20edfaf3fb2a81f9c08298c123cc39a right?

**Comment by adybbroe** [comment]
Yes! :-)
