### ISSUE TITLE
Adding coastlines to single channel not working

### ISSUE THREAD

**Issue by peters77** [pytroll/satpy#449]
**Describe the bug**
Adding coastlines to single channel pictures not working.

**To Reproduce**
```python
composite = 'natural_color_sun'
....
new_scene = global_scene.resample('eurol')
new_scene.save_dataset(composite, './MSG4.png', overlay = {'coast_dir': '/home/cpeters/software/','color': (255, 255, 0), 'width': 1.0, 'resolution': 'i'})
```
works! 
```python
composite = 'VIS006'
....
new_scene = global_scene.resample('eurol')
new_scene.save_dataset(composite, './MSG4.png', overlay = {'coast_dir': '/home/cpeters/software/','color': (255, 255, 0), 'width': 1.0, 'resolution': 'i'})
```
stalls.

**Expected behavior**
Add coastlines to single channel picture.
Coastlines were not added to a single channel. Composite are working well.

**Actual results**
```python-traceback
[INFO: 2018-10-08 23:46:08 : satpy.writers] Add coastlines and political borders to image.
[DEBUG: 2018-10-08 23:46:08 : satpy.writers] Automagically choose resolution f
[DEBUG: 2018-10-08 23:46:09 : trollimage.xrimage] Interval: left=<xarray.DataArray 'reshape-59920bd5c4344e209a876883f95f2db3' (bands: 1)>
array([0.])
Coordinates:
  * bands     (bands) <U1 'L'
    quantile  float64 0.005, right=<xarray.DataArray 'reshape-59920bd5c4344e209a876883f95f2db3' (bands: 1)>
array([67.693016])
Coordinates:
  * bands     (bands) <U1 'L'
    quantile  float64 0.995
Traceback (most recent call last):
  File "msg4-ernst_single_channel.py", line 93, in <module>
    global_scene.save_dataset(composite,'./MSG4.png', overlay={'coast_dir': '/home/cpeters/software/', 'width':1, 'color':(200, 200, 200)})
  File "/home/cpeters/anaconda2/envs/pytroll/lib/python3.6/site-packages/satpy-0+unknown-py3.6.egg/satpy/scene.py", line 1054, in save_dataset
    **save_kwargs)
  File "/home/cpeters/anaconda2/envs/pytroll/lib/python3.6/site-packages/satpy-0+unknown-py3.6.egg/satpy/writers/__init__.py", line 611, in save_dataset
    decorate=decorate, fill_value=fill_value)
  File "/home/cpeters/anaconda2/envs/pytroll/lib/python3.6/site-packages/satpy-0+unknown-py3.6.egg/satpy/writers/__init__.py", line 354, in get_enhanced_image
    add_overlay(img, dataset.attrs['area'], fill_value=fill_value, **overlay)
  File "/home/cpeters/anaconda2/envs/pytroll/lib/python3.6/site-packages/satpy-0+unknown-py3.6.egg/satpy/writers/__init__.py", line 230, in add_overlay
    resolution=resolution, width=width, level=level_coast)
  File "/home/cpeters/anaconda2/envs/pytroll/lib/python3.6/site-packages/pycoast/cw_agg.py", line 418, in add_coastlines
    y_offset=y_offset)
  File "/home/cpeters/anaconda2/envs/pytroll/lib/python3.6/site-packages/pycoast/cw_base.py", line 598, in _add_feature
    x_offset=x_offset, y_offset=y_offset, **kwargs)
  File "/home/cpeters/anaconda2/envs/pytroll/lib/python3.6/site-packages/pycoast/cw_base.py", line 510, in add_shapes
    draw = self._get_canvas(image)
  File "/home/cpeters/anaconda2/envs/pytroll/lib/python3.6/site-packages/pycoast/cw_agg.py", line 52, in _get_canvas
    return aggdraw.Draw(image)
ValueError: bad mode
```

**Environment Info:**
 - OS: Linux
 - SatPy Version: latest 0.9.4 master 
 - PyResample Version:   1.10.1

**Comment by mraspaud** [comment]
Indeed, this is a known issue, but good that you got it in here so that we have it listed somewhere.

There would be a couple of solutions for that: 
- either fix pycoast to detect single channel images and just drawing the coastlines in black and white
- or convert the dataset to RGB before drawing the coastlines.

**Comment by ericacova** [comment]
I found the same problem.

My code:
`def createRGB(satCode, timestamp):

	import os
	import sys
	from glob import glob
	import datetime
	#import logging
	import subprocess
		
	from satpy.scene import Scene
	from pyresample.geometry import AreaDefinition
	from PIL import Image
	from pycoast import ContourWriterAGG

	
	#---------------------- Aree --------------------------
	
	from pyresample.geometry import AreaDefinition

	area_id = 'EuropaAtlantico'
	description = 'Europa e un pezzo di atlantico'
	proj_id = 'EuropaAtlantico'
	proj_string = '+proj=utm +zone=32'
	width = 1920
	height = 1080
	area_extent = ( -3008282, 3024683, 4008282, 7012018 )
	EuropaAtlantico = AreaDefinition(area_id, description, proj_id, proj_string, width, height, area_extent)

	#------------------------------------------------------
	
	time_slot = datetime.datetime.strptime(timestamp, '%Y%m%d%H%M')
	
	#lgr.info("CREATE RGB - %s %s", satCode, time_slot)

	filenames = glob("./decompress/*"+timestamp+"*")

	global_scene = Scene(reader="seviri_l1b_hrit", filenames=filenames)
	global_scene.load(['VIS006','VIS008','IR_016','IR_039','WV_062','WV_073','IR_087','IR_097','IR_108','IR_120','IR_134','HRV'])

	local_scene = global_scene.resample(EuropaAtlantico)
	local_scene.load(["VIS008"])
	imgpath='./VIS008_'+timestamp+'.png'
	local_scene.save_dataset('VIS008', imgpath)

	imgread = Image.open('VIS008_'+timestamp+'.png')
	proj4_string = '+proj=utm +zone=32'	
	area_extent = ( -3008282, 3024683, 4008282, 7012018 )
	area_def = (proj4_string, area_extent)
	cw = ContourWriterAGG('./confini/')
	cw.add_coastlines(imgread, area_def, resolution='l', level=1, width=0.5, outline_opacity=200)
	cw.add_borders(imgread, area_def, resolution='l', width=0.5, outline_opacity=200)

	
createRGB("MSG3","201904300815")`

Results:
`/usr/local/lib/python3.6/dist-packages/pyresample/geometry.py:931: RuntimeWarning: invalid value encountered in double_scalars
  self.pixel_size_y = (area_extent[3] - area_extent[1]) / float(height)
/usr/local/lib/python3.6/dist-packages/pyresample/spherical.py:123: RuntimeWarning: invalid value encountered in true_divide
  self.cart /= np.sqrt(np.einsum('...i, ...i', self.cart, self.cart))
Traceback (most recent call last):
  File "prova_confiniEA.py", line 56, in <module>
    createRGB("MSG3","201904300815")
  File "prova_confiniEA.py", line 50, in createRGB
    cw.add_coastlines(imgread, area_def, resolution='l', level=1, width=0.5, outline_opacity=200)
  File "/home/rgbmsg/.local/lib/python3.6/site-packages/pycoast/cw_agg.py", line 414, in add_coastlines
    y_offset=y_offset)
  File "/home/rgbmsg/.local/lib/python3.6/site-packages/pycoast/cw_base.py", line 591, in _add_feature
    x_offset=x_offset, y_offset=y_offset, **kwargs)
  File "/home/rgbmsg/.local/lib/python3.6/site-packages/pycoast/cw_base.py", line 511, in add_shapes
    draw = self._get_canvas(image)
  File "/home/rgbmsg/.local/lib/python3.6/site-packages/pycoast/cw_agg.py", line 45, in _get_canvas
    return aggdraw.Draw(image)
ValueError: bad mode
`

**Comment by djhoese** [comment]
Ah I now realize why this isn't working for you. Is there a reason you are saving the image and then reopening it? Satpy itself has some functionality for creating/adding coastlines and borders from the `save_dataset` method and will automatically convert the image to RGB if needed. With the way you've done it now, this error is expected as pycoast will not automatically convert the image mode to RGB (it won't assume what's best for the user at this lower-level). You could try `imgread = imgread.convert('RGB')` (I think) before calling `add_coastlines` and this may fix it for you. In the long run though it may be better to use Satpy's interface directly.

**Comment by mraspaud** [comment]
@ericacova here is an example to add coastlines without needing to reopen the file:
```python
local_scene.save_dataset('VIS008', imgpath,
                         overlay={'coast_dir': '/path/to/gshhs/shapes/', 'color': (255, ), 'resolution': 'i'})
```

**Comment by ericacova** [comment]
Thank you, that worked perfectly! 
I was following this tutorial https://pycoast.readthedocs.io/en/latest/usage.html.
Where do I find the documentation of the example you posted?

**Comment by mraspaud** [comment]
@ericacova here is the documentation of the `add_overlay` method:
https://satpy.readthedocs.io/en/latest/api/satpy.writers.html#satpy.writers.add_overlay
