### ISSUE TITLE
Add GMS series satellite data reader

### ISSUE THREAD

**Issue by CyanideCN** [pytroll/satpy#486]
**Is your feature request related to a problem? Please describe.**
I'm dealing with a project which requires processing GMS satellite data, but it seems that there's no existing program that can read the data.

**Describe the solution you'd like**
A reader for GMS series satellite.

**Additional context**
GMS users guide, which includes georeference method in appendix E.
http://www.data.jma.go.jp/mscweb/en/operation/docs/GMS_Users_Guide_3rd_Edition_Rev1.pdf
GMS1-4 file format
http://www.data.jma.go.jp/mscweb/en/operation/docs/VISSR_FORMAT_GMS-4.pdf
GMS5 file format
http://www.data.jma.go.jp/mscweb/en/operation/docs/VISSR_FORMAT_GMS-5.pdf
Data source
ftp://mtsat.cr.chiba-u.ac.jp

**Comment by sfinkens** [comment]
A reader for GMS-5 is now available in satpy-0.43
