### ISSUE TITLE
Mask space pixels in AHI HSD reader

### ISSUE THREAD

**Issue by sfinkens** [pytroll/satpy#531]
Use ``satpy.readers.utils.get_geostationary_mask`` in ``ahi_hsd`` once #524 is merged

**Comment by djhoese** [comment]
I was thinking about this this morning and was wondering if maybe this should be made in to a modifier. There may be a time where someone wants to see if there is any useable data in the space pixels and with the "easy" solution of applying this in the reader it would be difficult to turn this masking off.

Another possibility would be having this applied in the sunz_corrector where it would be specifically configured for geo instruments that need it (by creating a `sunz_corrected` modifier in the `composites/<sensor>.yaml` config).

Thoughts (@sfinkens @mraspaud )?

**Comment by sfinkens** [comment]
@djhoese Nice, you really have the big picture in mind! Technically a good idea. Although I'm not aware of such applications. Maybe this is something to be considered when somebody asks for it? :smile: The modifier approach seems more suitable to me, because the sunz_corrector would only be applied to visible channels (correct?), but IR channels need to be masked as well.

**Comment by djhoese** [comment]
Oh good point on the IR channels. I've seen some people get "excited" about being able to see the moon in some of the space pixels. Now is this a common use case or even something that is "important"? Probably not. I'm kind of 50/50 on this. I don't like the idea of the reader being too magical (blame @adybbroe and @mraspaud for that) and applying things that can't be reversed.

**Comment by sfinkens** [comment]
I agree with you on the magical reader. From the software point of view It would be cleaner to do the masking separately and on demand. But maybe calibrating and masking are not so independent after all. Two examples came to my mind:
- You can correct earth pixels for SZA, but not space pixels, so the image becomes inhomogeneous
- Some lookup tables (I think it was GOES and MTSAT) produce IR BTs ~100 Kelvin for space pixels, which is nonsense

In these two cases it would make more sense to mask space pixels in order to provide consistent and useful data to the user.

**Comment by simonrp84** [comment]
Hi,
My research group uses the 'space' pixels of the Himawari images, they are useful for 2 reasons:
1) The space data sometimes contains polar mesospheric (noctilucent) cloud pixels, which we use to retrieve cloud properties. Losing the space data would mean we lose the only GEO satellite capable of seeing these clouds (they're cut off at source in MSG L1.5 and GOES-R/S data).
2) The actual deep space pixels, plus the moon, give a useful uncertainty + noise estimate, which we use to calibrate our atmospheric retrieval algorithms.

My thought is: Why mask these pixels? There's not many of them so it's hardly a massive processing burden to include them. Seems like cutting out data for no reason, tbh! Plus, as @djhoese says, some people like to see the moon :-)

**Comment by djhoese** [comment]
@simonrp84 Thanks for your response. This is exactly what I was worried about.

As for processing burden, it is actually more work to mask them out than it is just process them as normal pixels.

As for why we would want to mask them, most of the core developers and our existing users are or work with atmospheric scientists and forecasters. In most of these cases the "space" pixels don't provide very much useful information and just make an "uglier" image when visualization is the main process. As far as I can tell, a lot of people I've come in to contact with don't consider them "stable" or reliable. Additionally, these instruments are designed for observing the earth so I'd be curious what kind of noise/error bars you have with these space pixels. I'd be curious what your experience is with noise and reliability of space pixels.

All of that said, however we do it in satpy, whether it is the default behavior or not, masking the space pixels will be a configurable option.

**Comment by simonrp84** [comment]
Yes, the mesosphere pixels do have quite a bit of noise (the digital count is only 5-10 above the deep space value) but by sampling over an hour or so of observations you can generate meaningful statistics.
Himawari in particular seems pretty good for cold/dark targets like the upper atmosphere,there's far less noise than in the L1.0 SEVIRI data, for example.

Am glad that this would be a configurable option, sounds good!

**Comment by djhoese** [comment]
I'm guessing you and your colleagues have difficulty convincing the space agencies to keep the space pixels in the data (ex. GOES-R series)?

**Comment by sfinkens** [comment]
@simonrp84 Very interesting! So if the user requests Counts or Radiance, the space pixels could be included by default. Regarding calibration to Reflectance/Brightness-Temperature I would vote for masking them by default.

**Comment by pnuu** [comment]
The noctilucent clouds are something that I wanted to check for my hobby few years back, but as indicated, Eumetsat removes the space pixels. At that time Himawari-8 wasn't up yet, and forgot to go back to it. Have to wait for a proper display and get some data!

What @sfinkens suggest about masking sounds good.

**Comment by simonrp84** [comment]
@pnuu We're getting a little off topic here, but you can ask EUMETSAT for data centre access to the L1.0 SEVIRI data. PMCs are visible in the HRV channel and sometimes in the 0.6 + 0.8 micron channels too.
Happy to email you a script (IDL unfortunately) that can read the L1.0 data: simon(dot)proud[at]physics.ox.ac.uk

**Comment by mraspaud** [comment]
@simonrp84 well that would be a great christmas project: port your L1.0 data reader to satpy ;)

**Comment by simonrp84** [comment]
@mraspaud There be dragons ;) I was thinking about a summer student project to do this, actually - so maybe I can add a reader in the middle of next year..

**Comment by mraspaud** [comment]
Sounds good!
