### ISSUE TITLE
Support GOES-15 in netcdf format from Eumetcast (`nc_goes` reader)

### ISSUE THREAD

**Issue by howff** [pytroll/satpy#534]
Eumetcast will distribute GOES-15 data in filenames such as
goes15.2018.289.120018_1.nc.bz2
but the geolocation will be in a separate file
goes15.2018.289.120018_geo.nc.bz2

The reader can be modifed to support the new filenames by editing nc_goes.yaml
but getting the lat,lon is more tricky.

Sample files:
ftp://ftp.eumetsat.int/pub/OPS/out/test-data/Test-data-for-External-Users/GOES-15_netCDF_rad/

**Comment by howff** [comment]
Sorry, I didn't see the PR, only looked at the Issues, and wanted to create one to reference in a forthcoming pull request, so it's great that someone has beaten me to it :-)

**Comment by sfinkens** [comment]
@howff @mraspaud Exactly! The PR will be ready for merge soon. We are currently adding tests for the EUM reader.

**Comment by mraspaud** [comment]
No problem ! We will close this issue when the PR is merged.
