### ISSUE TITLE
Can not show or save ABI true color image (RuntimeWarning: invalid value encountered in log)

### ISSUE THREAD

**Issue by tiehfood** [pytroll/satpy#569]
I'm trying to generate a true color image from some GOES16 data (downloaded from AWS) but I always get the following error if I try to show or save the image (regardless of filetype):

```
[DEBUG: 2019-01-08 04:37:22 : satpy.scene] Setting 'PPP_CONFIG_DIR' to '/home/sat/.local/lib/python3.6/site-packages/satpy/etc'
[DEBUG: 2019-01-08 04:37:22 : satpy.scene] Resampling DatasetID(name='C01', wavelength=(0.45, 0.47, 0.49), resolution=1000, polarization=None, calibration='reflectance', level=None, modifiers=('sunz_corrected',))
[DEBUG: 2019-01-08 04:37:22 : pyresample.geometry] Projections for data and slice areas are identical: geos
[DEBUG: 2019-01-08 04:37:22 : satpy.scene] Resampling DatasetID(name='C02', wavelength=(0.59, 0.64, 0.69), resolution=500, polarization=None, calibration='reflectance', level=None, modifiers=('sunz_corrected',))
[DEBUG: 2019-01-08 04:37:22 : pyresample.geometry] Projections for data and slice areas are identical: geos
[DEBUG: 2019-01-08 04:37:22 : satpy.scene] Resampling DatasetID(name='C03', wavelength=(0.8455, 0.865, 0.8845), resolution=1000, polarization=None, calibration='reflectance', level=None, modifiers=('sunz_corrected',))
[DEBUG: 2019-01-08 04:37:22 : pyresample.geometry] Projections for data and slice areas are identical: geos
[DEBUG: 2019-01-08 04:37:22 : satpy.composites] Sharpening image with high resolution red band
[DEBUG: 2019-01-08 04:37:22 : satpy.scene] Unloading dataset: DatasetID(name='C01', wavelength=(0.45, 0.47, 0.49), resolution=1000, polarization=None, calibration='reflectance', level=None, modifiers=('sunz_corrected',))
[DEBUG: 2019-01-08 04:37:22 : satpy.scene] Unloading dataset: DatasetID(name='C02', wavelength=(0.59, 0.64, 0.69), resolution=500, polarization=None, calibration='reflectance', level=None, modifiers=('sunz_corrected',))
[DEBUG: 2019-01-08 04:37:22 : satpy.scene] Unloading dataset: DatasetID(name='C03', wavelength=(0.8455, 0.865, 0.8845), resolution=1000, polarization=None, calibration='reflectance', level=None, modifiers=('sunz_corrected',))
[DEBUG: 2019-01-08 04:37:22 : satpy.scene] Unloading dataset: DatasetID(name='green_raw', wavelength=None, resolution=None, polarization=None, calibration=None, level=None, modifiers=None)
[DEBUG: 2019-01-08 04:37:22 : satpy.writers] Reading ['/home/sat/.local/lib/python3.6/site-packages/satpy/etc/writers/simple_image.yaml']
[DEBUG: 2019-01-08 04:37:22 : satpy.writers] Enhancement configuration options: [{'name': 'cira_stretch', 'method': <function cira_stretch at 0x7f31afcc1f28>}]
[DEBUG: 2019-01-08 04:37:22 : satpy.enhancements] Applying the cira-stretch
[DEBUG: 2019-01-08 04:37:22 : satpy.writers.simple_image] Saving to image: GOES16.png
/home/sat/.local/lib/python3.6/site-packages/dask/core.py:137: RuntimeWarning: invalid value encountered in greater
  return func(*args2)
/home/sat/.local/lib/python3.6/site-packages/dask/core.py:137: RuntimeWarning: invalid value encountered in log
  return func(*args2)
```
**To Reproduce**

```python
from satpy.utils import debug_on; debug_on()
from satpy import Scene
from glob import glob
scn = Scene(filenames=glob('/home/sat/Schreibtisch/*20190031715362*'), reader='abi_l1b')
scn.load(['true_color'])
scn_res = scn.resample(scn.min_area(), resampler='native')
scn_res.save_dataset('true_color', filename='GOES16'+'.png')
```

**Environment Info:**
 - OS: Ubuntu 18.04
 - SatPy Version: satpy-0.11.1
 - PyResample Version: pyresample-1.10.3

**Comment by djhoese** [comment]
That is only a warning, not an error. Did you check if the output file was actually created? The log output seems like it was. If it doesn't exist then it may be a memory issue. First, double check that the imahe wasn't created.

**Comment by tiehfood** [comment]
It doesn't create any output image. It also sometimes says "Getötet" (something like 'died' in english) at the end.
If I run it directly inside python, python crashes after that message...

**Comment by tiehfood** [comment]
You're right, it was a memory problem :)
Sorry...

**Comment by djhoese** [comment]
So there are two things that you could do to try to improve the memory usage here (something we are always working on):

1. Reduce the size of the chunks that the dask library is processing. This can be configured in a hacky way right now and should be easier in future versions of satpy. You can configure it by setting this environment variable before opening python (or at least importing satpy):

```
    export PYTROLL_CHUNK_SIZE=2048
```

2. The other thing to look at is how many dask workers are being created/used on your system. Do you know how many logical CPU cores you have? Dask by default will create on worker per logical core which on some systems is too much. You can configure this by putting your satpy code inside the following statement:

```python

import dask
from multiprocessing.pool import ThreadPool
with dask.config.set(pool=ThreadPool(4)):
    # satpy code here
```

It has been a while since I've tested this but I believe this is supposed to work.

If you have more than 8 cores on your system I would try doing option 2 first. Otherwise, I would start with 1 to see if it helps. If you still have memory issues then try both options. If you *still* have issues then I am curious how much memory you have on your system? You could try smaller numbers for both options, but lowering them any further will hurt performance a lot.

**Comment by anikfal** [comment]
For my case, always an empty image is generated (sample file name: MOD021KM.A2020217.1905.061.2020218071403.hdf).
> there are two things that you could do to try to improve the memory usage

None of the above solutions works for this case.

**Code:**
```python
from satpy.scene import Scene
from satpy import find_files_and_readers
from datetime import datetime
files = find_files_and_readers(base_dir='/home/anikfal/datamsg8/modis',
                               sensor="modis",
                               #start_time=datetime(2019,4,1,9,00),
                               #end_time=datetime(2019,4,1,9,15),
                               reader='modis_l1b')
scn = Scene(filenames=files)
composite_name = 'true_color'
scn.load([composite_name], resolution=1000)
scn.save_datasets(writer='simple_image')
```

**Warning message:**

> /home/anikfal/miniconda3/envs/mysat/lib/python3.8/site-packages/dask/core.py:121: RuntimeWarning: invalid value encountered in less
  return func(*(_execute_task(a, cache) for a in args))

**Environment info:**

- OS: Fedora-31
- Satpy Version: 0.22.0

**Comment by anikfal** [comment]
For other supported Modis L1 data (sample file name: MOD02HKM.A2020217.0800.061.2020217192109.hdf):

**Code:**
```python
from satpy.scene import Scene
from satpy import find_files_and_readers
from datetime import datetime
files = find_files_and_readers(base_dir='/home/anikfal/datamsg8/modis',
                               sensor="modis",
                               #start_time=datetime(2019,4,1,9,00),
                               #end_time=datetime(2019,4,1,9,15),
                               reader='modis_l1b')
scn = Scene(filenames=files)
#print(scn.available_dataset_ids())
scn.load(name='1', wavelength=(0.62, 0.645, 0.67), resolution=500, polarization=None, calibration='radiance', level=None, modifiers=())
```
**Error message:**
> Traceback (most recent call last):
  File "3.py", line 11, in <module>
    scn.load(name='1', wavelength=(0.62, 0.645, 0.67), resolution=500, polarization=None, calibration='radiance', level=None, modifiers=())
TypeError: load() missing 1 required positional argument: 'wishlist'

**Comment by simonrp84** [comment]
I think you should make a new issue for this, so not to confuse with the old ABI issue.

Are you running the latest satpy from github, or a release from conda? There have been some changes in recent the recent github master that could cause this - so please try with the last release and see if the problem is still there.

**Comment by anikfal** [comment]
This is a Satpy release from conda.

**Comment by djhoese** [comment]
@anikfal please create a new issue so we can address your problem specifically.

**Comment by anikfal** [comment]
@djhoese Created.
It is interesting that I cannot regenerate the same errors/warnings.
