### ISSUE TITLE
PPP_CONFIG_DIR set locally does not include the global dir for the eps_l1b reader

### ISSUE THREAD

**Issue by TAlonglong** [pytroll/satpy#583]
If you have a local config dir set to PPP_CONFIG_DIR like:

PPP_CONFIG_DIR=/software/pytroll/etc/satpy/etc

the eps_l1b reader will not find the needed eps_avhrrl1b_6.5.xml file. 
See https://github.com/pytroll/satpy/blob/master/satpy/readers/eps_l1b.py#L67

Somehow the original PPP_CONFIG_DIR should be added in the search path for the eps_avhrrl1b_6.5.xml file

**Comment by gerritholl** [comment]
Is this still relevant with SATPY_CONFIG_PATH?

**Comment by djhoese** [comment]
I think this can be closed as the new line is:

https://github.com/pytroll/satpy/blob/8c61f39ecfab68464d920c37e95dbf373011550f/satpy/readers/eps_l1b.py#L57

which is using the higher-level config logic which should handle this "stuff". I actually think this reader was the reason I made that function.
