### ISSUE TITLE
Re-use of calculated resampling parameters

### ISSUE THREAD

**Issue by pnuu** [pytroll/satpy#60]
At the moment satpy doesn't re-use the calculated resampling parameters for the following channels with identical fingerprints if the cache_dir kwarg is not given. With cache_dir set, the resampling parameters are written to disk the first time, and then **reloaded** for each of the matching datasets.

My suggestion is to find a way to resample the datasets in such order that all matching datasets are processed consecutively and the resampling parameters could be kept in-memory for that duration. In this way the parameters would not need to be reloaded (cache_dir set) or recalculated (cache_dir not set) for each dataset. The extra time used is even more pronounced when using bilinear sampling and/or large areas.

For testing:

Set debugging messages on
`from satpy.utils import debug_on`
`debug_on()`
Create a scene from some files
`glbl = Scene(filenames=fnames)`
Load all available datasets
`glbl.load(glbl.available_dataset_names())`
Resample without cache. Note that the resampling is recalculated for each dataset
`lcl = glbl.resample('euron1')`
Resample with cache. Note that the resampling parameters are reloaded, if already calculate and saved, for each dataset
`lcl = glbl.resample('euron1', cache_dir='/tmp')`

**Comment by pnuu** [comment]
Did some timing using Suomi-NPP/VIIRS data (I channels + DNB) on a rather large area.

> REGION: EPSG_3035_375m {
>         NAME: EPSG:3035 with 375 m resolution
>         PCS_ID: ETRS89 / ETRS-LAEA
>         PCS_DEF: init=EPSG:3035
>         XSIZE: 10314
>         YSIZE: 10448
>         AREA_EXTENT: (2426378.0132, 1528101.2618, 6293974.6215, 5446513.5222)
> };

`%time lcl = glbl.resample('EPSG_3035_375m', nprocs=1, resampler='nearest')`
> CPU times: user 16min 26s, sys: 2min 5s, total: 18min 31s
> Wall time: 6min 48s

Calculating the resampling parameters for one channel (`I05`) takes 75 to 80 seconds.

`%time lcl = glbl.resample('EPSG_3035_375m', nprocs=1, resampler='nearest', cache_dir="/home/lahtinep/data/cache")`
> CPU times: user 54.2 s, sys: 54.8 s, total: 1min 48s
> Wall time: 3min 59s

Running again with the pre-calculated parameters:

> CPU times: user 31.5 s, sys: 17.2 s, total: 48.7 s
> Wall time: 52 s

**Comment by davidh-ssec** [comment]
To be clear (correct me if I'm wrong), the parameters are being cached but they are only *matching* if the datasets completely match. The `cache_dir` parameter is for saving them to disk and reusing them in another session/interpreter. In most cases I01, I02, I03 should use the same parameters and I04, I05 should use the same. The missing/fill values of each dataset has to be considered when generating the kdtree with the current kdtree implementation because otherwise you will get neighbor indexes for invalid values.

If you reuse the same parameters/kdtree for every channel with the same resolution then it will go faster but you won't know which data values are missing until after the kdtree is created. Possible solutions include:

1. Add functionality to kdtree (pykdtree) querying to take in a mask and keep searching for neighbors until it finds a not masked neighbor.
2. I forgot the other ones I thought of.

**Comment by pnuu** [comment]
The gotcha with the current implementation in satpy is that at high latitudes with MSG RSS, due to shifting northern scan extent (see images below), practically every image would have separate resampling LUTs. This would accumulate more and more saved parameters, and the recalculation would effectively nullify the LUT usefulness. With MSG RSS we could live without the LUTs, but when MTG RSS becomes available (around 2021) we wont afford the constant recalculations. I'd assume the same goes with GOES-16 data. In my experience a missing scanline in some images are acceptable as long as the images are not delayed.

Our operations are still using mpop which has a shared mask for similar channels (same resolution) and creates the LUT filenames based on the input and output area extents and is masked-value-agnostic, which suits us fine :-)

I'll discuss this more with @mraspaud at Pytroll WS next week.

**Comment by davidh-ssec** [comment]
@pnuu What causes the shifting extents on the above images? Is it constantly shifting?

I agree this is a problem. As long as we come up with a solution that serves both use cases. FYI The "EWA" resampling that I added to pyresample and that I use in Polar2Grid does internal checks for missing values so I don't really need to separate based on data fill values.

Another option to the ones I suggested above would be to request more than 1 neighbor from the kdtree and come up with a nice way to say "this neighbor is a fill value, go to the next neighbor, ...".

Another simple option as a "quick fix" might be to have a keyword argument for "ignore data mask in cache" or something.

**Comment by pnuu** [comment]
The shifting is due to slight satellite wobble and the northernmost segment not being imaged in RSS mode. With the full disk mode this wobble isn't a problem, as there's enough extra in the last segment to cover the whole disk.

We didn't manage to talk much about this issue in Lannion, but I'd like the last option, that's roughly what's done with mpop.

**Comment by pnuu** [comment]
This was solved by the existing - although well hidden - `scn.resample(..., mask_area=False)` kwarg. Closing the issue as solved.
