### ISSUE TITLE
Update 'generic_image' reader to use rasterio for area creation

### ISSUE THREAD

**Issue by djhoese** [pytroll/satpy#617]
**Is your feature request related to a problem? Please describe.**
The geotiff writer currently only needs the `rasterio` library installed and will drop support for using the python `gdal` package in the future. This means that for most use cases the `gdal` python package is not needed. The `generic_image` reader currently uses both `rasterio` and `gdal` python to load a geotiff and then compute the AreaDefinition (opening the file twice).

**Describe the solution you'd like**
The `get_geotiff_area_def` function could be replaced by pyresample's new `get_area_def_from_raster` function (https://github.com/pytroll/pyresample/blob/master/pyresample/utils/_rasterio.py#L75) added by @drnextgis

**Describe any changes to existing user workflow**
No.

**Additional python or other dependencies**
It would remove the `gdal` python package dependency.

**Describe any changes required to the build process**
No `gdal` python package needed for testing...I think.

**Comment by djhoese** [comment]
@pnuu originally created this reader and created the function to be replaced (before the pyresample utility function existed). If there are any questions about the reader he can probably answer them.

**Comment by Suyash458** [comment]
Does this still need work? I'd like to pick this up

**Comment by djhoese** [comment]
@Suyash458 Yes, I don't think this has been tackled yet. As mentioned above @pnuu originally wrote this reader so he may have to answer any detailed questions, but he is also on vacation right now so he may be slow to answer.

I think it would be nice if the reader used rasterio if it was available, but had a fall back to gdal if not available. At least for backwards compatibility.

**Comment by Suyash458** [comment]
Sounds good, I'll take a look at `get_area_def_from_raster` and open a PR

**Comment by Suyash458** [comment]
@pnuu `GenericImageFileHandler.read` was using `xarray`'s `open_rasterio` function so does it make sense to have a fall back to gdal in case `rasterio` isn't available?

**Comment by pnuu** [comment]
No, I don't thing `gdal` fallback makes sense in this case, as `rasterio` is needed anyway.

**Comment by djhoese** [comment]
Ah I didn't realize rasterio was used otherwise. @pnuu is right, a fallback doesn't make sense.

**Comment by Suyash458** [comment]
Should `test_get_geotiff_area_def` be removed from `test_generic_image` since `get_area_def_from_raster` is already tested in `pyresample` ?

**Comment by djhoese** [comment]
Yeah, I'd be ok with that.
