### ISSUE TITLE
Consider using setuptools-scm instead of versioneer

### ISSUE THREAD

**Issue by djhoese** [pytroll/satpy#678]
Versioneer is no longer maintained. It was brought up on https://github.com/pydata/xarray/issues/2853 that setuptools-scm may be a good alternative and it looks like it has recent releases.

https://pypi.org/project/setuptools-scm/

**Comment by mraspaud** [comment]
Thanks for bringing this up @djhoese. Indeed if versioneer isn't maintained, we'll have to move away from it.
