### ISSUE TITLE
How to save the raw data to disk?

### ISSUE THREAD

**Issue by XichaoTeng** [pytroll/satpy#70]
This project is really helpful to read Himawari 8 data in HSD format, Thanks a lot!!!
I used "global_scene.save_dataset" to save the data, but I found that the data was converted to 8 bit after it is saved to disk. I want to know how to save the raw data (16 bit) ? Thank you!

**Comment by mraspaud** [comment]
By default the geotiff writer saves to 8bits indeed. I assume you want to save to geotiff right ? The writer is capable of saving floating points in 16 bits, so I think you can just call
```python
scn.save_dataset(..., floating_point=True)
```

**Comment by davidh-ssec** [comment]
@XichaoTeng Did this help you? Were you able to get what you wanted accomplished?

**Comment by XichaoTeng** [comment]
Thank you for your reply! I want to save data to geotiff. I call the command:

`global_scene.save_dataset(dataset,filename, floating_point=True)`

but I get the error: 

```
  File "/usr/local/lib/python2.7/dist-packages/satpy/scene.py", line 627, in save_dataset
    overlay=overlay, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/satpy/writers/__init__.py", line 272, in save_dataset
    self.save_image(img, filename=filename, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/satpy/writers/geotiff.py", line 136, in save_image
    datasets = [img.datasets[0].astype(np.float64)]
AttributeError: 'Image' object has no attribute 'datasets'
```

After that, I read the SatPy's Documentation, I found that `floating_point=True `is the attribute of img, not dataset, I want to know how to save dataset in16 bits? Thanks a lot!

**Comment by mraspaud** [comment]
@XichaoTeng I will have a look later this week

**Comment by XichaoTeng** [comment]
@mraspaud  Hi, have you tested how to save dataset in 16 bits? thanks

**Comment by mraspaud** [comment]
@XichaoTeng your bug report is accurate, I just fixed it in the develop branch. Feel free to try it out.
And sorry for the delay.

**Comment by XichaoTeng** [comment]
@mraspaud ,thanks a lot! I'll try it.

**Comment by davidh-ssec** [comment]
@XichaoTeng Did you get a chance to test this? I'm going to close this for now, but if you still have this issue then we can reopen it.
