### ISSUE TITLE
Add reader for FY3D MERSI2 L1B data

### ISSUE THREAD

**Issue by TAlonglong** [pytroll/satpy#706]
Add reader for FY3D MERSI2 L1B data

A small testdata set is available from here: http://doi.org/10.5281/zenodo.2634027

**Comment by TAlonglong** [comment]
MERSI-2 is improved over MERSI(MERSI-1)

https://www.wmo-sat.info/oscar/instruments/view/278
https://www.wmo-sat.info/oscar/instruments/view/279

For the format I dont know.

**Comment by djhoese** [comment]
FYI I'm working on this now.
