### ISSUE TITLE
Standardise self.mda for SEVIRI attributes

### ISSUE THREAD

**Issue by simonrp84** [pytroll/satpy#722]
## Feature Request

**Is your feature request related to a problem? Please describe.**
Currently, the L1B SEVIRI readers store some attributes as `self.XYZ` and some as `self.mda['XYZ']`.

As an example, the HRIT reader currently stores platform_id as:
`self.platform_id`
While the NAT reader has:
`self.mda['platform_id']`
Which leads to issues with calibration, for NAT files IR calibration fails as the platform ID is not in the expected place.

**Describe the solution you'd like**
It would be good to standardise this so that all attributes are in the same place, preferably `self.mda`.

**Describe any changes to existing user workflow**
In the majority of cases this will be transparent to the user, but may be noticable if they have need for some specific attributes that get moved.

**Comment by sjoro** [comment]
quick reminder note regarding the discussion in slack `self.mda` should be renamed to something more obvious to new user, for example, `self.metadata`. i'm open to other suggestions as well.

**Comment by sfinkens** [comment]
@simonrp84 This has been addressed in #721, right? Besides, the problem of the calibration methods relying on other file handler attributes will be resolved by #1457. where the calibration is made independent of the file handler.

**Comment by simonrp84** [comment]
This looks like it's now been fixed. Closing.
