### ISSUE TITLE
GOES16/17 netcdf reader fails with rasterio installed

### ISSUE THREAD

**Issue by WBMol** [pytroll/satpy#742]
**Describe the bug**
Unable to read GOES16/17 `.nc` files using SatPy's `abi_l1b` reader with `rasterio` installed for exporting to GeoTIFF.

**To Reproduce**

```python
from satpy import Scene
from glob import glob

reader = 'abi_l1b'
fpaths = glob('./satdata/goes16/*G16*2019098045*')

scene = Scene(filenames=fpaths, reader=reader)
```

**Expected behavior**
Creating a scene containing GOES16/17 data

**Actual results**
```bash
home/wouter/Venvs/satpy/lib/python3.7/site-packages/pyspectral/config.py:75: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  config = recursive_dict_update(config, yaml.load(fp_))
[DEBUG: 2019-04-29 16:18:24 : satpy.scene] Setting 'PPP_CONFIG_DIR' to '/home/wouter/Venvs/satpy/lib/python3.7/site-packages/satpy/etc'
[DEBUG: 2019-04-29 16:18:24 : satpy.readers] Reading ['/home/wouter/Venvs/satpy/lib/python3.7/site-packages/satpy/etc/readers/abi_l1b.yaml']
[DEBUG: 2019-04-29 16:18:24 : satpy.readers.yaml_reader] Assigning to abi_l1b: ['./satdata/goes16/OR_ABI-L1b-RadF-M6C01_G16_s20190980450286_e20190980459563_c20190980500008-118900_0.nc', './satdata/goes16/OR_ABI-L1b-RadF-M6C02_G16_s20190980450286_e20190980459563_c20190980500003-120000_0.nc', './satdata/goes16/OR_ABI-L1b-RadF-M6C03_G16_s20190980450286_e20190980459563_c20190980500012-119000_0.nc', './satdata/goes16/OR_ABI-L1b-RadF-M6C05_G16_s20190980450286_e20190980459563_c20190980500011-119101_0.nc', './satdata/goes16/OR_ABI-L1b-RadF-M6C06_G16_s20190980450286_e20190980459569_c20190980500001.nc', './satdata/goes16/OR_ABI-L1b-RadF-M6C07_G16_s20190980450286_e20190980459575_c20190980500010.nc', './satdata/goes16/OR_ABI-L1b-RadF-M6C08_G16_s20190980450286_e20190980459563_c20190980500011.nc', './satdata/goes16/OR_ABI-L1b-RadF-M6C09_G16_s20190980450286_e20190980459570_c20190980500027.nc', './satdata/goes16/OR_ABI-L1b-RadF-M6C10_G16_s20190980450286_e20190980459575_c20190980500024.nc', './satdata/goes16/OR_ABI-L1b-RadF-M6C11_G16_s20190980450286_e20190980459563_c20190980500022.nc', './satdata/goes16/OR_ABI-L1b-RadF-M6C12_G16_s20190980450286_e20190980459570_c20190980500025.nc', './satdata/goes16/OR_ABI-L1b-RadF-M6C13_G16_s20190980450286_e20190980459576_c20190980500030.nc', './satdata/goes16/OR_ABI-L1b-RadF-M6C14_G16_s20190980450286_e20190980459563_c20190980500029.nc', './satdata/goes16/OR_ABI-L1b-RadF-M6C15_G16_s20190980450286_e20190980459570_c20190980500030.nc', './satdata/goes16/OR_ABI-L1b-RadF-M6C16_G16_s20190980450286_e20190980459575_c20190980500030.nc']
[DEBUG: 2019-04-29 16:18:24 : satpy.readers.yaml_reader] Can't parse ./satdata/goes16/OR_ABI-L1b-RadF-M6C01_G16_s20190980450286_e20190980459563_c20190980500008-118900_0.nc with {system_environment:2s}_{mission_id:3s}-L1b-{observation_type:3s}{scene_abbr:s}-{scan_mode:2s}C01_{platform_shortname:3s}_s{start_time:%Y%j%H%M%S%f}_e{end_time:%Y%j%H%M%S%f}_c{creation_time:%Y%j%H%M%S%f}.nc{nc_version}.
Traceback (most recent call last):
  File "/home/wouter/Venvs/satpy/lib/python3.7/site-packages/xarray/backends/file_manager.py", line 167, in acquire
    file = self._cache[self._key]
  File "/home/wouter/Venvs/satpy/lib/python3.7/site-packages/xarray/backends/lru_cache.py", line 42, in __getitem__
    value = self._cache[key]
KeyError: [<function _open_netcdf4_group at 0x7f642df6d0d0>, ('/home/wouter/Work/satellite/satdata/goes16/OR_ABI-L1b-RadF-M6C01_G16_s20190980450286_e20190980459563_c20190980500008-118900_0.nc', CombinedLock([<SerializableLock: 611121c5-1f7d-4631-8e3e-e0c5865c957a>, <SerializableLock: ace41451-e117-4f3d-b88f-da6eff357d9e>])), 'r', (('clobber', True), ('diskless', False), ('format', 'NETCDF4'), ('group', None), ('persist', False))]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "minimal_bug_example.py", line 9, in <module>
    scene = Scene(filenames=fpaths, reader=reader)
  File "/home/wouter/Venvs/satpy/lib/python3.7/site-packages/satpy/scene.py", line 158, in __init__
    reader_kwargs=reader_kwargs)
  File "/home/wouter/Venvs/satpy/lib/python3.7/site-packages/satpy/scene.py", line 203, in create_reader_instances
    ppp_config_dir=self.ppp_config_dir)
  File "/home/wouter/Venvs/satpy/lib/python3.7/site-packages/satpy/readers/__init__.py", line 753, in load_readers
    reader_instance.create_filehandlers(loadables, fh_kwargs=reader_kwargs_without_filter)
  File "/home/wouter/Venvs/satpy/lib/python3.7/site-packages/satpy/readers/yaml_reader.py", line 511, in create_filehandlers
    fh_kwargs=fh_kwargs)
  File "/home/wouter/Venvs/satpy/lib/python3.7/site-packages/satpy/readers/yaml_reader.py", line 497, in new_filehandlers_for_filetype
    return list(filtered_iter)
  File "/home/wouter/Venvs/satpy/lib/python3.7/site-packages/satpy/readers/yaml_reader.py", line 469, in filter_fh_by_metadata
    for filehandler in filehandlers:
  File "/home/wouter/Venvs/satpy/lib/python3.7/site-packages/satpy/readers/yaml_reader.py", line 412, in new_filehandler_instances
    yield filetype_cls(filename, filename_info, filetype_info, *req_fh, **fh_kwargs)
  File "/home/wouter/Venvs/satpy/lib/python3.7/site-packages/satpy/readers/abi_l1b.py", line 53, in __init__
    chunks={'x': CHUNK_SIZE, 'y': CHUNK_SIZE})
  File "/home/wouter/Venvs/satpy/lib/python3.7/site-packages/xarray/backends/api.py", line 363, in open_dataset
    filename_or_obj, group=group, lock=lock, **backend_kwargs)
  File "/home/wouter/Venvs/satpy/lib/python3.7/site-packages/xarray/backends/netCDF4_.py", line 352, in open
    return cls(manager, lock=lock, autoclose=autoclose)
  File "/home/wouter/Venvs/satpy/lib/python3.7/site-packages/xarray/backends/netCDF4_.py", line 311, in __init__
    self.format = self.ds.data_model
  File "/home/wouter/Venvs/satpy/lib/python3.7/site-packages/xarray/backends/netCDF4_.py", line 356, in ds
    return self._manager.acquire().value
  File "/home/wouter/Venvs/satpy/lib/python3.7/site-packages/xarray/backends/file_manager.py", line 173, in acquire
    file = self._opener(*self._args, **kwargs)
  File "/home/wouter/Venvs/satpy/lib/python3.7/site-packages/xarray/backends/netCDF4_.py", line 244, in _open_netcdf4_group
    ds = nc4.Dataset(filename, mode=mode, **kwargs)
  File "netCDF4/_netCDF4.pyx", line 2291, in netCDF4._netCDF4.Dataset.__init__
  File "netCDF4/_netCDF4.pyx", line 1855, in netCDF4._netCDF4._ensure_nc_success
OSError: [Errno -101] NetCDF: HDF error: b'/home/wouter/Work/satellite/satdata/goes16/OR_ABI-L1b-RadF-M6C01_G16_s20190980450286_e20190980459563_c20190980500008-118900_0.nc'

```
**Environment Info:**
 - OS: Manjaro 18.0.4 Illyria
 - Satpy Version: 0.14.2 (0.14.0 also fails)
 - PyResample Version: 1.12.0
-  rasterio        1.0.22
 - Readers and writers dependencies (when relevant): `abi_l1b:  ok`

**Additional context**
It used to work when I created just png images. Today I wanted to create a GeoTIFF, and got prompted to install `rasterio` for this. After installing `rasterio`, I'm unable to read the netcdf files. Reading `hrit` data for `MSG` still works fine.

I am still able to open the `nc` files manually with `rasterio` installed using:
```python
import netCDF4 as nc4
import xarray

filename = <exact copy of the full file path that gets returned in the traceback above>

data = nc4.Dataset(filename)  # this succeeds
data_ = xarray.open_dataset(filename) # this also succeeds
```

I can read the GOES16/17 netcdf files again after uninstalling `rasterio`, although this means GeoTIFF exports won't work anymore.

I'm not sure what to do from here. `rasterio` does not seem to have any xarray/netcdf dependencies, but it still seems to conflict with SatPy.

**Comment by djhoese** [comment]
Congratulations, I've never seen this error before!

Let's see, a couple questions:

1. Even though your path is in `/home`, is this a symbolic link to a network storage (NFS)? Something like gluster/lustre?
2. It doesn't look like you are using a conda environment, so I'm wondering how you ended up installing rasterio? And how did you install netCDF4-python?
3. Have you ever used dask on your machine before? Do you possible have some conflicting dask configurations in `~/.dask` or `~/.config`? Are you intentionally trying to run dask with a scheduler other than the default?

My guesses as to a solution:

Force a reinstall/rebuild of the netCDF4-python library. My guess is that when you installed rasterio required a new version of NetCDF. This new version of the NetCDF C library is different enough that the netCDF4-python library is no longer working. Hhhhmmm except you said that xarray `open_dataset` is still working...well let's see what we get from your answers to my questions.

**Comment by WBMol** [comment]
> Congratulations, I've never seen this error before!

Thanks, I'm honoured haha

As for your questions:
1. `/home/` is a location on my harddisk, so local files only
2. `virtualenv` and `pip install <package>`,  system packages just via my package manager (`pacman`)
3. Not that I recall, but I'll have a closer look later

I will also try rebuilding netCDF(-python). I'll come back in two days with more answers. Thanks for the help so far

**Comment by WBMol** [comment]
Alright, I've tried reinstalling both system and python netcdf packages after installing rasterio. This has not helped unfortunately. 

As for `dask`, the first time I've consciously used it is with SatPy. I can't find any related configs in  `~/.dask` or `~/.config`.

I have figured out more specifically where it goes wrong, however. The following works:
```python
import xarray
import satpy
fpath = '/path/to/netcdf.nc'

xarray.open_dataset(fpath) # no issues here
```
Surprisingly, this fails (notice the import order has changed):
```python
import satpy
import xarray
fpath = '/path/to/netcdf.nc'

xarray.open_dataset(fpath) # throws the same traceback as posted in the OP
```
This also applies to the script I posted in the OP. Adding `xarray` import statements before import `satpy` will result in the successful reading of the (GOES16/17) `.nc` files.

**Comment by mraspaud** [comment]
What version of hdf5 do you have? We stumbled upon problems when using both netcdf and hdf5 with older versions of the hdf5 library. (1.8 & 1.6 iirc)

**Comment by WBMol** [comment]
`hdf5:  1.10.5-1`
`netcdf: 4.6.3-1`

**Comment by djhoese** [comment]
@WBMol I'm wondering if you could try your imports again but try `importer rasterio` instead of importing `satpy`?

If that doesn't cause the failure, what about `import gdal` instead of `rasterio`?

**Comment by WBMol** [comment]
If I replace `satpy` with `rasterio` it fails as well, interesting. No issues with `gdal`.
Flipping around the import order as with the `import satpy` example fixes the issues. In both cases version `1.0.22` of `rasterio` is imported.

**Comment by mraspaud** [comment]
sounds like a rasterio problem then. Did you try upgrading or downgrading it ?

**Comment by WBMol** [comment]
I've had to go back as far as version `1.0.2` for `rasterio` (july 27, 2018) until the error disappeared. I prefer the solution of reordering the imports, though I have still no clue as to why that works.

**Comment by mraspaud** [comment]
This should probably be reported as an issue on the rasterio github page

**Comment by djhoese** [comment]
@WBMol Were you able to file a bug with rasterio on this? Since you are the only one who has run in to this so far it will be difficult for us to test it and reproduce it.

**Comment by WBMol** [comment]
I'll file a bug with rasterio instead, and close this one. The workaround is so simple that I haven't been working on trying to fix it (and kind of forgot about it, hence the late response).

Thanks for the help
