### ISSUE TITLE
Update custom reader documentation to mention coordinates and available datasets

### ISSUE THREAD

**Issue by djhoese** [pytroll/satpy#782]
Custom reader documentation currently only mentions creating a gridded area definition, but should also mention creating a SwathDefinition via the `coordinates` parameter in the YAML.

Other things that could/should be added (I'll add more if I think of them):

 - `available_dataset_ids`, at least a sentence or two about it and pointing to the more thorough API docs

**Comment by gerritholl** [comment]
It would also be helpful to point out explicitly that it's not mandatory to list all the available datasets in the yaml file; for a NetCDF file with lots of datasets, this just duplicates the self-documenting NetCDF header.
