### ISSUE TITLE
SEVIRI channels loaded from netcdf in Scene object appear to have wrong names and calibration

### ISSUE THREAD

**Issue by TalfanBarnie** [pytroll/satpy#826]
**Describe the bug**
SatPy seems to load the wrong data / calibration parameters for certain bands when opening a netcdf file.

**To Reproduce**

```python
from satpy.scene import Scene

files=[attached_file]
reader = 'seviri_l1b_nc'
scn = Scene(files, reader=reader)
bands = ['WV_062','WV_073','IR_087','IR_097','IR_108','IR_120','IR_134']
scn.load(bands,calibration='brightness_temperature')

```

**Expected behavior**
```python
scn['IR_087']
 ```
 should retrieve the appropriate xarray dataset from the Scene object

**Actual results**
```python
scn['IR_087']
```
gives

```python
<xarray.DataArray 'ch5' (y: 149, x: 556)>
dask.array<shape=(149, 556), dtype=float32, chunksize=(149, 556)>
Coordinates:
    lat      (y, x) float32 dask.array<shape=(149, 556), chunksize=(149, 556)>
    lon      (y, x) float32 dask.array<shape=(149, 556), chunksize=(149, 556)>
  * x        (x) float64 -1.761e+06 -1.758e+06 ... -1.08e+05 -1.05e+05
  * y        (y) float64 5.305e+06 5.302e+06 5.299e+06 ... 4.864e+06 4.861e+06
Attributes:
    orbital_parameters:   {'projection_longitude': 0.0, 'projection_latitude'...
    valid_min:            0
    standard_name:        toa_brightness_temperature
    file_type:            seviri_l1b_nc
    long_name:            SEVIRI water vapour 6.2 micron pixel counts
    resolution:           3000.403165817
    calibration:          brightness_temperature
    nc_key:               ch5
    sensor:               seviri
    comment:              Radiance in mW m-2 sr-1(cm-1)-1 = add_offset + ( pi...
    polarization:         None
    scale_factor:         0.008318111189855896
    add_offset:           -0.42422367068265077
    name:                 IR_087
    level:                None
    modifiers:            ()
    platform_name:        Meteosat-11
    wavelength:           (8.3, 8.7, 9.1)
    valid_max:            1023
    units:                K
    start_time:           2019-05-24 06:00:11.155000
    end_time:             2019-05-24 06:15:11.333000
    area:                 Area ID: some_area_name\nDescription: On-the-fly ar...
    ancillary_variables:  []
```

The long_name, nc_key and data array name appear to be wrong, and the Brightness Temperatures are suspiciously low (~180K). Both the water vapour channels also appear to have the same problem, although 10.8, 12.0 and 13.4 look fine.

Thanks for your help!

Talfan

Example files: 
[W_XX-EUMETSAT-Darmstadt,VIS+IR+HRV+IMAGERY,MSG4+SEVIRI_C_EUMG_20190524060011.zip](https://github.com/pytroll/satpy/files/3307961/W_XX-EUMETSAT-Darmstadt.VIS%2BIR%2BHRV%2BIMAGERY.MSG4%2BSEVIRI_C_EUMG_20190524060011.zip)

**Environment Info:**
 - OS: Ubuntu 18.04.1
 - Satpy Version: 0.15.2+245.g4f63df8d
 - PyResample Version: 1.12.3
 - Readers and writers dependencies (when relevant): 
Readers
=======
abi_l1b:  ok
abi_l1b_scmi:  ok
acspo:  ok
ahi_hrit:  ok
ahi_hsd:  ok
amsr2_l1b:  ok
avhrr_l1b_aapp:  ok
avhrr_l1b_eps:  ok
avhrr_l1b_gaclac:  cannot find module 'satpy.readers.avhrr_l1b_gaclac' (No module named 'pygac')
avhrr_l1b_hrpt:  cannot find module 'satpy.readers.hrpt' (No module named 'pygac')
caliop_l2_cloud:  cannot find module 'satpy.readers.caliop_l2_cloud' (No module named 'pyhdf')
clavrx:  cannot find module 'satpy.readers.clavrx' (No module named 'pyhdf')
electrol_hrit:  ok
fci_l1c_fdhsi:  ok
generic_image:  ok
geocat:  ok
ghrsst_l3c_sst:  ok
goes-imager_hrit:  ok
goes-imager_nc:  ok
grib:  ok
hsaf_grib:  ok
iasi_l2:  ok
jami_hrit:  ok
li_l2:  cannot find module 'satpy.readers.li_l2' (No module named 'h5netcdf')
maia:  ok
mersi2_l1b:  ok
modis_l1b:  cannot find module 'satpy.readers.modis_l1b' (No module named 'pyhdf')
modis_l2:  cannot find module 'satpy.readers.modis_l2' (No module named 'pyhdf')
msi_safe:  cannot find module 'satpy.readers.msi_safe' (No module named 'glymur')
mtsat2-imager_hrit:  ok
nucaps:  ok
nwcsaf-geo:  ok
nwcsaf-pps_nc:  ok
olci_l1b:  ok
olci_l2:  ok
omps_edr:  ok
safe_sar_l2_ocn:  ok
sar-c_safe:  ok
scatsat1_l2b:  ok
seviri_l1b_hrit:  ok
seviri_l1b_native:  ok
seviri_l1b_nc:  ok
slstr_l1b:  ok
tropomi_l2:  ok
vaisala_gld360:  ok
viirs_compact:  ok
viirs_edr_active_fires:  ok
viirs_edr_flood:  cannot find module 'satpy.readers.viirs_edr_flood' (No module named 'pyhdf')
viirs_l1b:  ok
viirs_sdr:  ok
virr_l1b:  ok

Writers
=======
cf:  ok
geotiff:  ok
mitiff:  ok
ninjotiff:  cannot find module 'satpy.writers.ninjotiff' (No module named 'pyninjotiff')
scmi:  ok
simple_image:  ok

Extras
======
cartopy:  ok
geoviews:  No module named 'geoviews'

**Comment by mraspaud** [comment]
@TalfanBarnie thank you very much for the very good bug report!
If you feel like investigating this more, you can have a look at the satpy/readers/seviri_l1b_nc.py file and see if you can see anything wrong in the calibration functions.

**Comment by TalfanBarnie** [comment]
Thanks!

I checked and it looks like it's the 'nc_key' terms in the seviri_l1b_nc.yaml file

the following need to be changed:

WV_62
nc_key: 'ch5'

WV_073 
nc_key: 'ch6'

IR_087
nc_key: 'ch7'

The rest appear to be ok.

**Comment by mraspaud** [comment]
You are absolutely right, those are wrong in the current code I believe. Thanks for tracking this down. Feel free to submit a pull request. Otherwise maybe @ColinDuff can look at it next week ?
