### ISSUE TITLE
modis_l2 reader is not working properly.

### ISSUE THREAD

**Issue by masabhathini** [pytroll/satpy#835]
**Describe the bug**
There may be a bug in the modis_l2 reader. 

**To Reproduce**

```python
ss = Scene(glob.glob('/home/satviz/Work/scripts/junk/MOD35_L2/MOD35_L2.A2019177.2335.061.2019178071104.hdf', reader='modis_l2')
```

**Expected behavior**
It's not able to read modis data. 
**Actual results**
No warnings and no debug.

**Screenshots**
![image](https://user-images.githubusercontent.com/25902165/60337563-026dd100-99c1-11e9-8d4e-3c1dbf70368c.png)
**Environment Info:**
 - OS:  Linux
 - Satpy Version: 0.16.0
 - PyResample Version: 1.12.3
 - Readers and writers dependencies (when relevant): 

[MOD35_L2.A2019177.2150.061.2019178071104.zip](https://github.com/pytroll/satpy/files/3338848/MOD35_L2.A2019177.2150.061.2019178071104.zip)
Readers
=======
abi_l1b:  ok
abi_l1b_scmi:  ok
acspo:  ok
agri_l1:  cannot find module 'satpy.readers.agri_l1' (No module named 'satpy.readers.agri_l1')
ahi_hrit:  ok
ahi_hsd:  ok
amsr2_l1b:  ok
avhrr_l1b_aapp:  ok
avhrr_l1b_eps:  ok
avhrr_l1b_gaclac:  cannot find module 'satpy.readers.avhrr_l1b_gaclac' (No module named 'pygac')
avhrr_l1b_hrpt:  cannot find module 'satpy.readers.hrpt' (No module named 'pygac')
caliop_l2_cloud:  ok
clavrx:  ok
electrol_hrit:  ok
fci_l1c_fdhsi:  ok
generic_image:  ok
geocat:  ok
ghrsst_l3c_sst:  ok
goes-imager_hrit:  ok
goes-imager_nc:  ok
grib:  ok
hsaf_grib:  ok
iasi_l2:  ok
insat3d_l1b_hdf:  cannot find module 'satpy.readers.insat3d_hdf5' (No module named 'satpy.readers.insat3d_hdf5')
jami_hrit:  ok
li_l2:  ok
maia:  ok
mersi2_l1b:  ok
modis_l1b:  ok
modis_l2:  ok
msi_safe:  cannot find module 'satpy.readers.msi_safe' (No module named 'glymur')
mtsat2-imager_hrit:  ok
nucaps:  ok
nwcsaf-geo:  ok
nwcsaf-pps_nc:  ok
olci_l1b:  ok
olci_l2:  ok
omps_edr:  ok
safe_sar_l2_ocn:  ok
sar-c_safe:  ok
scatsat1_l2b:  ok
seviri_l1b_hrit:  ok
seviri_l1b_native:  ok
seviri_l1b_nc:  ok
slstr_l1b:  ok
tropomi_l2:  ok
vaisala_gld360:  ok
viirs_compact:  ok
viirs_edr_active_fires:  ok
viirs_edr_flood:  ok
viirs_l1b:  ok
viirs_sdr:  ok
virr_l1b:  ok

Writers
=======
cf:  ok
geotiff:  ok
mitiff:  ok
ninjotiff:  cannot find module 'satpy.writers.ninjotiff' (No module named 'pyninjotiff')
scmi:  ok
simple_image:  ok

Extras
======
cartopy:  No module named 'cartopy'
geoviews:  No module named 'geoviews'

**Additional context**

**Comment by mraspaud** [comment]
@masabhathini Thank you for reporting this.
@LTMeyer @BENR0 Could you have a look at this ?

**Comment by masabhathini** [comment]
Sorry, There is a typo mistake in it.
BTW, Thanks alot.
