### ISSUE TITLE
Resampling data read with generic image reader corrupts data

### ISSUE THREAD

**Issue by pnuu** [pytroll/satpy#893]
**Describe the bug**
Reported by @TAlonglong in Slack.

With some valid GeoTIFF files (e.g. https://eoimages.gsfc.nasa.gov/images/imagerecords/144000/144898/BlackMarble_2016_01deg_geo.tif) the resampled scene has all values set to `255`.

**To Reproduce**

```python
import numpy as np
from satpy import Scene

glbl = Scene(reader='generic_image', filenames=['/tmp/BlackMarble_2016_01deg_geo.tif'])
glbl.load(['image'])
print("global:", np.nanmin(glbl['image']), np.nanmax(glbl['image']))
lcl = glbl.resample('euro4')
print("local:", np.nanmin(lcl['image']), np.nanmax(lcl['image']))
```

**Expected behavior**
The prints should be equal for both global and local scenes:
```python
global: 0 255
local: 0 255
```

**Actual results**
The local scene has all the values set to `255`.
```python
global: 0 255
local: 255 255
```

**Environment Info:**
 - Satpy Version: current master
 - Pyresample Version: current master
 - Trollimage version: current master

**Comment by djhoese** [comment]
So a couple things I'm thinking about with this:

* `255` is a strange final result. I *think* this comes from some work @mraspaud and I did where the default fill value for integer arrays is the maximum for that particular data type. For this uint8 data that would be 255. You could check this by specifying `fill_value=0` to `resample`.
* This geotiff is a lat/lon projection. The `resample` default method of determining `distance_upper_bound` does a really poor job for lat/lon projections. I *thought* made an issue for this, but now I can't find it. Forcing distance_upper_bound could be set in `resample` and you may get much better results.

**Comment by pnuu** [comment]
Was in a hurry yesterday and forgot to mention that I did test setting the `fill_value`
```In [41]: lcl = glbl.resample('EPSG_3035_4km', fill_value=0)                     
In [42]: print(np.nanmin(lcl['image']), np.nanmax(lcl['image']))                
0.0 0.0
In [43]: lcl = glbl.resample('EPSG_3035_4km', fill_value=135)                   
In [44]: print(np.nanmin(lcl['image']), np.nanmax(lcl['image']))                
135.0 135.0
In [45]: lcl = glbl.resample('EPSG_3035_4km', fill_value=None)                  
In [46]: print(np.nanmin(lcl['image']), np.nanmax(lcl['image']))                
nan nan
In [49]: glbl['image'].data = glbl['image'].data.astype(np.float32)             
In [50]: lcl = glbl.resample('EPSG_3035_4km', fill_value=np.nan)                
In [51]: print(np.nanmin(lcl['image']), np.nanmax(lcl['image']))                
nan nan
```

The `resample` call doesn't recognize the kwarg `distance_upper_bound`, neither could I find it from the whole source tree of satpy or pyresample. After some thought setting `radius_of_influence=50e3` did the trick!

**Comment by TAlonglong** [comment]
Thanks @pnuu and @djhoese. This indeed did the trick, setting the `radius_of_influence=50e3`

**Comment by djhoese** [comment]
Yes, sorry, distance upper bound is what I called it in polar2grid.

**Comment by pnuu** [comment]
Closing, the `radius_of_influence` "fixes" the issue.
