### ISSUE TITLE
Convert mpop readers to satpy yaml readers

### ISSUE THREAD

**Issue by mraspaud** [pytroll/satpy#9]
- [x] viirs compact
- [x] gac
- [x] nwcsaf MSG
- [x] nwcsaf PPS
- [ ] xsar
- [x] lac

(copying @davidh-ssec 's items here)
- [x] VIIRS SDR
- [x] VIIRS L1B
- [x] NUCAPS
- [x] OMPS

**Comment by davidh-ssec** [comment]
In addition the following readers were written for the old satpy .cfg method but should be converted to YAML:
- [ ] VIIRS SDR
- [ ] VIIRS L1B
- [ ] NUCAPS
- [ ] OMPS

**Comment by mraspaud** [comment]
I thinks this can be closed. The missing reader isn't relevant right now.
