### ISSUE TITLE
Clarify orbital_parameters metadata

### ISSUE THREAD

**Issue by djhoese** [pytroll/satpy#922]
Currently the orbital_parameters and what values are likely to be found in this channel metadata are defined in the readers documentation [here](https://satpy.readthedocs.io/en/latest/readers.html). However, there is no mention of `orbital_parameters` in the custom reader documentation. The current docs are also unclear about what units some of these values are in. Most importantly `altitude` needs to be in kilometers (why?!?!?) for the angle calculations in pyorbital and needs to be relative to the surface of the earth. Docs currently say:

> Current position of the satellite at the time of observation in geodetic coordinates (i.e. altitude is normal to the surface).

The word `normal` to me says "perpendicular" to the surface, but does not necessarily mean relative to the surface.

**Comment by sfinkens** [comment]
@djhoese I think this was one of the reasons why @mraspaud proposed to attach units to these quantities. I remember that `unyt` was an option on the table, but that was a couple of months ago. Until this is implemented, we should mention the required units in the reader docs. 

I will also clarify the wording (I think "relative and normal to the surface" should do?) and link to the reader:metadata conventions from the custom reader docs.

**Comment by mraspaud** [comment]
two quick comments:
- we should use the same units for all satellites until we have the unit carried with the quantity
- I started using pint in the ninjotiff writer, as it's compatible with xarray.DataArrays (unyt isn't so much). Also there is a pint/xarray integration work going on https://github.com/hgrecco/pint/issues/849

**Comment by djhoese** [comment]
Ok so we can document what the units are for now. In the future when things are a little more stable with pint. I'm fine with that, I would like to avoid extra dependencies if we can for now.

We could even go further in the future and allow ECEF coordinates which is what I was converting when I got confused by this. Eh maybe that's a bad idea.
