### ISSUE TITLE
Swap names for Vis/IR default natural_color and natural_color_sun composites

### ISSUE THREAD

**Issue by djhoese** [pytroll/satpy#936]
The builtin composite for `natural_color` does not apply the `sunz_corrected` modifier to its inputs. To get those applied you have to ask for `natural_color_sun`. My current issue is that it has become fairly standard for `natural_color` in sensor-specific configs to be the sunz_corrected version.

As it is right now a sensor will see `natural_color` and `natural_color_sun` as two types of composites that could be generated, but they are actually the same thing.

Thoughts?

**Comment by pnuu** [comment]
The SZA-cosine corrected version is the one we at FMI have in production. Also, we have them defined in local configs so I don't mind the change. As a disclaimer I should note that *all* the composites we use are locally defined, and we never use the built-in composites directly. And, frankly, I think no one should use them that way in operational context. Ever.

**Comment by djhoese** [comment]
Looks like this was closed in #1066.
