### ISSUE TITLE
Add a CMSAF reader

### ISSUE THREAD

**Issue by gerritholl** [pytroll/satpy#958]
## Feature Request

**CMSAF reader**

For fogpy to work on SEVIRI archive data, a reader is needed for CMSAF data (in particular cloud optical depth (COD), liquid water path (LWP), and effective radius (Reff)).  Currently satpy has a NWCSAF reader but not a CMSAF reader. 

**Describe any changes to existing user workflow**
No backward incompatibility problems foreseen.

**Comment by sfinkens** [comment]
Good idea :) I can help/review if needed
