### ISSUE TITLE
Documentation on storing area definitions has a broken fragment identifier link to pyresample

### ISSUE THREAD

**Issue by gerritholl** [pytroll/satpy#990]
**Describe the bug**

In the [satpy resampling documentation on storing area definitions](https://satpy.readthedocs.io/en/latest/resample.html#store-area-definitions), it says:

> Area definitions can be added to a custom YAML file (see [pyresample’s documentation](http://pyresample.readthedocs.io/en/stable/geo_def.html#pyresample-utils) for more information) and loaded using pyresample’s utility methods

where *pyresample's documentation* is a link to:

https://pyresample.readthedocs.io/en/stable/geo_def.html#pyresample-utils

Although that page exists, there is no fragment identifier `pyresample-utils` and there does not appear to be documentation on storing or loading area definitions from a file there.

**To Reproduce**

1. Go to the [satpy documentation](https://satpy.readthedocs.io)
2. Click on *Resampling* -> *Store area definitions*
3. Click on the link anchored *pyresample's documentation*
4. Search and fail to find the promised information on the YAML files

**Expected behavior**

I'm looking for documentation on the syntax of the YAML area files and information on how their loading works, such as the behaviour of the `parse_area_file` utility function.

**Actual results**

In reality, that documentation may or may not exist, but it does not exist in the linked location.

**Environment Info:**
 - OS: openSUSE 15.0
 - Satpy Version: 0.18.2
 - PyResample Version: 1.13.2

**Comment by gerritholl** [comment]
There is a [`parse_area_file`](https://pyresample.readthedocs.io/en/stable/API.html#pyresample.area_config.parse_area_file) function in `pyresample`, but it`s in the `area_config` module, not in `utils`.  There is also `load_area` which appears to be doing something very similar (I'm not sure what the differences are).

**Comment by djhoese** [comment]
What about this: https://pyresample.readthedocs.io/en/latest/geometry_utils.html#loading-from-disk
