### ISSUE TITLE
In the sar-c_safe reader, add platform_name to the attribute.

### ISSUE THREAD

**Issue by TAlonglong** [pytroll/satpy#996]
I would like to have the platform_name in the attributes in this reader.

The filename_info has the `mission_id`. This can be translated to platform_name like:

In the init of the `SAFGRD`:
`self._mission_id = filename_info['mission_id']`

and in `get_dataset` something like:
`data.attrs.update({'platform_name': self._mission_id})`

**Comment by mraspaud** [comment]
Good idea! PR welcome :)
